### ISSUE TITLE
Custom rpc block explorer links are broken

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10041]
all assets under all custom RPCs go to broken link on Metamask when trying to "view on etherscan"

**Steps to reproduce**
1. add a custom RPC network, such as [binance](https://docs.binance.org/smart-chain/wallet/metamask.html)
2. add a custom asset
3. Click the asset to go to the asset page
4. Click the three-dot menu and select 'view on etherscan'
5. See a 500 error page on etherscan

**Comment by brad-decker** [comment]
Additional context:

All asset pages, with the exception of the primary asset, do not make use of the custom block explorer URL. It is likely possible for certain block explorers to not follow a URL pattern that is compatible with etherscan. This would make it such that even the native link would not work. 

Also, if adding from the token list instead of a custom token, the etherscan link will not be broken but will not be the proper block tracker for the given network.

**Comment by Gudahtt** [comment]
It looks like there is a draft EIP for this: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3091.md

Not sure how widely adopted it is though.

The minimal solution here would be to not show _any_ block explorer link on custom networks. That would be unfortunate though - that link is quite useful. We don't expose the token address anywhere else for example - so losing that would be pretty bad (though that could be addressed by adding it to the token page somewhere).

**Comment by Gudahtt** [comment]
I think the best solution for now would be to follow EIP-3091, and add a metric event to track which custom block explorers are being used so we can adjust this as needed in the future.

**Comment by Gudahtt** [comment]
Note that this applies to block explorer links throughout the application, not just on the asset page. The block explorer links in the activity log have the same problem for example.
