### ISSUE TITLE
Speed up gas estimates are not in the correct order - Fast is slower than Avg.

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#10059]
**Describe the bug**
When clicking speed up a tx, the options offered are not in the correct order, Fast is actually less gas than Average option.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/101929236-34b2c480-3b9c-11eb-8dba-bfc00b901825.png)

**Browser details (please complete the following information):**
Firefox, MM v8.1.8

**Comment by darkwing** [comment]
After some research, I believe this is an API issue.

We retrieve the gas estimates here:

https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/ducks/gas/gas.duck.js#L136-L161

The only modifications we make on each of them is `BigNumber(price, 10).toNumber())`.

The API call is here:

https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/ducks/gas/gas.duck.js#L98-L108

Since we aren't messing with the numbers from the API, this really has to be an API issue.

**Comment by darkwing** [comment]
This has been confirmed as an API bug.
