### ISSUE TITLE
Recovering an account from the backup files?

### ISSUE THREAD

**Issue by testoviron33** [MetaMask/metamask-extension#10186]
Hi

(I was not sure if this was the best place to post it(or if not stack-exchange as it was suggested, so sorry in advance if I've chosen wrongly)
I'm not very techie but as I feel it might be possible to recover MetaMask wallet from the backup files of the browser.
I did this locally, meaning on the same PC and user account, firstly I've created a MetaMask wallet, then I've copied the whole user folder of that chromium user, then deleted the original one and then replaced with the copy. After that the wallet was normally working, just asking me for the local password obviously.
However when I did the same thing(even coping the whole Chromium folder) but on another machine or system account, the metamask extension didn't even appear.

Am I sensing it correctly that it still could be done somehow, but I am doing some mistake?
Do we know where the responsible files are/should be stored?

**Comment by Gudahtt** [comment]
Great question! I think you're right, that this is often possible. We don't have reliable guides for how to do this though, because browsers have various different strategies for persisting extension state that differ between operating systems and versions, so it's been a bit difficult to keep up with.

In general we'd never recommend this approach - you should instead backup the seed phrase, and use that to recover the account whenever necessary. But we have suggested this before as a last resort. It's by no means comprehensive, but we have a support article here explaining a few approaches we've taken: https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data

In the future I'd recommend such questions be directed to our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics).
