### ISSUE TITLE
Sesify

### ISSUE THREAD

**Issue by Sentrycs** [MetaMask/metamask-extension#10211]
This is probably related to the issue  "Temporarily disable sesify viz step #9841".

Yarn Dist results in 
Error cannot find module sesify

What is the remedy/workaround.

**Comment by Gudahtt** [comment]
Did you run `yarn install`? It sounds like `sesify` is not installed.

**Comment by Sentrycs** [comment]
yarn installed.
module sesify is not installed , because loader.js cannot  find it (it shows as  deprecated in Github)

**Comment by Gudahtt** [comment]
What is `loader.js`? Are we talking about the same thing here? :sweat_smile: 

I thought this was a question about how to build the MetaMask extension. The instructions for this are here: https://github.com/MetaMask/metamask-extension#building-locally
Everything works correctly for me when I run `yarn && yarn dist` using Node v10.20.1 and Yarn 1.22.5 on Ubuntu.

Are you using a different version of Node.js or Yarn? Are you building on a different OS? Or are you doing something completely different?

**Comment by Sentrycs** [comment]
OS=Windows 10
Node 10.16.0
Yarn 1.22.5
yarn dist returns loader.js error cannot find sesify module :
![yarn dist](https://user-images.githubusercontent.com/42841002/105058377-d15f6080-5a7e-11eb-8d8a-fc2db05cc5a1.jpg)
manual npm install sesify returns error because sesify is deprecated on Github
![install sesify](https://user-images.githubusercontent.com/42841002/105058451-e3d99a00-5a7e-11eb-9518-94575a006413.jpg)

**Comment by Gudahtt** [comment]
Thanks for the screenshots! That helps somewhat.

As documented in our README, the command you should run to install dependencies is `yarn`. We use `yarn` as our package manager, not `npm`. This command has to be run before you run `yarn dist`.

**Comment by Sentrycs** [comment]
The same result - sesify package is missing in Git
![yarn](https://user-images.githubusercontent.com/42841002/105063034-f0142600-5a83-11eb-9c1e-f0c7766e148c.jpg)

**Comment by Gudahtt** [comment]
It looks like you have a dirty working tree; i.e. you've made changes since cloning the repository. Any of those changes could have broken the build. For starters, I'd suggest deleting `package-lock.json` (as suggested by the warning shown), which was created as a side-effect of running `npm install`.

The last error shown indicates that either `git` is not installed, or that you have the wrong copy of that package cached locally. I'd suggest [ensuring that `git` is installed](https://git-scm.com/download), and then running `yarn cache clean`. Then try running `yarn` again.

**Comment by Gudahtt** [comment]
I'm going to close this for now, as we'd rather use our GitHub issues to track product bugs and enhancements rather than developer questions. If you have any further questions, please post on the [Developer Questions topic of our Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics/360001751291-Developer-Questions) and someone can provide further assistance there. Thanks!
