### ISSUE TITLE
web3.contract.methods.xxx.send({ ...}).on('receipt', ...) is not trigger after upgrade to metamask v9.0.1

### ISSUE THREAD

**Issue by onimusya** [MetaMask/metamask-extension#10215]
Hi,
   After I upgraded to metmask v9.0.1, my web3 is not receiving any **.on('receipt, ...)**, **.on('confirmation', ...)** events after call a contract object with send. Everything is working fine before upgrade to metamask v9.0.1.

- OS: Windows 10 v10.0.19042.76
- Browser: Chrome Version 87.0.4280.141 
- Metamask v9.0.1
- Web3js v1.3.1

Thanks.

Regards,
   Francis Hor

**Comment by rekmarks** [comment]
Hi @onimusya, thank you for your report. The events you are trying to listen to depend on subscriptions via the `eth_subscribe` JSON-RPC method, which are currently broken in `web3@1.x`. It's up to `web3` to fix this problem, which we notified them of this past July. Please see this issue for details: https://github.com/ChainSafe/web3.js/issues/3651

Since there's nothing for us to do here, I will now close this issue.
