### ISSUE TITLE
BigNumber Error when trying to cancel a transaction on different network

### ISSUE THREAD

**Issue by randymetamask** [MetaMask/metamask-extension#10304]
**Describe the bug**
In case number 77758 user encountered an error after trying to cancel a pending transaction in a custom Network:

HECO MAINNET
https://scan.hecochain.com/

```
Message: new BigNumber() not a base 16 number: undefined
Code: BigNumber Error
```

![case77758](https://user-images.githubusercontent.com/72138609/106158753-5f74ce80-6184-11eb-8b3c-6d3679057c36.png)

**Browser details (please complete the following information):**
 - OS: 
 - Hardware Wallet: 
 - Browser: 
 - MetaMask Version: 8.1.9

**Comment by brad-decker** [comment]
Alright well, I'm not getting a crash on Develop when trying to recreate this issue but it isn't behaving appropriately.

My Steps:
1. [Added Huobi eco testnet](https://docs.hecochain.com/#/en-us/wallet?id=testnet)
2. [Got some "HT" from faucet](https://scan-testnet.hecochain.com/faucet)
3. Sent 0.1 HT from one address to another in my wallet
4. Set gas price to 0
5. Waited for speed up and cancel to both be possible.
6. clicked Cancel.
7. popup doesn't close
![image](https://user-images.githubusercontent.com/4448075/106648019-4c337b80-6555-11eb-9287-acb410982d5c.png)
8. Logs indicate a replacement transaction underpriced. 
![image](https://user-images.githubusercontent.com/4448075/106648052-5eadb500-6555-11eb-83d5-3d9ab31b8f11.png)
9. The cancel transaction is never created, and the original transaction appears in this way (probably due to 0 gas) 
![image](https://user-images.githubusercontent.com/4448075/106648119-75eca280-6555-11eb-9a9b-c51e9e3ba57f.png)
10. In the reported case the transaction in question appears to be a contract interaction (staking), so the details for the bigNumber might require much more specific repro steps to get the tx exact.


Will continue exploring
