### ISSUE TITLE
Password for MetaMask stops working intermittently

### ISSUE THREAD

**Issue by Z-and** [MetaMask/metamask-extension#10385]
I've been having this issue on both Chrome and Brave for the last few weeks now. Every so often (lately very often) my password stops working despite entering it in correctly. I'm not sure how to recreate the issue, seems to happen at random. Usually I'll just restore my wallet from backup seed until I run into the same issue again. I saw a few topics from 2017 and 2018 but there didn't seem to be any resolution.

**Comment by Gudahtt** [comment]
Thanks for the report! So when you say that your password "stops working", what do you mean exactly? Do you see the "Incorrect password" error message, or do you get stuck on a loading screen, or are you seeing something else?

Could you share which browser, operating system, and MetaMask version you were using as well?

**Comment by Z-and** [comment]
> Thanks for the report! So when you say that your password "stops working", what do you mean exactly? Do you see the "Incorrect password" error message, or do you get stuck on a loading screen, or are you seeing something else?
> 
> Could you share which browser, operating system, and MetaMask version you were using as well?

I get the "Incorrect password" error message. I've tried this on both the latest version of Brave and Chrome, Windows 10 Home edition, MetaMask version 9.0.4

**Comment by pcdavis** [comment]
I am having the same problem on both Chrome and Brave. Both browsers are up-to-date and when I attempt to sign in to the Metamask extension with the correct password and it rejects it. I end up having to use my seed phrase, create a new password, only to have the same issue happen when I switch computers (e.g. go from my desktop to my laptop).  Both computers are Windows 10 machines with the latest updates installed.

**Comment by ryanml** [comment]
Hey @Z-and and @pcdavis - do you think you could go ahead and try these steps:

1. Close active MetaMask tabs, Navigate to `chrome://inspect/#extensions`
2. Under `MetaMask`, hit `inspect`
3. In the `Console` tab of the window that comes up, clear previous logs by hitting the cancel button in the top left of the window.
4. While keeping the window in step 3 open, open a MetaMask tab/popup and attempt to login with your password
5. Let me know what you see appear in that console tab after that happens

That may help point us in the direction of finding a fix. Much appreciated!

**Comment by aruialmeida** [comment]
Hi ryanml,

i have a problem with password in metamask.
i need some help.
i have been exchanging emails with yan zhu from brave, and she advise me to ask here for help.

i already try what you suggest above and after clean the console, and in chrome try to open metamask with my password it does not work ("incorrect password"). 

But this is not a normal situation.
i dont know if here is the best place to talk everything, because i don´t know if it´s correct to expose here brave mistakes. 
i just want to solve this.

I create some months ago a crypto wallet in brave and it give me 24 word phrase that i put in a paper safe.
I always read that if we have the 24 word phrase secure we will always be able to restore the account.

Meanwhile i import that account to metamask in chrome and have been using that way. is my only account (address), i used often.

some weeks ago, i thought to test my 24 seed phrase, only to make sure it is ok. and in another user account in my computer i realise that it doesn´t work, it ask for 12 words.
I google it and realize it is a commen problem.

So i went to brave community support and ask for help.
at this point i think is better to explain you privately, because i don´t want to talk bad about people in brave community, i just want to solve my problem.

thanks

**Comment by ryanml** [comment]
_ already try what you suggest above and after clean the console, and in chrome try to open metamask with my password it does not work ("incorrect password")._

@aruialmeida - when you did this, did you see any errors or other information appear in the console as you received the "Incorrect password" notification?

**Comment by aruialmeida** [comment]
(I edited my message above with all the history).

No, the console continue empty.

**Comment by ryanml** [comment]
@aruialmeida - thank you for providing this. We'll continue to investigate and see what could be happening.

**Comment by aruialmeida** [comment]
Ok, thanks.
I have a considerable amount in that account.

**Comment by cnxzcxy** [comment]
same problem here
always get incorrect password, confirm that I have input right password.

Version 9.5.3
