### ISSUE TITLE
bug: rEth shows up in Metamask as 0 tokens

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#10415]
> So, I was trying out the Rocketpool Beta, and it's interesting how rEth shows up in Metamask as 0 tokens, even though it's ERC20 and even though it shows the deposit info in a dialog when you click on the token row.  Is that expected?

**Comment by jaerith** [comment]
Hey, what a coincidence!  The same thing happened to me!  :P

**Comment by GoingGlobal2000** [comment]
yeah i'mm having the same issue trying to swap POLS for wETH. There's a short subreddit from late last year with ppl experiencing the same issue..so it's a longer standing one, apparently.

Even if just a UI glitch and the balances would process correctly, I am still not going to take a chance by confirming a transaction which looks like paying gas fees to make the tokens vanish.

I hope this issue is soon resolved because sending the funds over to a different wallet to swap from there, instead would be a total drag in gas fees and inoperability of metamask.

**Comment by tmashuang** [comment]
Can anyone with this issue provide any pertinent information that can reliably reproduce this? Even sending state logs to support and referencing the ticket number here.

**Comment by jaerith** [comment]
Sure, I can provide some info.  In order to reproduce the issue, you can go to the Rocketpool Beta site.  Using your wallet on the Goerli network (and assuming that you have the minimum Ether), you can trade some Ether for rEth tokens.  When you get the rEth tokens, you'll notice 0 rEth shows up in the Metamask extension, with the "i" icon reporting (with the hover of your mouse icon):

"You had trouble loading your token balances."

I can upload the state logs to ticket # 10415, if that would help.

**Comment by tmashuang** [comment]
@jaerith Can u provide a token address for rEth? I cant seem to find any indication of what the address is on their site or any of there documentation.

**Comment by jaerith** [comment]
Sure.  I think that the contract address is:

0xd91932aece793791cb5a7430a90d7822d3440c21

You can find the trx on Etherscan here:

https://goerli.etherscan.io/tx/0x556a4b83ac2436865d9b52f62e674cecfc370c6d7bbf40ab1fb3c630105db8d4

**Comment by tmashuang** [comment]
I see no indication that the address provided is an token address, the method called isn't one of the basic erc20 methods. I had to go to the their community Discord to fine the correct address, which is `0x721c917a4BA29b8fA5C86dd5108E4BC24d603C01`. After adding that address, the symbol, and 18 decimal precision was I able to see the token balance.

**Comment by jaerith** [comment]
Ah, I see!  My bad, you're right.

It's interesting - I went down this rabbit hole because I assumed that the contract address mentioned was ERC20.  When I provided this contract address to "Add Token", Metamask was able to know something about my trx, saying:

Deposit                                          -4 ETH
Feb 8 - beta.rocketpool.net        -4 ETH

So obviously Metamask is smart enough to figure out something based on context.  By looking it up in Etherscan?  Sorry, I'm a newb when it comes to Metamask.

In any case, I apologize for wasting your time.  Thanks for the help!

**Comment by tmashuang** [comment]
No worries, the testnets don't have as extensive information as mainnet does for contract decoding and verification. `0xd91932aece793791cb5a7430a90d7822d3440c21` could be a proxy contract to purely to verify deposit/balance and allocate the actual token. However it is setup is definitely not ideal and up to the dapp devs to how it is implemented, but getting information from the sources, dapp community discords/blogs/etc can demystify some confusion.
