### ISSUE TITLE
Intermittent token display rounding error

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10534]
I have not seen this issue myself, but it is shared here and then several people in the replies claim they’ve seen it before themselves.

I checked for duplicate issues, I can find no former reports with us, did not check in ZenDesk though, there might be some repro state logs in there.

https://twitter.com/missbitcoin_mai/status/1365668356079017984?s=21

**Comment by danfinlay** [comment]
Moving to ready, but the first phase is "Reproduce this".

**Comment by Gudahtt** [comment]
Possibly related to https://github.com/MetaMask/metamask-extension/issues/9777, if the token was added with `0` as decimals accidentally.

**Comment by NiranjanaBinoy** [comment]
The issue with token rounding was occurring because of the failure to fetch the decimal values, with the existing implementation the decimal value was defaulting to zero when the fetch fails to result in showing the wrong number of tokens.

With the changes in #10956  if we add a Custom Token (eg. `MASK` token ) with the correct decimal value (18 for MASK) gave the correct token value representations, you can verify the decimal value from the link provided in the warning message. 

Any value other than 0 will give the token with decimal points corresponding to the number entered. If the user enters a wrong value, removing the token from the list and re-adding it will allow you to edit the token decimal. 

If the user enters 0 you will get a huge token value, the subsequent recurring calls to `UseTokenTracker()` will fetch the correct decimal value when the service is reestablished.

**How the decimal value is handled in UseTokenTracker:**

From `buildTracker` method of `UseTokenTrackercalls` the `eth-token-tracker` is called. When the instance of the tokenTrackeris created, it checks if the decimal value is present in the `opts` (when the user enters zero this check returns false), if true that value will be used, for false `undefined` will be assigned to the `this.decimals`. Later when `update()` is called, it will check if `this.decimals` exist if true no update happens, but if false `updateDecimals()` will be called which will fetch the correct decimal value. In case the `updateDecimals()` fetch fails, then the value of decimals will be assigned as 0 while serializing the token.
