### ISSUE TITLE
Do not show the ethereum logo on the base currency balance for non-eth networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10573]
The use of non-eth-mainnet networks is growing dramatically, we need to be cleaning up any parts of the code that are overly-opinionated to eth.

Currently we show the eth logo on the user's main balance on any chain. We should hide it. Maybe on everything but `chain_id:1`, but I could see the argument to keep it on eth testnets also..

Maybe we should have a `logo` field for our custom network API?

**Comment by brad-decker** [comment]
Fixed in #10413 -- at least partially. We no longer show the eth logo when the native asset is not eth. Probably room for improvement on what to show? 

EIP-3085 specifies a iconUrl, we just don't use it in the extension yet. 

THis issue shouldn't be closed just reworded to improving what we show.

<details>
<summary>Screenshot</summary>

<img src="https://user-images.githubusercontent.com/4448075/109843788-13003100-7c11-11eb-9a38-d792379bed76.png" />


</details>

**Comment by danfinlay** [comment]
Ok I'll leave this open _at least_ for correcting "Send eth" to "Send".
