### ISSUE TITLE
Metamask asking for seed phrase instead of password

### ISSUE THREAD

**Issue by MojoMoe** [MetaMask/metamask-extension#10647]
Metamask worked fine for a few days after installing. About a week or so later when I click on the Metamask Firefox plugin icon, I don't get the option to enter the password, instead I am asked to enter seed phrase and create a new password (which I have done now already and I can access the account). It is possible that this happened after Metamask updated itself on 9th March 2021, to 9.1.1. It worked fine before that date. I only tried logging in before that date, and the date it failed was 13th March.

This happened on the same PC, and the same network. So nothing has changed since the last time I was able to successfully use the old password.

 - OS: Ubuntu 20.04 x64
 - Browser: Firefox Browser 86.0 (64-bit)]
 - MetaMask Version: 9.1.1

**Comment by rogierbattem** [comment]
I was facing the same thing. I can not login to Metamask, but can only see the plugin in the Brave Browser. Instead of a possibility to login with Metamask, Brave Browser asked me for a new wallet password and and gave new seed phrase. 
* Mac OS 10.12.6
* Brave V1.21.76
* Meta Mask 9.1.1

**Comment by rogierbattem** [comment]
I solved my problem. The extension for Metamask in Brave Browser is visible in the top- right symbol for extensions. Clicking the black icon brings you with the wallet-extensions including Metamask, Brave etcetera.

**Comment by tmashuang** [comment]
We've heard of issues with certain updates in previous versions as well. There isn't a clear indicator of how this happens, but have a theory that in the update process some data is overwritten/corrupted and needs deep investigation on the possible causes. This can could caused by new migrations that fail.

**Comment by jacobcantele** [comment]
The Brave issue @rogierbattem is reporting sounds unrelated. We need to understand if any other users have experienced this issue and need to reproduce the issue.

**Comment by malmstrom85** [comment]
Dears at Metamask,
I do have the same problem. 

I am using different blockchains connected to my Metamask account. Strangely Metamask stopped showing login\password screen and instead prompting me to restore the account with Seed Phrase and New Password. 

This is strange because I can access my Metamask account (directly not through a connected blockchain site) with my current password without any problem.

This happens only from a blockchain sites. 

For example I do use VESPER Finance which is automatically connected to metamask. When I do try some operations like deposits of withdrawals a new window pops up asking to restore my metamask account. 

I am therefore unable to complete my operations.

Please can you help me with this strange issue? 

Thank you very much,

Marco

**Comment by rogierbattem** [comment]
Hi Marco & Metamask,

I bypassed my issue temporarily by using the mobile app of Metamask. Here my assets do show. But with Metamask  connected to Brave on desktop Metamask shows no assets, while there are 0,3 eth within the wallet. Transfers are visible though. 
Greatings and regards, Rogier

**Comment by richardsonn09** [comment]
@rogierbattem 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
