### ISSUE TITLE
My Alice-BNB LP show Zero !! Without any action

### ISSUE THREAD

**Issue by sphamm** [MetaMask/metamask-extension#10796]
Steps to Reproduce

Go to My farm
Click on Alice BnB have Cake to harvest but LP Dont show
Expected Behavior
Show the right number of my LP

Additional Context
I connect Yieldwatch and see my LP there but its show on Pancake swap site
![891411E5-F5EA-4E16-B61A-49F600EA9286](https://user-images.githubusercontent.com/3253470/113309010-ee42ca80-9330-11eb-8eea-90e410ee3e4d.jpeg)

**Comment by tmashuang** [comment]
The steps provided to reproduce the issue is not sufficient. Within MetaMask there is no notion of `Farms`, `Alice BnB`, `Cake`, or `LP`. The screenshot you provided is not within MetaMask, I can only assume that it is from some unknown dapp. If you are having dapp issues, I recommend you contacting the dapp.
