### ISSUE TITLE
Can't add liquidity to PancakeSwap using testnet

### ISSUE THREAD

**Issue by mcoelho80** [MetaMask/metamask-extension#10861]
I'm trying to deploy a smart contract using PancakeSwap and testnet.

Unfortunately, it's impossible to add liquidity, because Metamask produces a JavaScript error while estimating gas to complete the transaction.

Here is the error message:

{code: -32603, message: "Internal JSON-RPC error.", data: {…}}
code: -32603
data: {code: -32000, message: "gas required exceeds allowance (30000000) or always failing transaction"}
message: "Internal JSON-RPC error."

Steps to reproduce this problem:

1. Create a token using remix.ethereum.org
2. Deploy using BSC Testnet
3. Access exchange.pancakeswap.finance
4. Try to add some liquidity to your recent created token.

Thank you.

**Comment by mclittle** [comment]
Hello there. I think your problem was caused by from second part of error message "always failing transaction". Wherever I faced this error, it was because of something wrong on my contract calling parameters. The problem can be the contract address to, if you want to use PancakeSwap contract, you should find the testnet address, not the mainnet.

**Comment by danjm** [comment]
@mcoelho80 as @mclittle said, this is likely due to an error in smart contract code. I will close for now, but if you have corrected and verified your code and this problem is still happening, please open another issue.
