### ISSUE TITLE
Why add 1.5X buffer to estimateGas

### ISSUE THREAD

**Issue by xwartz** [MetaMask/metamask-extension#10913]
**Describe the bug**
I see that the following code makes estimateGas 1.5 times larger, what is the reason for this? 
Will using estimateGas directly cause the transaction to fail?

```js
try {
    const estimatedGas = await estimateGasMethod(paramsForGasEstimate);
    const estimateWithBuffer = addGasBuffer(
      estimatedGas.toString(16),
      blockGasLimit,
      1.5,
    );
    return addHexPrefix(estimateWithBuffer);
  } catch (error) {
    const simulationFailed =
      error.message.includes('Transaction execution error.') ||
      error.message.includes(
        'gas required exceeds allowance or always failing transaction',
      );
    if (simulationFailed) {
      const estimateWithBuffer = addGasBuffer(
        paramsForGasEstimate.gas,
        blockGasLimit,
        1.5,
      );
      return addHexPrefix(estimateWithBuffer);
    }
    throw error;
  }
```
https://github.com/MetaMask/metamask-extension/blob/af3c740b1b/ui/app/pages/send/send.utils.js#L206-L279

**Steps to reproduce (REQUIRED)**
1. Send a token transaction, gasLimit is 1.5 times larger than estimateGas

**Expected behavior**
gasLimit should be equal to estimateGas

**Comment by danfinlay** [comment]
The problem is that `estimateGas` only returns the final gas used, but because of gas refunds, a transaction can actually require more gas during the course of its execution.

We would love if there was a version of `estimateGas` that reflected this, like `estimateMaxGas`, but there currently is not, so our best move is to add a safety buffer over the node's estimate.

**Comment by xwartz** [comment]
@danfinlay But why 1.5 times? In most cases, the estimateGas should be enough?
