### ISSUE TITLE
MetaMask can't connect to ledger in Chrome 91

### ISSUE THREAD

**Issue by cryptogohan** [MetaMask/metamask-extension#10925]
**Describe the bug**
Let's get right to the interesting part.
* I tested with multiple ledgers. None work.
* Tested with multiple chrome profiles, even a new one, none work.
* Reinstalled MetaMask extension, doesn't work.
* Cleared files and image cache, nope.
* Reset NVRAM (Ledger recommended this ¯\\_(ツ)_/¯ ).
* .. tested in Brave with MetaMask, works!

**Steps to reproduce (REQUIRED)**
* Chrome 91.0.4472.19.
* New profile, install metamask
* Connect, unlock ledger, open ethereum app
* MetaMask -> Connect Hardware Wallet
> We had trouble connecting to your ledger, try reviewing our hardware wallet connection guide and try again.

Chrome console shows:

> TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

![Screenshot 2021-05-26 at 15 04 02](https://user-images.githubusercontent.com/80852256/119664525-b4bfa480-be33-11eb-87f5-545b41f66051.png)

**Expected behavior**
Connected hardware wallet.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: MacOS
 - Hardware Wallet: Ledger Nano S Firmware version 1.6.6]
 - Browser: Chrome Version 91.0.4472.19 (Beta Build) (64-bit)
 - MetaMask Version: 9.4.0

**Additional context (Error Messages, etc.)**

**Comment by cryptogohan** [comment]
Installed Chrome Stable, working now. Unsure if it had anything to do with that. I'll leave this open so whomever closes this might have a clue if people start reporting the same issue with Chrome 91.

Feel free to close 👍 .

**Comment by bkbooth** [comment]
Chrome 91 is now stable and I can't connect my Ledger Nano S.

I thought I must have been going crazy because I was using my Ledger and it was yesterday.

I've been doing a bunch of development work with my Ledger recently, so it'd be good to know if @cryptogohan (and others) are seeing this issue too.

- OS: MacOS
- Hardware Wallet: Ledger Nano S Firmware version 2.0.0
- Browser: Chrome Version 91.0.4472.77 (Official Build) (x86_64)
- MetaMask Version: 9.5.4

**Comment by bkbooth** [comment]
My best guess is that Chrome is now preventing using U2F to communicate with Ledger devices.

https://bugs.chromium.org/p/chromium/issues/detail?id=1179077

**Comment by cryptogohan** [comment]
@bkbooth can confirm. Updated this morning, communication with Ledger suddenly stopped working.

@darkwing I'd suggest we re-open this ASAP, you're probably about to get a flood-wave of unhappy users 😬 . I'll create a new issue to draw attention.

**Comment by cryptogohan** [comment]
Hé @agl, I found your handle through the commit that seems involved here. (Not sure! but looks like it to me)

The MetaMask extension shows "4,000,000+ users" in the Chrome webstore. Ledger is one of the, if not the largest supplier of crypto hardware wallets. I thought perhaps you'd be interested in offering your view on what the MetaMask team could do to fix this issue (:

**Comment by agl** [comment]
Chrome supports a postMessage-based Javascript API, and a USB HID protocol, both called U2F. It's for 2nd-factor authentication using security keys, e.g. [these things](https://www.yubico.com/products/security-key/). It involves any website being able to silently send messages to USB devices, which is a little terrifying. Embedded devices on the USB bus are often written in 1990's-style C and, if compromised, their position on the bus allows some very powerful attacks.

This risk is balanced because the browser reconstitutes all the protocol messages and the fields that remain opaque are either not parsed by security keys, or are ciphertexts and thus (shouldn't) be attacker controllable.

However, some devices have decided to advertise themselves on the bus as a security key and tunnel other protocols inside of those opaque fields. There's no way that, when implementing that, these devices weren't aware that it was a dodgy abuse of U2F. I've not looked at Ledger specifically, but even brief experimentation with some others quickly turns up concerning behaviour (which can be exercised by any website that a user visits!)

We don't want to add friction to the security key flow, but we're one BlackHat-talk-seeded-media-circus away from a big mess. Thus Chrome 91, as a first step, requires that signatures from devices claiming to be security keys actually parse as signatures. This doesn't stop tunneling, but I understand that some of these devices can also actually act as security keys and we didn't want to lock any users out. (Devices that decide to update to work around this then become candidates for blocking by VID:PID.)

[WebUSB](https://wicg.github.io/webusb/) and [WebHID](https://wicg.github.io/webhid/) exists for sites (and extensions) to communicate with USB devices. That's not risk free because USB devices are very powerful, but users get to affirmatively allow websites to communicate with a device rather than exposing them to every website visited.

We contacted Ledger about this in December 2020 and they confirmed that they were in the process of moving away from using the U2F API like this, so there might be a solution from Ledger already. (We probably didn't find and alert every affected device, however, because there's not a list of them.)

**Comment by darkwing** [comment]
Hello excellent community members!

Over the past few months we've been working on integrating the Ledger Live bridge as another option for Ledger connectivity.  This work is completed (which is why the issue had been closed) and was due to be released in version 9.6.0, but due to Chrome's v91 release, we're looking to get a hotfix shortly.  We appreciate your patience!

In the mean time, U2F still works in Firefox and Edge, so connecting your Ledger there should allow you to use your device until the Chrome hotfix lands.

**Comment by bkbooth** [comment]
Thanks for the explanation @agl, and thanks for the update @darkwing!

Did MetaMask look at using Ledger [hw-transport-webusb](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-webusb)? If so was there a particular reason it wasn't used? In my understanding it would be difficult with how MetaMask uses an iframe bridge to communicate with Ledger devices, and requiring a user interaction event to request WebUsb access.

**Comment by unnawut** [comment]
> In the mean time, U2F still works in Firefox, Brave, and Edge, so connecting your Ledger there should allow you to use your device until the Chrome hotfix lands.

I'm now experiencing this issue on Brave as the latest Brave version now uses Chrome 91.

![image](https://user-images.githubusercontent.com/921194/120205948-c6021a00-c254-11eb-959e-4ab461a49c80.png)

**Comment by andy0130tw** [comment]
I noticed that there is already an issue for this: #8100.

**Comment by cryptogohan** [comment]
@andy0130tw mmm, not exactly I'd say. I'll actually go ahead and close this one now. MetaMask recently released an update to use the Ledger Live bridge so that now MetaMask can connect to Ledgers in Chrome 91 🙌 . Issue closed!

If I understand the other issue correctly that one is about using webUSB. It's a bit ambiguous if the issue wants the webUSB module to be used period, or if the use of the bridge makes it superfluous but I'll leave that to the people over there to decide 😄 .
