### ISSUE TITLE
"Approve" confirmation says "Unlimited" even though it's not

### ISSUE THREAD

**Issue by tennox** [MetaMask/metamask-extension#11125]
**Describe the bug**
Follow-up to https://github.com/MetaMask/Design/issues/38 and in specific this comment by @pi0neerpat https://github.com/MetaMask/Design/issues/38#issuecomment-651469823 as @Gudahtt requested to open a new issue.

I encountered that MetaMask would show "Unlimited" even though I requested a specific (small) amount:
![Screenshot from 2021-05-18 13-15-45](https://user-images.githubusercontent.com/2084639/118643334-b6a6b980-b7dc-11eb-8b08-a935d87bfbca.png)

Only in case of requesting `0` it would show the expected "Proposed Approval Limit":
![Screenshot from 2021-05-18 13-33-46](https://user-images.githubusercontent.com/2084639/118644356-033ec480-b7de-11eb-9b66-af846a73134b.png)

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. `tokenContract.approve(spenderAddress, BigNumber.from(ethers.constants.WeiPerEther))`
2. Click on 'Edit permissions'

**Expected behavior**
Show **"Proposed Approval Limit"** UI except when the amount is the maximum uint265 amount `1.157...e+59`

**Browser details (please complete the following information):**
 - OS: Pop!OS
 - Browser: Version 1.24.64 Chromium: 90.0.4430.72 (Official Build) beta (64-bit)
 - MetaMask Version: 9.5.2

**Comment by TeNNoX** [comment]
See also: https://github.com/ethereum/EIPs/issues/717

**Comment by danjm** [comment]
To reproduce using https://metamask.github.io/test-dapp/:

1. Switch to a Rinkeby or Ropsten account that has some ETH
2. Go to https://metamask.github.io/test-dapp/
3. Connect
4. Click the "Create Token" button and confirm the transaction in the popup
5. Wait for the transaction to be confirmed
6. Once the transaction is confirm, the contract address will appear under the "Token:" label in the "Send Tokens" section of the test dapp page.
7. Copy the token contract address
8. Open MetaMask in a new tab, so that the test dapp remains open.
9. Click "Import Tokens" on the main screen of MetaMask.
9. Paste the copied address in the "Token Contract Address" field
10. Click "Add Custom Token" and confirm
11. Using the send feature within MetaMask, send 5 of the newly added TST tokens to another one of your MetaMask accounts
12. After the send is complete, you should have 5 TST in your current account
13. Go back to the tab where you first opened https://metamask.github.io/test-dapp/
14. Click the "Approve Tokens" button
15. On the confirmation screen, click "View full transaction details" and then "Edit" in the "Permission" section

You should now see it say "Unlimited"

I believe this is what appens when the requested approval amount is greater than the users current token balance.
