### ISSUE TITLE
Confirmation screen should show local nicknames even when invoking a contract method

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11148]
When sending to a contract, even if the user adds the address to their address book (adding a nickname) in the send view, the confirmation screen does not show the nickname.

Ideally, we always show a local nickname instead of an address if one is available.

**Comment by namrapatel** [comment]
hello! to clarify, is the task here to show the Local Nickname (in my case it's "cWBTC"), instead of showing the existing Contract Nickname, which appears to be "Compound..." in my case?

<img width="358" alt="Screen Shot 2021-06-28 at 1 53 04 PM" src="https://user-images.githubusercontent.com/25423974/123695750-c966d200-d80f-11eb-8ded-d401a77b5805.png">
