### ISSUE TITLE
Ledger Live bridge in Ubuntu 20.04

### ISSUE THREAD

**Issue by cyberducketh** [MetaMask/metamask-extension#11219]
Is the latest Ledger Live bridge for Chromium browsers supported on Ubuntu 20.04? I switched on the toggle, restarted browser, have Ledger Live running, and nothing happens when I try to get a transaction through to my ledger.

**Comment by Gudahtt** [comment]
Unfortunately Ledger Live does not appear to support the Ledger Live bridge on Linux. We've been talking with the Ledger team about addressing this issue, but I'm not yet sure why it doesn't work, or when it might be fixed.

The easiest workaround is to use Firefox instead. There is a way to get it working on Chrome, but it requires running the Ledger Live bridge script manually from the command line. Here are the steps:

* [Install Node.js](https://nodejs.org/en/) (I've tested this with Node v12 and v14)
* Install the `ledger-live` package globally (`npm install -g ledger-live`)
  * Note that this is _very slow_, and may produce a bunch of warnings and errors despite succeeding.
* Run this command to start the Ledger Live bridge: `npx --no-install ledger-live proxy -v`

Once the bridge is running, you should see debug output whenever MetaMask tries to connect to it (omit the `-v` flag if you don't want to see this). Unfortunately I don't know of a way of gracefully stopping the proxy - I'd suggest closing the terminal altogether or pressing CTRL+C a few times, until it gives up on interrupting and finally kills the process.

Not a simple workaround, but it seems to work at least! I've tested this on PopOS 20.10 (based on Ubuntu 20.10), using a Ledger Nano X. I'd be interested to hear whether it works with other distros/versions and devices.

**Comment by DMats** [comment]
I am also running into this issue.  Eagerly awaiting a fix.

**Comment by darkwing** [comment]
We've been in touch with the Ledger team and they know that there is an issue on some Linux platforms.  The easiest path forward is using Firefox until the Ledger team makes Ledger Live more accessible on Linux.

**Comment by DMats** [comment]
Since I didn't want to set up Firefox, I followed the instructions posted by @Gudahtt.  

I'm on Ubuntu 20.04 LTS. I used Node v14.17.0 installed from the [nodesource PPA](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

I installed ledger-live locally in my user home directory because I got errors while attempting a global install.

```console
cd
npm install ledger-live
npx ledger-live proxy -v
```

**Comment by SCBuergel** [comment]
This does not work for me. I followed the instructions, then attempted to connect HW wallet in MM, selected ledger and it still showed the `Internal JSON-RPC error.` msg.

When ledger live starts I observe the following output in the npx command line output though:
```
Checking for update
Update for version 2.29.0 is not available (latest version: 2.29.0, downgrade is disallowed).
spawned internal process 6286
```

**Comment by SCBuergel** [comment]
still the same - not able to make it work though now I do not get the above error message of some update not available, simply `Internal JSON-RPC error.`

```
$ npx ledger-live proxy -v
proxy: DEVICE_PROXY_URL=ws://localhost:8435
proxy: DEVICE_PROXY_URL=ws://192.168.178.135:8435
proxy: 
Nano S proxy started on 192.168.178.135
```
and some more version details:
```
$ npx ledger-live version
ledger-live cli: 19.10.0
@ledgerhq/live-common: 19.11.3
@ledgerhq/ledger-core: 6.11.3
libcore: 3.5.0
$ node --version
v12.19.0
$ npx --version
6.14.8
```

**Comment by arno01** [comment]
Firefox is not an option since it does not support [Keplr](https://github.com/chainapsis/keplr-extension) where one would need both MetaMask & Keplr, e.g. Sifchain DEX needs that.

The MetaMask and Ledger Nano X combination is working for me.
Hoping the following will make it working for you too.

OS: Linux on **Ubuntu 20.04**.3 LTS
Browser: **Google Chrome** Version 92.0.4515.159 (Official Build) (64-bit)

Since I'm using **AppImage**, browser can't open `ledgerlive://bridge?appName=Ethereum` as there is no `ledgerlive` scheme handler.
You need to either start the Ledger Live Desktop bridge manually (Option A.) or create the `ledgerlive` desktop file pointing to your Ledger Live Desktop **AppImage** so that you will get the scheme handler registered. (Option B.)

## Option A. Start the Ledger Live Desktop bridge manually (workaround)

To open the bridge, start your Ledger Live Desktop and then type the following in the terminal:

```
ledger-live-desktop-2.32.2-linux-x86_64.AppImage ledgerlive://bridge?appName=Ethereum
```

You will see the following:

![image](https://user-images.githubusercontent.com/3791945/130479716-aa0873f8-c40c-46cd-9de0-e2276b2b71d0.png)

You will also see it is now listening over the 8435/tcp port now:

![image](https://user-images.githubusercontent.com/3791945/130479785-2c795365-373f-4583-8ed9-b7b106db6137.png)


## Option B. Register ledgerlive protocol with xdg (permanent fix)

Create a file named `ledgerlive.desktop` in `~/.local/share/applications/` with the following content:

> Update `/path/to/ledger-live-desktop-2.32.2-linux-x86_64.AppImage` to your actual Ledger Live desktop appimage!

```
[Desktop Entry]
Name=Ledger Live
Exec=/path/to/ledger-live-desktop-2.32.2-linux-x86_64.AppImage
Type=Application
Categories=Finance; 
Terminal=false
MimeType=x-scheme-handler/ledgerlive;
```

Then run:

```
sudo update-desktop-database
xdg-mime default ledgerlive.desktop x-scheme-handler/ledgerlive
```

Now you can either start it via the browser (as you would normally do it with MetaMask) or test it manually in the terminal to make sure XDG registered it properly:

```
xdg-open ledgerlive://bridge?appName=Ethereum
```


That's all.

**Comment by dpazdan** [comment]
Please note we will be deprecating the ledger live bridge and implementing webhid support. This will likely resolve your issue. In the meantime continue to use the Firefox workaround. Refer to: #11978, thanks!

**Comment by DMats** [comment]
I'm still using the solution described by @Gudahtt using the ledger live bridge with Brave browser and that I described in my previous comment https://github.com/MetaMask/metamask-extension/issues/11219#issuecomment-858041001

Are you saying this method will stop working before webhid is implemented and released?

**Comment by MattiasBurstrom** [comment]
> Please note we will be deprecating the ledger live bridge and implementing webhid support. This will likely resolve your issue. In the meantime continue to use the Firefox workaround. Refer to: #11978, thanks!

When can this update be expected?

**Comment by darkwing** [comment]
Ledger Live will still work once we release WebHID.

**Comment by andresmatasuarez** [comment]
when is webhid support expected to be released? I'm seldom able to make MM work with Ledger using the Ledger Live bridge, it's a 30/70 chance I'd say

**Comment by dimyself** [comment]
Save thing here... On Arch, latest firmwares. I CAN connect to Brave wallet using Ledger nano. But, not MM. It just stalls at "looking for ledger device" spinning.

**Comment by AlexJupiter** [comment]
WebHID has been released now (https://consensys.net/blog/metamask/metamask-and-ledger-integration-fixed/). Is anyone still experiencing this problem? Otherwise I'll move to closing this issue.

**Comment by Waxxx333** [comment]
> 

You're the GOAT

**Comment by dimyself** [comment]
Hmm, its STILL not working for me ugh!

I dont know whats going on, or where exactly the problem lies, but I
haven't been able to connect my Ledger to Metamask for a long time.

I'm using Brave. In Brave nothing I do will work with Metamask Ledger
connection (Brave wallet DOES work to connect to ledger however)...

I'm using Arch linux. Chromium metamask will connect to ledger.

Only Brave has this problem!

But also, anytime I change a setting (ex. Advanced -> change U2F -> to
Webhid)... My settings just spin. I have to refresh the page to get
rid of the metamask spin.

I updated metamask to the latest version 10.12.4, latest ledger ETH
app, and brave to its latest version. Nothing has changed for me. When
I try to connect to my ledger, it still just spins and says "looking
for ledger".

Not sure if its an issue with just Brave, or metamask in brave

It is very annoying, I use Brave. And I have to use Chromium for all
ledger things.

Thanks!

**Comment by 0xKonstantin** [comment]
Hey all, 

commenting here and reopening this as I can't find an answer to save my life.

I have an issue connecting my ledger to any browser extension in Ubuntu 23.10, both in a VM and a bootable USB. I can get the ledger to be detected and work with certain app-based wallets, but MM, Phantom, and Kepler neither will actually connect. It will either do nothing when I click ledger, or will say i rejected the signature when I never even was prompted any recommendations here?

**Comment by blahah** [comment]
@0xKonstantin do

```sh
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo sh
```

Then it should work.
