### ISSUE TITLE
Can't connect to Ledger on Brave (Ubuntu)

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-extension#11222]
**Describe the bug**
Metamask cannot find Ledger on Chrome or Brave, Firefox works though.

**Steps to reproduce (REQUIRED)**
1. Go to 'Connect Hardware Wallet'
2. Click on 'Ledger'
4. See error: Nothing happens, keeps saying 'Looking for your Ledger...' and eventualy 'Internal JSON-RPC error.'

**Expected behavior**
Expected to show me the accounts from my Ledger.

Alternatively, I expected to see the "Use Ledger Live" settings from the advanced settings but it's not there.

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Hardware Wallet: Ledger Nano X, Firmware 1.3.0 (latest)
 - Browser:
   - Brave: Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit) -> doesn't work
 - MetaMask Version: 9.5.7

**Additional context (Error Messages, etc.)**
Both Ledger Live and Metamask on Firefox are able to connect to my Ledger Nano X.

**Comment by Gudahtt** [comment]
Thanks for the report! The Ledger Live setting had to be recalled in 9.5.7 due to an unrelated regression, and was re-added in v9.5.8. This version should now be deployed to all users, so you should see that setting again now.

Though on Linux it still won't work unfortunately, which is covered by #11219. Please see that issue for the workaround, and to be informed of further updates to the situation.
