### ISSUE TITLE
v9.5.9 on Firefox does not update gas limit for erc20 from main send button

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#11255]
**Describe the bug**
When trying to send ERC20 tokens from the main SEND button, gas limits do not change from the preset 21000 that is already displayed for ETH.  

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open MM
2. Click Send
3. Scroll down to any ERC20 token 
4. See gas estimates not change
5. Some users might proceed and the tx will always fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/121278297-edca3100-c897-11eb-9773-b27da868efed.png)
![image](https://user-images.githubusercontent.com/16330048/121278307-f1f64e80-c897-11eb-8602-8c4aeaa4d0e8.png)
![image](https://user-images.githubusercontent.com/16330048/121278314-f589d580-c897-11eb-97fa-816546ff315e.png)

 probably related: https://github.com/MetaMask/metamask-extension/issues/3923#issuecomment-851865897

**Comment by danjm** [comment]
Dan  8 hours ago
so I have not been able to understand why yet, but this bug happens because estimatedGas on line 256 of send.utils.js, which is ultimately a result of an async call to the estimateGas method on the metamask controller, is an object (resembling a BN object, but its prototype is just an object... i.e. it doesn't have any BN methods) in firefox, but a hex string in chrome
I am guessing this is related to the dnode change. Does that sound right @mark.stacey?

Mark 7 hours ago
Hmm. Not sure I follow how this could be transport-related. An object and a hex string are fairly different

Mark  7 hours ago
Oh, wait, you're suggesting that the prototype is stripped from the object on Firefox so it's not serialized to a string properly. I see, yeah that's a good theory.
:heavy_plus_sign:

Dan  7 hours ago
yeah, something like that

Mark  7 hours ago
I have noticed differences between Firefox and Chrome in how the port stream serializes data. Chrome converts undefined properties to null for example, whereas Firefox does not. I wasn't aware of anything like this though.

Mark  7 hours ago
As a general rule we should only be sending JSON between processes, that's it. Not BN or anything with a prototype. That's all the API is meant to support, and that's all that works consistently between browsers.
So the solution might be to normalize the value to a string in the background before sending it.

Dan  7 hours ago
> So the solution might be to normalize the value to a string in the background before sending it.
That sounds like a good solution
