### ISSUE TITLE
Ubuntu closes popup on file prompt

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1136]
This means Ubuntu/Linux(?) users cannot use the JSON import feature.

**Comment by flyswatter** [comment]
This means account importing needs to be done from a new window, not from the popup for Ubuntu.

A new argument for that!  I'll add it to the big list!  Sooooon....

**Comment by flyswatter** [comment]
Experiment with opening a new popup when clicking the fox?

**Comment by flyswatter** [comment]
We need to open an issue with chrome, then we can mark this as blocked.

**Comment by Zanibas** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=721455
submitted

**Comment by flyswatter** [comment]
A little workaround hack is to visit the popup UI in your main browser tab by visiting:
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html

**Comment by QingyangKong** [comment]
is this solved?

**Comment by Zanibas** [comment]
I believe this is still broken unfortunately, but our new UI will have the ability to go to a tab from the app itself instead of that workaround up there.

**Comment by tmashuang** [comment]
Closing, workaround is in master to popup MetaMask on browser tab.

**Comment by sxiii** [comment]
2021, still the same issue. Workaround does not help at all, because my popup window has no top bar and, hence, no "Import account" option for me.

**Comment by kewpiedoll** [comment]
Can someone explain how to "pop up" metamask in firefox. A user clicks on the Fox. The app opens. A user clicks anywhere else, it closes. This means one cannot import the json file because that closes it as well.

**Comment by aspiers** [comment]
Option 1:

Make a stupidly simple and obvious change to the UI which:

- checks whether the user is trying to import JSON from within a popup
- helpfully opens MetaMask in a new tab, or at least **explain to the user that's not possible due to browser limitations, that they need to open it a new tab themselves, and briefly describe how to do that**

Option 2:

Do nothing except close this issue, so that for the forseeable future users trying to import JSON from the popup get hopelessly confused by how NOTHING HAPPENS and their file doesn't get imported. Then witness a constant stream of duplicate issues being opened over the next few years.

Hmm, I wonder which one is more sensible?

Sorry for the sarcasm, I'm sleep deprived and in a bad mood, but it really astonishes me how developers can be so blind to putting themselves in users's shoes and making stupidly simple tweaks which can a huge improvement to UX.  But this seems to be a general theme with MetaMask so it's not so surprising.  I guess the Consensys team is chronically underfunded or something.

BTW, when I import from a tab, it warns it may take a while, then freezes the whole tab and extension for a few minutes. Nice.

**Comment by qiujiangkun** [comment]
The workaround is also broken. I have no place to "Import json file"
![image](https://user-images.githubusercontent.com/33482468/152120058-cf26c50b-fdd4-4f2b-839f-c1a2143a1a22.png)


> 2021, still the same issue. Workaround does not help at all, because my popup window has no top bar and, hence, no "Import account" option for me.

**Comment by qiujiangkun** [comment]
Another work around:
Inspect(F12) on the pop ups, then the pop ups will not close automatically.
