### ISSUE TITLE
Incorrect balance on Arbitrum

### ISSUE THREAD

**Issue by willhennessy** [MetaMask/metamask-extension#11378]
**Describe the bug**
Metamask extension displays the incorrect balance on Arbitrum network.

**Steps to reproduce (REQUIRED)**
1. Visit https://bridge.arbitrum.io/
2. Connect to Arbitrum's  _Rinkeby public testnet_
3. Deposit 0.1 ETH from Rinkeby L1 to the Bridge
4. Wait a few minutes for the bridge tx to complete
5. Observe correct wallet balance in the bridge web interface (0.099... ETH)
6. Observe incorrect wallet balance in the metamask extension (198.3... ETH)

**Expected behavior**
Metamask should show a balance of 0.099 ETH

**Screenshots**
<img width="1259" alt="Screen Shot 2021-06-24 at 12 40 42 PM" src="https://user-images.githubusercontent.com/5455577/123301431-a5db1900-d4e9-11eb-9e31-7053e5943082.png">

**Browser details (please complete the following information):**
 - OS: OX X
 - Browser: Chrome 91.0.4472.114
 - MetaMask Version: 0.6.1

**Comment by jejopl** [comment]
It's showing USD value instead of ETH value. I have the same issue when I'm connecting metamask with my local ganache-cli blockchain. 

More people have the simillar issue, you can visit this one and see last two comments:
https://github.com/MetaMask/metamask-extension/issues/6580

**Comment by brad-decker** [comment]
Might be related to #9492 ? cc @adonesky1

**Comment by adonesky1** [comment]
> Might be related to #9492 ? cc @adonesky1

I'll take a look!

**Comment by adonesky1** [comment]
@willhennessy, for the short term,  if you go into your network settings and add ETH as the currency symbol, this conversionRate issue should go away:
<img width="437" alt="Screen Shot 2021-06-25 at 12 06 03 PM" src="https://user-images.githubusercontent.com/34557516/123460748-b8b72180-d5ad-11eb-8c6e-76c21ffe4800.png">

Let me know if that doesn't work though?

In our next release we have a fix for this issue, so that no manual followup (like the one recommended above) is required.

**Comment by willhennessy** [comment]
Great, the workaround works and I'm glad the fix is releasing soon! We're excited for Arbitrum to open up the allowlist on mainnet in a week or two, so very thankful you're on top of this!
