### ISSUE TITLE
Show function params on tx confirmation screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1142]
I think I'd been waiting for an on-chain version of this, but we could make great progress by leveraging 4byte.directory:

https://www.4byte.directory/docs/

We could even make the method parameters editable right on the tx approval screen.

**Comment by flyswatter** [comment]
From @micahzoltu:

Parity launched a method registry dApp a while back that allows contract authors to publish the ABI of their contracts to Ethereum so that signers (e.g., MetaMask, Parity, etc.) can display to the user the name of the function being signed and the parameters being passed rather than just telling the user "you are signing a thing!".

In order to provide users with more confidence that the dApp they are calling is doing something reasonable/expected, it would be nice if MetaMask supported using this registry to display contract information.

The registry can be found here: https://github.com/paritytech/contracts/blob/master/SignatureReg.sol As far as I know, the UI for the dApp is only available in Parity, but presumably it could be hosted elsewhere fairly easily.

This is what the Parity UI looks like when using the register metadata:
![image](https://cloud.githubusercontent.com/assets/886059/26279112/c54a60aa-3d5f-11e7-8c1f-af779492cc3b.png)

**Comment by Zanibas** [comment]
* Needs Design
        * Schedule a meeting with Christian

**Comment by stefek99** [comment]
Repost: https://github.com/MetaMask/metamask-extension/issues/1925#issuecomment-331729721

Serious money is (could be) on the line.

**Comment by dchudz** [comment]
Maybe a quick option would be just to show the (not human readable) raw tx data, and rely on other tools to help users figure out (to the extent possible) what those bits mean in the context of the contract they're sending to?

(Just as a holdover until something better can be implemented.)

**Comment by danfinlay** [comment]
Closing in favor of #2847.
