### ISSUE TITLE
Metamask don't work Tor Browser+Trezor

### ISSUE THREAD

**Issue by bug-repport** [MetaMask/metamask-extension#11502]
Metamask dont't work in the Tor Browser + Trezor.

1. Install Trezor Bridge 2.0.27.
2. Install Tor Browser.
3. Install the Metamask plugin.
4. Change the Tor Browser settings in about: config:

user_pref ("privacy.firstparty.isolate", false);
user_pref("network.proxy.no_proxies_on", "127.0.0.1");

5. Change the Tor Browser settings in Options:

Privacy & Security > Block pop-up windows (uncheckbox)

6. Connect Trezor and enter the PIN code if installed.
7. Go to the website https://www.myetherwallet.com/ and check the work of Trezor, then close the page.
8. Click the Metamask plugin > Connect Hardware Wallet > Trezor > Continue.
9. We get the error: "Popup error: Unable to establish connection with iframe".

![myetherwallet+metamask](https://user-images.githubusercontent.com/59339852/125206544-63e6fc80-e277-11eb-9fc9-67cf2c04be64.gif)

Browser Information:
OS: Windows 10
Hardware Wallet: Trezor T, Firmware version 2.4.0
Browser: Tor Browser 10.5 (based on Mozilla Firefox 78.11.0esr) (64-bit)
MetaMask Version: 9.7.1

**Comment by brianddk** [comment]
A reddit thread that may be related: https://www.reddit.com/r/TREZOR/comments/og575n/

**Comment by Rachelmorgan6** [comment]
Hi
I had a similar situation but it’s been fixed by the Metamask support team, you’ll need to text them through their number on WhatsApp +1 562-473-3934, they replied me instantly and fixed all my issues

**Comment by kevinghim** [comment]
MetaMask Support team does not have a WhatApp. If you contact that number,
it'll lead to a phishing attempt. Please do not contact that WhatsApp
number. All MetaMask support queries should be done at MetaMask Support
https://metamask.zendesk.com/hc/en-us.

**Comment by BreakStacks** [comment]
Wow guys! Last version Tor Browser is worked Metamask + Trezor :D

11.0 (based on Mozilla Firefox 91.3.0esr) (64-bit)

**Comment by AlexJupiter** [comment]
Closing this due to this bug reportedly being fixed.

**Comment by brianddk** [comment]
Anyone reading this issue later, I seriously doubt anything in MM or Trezor fixed it, likely "fix" is to simply use obscure Tor bridges.  Many CDN networks and DDoS proxies like Cloudflare will block known Tor exit relays.  By obscuring your Tor relay's with bridges you can fool the CDNs for a while.

I eventually found that most of my problems in Tor could be fixed by about ten retries, with a new bridge on each attempt.

Only real fix is to provide onion endpoints for all the CDN content.  Apps like Electrum offer this option up, but I don't see that enabled in MM yet.  Trezor did transition all their CDN content to onion, but I don't see MM using the onion links for Trezor Connect.
