### ISSUE TITLE
Brave web3 + Metamask 9.8.2 not working

### ISSUE THREAD

**Issue by jcp3alex** [MetaMask/metamask-extension#11623]
Ever since the update to 9.8.2 MetaMask fails to connect to web3 websites on Brave browser. Up until today, I was able to get it working by uninstalling the addon and re-installing the addon, but today that doesn't work any longer. Sometimes I will get a Metamask pop-up, independent of the addon that I can sign in to, but it happens randomly. I have tried re-installing after I shut down my PC, but that doesn't work either,

**Comment by sfaujour** [comment]
@jcp3alex My current fix on brave was to visit brave://extensions/ and to turn off the default "crypto wallet" extension.. now it seems to be working

**Comment by jcp3alex** [comment]
That didn't work for me, the only way I can use Metamask right now is from within the crypto wallet built into the browser.

**Comment by jacobcantele** [comment]
Hi this is actually an issue with Brave, rather than MetaMask. You can solve this issue by navigating to brave://settings/extensions and selecting MetaMask as your wallet provider. 
![Screenshot from 2021-11-11 16-48-47](https://user-images.githubusercontent.com/10467486/141380549-18b14d45-4d75-4d79-bdde-0936802009c2.png)
