### ISSUE TITLE
EIP-1559 - The EditGasPopover Submit Button Stays Disabled

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#11642]
Sometimes the "Submit" button of the EditGasPopover is disabled when it shouldn't be:

<img width="365" alt="DisabledButton" src="https://user-images.githubusercontent.com/46655/127225260-2e6a1642-3832-4002-b6db-9d0a9fb4c00c.png">

At present we check `hasGasErrors || isGasEstimatesLoading` to see if we should disable the button, and it looks like `isGasEstimatesLoading` stays `true` when it shouldn't.

**Comment by PeterYinusa** [comment]
Steps:

1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Edit link in the Estimate gas fee section
6. Block the request to the gas api `/suggestedGasFees`

Expected behavior:
- The Submit button is enabled after the request has failed
