### ISSUE TITLE
Cannot reconnect to ledger

### ISSUE THREAD

**Issue by lonnylot** [MetaMask/metamask-extension#11715]
**Describe the bug**
When I initially connect a wallet it prompts me for the device bridge, which works successfully.

On subsequent connects I am not prompted for the device bridge anymore.

This worked find on July 8th. I don't think I've used it from then until now.

**Steps to reproduce (REQUIRED)**
1. Turn on 'ledger live', connect to new ledger, enable device bridge
2. Disconnect
3. Try to reconnect

**Expected behavior**
Re-prompt for device bridge

**Browser details (please complete the following information):**
 - OS: 11.5 (20G71)
 - Hardware Wallet: Ledger Nano X Firmware 1.8.8
 - Browser: Chrome 92.0.4515.107
 - MetaMask Version: 9.8.4

**Comment by darkwing** [comment]
@lonnylot If you have a moment, could you go into Settings > Advanced, then toggle the Ledger Live setting to "off", then "on" again.  Does that temporarily fix the issue?

**Comment by lonnylot** [comment]
@darkwing no. I tried that and still no prompt

**Comment by lonnylot** [comment]
I found my updated Ledger Eth. firmware switched 'allow contract data in transactions' back to 'disallowed'. Once I switched it back to 'allowed' everything started working as expected.

@darkwing Perhaps it's worth updating a help doc saying this can happen on update?

**Comment by TalkCryptoToMeBaby** [comment]
I'm also having this issues, tho I'm on polygon and bsc. Same behavior though.

After confirming in metamask ledger bridge does not prompt and cannot approve on ledger. 

**Steps to reproduce** (REQUIRED)

1. Turn on 'ledger live', connect to usb to ledger
2. Allow contract data on ledger s eth app
3. Connect to pkswap (BSC)/qswap (polygon) on desktop
4. approve contract
5. confirm in metamask
6. (device bridge does not prompt, cannot approve on ledger device)
7. switch networks (cancel txn)
8. switch network back 

MM error: 
```
Transaction NaN failed! Error: Transaction found as "approved" during boot - possibly stuck during signing
```

**Expected behavior**
Prompt for device bridge, then approve on ledger device

Ledget Live: v2.31.1
Hardware Wallet: Ledger Nano S Firmware 2.0.0
Browser: Brave chromium 92.0.4515.115
MetaMask Version: 9.8.4

**Comment by dpazdan** [comment]
Please note we will be deprecating the ledger live bridge and implementing webhid support. This will likely resolve your issue. In the meantime you can continue to use this method or use Firefox + MM + Ledger. Refer to: #11978, thanks!

**Comment by jacobcantele** [comment]
Hi friends, the new Ledger integration is now live in MetaMask 10.5. It is no longer necessary to use Ledger Live. You can reconnect your hardware wallet using the new integration.
