### ISSUE TITLE
Trezor pairing broken

### ISSUE THREAD

**Issue by vying1** [MetaMask/metamask-extension#11809]
Issue is with version 10.0.0.  During pairing of a Trezor the extension attempts to load 

chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/trezor-usb-permissions.html

This results in

Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

**Comment by darkwing** [comment]
I just paired Trezor with both Chrome and Firefox, on latest firmware, with no issue.  What model of Trezor?  Could you provide a screenshot of the JavaScript console so we can see if there are more errors?

**Comment by vying1** [comment]
You're probably using Trezor Bridge.  The error is with WebUSB.  To reproduce, uninstall Trezor Bridge and use Chrome.  This will trigger the WebUSB path, which will cause the error.

**Comment by SerhiiMorozov** [comment]
I have the same error
ERR_FILE_NOT_FOUND
Trezor Bridge not installed

**Comment by ipha** [comment]
Steps to reproduce:

1) Ensure Trezor Bridge/trezord is uninstalled or disabled so that WebUSB is used instead.
2) Connect a new hardware wallet
3) Select Trezor
4) Connect Trezor and select Pair devices
*) Error is displayed here and can not proceed. URL of error is `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/trezor-usb-permissions.html`

![image](https://user-images.githubusercontent.com/924797/129824425-472afe8e-152f-42ba-8524-f57af5c0d510.png)
![image](https://user-images.githubusercontent.com/924797/129824448-3bfdaf43-b133-486b-aab2-41767b2b692e.png)
![image](https://user-images.githubusercontent.com/924797/129824485-101f27e9-3421-4903-bef2-615fb70681b5.png)

**Comment by ipha** [comment]
This broke at commit 9f4820ee987ac6d2af382f1a6672dad97bac8d47

After this, app/trezor-usb-permissions.html isn't getting copied to the package. If I manually copy it to dist/chromium, trezor pairing works.

**Comment by danjm** [comment]
Thanks for the contribution, we will review asap
