### ISSUE TITLE
Rinkeby Testnet Swaps - funny business (not registering new Token, wrong quotes,...)

### ISSUE THREAD

**Issue by HeroHann** [MetaMask/metamask-extension#11839]
**Describe the bug**
I am Testing the Swaps feature (which is only available on Mainnet and Rinkeby). When Swapping the transaction works normally, but the new Tokens are not shown in the "Tokens"-tab. Furthermore the quote is really wrong. The Quote on Uniswap is way different and in most cases way better.

**Steps to reproduce (REQUIRED)**
Setup a Metamask Wallet
Switch to Rinkeby
Swap some Testet ETH to UNI (or any other Token)
Watch as the tx is being confirmed, but the tokens are not shown.

Go to Uniswaps DEX and Swap some Testet ETH to UNI
See as it works without Problems and the Tokens show up in the "Tokens"-Tab.
The quote is way different than what the Metamask Swap feature tells the user (like 1000x less)

**Expected behavior**
Expected would be to get the same quotes as on Uniswap (or better when available) and also to register the new tokens in the tokens tab.

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Brave
 - MetaMask Version: 10.0

**Additional context (Error Messages, etc.)**
I would also like to mention, that the swap feature should IMO work in any testnet. Maybe make Ropsten available also...

**Comment by dan437** [comment]
Hi, thanks for reporting this and giving us your feedback! We enabled Swaps on Rinkeby for internal testing purposes while we were testing EIP-1559. The reason why you don't see a target token after a swap is because we don't have our Swaps smart contract deployed on Rinkeby.

We also recently disabled Swaps on Rinkeby in production, which should go live soon and then only selected mainnets will be allowed for Swaps: https://github.com/MetaMask/metamask-extension/pull/14372

If there would be more demand for supporting testnets in Swaps, we can reconsider doing it in the future.
