### ISSUE TITLE
"Advanced gas control" option ineffective in newest updates

### ISSUE THREAD

**Issue by PhiMarHal** [MetaMask/metamask-extension#11923]
Toggling the advanced gas control option on and off doesn't change behavior at all in newest versions of Metamask.

With either choice, there is first an "edit" button on top of the gas fee in the transaction page, which then leads to a warning about the suggested gas fee, and takes another click to get to gas controls.

Expected behavior: see older versions. Let us edit gas price and gas limit directly in the transaction page if the "advanced gas control" option is enabled.

**Comment by beeb** [comment]
Agreed, this is very annoying. The option is currently useless.

**Comment by beeb** [comment]
> I believe this will be addressed by #11916

Will that work for PoS or PoA chains?

**Comment by mats-42** [comment]
I have the same problem. From my support ticket:

Since about 2-3 weeks ago I cannot access the advanced gas controls directly in the buy/confirm screens anymore, even though I have the setting activated under Settings > Advanced. I tried emptying my browser cache, and even removing and reinstalling the extension, but nothing helped. 

I use 

- a Mac running MacOS Big Sur 11.5.2 (20G95)
- Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- Metamask Chrome extension Version 10.0.3

I believe this behaviour started with the upgrade to the Chrome extension version 10.0.3.

**Comment by bschorchit** [comment]
Closing as this is not relevant anymore since v2 has already been released. https://github.com/MetaMask/metamask-extension/pull/11916#issuecomment-942474108
