### ISSUE TITLE
Support Webhid for Ledgers and deprecate ledger live bridge

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#11978]
Webusb was broken in new versions of Chrome.  Ledger Live bridge adds a level of complexity to user experience.  Proposing implementing webhid similar to this fork: https://github.com/hectorchu/metamask-extension.

**Comment by Gudahtt** [comment]
>Webusb was broken in new versions of Chrome.

What is this referring to? WebUSB should work just fine as far as I know.

**Comment by artdgn** [comment]
Coming here from https://github.com/MetaMask/metamask-extension/issues/11973

> Please note we will be deprecating the ledger live bridge and implementing webhid support

A couple of questions / suggestions:

1. Is there any post / docs explaining current MM ledger support plans / roadmap / thoughts etc? 

2. It seems that at least in this case the live bridge, with its bad UX and all, still worked and provided an important workaround for otherwise completely broken state and inability to transact. Perhaps instead of deprecating it, it would be best to keep it as option for some sunset time, or at least until there is another workaround (in case the new "main" way fails again for some other reason in the future).

**Comment by DMats** [comment]
I agree with @artdgn. Please do not remove ledger live bridge support until after an alternative is released.

**Comment by arsenicks** [comment]
Definitely agree, it would be great to keep the live bridge support as a backup plan if there's no major security risk involved at least. Indeed it's not user friendly but in case another update break things we will at least have this workaround available!

**Comment by prejudicedad** [comment]
I greatly appreciate all the hardwork you guys have put into improving the MM and Ledger integration. I am currently having a major issue with my integration since restoring my Ledger. Firstly the blind signing doesnt push to my Ledger with WebHID now or Ledger Live Web Socket connect. Also ledger live update banner is not working so I might need to reinstall Ledger Live. However the HD path when I go to connect my Ledger with MM is not showing up. Is this because I already have connected my Hardware wallet and it is only now suggesting new paths? I am at a loss here and would greatly appreciate any advice. Thank you kindly.
