### ISSUE TITLE
Queued transactions getting stuck 

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12001]
We're getting support tickets from users saying their swap transactions are getting stuck.

[User 1:](https://consensys.zendesk.com/agent/tickets/305423)
I attempted to swap PSWAP for ETH within MetaMask and its stuck in pending. On etherscan it says Success. I've read about resetting the account, but it advised to send you the log first, which is attached.

 - OS: Win
 - Hardware Wallet: None
 - Browser: Chrome
 - MetaMask Version: 10.0.2

[User2: ](https://consensys.zendesk.com/agent/tickets/302450)

 - OS: Mac
 - Hardware Wallet: Yes
 - Browser: Chrome
 - MetaMask Version: 10.0.2

**Comment by danjm** [comment]
> There is a very simple solution to this: check for this specific error message, and set the transaction to 'failed' if we see it. But this is a poor solution because then our transaction logic only works with geth, and might break if they change this specific error message.
In the general case, when we encounter a network error after "resubmitting" a transaction, I'm guessing that we decided not to consider that a failure because by that time the transaction is already in the mempool. So even if the resubmit failed, the transaction might proceed and eventually get confirmed.
But in this case, we're "resubmitting" a transaction that was not yet submitted, because it started out as a queued transaction. So maybe we need to special-case the situation where it's the first transmission?

**Comment by AlexHerman1** [comment]
@hilvmason do we know if there is a fix that could be merged for this? helpdesk is still reporting occurences.

**Comment by bschorchit** [comment]
> @hilvmason do we know if there is a fix that could be merged for this? helpdesk is still reporting occurences.

Is this still happening, @AlexHerman1 ?

**Comment by AlexHerman1** [comment]
this does still happen

**Comment by bschorchit** [comment]
@AlexHerman1 sorry for checking in again, but are users still facing this issue? We'll look into it if yes as we have now capacity for it.
