### ISSUE TITLE
Using Swaps Adds Custom Token to Token List

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#12103]
After getting a swap quote, a new "custom" token is added to the tokens dropdown:

https://user-images.githubusercontent.com/46655/133307250-17abc43c-4b37-44d7-8b76-0807f3464f12.mp4

This is problematic, as it erodes trust in what the user is swapping to.

When selecting that icon, the user must then acknowledge that they know the token is custom.

**Comment by danjm** [comment]
Note that it is fairly certain that this is just a problem on develop, and not in prod

**Comment by danjm** [comment]
My guess is that one of two things is happening with the bug in question:

- either contractExchangeRates[toTokenAddress] === undefined is true when it shouldn't be, due to a recent regression, or
- there is some other logic that is adding the users local tokens as a separate entry to the list of tokens shown in the dropdowns on the swaps screen

it is also possible that their is just a problem with the icon after the token gets added to the users own token list. Tokens in the users own list appear at the top of the dropdown, so maybe there is just an error in the display of the token icons.

**Comment by mcmire** [comment]
Can confirm that it's something to do with `contractExchangeRates`, am investigating further.

**Comment by mcmire** [comment]
Looked into this further. It seems that `state.metamask.tokenList` is what I would expect it to be and contains all the tokens that are in the token dropdown. Howeer, both `state.metamask.allTokens` and `state.metamask.tokens` are empty, which means we can't fill `contractExchangeRates`. 

I tried going back in time and testing this feature with a few commits, and it seems that this bug started happening when we started using TokensController: https://github.com/MetaMask/metamask-extension/commit/490d3b8d4049a4ba09d87d58fa8fba496fb7687c.
