### ISSUE TITLE
Issue with ledger and 10.1.0

### ISSUE THREAD

**Issue by spyrosonic10** [MetaMask/metamask-extension#12117]
When executing transaction on any dApp getting error " Error: [object Object]"

**Comment by danjm** [comment]
Hi,

 It is probably that the you need to allow contract data via the ledger device settings. One of our engineers saw a similar error a few of days ago and then had this to say:
"Well i figured out my ledger issue. Apparently when you update the app it resets settings, including allowing contract data :wink:"
And after changing the settings on the ledger device, everything was working again

**Comment by patidarmanoj10** [comment]
I have same issue with my ledger nano s.  

Steps I followed.
1. Enable "Use ledger live under settings -> advance" in Metamask.
2. Open and unlock ledger live app. 
3. Connect ledger wallet and unlock it.  Allow smart contract data is already enabled in ledger. 
4. Go to Sushiswap, connect wallet. 
5. Swap.  Metamask ask for confirmation.  then ledger bridge open. 
6. It is expected that ledger harware wallet ask for confirmation. Instead of this , dApp show Error [Object, object] immediately on screen.
I tried other dapp also but same results. 

**I am using following**
Ledger nano, firmware 2.0.0
eth app 1.9.4
ledger live 2.33.1
brave 1.29.81
metamask 10.1.0

**Comment by danjm** [comment]
@patidarmanoj10 Did you update the smart contract data setting since updating the eth app to 1.9.4?

**Comment by patidarmanoj10** [comment]
@danjm I was wrong. I my contract data setting was off. I allowed contract data and its working fine now.

**Comment by kelhkc** [comment]
I have similar problem and my BUSD in Binance Smart Chain is stucked.

Steps I followed.
1. Object object error pop up when I am trying to transfer BUSD token back to Binance hot wallet.
2. I tried transferring BUSD using metamask and Binance extension wallet but same problem exists.
3. tried to swap BUSD to USDT in ellipsis.finance and same problem exists.
4.I tried transferring BNB back to Binance hot wallet and it works.
I would conclude that this problem is about BUSD token.

I am using following
Ledger nano X, firmware 1.2.4.6
eth app 1.8.6 (my ledger live shows latest version is 1.8.6 but I know there is 1.9.4. )
ledger live 2.33.0
Firefox
Metamask
Binance Extension wallet

**Comment by rockyDK** [comment]
Hi @danjm 

I have the same issue with my ledger nano S when calling Ethereum Contract.
Error: [object Object] displays, and no msg pops up on  ledger device

I am using below setting 
Ledger nano S
ETH APP 1.6.4 with setting "Contract Data allowed"
Firefox Developer Edition
Metamask 10.1.0

**Comment by kroggen** [comment]
My Metamask was automatically updated today and this error is happening (I forgot to disable auto-update).

I am using Firefox.

I updated the Ethereum app on the device, enabled the Contract Data, but the same error occurs...

**Comment by kroggen** [comment]
I was able to "fix" it by downgrading the extension and disabling auto-update... I hope you fix this later

**Comment by fabien007** [comment]
Hello, yes the issues seems linked with the functionnality "priorities fees" Because it works on network polygon ans BSC. but not on avalanche or ethereum. downgrading fix the problem.

**Comment by dpazdan** [comment]
FYI: https://twitter.com/MetaMaskSupport/status/1438609003928555527?s=20

And yes to your point @fabien007 as this likely only impacts networks w/ EIP-1559 support.

**Comment by fabien007** [comment]
@dpazdan thanks for your reply. It works with 10.1.0 and ledger firmware 2.0

**Comment by danjm** [comment]
@kroggen Was the error happening for you on all transactions? Or just a specific dapp? If just a specific dapp, it would be helpful to know what dapp you are interacting with. You can share that here or privately via a support ticket https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by kroggen** [comment]
The firmware in my device is older. This may be the reason to fail with the 10.1.0 version

**Comment by Chanuttha** [comment]
Ledger Live V 2.33.1 + Firefox + Metamask 10.1.0 (updated 17 SEP)
Eth - Contract data Allowed
Avalanche - Sign Hash Policy Allowed
All Transaction fail with Error: [object Object]

**Comment by Chanuttha** [comment]
Additional info:
Ethereum version 1.9.4
Avalance version 0.5.3

**Comment by dpazdan** [comment]
> Ledger Live V 2.33.1 + Firefox + Metamask 10.1.0 (updated 17 SEP)

@Chanuttha make sure the firmware on the ledger device is updated, this is required, more so than updating the Ledger Live app on your computer.

https://twitter.com/MetaMaskSupport/status/1438609003928555527?s=20

**Comment by Chanuttha** [comment]
Yes, I have Nano S firmware 2.0.0 ... It fails every transaction immediately

**Comment by bjweaver** [comment]
I ended up downgrading to the previous metamask version and things are working again.   My ledger is still on eth app 1.8.6

**Comment by Chanuttha** [comment]
I also downgrade MM to previous version. It works with previous version. 
 It is tiring to wait for the fix that never comes.
