### ISSUE TITLE
Replaced Transactions Are Constantly Rebroadcasted While Metamask is Locked

### ISSUE THREAD

**Issue by nisdas** [MetaMask/metamask-extension#12159]
**Describe the bug**

Metamask was constantly performing  `eth_sendRawTransaction` rpc calls to my local geth node. This was pretty worrying as the wallet was supposed to be 'locked' and inactive. The rpc calls stopped immediately, the moment I closed my browser. Once I was able to isolate metamask as the source of the rpc calls, I spun up wireshark to capture the raw rpc calls and decode them. After decoding them, I was able to determine that fortunately they were 2 months old signed transactions that had been replaced and not something that was initiated by an unauthorized party.  

**Steps to reproduce (REQUIRED)**

I don't have a foolproof way to reproduce this but, I can give a series of steps that might reproduce this.

1) Send a transaction to a desired contract/address. 
2) Speed up that transaction with another one with a higher base fee/gas price. 
3) Once that is mined and confirmed by the network, metamask might try to broadcast already 
replaced transactions.

Just to clarify, this does not happen to every sped up transaction just a very small subset(or only 1 in my case). Also the transaction was in the legacy format and had been signed before eip-1559 was active in mainnet.

**Expected behavior**

Metamask shouldn't be rebroadcasting transactions while the wallet is locked. If this is unavoidable, it 
should not be rebroadcasting already replaced transactions from which are a few months old. 

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Brave 1.29.81 (64-bit)
 - MetaMask Version: 10.1.0

**Additional context (Error Messages, etc.)**

**Comment by danjm** [comment]
Thanks for reporting this

**Comment by Gudahtt** [comment]
If your extension is still in this state, or if you can easily reproduce this, it would help if you sent a state log to our support team.

There are a few things going on here. Firstly, we're supposed to stop retrying transactions once they are replaced, so that part of the reported behaviour is a bug. Those transactions should not be considered as "pending" by us.

But it is intentional that any pending transactions are rebroadcast constantly until they have been confirmed, as long as some MetaMask UI is open. Even if the extension is locked, having the UI open ensures the rebroadcasting continues. Perhaps we should adjust how this works to pause background network requests while the extension is locked - that might be more intuitive.
