### ISSUE TITLE
Incorrect default locale

### ISSUE THREAD

**Issue by gWOLF3** [MetaMask/metamask-extension#12353]
![Screen Shot 2021-10-13 at 6 08 42 PM](https://user-images.githubusercontent.com/34167140/137224606-90c85a10-8e23-4161-a73a-8bdb9912e7c3.png)

**Comment by gWOLF3** [comment]
setting this up in chinese was hell. please add language selection option AT STARTUP - NOT AFTER YOU HAVE COMPLETED SETUP

**Comment by raisedadead** [comment]
Thanks for getting back on this issue. 

To be clear this is sort of an oversight in the onboarding/installation workflow. 

I understand we are defaulting to the browser's language settings. That is fine, but I am not sure how & why browsers are giving the onboarding flow erroneous data, to begin with? Perhaps they are mistakenly prioritising the region somehow.

In any case, this is a pretty bad UX for end-users who happen to be in a region but do not use/speak the native language for example.

The above is more common than you might think, especially in a demographic like India (it may be true elsewhere too), where it's a dozen languages across the country. However, I would bet that 99% of the user's default to using English as the interface regardless of the native language they speak in India.

If browsers are feeding the onboarding flow that the user doesn't understand, we can fix this by:

1. Default to the browser / system settings like we are. 
2. Have a dropdown in addition on the very first onboarding page to override when the heuristic fails. 

That way the user is able to avoid this nightmare.

Here are my settings in case it helps:

Chrome:

![image](https://user-images.githubusercontent.com/1884376/137839379-98e11b24-5daf-4494-872c-602206c21ea0.png)

Windows 11, Language Settings:

![image](https://user-images.githubusercontent.com/1884376/137839546-0292d229-e7a5-4a35-829b-d35c68eb1ca3.png)


--

Thanks for everything you all do. BTW, I am a huge fan of your blog @darkwing

**Comment by Gudahtt** [comment]
In the example shown, it seems clear that English is preferred, so we should use the generic version of the locale instead of the next preferred language. There are some ambiguous cases I'm not sure how to handle though.

For example, what if the preferred languages are:
- English (UK)
- Hindi
- English

Do we respect the user's wishes to use Hindi over the non-region-specific English? The user would not _knowingly_ set that order unless that's what they wanted. But a lot of users have weird language settings and claim to have no knowledge of why they were set that way (maybe they were set by group policy, or by another user, or strange OEM defaults).

I can see the argument either way, but it would probably avoid more support tickets if we always went with the closest match for the top preferred language, rather than strictly obeying the preferred language settings. That's also the simpler solution to implement as well.

We'll be adding a locale dropdown to the onboarding flow soon anyway, so that will help out users that still don't get their preferred default language for whatever reason.
