### ISSUE TITLE
Block Explorer URL not work correctly

### ISSUE THREAD

**Issue by ngthtung** [MetaMask/metamask-extension#12465]
**Describe the bug**
Block Explorer URL not return URL expected what I want

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Create network name ( example - not real ) like this:
```
Network Name: BSC Testnet
New RPC URL: https://data-seed-prebsc-1-s2.binance.org:8545
Chain ID: 97
Currency Symbol (optional): BSC
Block Explorer URL (optional): https://testnet.bscscan.com/#/ ( having #/ )
```
2. Create a transaction, and click view at like this:
![image](https://user-images.githubusercontent.com/43090730/138592261-ea5578e3-b4d7-413b-b9e3-249fbec24674.png)
3. URL will be:
```
https://testnet.bscscan.com/tx/<hash>#/
```
**Expected behavior**
URL will be: 
```
https://testnet.bscscan.com/#/tx/<hash>
```

**Browser details (please complete the following information):**
 - MetaMask Version: 10.2.2

**Comment by danjm** [comment]
@EHaracic I believe the acceptance criteria are well defined in the above ticket description, but let me know if you have any questions

**Comment by david0xd** [comment]
Please note that the token symbol specified is not correct. It should be BNB instead of BSC. That was bringing some confusion while testing.

Full specification taken from Binance:
```
Testnet
Network Name: Smart Chain - Testnet
New RPC URL: https://data-seed-prebsc-1-s1.binance.org:8545/
ChainID: 97
Symbol: BNB
Block Explorer URL: https://testnet.bscscan.com
```
[https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain](https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain)

BNB test token can be obtained from this faucet: [https://testnet.binance.org/faucet-smart](https://testnet.binance.org/faucet-smart)

**Comment by VSaric** [comment]
We have some findings and quick fix for this ticket. The main problem is in `etherscan-link` library, so the changes are targeting `etherscan-link` library which is the source of the "problem".
Here is the PR to that: https://github.com/MetaMask/etherscan-link/pull/53/files

**Comment by EHaracic** [comment]
Pending Consensys: Waiting for the PR approve/merge: https://github.com/MetaMask/etherscan-link/pull/53/files
