### ISSUE TITLE
Chrome Extension: Duplicate wallet showing up in list

### ISSUE THREAD

**Issue by agileurbanite** [MetaMask/metamask-extension#12525]
**Describe the bug**
Created a new metamask wallet but it just duplicated an existing wallet, now the same wallet shows up on the list and is selected.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. On Chrome metamask extension, ensure you already have a wallet.
2. Create a new wallet and rename it something
3. Wallet is not created but a duplicate of an existing wallet shows up on the list.

**Expected behavior**
A clear description of what you expected to happen.

Wallet should not show the same wallet twice on the list and should not both be in the selected state.

**Screenshots**

![metamask-dupe-bug](https://user-images.githubusercontent.com/2501324/139378670-25ed8f58-3701-434d-8a3c-54357cb12c6d.gif)

**Browser details (please complete the following information):**
 - OS: Linux Mint 20.1 Ulyssa
 - Hardware Wallet: N/A
 - Browser: Google Chrome Version 95.0.4638.54 (Official Build) (64-bit)
 - MetaMask Version: 10.3.0

**Additional context (Error Messages, etc.)**

**Comment by danjm** [comment]
Thanks @agileurbanite we will be looking into this asap

**Comment by agileurbanite** [comment]
@danjm any updates?  Should I just delete the accounts and re-import?

**Comment by eternalfloweft** [comment]
i have the same problem

**Comment by rasoul369** [comment]
خب چرا همتون  بت من پیام میدین

**Comment by jpuri** [comment]
Hey @agileurbanite , @eternalfloweft : we are struggling to replicate this issue, are you also to replicate this issue following the steps above ? In case you are, can you plz share exact steps that you followed ?

**Comment by jpuri** [comment]
Hey @agileurbanite, @eternalfloweft : The issue happens if someone:

1. create 1 or more accounts in metamask
2. re-install metamask using the nemonic, at this stage it will have only one account
3. import accounts created in step-1
4. create more accounts

Above steps will result in duplicate account appearing in accounts list. Same account gets added as imported account and as created account.

Here please note that account creation is deterministic, created accounts are all linked to your nemonic. Thus you do not need to import accounts created using your metamask, you can use create account option again and it will create the same accounts. Import account is required only for accounts not created using your metamask.

To fix this in your metamask you can re-install metamask and use create account to add the accounts. Import only the accounts that you did not created using your metamask.
