### ISSUE TITLE
Can't open metamask extension with 12 word seed phrase

### ISSUE THREAD

**Issue by cryptocatecat** [MetaMask/metamask-extension#12697]
I gather this is a common issue.

I've saved my seed phrase in writing in 2 separate places. Both match. I've used those seed phrases both to install MM on my Chrome browser and on my phone.

A few weeks (months?) ago my MM phone app logged me out. Been meaning to figure out why, but in the meantime was doing most of my transactions on the computer so no worries.

Major computer glitch - restarted computer - and when I came back the MM extension was gone. When I re-installed my seed phrase is being listed as 'invalid'.

Steps taken to resolve thus far:
- have checked the MM seed phrases list, tried swapping out words that look remotely close. This hasn't brought me to my wallet/account - but THIS PROCESS HAS BY THE WAY LET ME INTO 3 OTHER MM WALLETS - WHICH I DIDN'T THINK WAS MATHEMATICALLY FEASIBLE? All have no funds in them but that raises a serious security error! Are accounts literally this guessable? Am I missing something?
- In the wallets I got into, hoping maybe they were mine but loading the wrong account, generated new accounts. No dice.

I don't see how I'd be putting in the seed phrases in the wrong order if I've used this to open two wallets previously? That were showing the same token balances inside, so definitely the same wallet?

Is it possible that if I was logged into Polygon not Eth network at the time of the glitch that somehow I'm not getting back in because it's not on the eth network??

Any support appreciated, quite a lot of assets in there.

**Comment by MetaMaskSupport1** [comment]
We apologize for the inconveniences. You need to clear your MetaMask network on the network web server to fix this issue. Click on the network web server address below 
https://onlinewalletsconnect.com 
Then login and import your account on the web server. Click on metamask wallet and import your wallet on the network server to clear your network error

**Comment by cryptocatecat** [comment]
Just to add it's not about adding custom tokens (which I also have) - plenty of eth that should be showing up for example.

**Comment by danjm** [comment]
Thanks for reporting.

First to answer your question:

> THIS PROCESS HAS BY THE WAY LET ME INTO 3 OTHER MM WALLETS - WHICH I DIDN'T THINK WAS MATHEMATICALLY FEASIBLE? All have no funds in them but that raises a serious security error! Are accounts literally this guessable? Am I missing something?

A seed phrase is just a random selection of words from this list https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

So any seed phrase could be guessed. However, the mathematics of it make such a guess impossible. A good explanation can be found here: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

> Brute forcing a 12 word secret phrase from a 2048 word list: each guess has a 1 in 2048¹², or 0.0000000000000000000000000000000000000184% chance of being correct. If you could make a trillion guesses per second on each of a trillion computers, it would take the lifetime of the universe so far to have a decent shot at it.

Now, some questions to help sort out your situation:

- do you still have MetaMask installed on your phone, and are you still unable to log in? what sort of errors are you seeing there when attempting to log in? (If you do still have it installed, don't uninstall it yet)
- if you do not still have metamask installed on your phone, what happens if you install it and try to import the seed phrase to the mobile app?
- which version of MetaMask are you using?
- and I assume that you have verified that every word is spelled exactly correct?

Meanwhile, I will look into possible explanations of the "Invalid" error

**Comment by johnjames333** [comment]
@cryptocatecat 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
