### ISSUE TITLE
MetaMask extension breaks Slack's PDF preview

### ISSUE THREAD

**Issue by espresso3389** [MetaMask/metamask-extension#13160]
**Describe the bug**
When I install/enable MetaMask extension, it magically breaks Slack's PDF Preview feature.
I can see the thumbnail on timeline, but clicking on the thumbnail shows such broken icon:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1311400/147325188-cd3be234-f512-4f4b-b358-5f5818ccdf9e.png">

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Install MetaMask extension
2. Go to some Slack site.
3. Clock some uploaded PDF file thumbnail

**Expected behavior**
Don't interfere with such websites.

**Browser details (please complete the following information):**
 - OS: Windows 11/macOS Monterey 12.1
 - Browser: Chrome 98.0.4758.9（Official Build）dev 
 - MetaMask Version: 10.8.1

**Comment by Tityz** [comment]
Hello  👋 and thanks kawasaki
Aki
Jodah.

**Comment by Arsamin-info** [comment]
#12964

**Comment by danfinlay** [comment]
Thanks for the report!

I've tried this out, and I have been unable to reproduce slack's in-browser PDF feature. Could you share an example PDF that you have this problem with? Once we can reproduce (and identify Slack's pdf preview origin), we can make a special exeception to avoid interacting with their PDF preview's frame.

This issue could also be solved on Slack's side, so next is little background on the probable cause (so that a slack developer could avoid this issue):

Sometimes what will cause sites to fail when MetaMask is on is an incorrect use of the [postMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). Many developers will write applications (like a PDF preview page's iframe) as if it can assume that all messages posted to that frame come from its same origin, and they forego checking the origin of messages that are posted.

Unfortunately, any extension that provides any API to a frame has no choice but to use the postMessage API, and so while we can make special exceptions (and [we do](https://github.com/MetaMask/metamask-extension/blob/56a0385e94b190522cb0d08a2382b32f404af4cc/app/scripts/contentscript.js#L271)), sites are also able to completely avoid this kind of problem with any extensions in the future by doing proper origin checks on [received events](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#the_dispatched_event).
