### ISSUE TITLE
Invalid warning: Could not fetch chain ID. Is your RPC URL correct?

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#13167]
Reproduction steps:

1. Settings > Networks > Add Network
2. Enter in a valid network settings but with a localhost (like `https://localhost:8871`)
3. Get the warning `Could not fetch chain ID. Is your RPC URL correct?`

Looking in the network tab of the background process, I can see that no chain_id validation request was sent. It seems some validation is getting triggered incorrectly, and preventing adding locally-hosted custom networks.

This error can also be shown when trying to edit the RPC of an existing domain to be a local one. So for example alternative repro:
1. Add a chain on https://chainlist.org/ like `Optimistic Ethereum`
2. Go to Settings > Networks > [the chain you just added]
3. Try editing the RPC to be `https://localhost:8871`.
4. You should get the above warning, although no network request is issued.

**Comment by danjm** [comment]
@danfinlay Were you running a local node at https://localhost:8871 when you saw this bug?

**Comment by david0xd** [comment]
I've been trying a couple of times to test this and to me it seems to be working in an expected way (up to some point).
So, I think it detects the wrong (not working) RPC during its construction and it has a way of checking it properly.
I've tried to add the localhost network ran by Ganache provided within MM Extension configuration (in package.json) and I was able to add and use the local blockchain network.

I've noticed that some of the errors can occur in the console of the app while they're also displayed in the Network tab and logged as failed requests. So, I think it's not always going through the background process, since I was using the main app console and network tab rather than background.

Here is an example of adding the provided RPC URL without running blockchain network on localhost (on that port, etc):
![Screenshot from 2022-01-11 14-36-29](https://user-images.githubusercontent.com/13301024/148953046-5413d24c-4ee6-4958-9adb-e28418fa514c.png)

![Screenshot from 2022-01-11 14-33-09](https://user-images.githubusercontent.com/13301024/148953072-6cb47bb2-58c3-4770-bff8-4044ee9e6116.png)

And here is the video where I was experimenting with local blockchain running with Ganache and where I was entering some invalid ports and invalid chain ids:
https://user-images.githubusercontent.com/13301024/148953258-d4ab9ac5-948f-4b63-b23b-f45a952e5ec3.mp4

The only thing I've noticed that might be incorrect is when I try to edit the network and put some invalid RPC instead of the valid one that I've added previously. In that case, it will takeover the form and return the valid RPC and network configuration as it was before.

We would appreciate getting more information on this and some acceptance criteria about what would need to be changed or investigated in the given scenario. Thanks.

//cc @danjm @danfinlay

**Comment by danjm** [comment]
@EHaracic I am removing this from the PS Team backlog for now. Given the difficulty in reproduction it is not important, and your findings so far are very helpful.

**Comment by moza88** [comment]
I am experiencing a similar issue when I try to add my localhost network. 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/5752954/164983198-00f5399a-170c-4d29-b0e8-2b37414722da.png">

I stood up my localhost instance using hardhat, I know hardhat has another chainID so in the hardhat.config file I explicitly set the chainID to 1337 like the following:
```
export default {
  solidity: "0.8.4",
  networks: {
    hardhat: {
      chainId: 1337
    },
    ropsten: {
      chainId: 3,
      url: `https://eth-ropsten.alchemyapi.io/v2/${process.env.ALCHEMY_API_KEY}`,
      accounts:
        // quick hack to get around changeme being an invalid private key
        process.env.ROPSTEN_PRIVATE_KEY !== "changeme"
          ? [process.env.ROPSTEN_PRIVATE_KEY]
          : []
    }
  }
}
```
Is there any way to bypass this validation field? Or double-check that the chainID is correct?

**Comment by seaona** [comment]
I am getting the same problem. The form behaves quite strangely as it keeps updating the chainId.

I have a geth node running with Rinkeby and every x seconds, Metamask updates the form to `1337` chainId, even though I change it to `4`. Everytime I change it, I get the "could not fetch chain Id". See below:

https://user-images.githubusercontent.com/54408225/166661120-d08eec18-652c-4650-9a4b-8a4427b6ad59.mp4

**Comment by rori4** [comment]
I was having the same issue and I opened the debugger and I saw a bunch of cors errors which prevented apperantly the get chainId requests to complete. So enabling cors fixed the issue for me
![image](https://user-images.githubusercontent.com/22402693/212139549-4c4e6184-b5e4-43b0-b5c4-0475333ca370.png)

**Comment by tibbarytsur** [comment]
Not sure if this is still being tracked, but for anyone having this problem this seems to be a problem with Firefox HTTPS-Only mode. 

If you enable Firefox' HTTPS-Only mode (even if you set your node's RPC endpoint in the exception list) Firefox forcefully upgrades the connection to HTTPS to check CORS, which fails if your endpoint doesn't support HTTPS. 
Note that the OPTION request to the node for checking CORS seems to be cached, so you don't always see that request.

Also the CORS setting of your node needs to allow the MetaMask extension. In the case of Erigon you can do this by adding the `--http.corsdomain=moz-extension://1eb35aab-28b1-49f5-b8ab-189f1b09c0f5` commandline option (or `--http.corsdomain=*` if you want to allow everything.

So the solutions is:
- either disable HTTP-Only mode completely in Firefox or configure HTTPS on your node.
- add the correct CORS setting to your node's configuration.

**Comment by kugguk2022** [comment]
How can i add my network and blockexplorer to metamask via chainlist.org? i made a fork, kept doing pull requests but i never can add my rcp url chain ID to chainlist.org, edit .jsons with my data, etc...the pull requests dissapear in hours. In ganache i can set values but at metamask  the chainID gives me the error https://github.com/MetaMask/metamask-extension/issues/. I dont know why is everything denied/deleted

**Comment by nhmartens** [comment]
I experience the same problem with Metamask in Firefox. However, I am not trying to add a local node but a regular testnet. Using Chrome I could add it, but in Firefox I always get the error "Could not fetch chain ID. Is your RPC URL correct?"
