### ISSUE TITLE
Cannot set properties of undefined (setting 'loadingDefaults')

### ISSUE THREAD

**Issue by gregegan** [MetaMask/metamask-extension#13197]
**Describe the bug**
New in the past month, when using hardhat and ethers - after performing a series of txn's, it will eventually end up getting a error `Cannot set properties of undefined (setting 'loadingDefaults')`. I am seeing many others report this issue as well as of the past 4 weeks (links below)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

I have not been able to produce this issue on any production environments. In order to resolve the issue, the ONLY solution is to completely close the browser and start over. This makes me thing this is a metamask state issue of some sort.

node v12.18.3
ethers: ^5.4.4
hardhat: ^2.6.0

**Screenshots**
![image](https://user-images.githubusercontent.com/6665100/147993779-a27b2c72-1d3d-4717-a564-8aadfea4b4ea.png)

**Browser details (please complete the following information):**
 - OS: Mac 12.0.1
 - Hardware Wallet: None
 - Browser: Chrome 96.0.4664.110
 - MetaMask Version: 10.8.1

**Additional context (Error Messages, etc.)**
It seems like many others are reporting this issue as well.

https://ethereum.stackexchange.com/questions/117184/metamask-error-cannot-set-properties-of-undefined-setting-loadingdefaults

https://www.reddit.com/r/Metamask/comments/rdyc9f/i_am_trying_to_execute_a_transfer_on_test_network/

https://stackoverflow.com/questions/70405024/metamask-rpc-error-cannot-set-properties-of-undefined-setting-loadingdefaul

**Comment by UsamaSaleem14** [comment]
Having the same issue for couple of weeks now. Before it was working fine but all of sudden this error started occurring. I have also tried to change the gas fee in the request from web3 as well as from Metamask but it still gives me this error.

**Comment by zsahmed** [comment]
Having the same issue as well with metamask version 10.8.1

**Comment by ryanmanchester** [comment]
Also having this issue using metamask version 10.8.1.

**Comment by rdinsta** [comment]
i was having the same issue with my reactjs project
node: v14.16.0
metamask: 10.8.1
chrome: Version 96.0.4664.110

i determined it to be a timing issue when making chained calls (approve and staking), so i wrapped the second call in a delay.  1 sec delay between 2nd call worked. while this is not elegant it works and can be extended handle more calls with a bit of refactoring. 

```
    stakeTokens = (amount) => {
    this.setState({ loading: true })
    this.state.diaToken.methods.approve(this.state.tokenBank._address, amount).send({ from: this.state.account }).on('transactionHash', (hash) => delayedCallback(this, hash));

    function delayedCallback(obj, hash) {
      console.log('in delay', obj.state.account)
      window.setTimeout(() => { console.log('approval', hash) 
        obj.state.tokenBank.methods.stakeTokens(amount).send({ from: obj.state.account }).on('transactionHash', (hash) => {
          obj.setState({ loading: false })
        })
      }, 1000)
    }
```

**Comment by pslowik** [comment]
solution from here https://stackoverflow.com/a/70601619/17873745 works for me, 
remove .on('transactionHash', (hash) and use async await syntax

```
  stakeTokens = async (amount) => {
    this.setState({ loading: true })
    await this.state.daiToken.methods.approve(this.state.tokenFarm._address, amount).send({ from: this.state.account })
    await this.state.tokenFarm.methods.stakeTokens(amount).send({ from: this.state.account })
    this.setState({ loading: false })
  }
```

**Comment by UsamaSaleem14** [comment]
> 

One second delay seems to be working great for me.

**Comment by UsamaSaleem14** [comment]
> i was having the same issue with my reactjs project node: v14.16.0 metamask: 10.8.1 chrome: Version 96.0.4664.110
> 
> i determined it to be a timing issue when making chained calls (approve and staking), so i wrapped the second call in a delay. 1 sec delay between 2nd call worked. while this is not elegant it works and can be extended handle more calls with a bit of refactoring.
> 
> ```
>     stakeTokens = (amount) => {
>     this.setState({ loading: true })
>     this.state.diaToken.methods.approve(this.state.tokenBank._address, amount).send({ from: this.state.account }).on('transactionHash', (hash) => delayedCallback(this, hash));
> 
>     function delayedCallback(obj, hash) {
>       console.log('in delay', obj.state.account)
>       window.setTimeout(() => { console.log('approval', hash) 
>         obj.state.tokenBank.methods.stakeTokens(amount).send({ from: obj.state.account }).on('transactionHash', (hash) => {
>           obj.setState({ loading: false })
>         })
>       }, 1000)
>     }
> ```

One second delay seems to be working great for me.

**Comment by John-Blair** [comment]
> solution from here https://stackoverflow.com/a/70601619/17873745 works for me, remove .on('transactionHash', (hash) and use async await syntax
> 
> ```
>   stakeTokens = async (amount) => {
>     this.setState({ loading: true })
>     await this.state.daiToken.methods.approve(this.state.tokenFarm._address, amount).send({ from: this.state.account })
>     await this.state.tokenFarm.methods.stakeTokens(amount).send({ from: this.state.account })
>     this.setState({ loading: false })
>   }
> ```

This worked for me too. Thanks.

**Comment by samlaf** [comment]
Having the same issue.
The async/await syntax does fix it... but it's actually waiting for the tx to be confirmed, which adds a lot of waiting.
I believe it is equivalent to replacing `.on("transactionHash")` with `.on("receipt")`, but someone should confirm this.

**Comment by samlaf** [comment]
I think I've figured this one out. As @gregegan mentioned, this only happens when you make a **series** of txs (more than 1 set of approve/operation pair!). Here is mine:
![image](https://user-images.githubusercontent.com/9342524/149994913-851dbf7c-5723-426b-8821-988ee79b3ba0.png)
The transaction that fails is actually the 2nd approve: https://kovan.etherscan.io/tx/0x47a3b7d382ccee0962e814e5e8dfab9e92e0848d3ee214915184fe3affd34efc

The Status only gives the uninformative "Fail", but the "to" section below has the key of the problem:
![image](https://user-images.githubusercontent.com/9342524/149995364-3b16019f-410a-4e58-9e78-e855e9ff793b.png)

We're running out of gas...? How is this possible?
Here is what Metamask is doing when you send a transaction, from my current understanding:
- Shoots the tx to an infura node to get an estimate of the gas used in the transaction
- Then dynamically sets the gas limit on the tx you are about to send!
When you send your approval tx, click on "Edit" next to the tx fee.
![image](https://user-images.githubusercontent.com/9342524/149995839-39a1adb7-857d-4935-8f94-cb7de4c3ee05.png)
Then click on "Edit suggested gas fee". You will see the gas limit set by Metamask for you:
![image](https://user-images.githubusercontent.com/9342524/149996055-f26042ca-af5a-4186-8fa8-a2faada6b3ef.png)

-----------------------------------------------------------------
So here's what's happening, why it fails, and why the async/await syntax is solving this issue (admitedly, in the wrong way I would argue as in my previous message).

1. You first send your first approve
2. You then send your 2nd tx with the operation you want to perform
3. The approve tx gets included in a block (this could happen before point 2, it doesn't matter)
4. Here (before your 2nd tx is included in a block!!), you send your second approve request
Here's what Metamask shows for the gas limit now:
![image](https://user-images.githubusercontent.com/9342524/149996744-958b3d25-17e6-4ac1-8363-f732a588a021.png)
39K?!? Why was it 69K the first time around and this time it's 39K?? Because your token is **ALREADY** approved to spend the amount, since your 2nd tx has still not been included in a block. Therefore, the smart contract doesn't need to update anything, and so it costs a lot less gas. If you cancel this tx, wait for your 2nd tx to be included in a block, and retry, you will see the gas limit come back to 69K! And this is precisely what the async/await solution that everyone is mentionning is doing.

-----------------------------------------------------------------
**@metamask**, how do we fix this?
Honestly I'm not 100% sure. Maybe change approvals to always have a 69K gas limit..?

**Comment by John-Blair** [comment]
In the original code I only get 1 prompt from metamask for the approve.  The 2nd prompt might occur 1 in 20 tries. The 2nd prompt always happens when i debug code line by line..and is auccessful ie not out of gas. This makes me think its a timing issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by subin-chella** [comment]
Changing the parameter value of 'on' function from 'transactionHash' to 'confirmation' fixed the issue. Had to change this while doing approve operation.

`sellTokens = (tokenAmount) => {
    this.setState({ loading: true })
    this.state.token.methods.approve(this.state.cryptoExchange.address, tokenAmount).send({ from: this.state.account }).on('confirmation', (receipt                                                                                                       ) => {
         
      
      this.state.cryptoExchange.methods.sellTokens(tokenAmount).send({ from: this.state.account }).on('transactionHash', (hash) => {
        this.setState({ loading: false })
      })
    })
  }`

**Comment by cinjon** [comment]
Is there any reason that this would happen for single transactions that use `connect(...)`? We are running into this bug in our testing suite from the following line that has no other preceding transaction: `await Entrypoint.connect(signer).createToken(...)`.

**Comment by harshalmaniya** [comment]
I'm getting this error when I close the metamask popup before the transaction details are loaded.
