### ISSUE TITLE
[Bug]: metamask won't connect to poocoin

### ISSUE THREAD

**Issue by rafawaka** [MetaMask/metamask-extension#13448]
### Describe the bug

I have just created my metamask and it won't connect to poocoin.app. I click connect and nothing happens. I have already changed to BSC. Does anyone have the same issue?

### Steps to reproduce

1.

### Version

10.8.1

### Browser

Chrome

### Operating system

Windows

**Comment by Gtonizuka** [comment]
@rafawaka I can reproduce this but it seems an issue with how poocoin app is connecting to MM. 
I see they init the provider but after you connect the wallet they don't give the user any extra feedback.

I would try to open an issue with them to ask if they know why this issue is happening - closing this for now
