### ISSUE TITLE
Create Password page

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13443]
- [x] "learn more" should be capitalized and lead to a link with more information about passwords in metamask rather than terms of service.*

- [ ] The create password screen does not adequately emphasize that we cannot recover the password, and it doesn't communicate what the password is used for very well.*

- [ ] Clicking on the password input doesn't work if you've recently typed a key into the other input. e.g. type something into "confirm password" then try clicking "password" right away. It does not work until you wait a few seconds. (personally I'm not able to reproduce this issue)

- [ ] 	After creating a password, it shows the login page briefly with a loading overlay before navigation to the success screen. This shouldn't happen. It should lead directly to the success screen.

- [ ] The "Passwords Don't Match" error has every word capitalized, but our convention is to only capitalize the first word of each phrase.

*requires design input (cc @rachelcope)

**Comment by Trisboyd** [comment]
Hey @adonesky1, first time contributor here. (Just an outsider)

Adjusting the capitalizations is easy as is replacing the link (although I could not find an ideal page for describing the password specifics, t[his post](https://metamask.zendesk.com/hc/en-us/articles/4405451730331-Passwords-and-MetaMask) could serve as a placeholder?).  I'm hesitant to add a full description for how passwords operate from outside the company and I haven't been able to replicate the other issues.
I can pull request these simple fixes if you'd like, keep cracking away at the others in an attempt to resolve the whole issue, or just let a real team member do the work.  Regardless, happy to help out!

**Comment by adonesky1** [comment]
Hey @Trisboyd thanks so much for jumping in to help! So this ticket is part of an [epic](https://github.com/MetaMask/metamask-extension/issues/13440) that may be a bit more difficult to tackle as an outside contributor since some of the updated designs/copy are in our team restricted Figma files. I'm going to look for some good alternative tickets to tackle as a first time contributor! We really appreciate your desire to contribute and are actively working on making outside contribution easier.

**Comment by adonesky1** [comment]
@Trisboyd this looks like a good first issue to me https://github.com/MetaMask/metamask-extension/issues/13277. You may want to comment on it to make sure some one internal hasn't started it and forgotten to indicate so. Thanks again!

**Comment by bschorchit** [comment]
> The create password screen does not adequately emphasize that we cannot recover the password, and it doesn't communicate what the password is used for very well.*

This bullet point should be solved by implementing [this new design](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2552%3A17984) that checks for password strength.

To check for password strength we should use [this module](https://github.com/dropbox/zxcvbn) and set the feedback according to the score:
```
case 0:
  return 'weak';
case 1:
  return 'weak';
case 2:
  return 'weak';
case 3:
  return 'good';
case 4:
  return 'strong';

```
[here](https://lowe.github.io/tryzxcvbn/) is a demo version of the library.

cc: @danjm

**Comment by EHaracic** [comment]
### Figma design(s)

### Acceptance criteria
- "learn more" should be capitalized and lead to a link with more information about passwords in metamask rather than terms of service.*
- Implement new design that checks for password strength. **See the notes for the implementation design.**
- After creating a password, it shows the login page briefly with a loading overlay before navigation to the success screen. This shouldn't happen. It should lead directly to the success screen.

### Notes
- Bullet point 2 implementation details:
1. Solve by implementing [this new design](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2552%3A17984) that checks for password strength.
2. To check for password strength we should use [this module](https://github.com/dropbox/zxcvbn) and set the feedback according to the score:
case 0:
  return 'weak';
case 1:
  return 'weak';
case 2:
  return 'weak';
case 3:
  return 'good';
case 4:
  return 'strong';

**Comment by SayaGT** [comment]
I have created designs to reflect strong, weak & average passwords here:
https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2552%3A17984

**Comment by Dentrax** [comment]
Hey! Ended up here to drop some ideas to check whether our password is exposed or not. I got "File not found" error on that Figma link and since I's a bit low res I couldn't clearly see if this feature in the UI. Here is the idea:

Similar to Bitwarden's password expose control mechanism:

![Screen Shot 2022-02-25 at 21 02 57](https://user-images.githubusercontent.com/16493751/155764962-1ee519bb-889c-4abb-9755-3fb0e6bac135.png)

If a given string has been breached already, it shows the following error:

![Screen Shot 2022-02-25 at 21 05 48](https://user-images.githubusercontent.com/16493751/155765302-871ef733-e60b-42c4-8128-15be1f04454f.png)

**Demonstrate:**

Let's assume our input is: `foo`

1. SHA1(foo) -> `0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33`
2. Get first 5 characters -> `0beec`
3. Send an API request to:

```
GET https://api.pwnedpasswords.com/range/{first 5 hash chars}
```

4. Remaining hash after you get rid of 5 characters is `sha1[5:35]` : -> `7b5ea3f0fdbc95d0dd47f3c5bc275da8a33`

5. Send the API request: 

```bash
$ curl -X GET https://api.pwnedpasswords.com/range/0beec 2>/dev/null | grep -i "7b5ea3f0fdbc95d0dd47f3c5bc275da8a33" | cut -f2 -d \:

5372
```

**Conditions**

* If count greater than `0`: show a warning popup & don't allow continuing
* If count equals `0`: it's safe to move forward
* If API get down, rate-limited, etc.: maybe do not enforce this & allow continuing

I hope this one give some ideas about enhancing the security layer a bit further and creates some awareness to users.

Waiting your thoughts!

cc @adonesky1 @EHaracic
