### ISSUE TITLE
[Bug]: Coinbase Wallet and Metamask Wallet conflicts

### ISSUE THREAD

**Issue by addmorebass** [MetaMask/metamask-extension#13622]
### Describe the bug

If a user connects to Coinbase wallet then disconnects, and tries to connect the MetaMask wallet, the Coinbase wallet is never disconnected.

### Steps to reproduce

1. Connect Coinbase wallet on a dApp
2. Disconnect wallet
3. Connect MetaMask wallet to the same dApp
4. Coinbase wallet still remains connected

### Version

10.9.2

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by sambacha** [comment]
this happens with multiple web3 wallets are running

**Comment by addmorebass** [comment]
@sambacha So it seems like there's no way to prevent this unless the user disables one or the other, right?

**Comment by sambacha** [comment]
> @sambacha So it seems like there's no way to prevent this unless the user disables one or the other, right?

correct

**Comment by addmorebass** [comment]
Let me know if you need any more info @rekmarks. Thanks.

**Comment by Sassun** [comment]
I have the same issue.

**Comment by n1c01a5** [comment]
I have the same issue.

**Comment by addmorebass** [comment]
I don't really know what the fix is here. Could Metamask detect that Coinbase wallet is enabled and prompt the user to disable it?

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/13407

**Comment by vandan** [comment]
@rekmarks Will the documentation and console warning implemented as part of #13407 handle the detection for multiple wallets (like Coinbase) as well?
We're going to peel off the area-api label unless there's a specific change needed there.

**Comment by ansonkao** [comment]
Dang, this is a huge barrier to the adoption of Web3 😢 have had this issue reported for over 8 months in my experience

**Comment by alessiogmonti** [comment]
Hello, I'm having this same issue. I've posted a stackoverflow question that describes a fix documented by coinbase:
https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance

My implementation of that fix does not work. As far as I understand, this is because the metamask object in window.ethereum.providers is a proxy with inaccessible properties.
https://stackoverflow.com/questions/73949836/window-ethereum-providers-findprovider-provider-ismetamask-returns-undefi

**Comment by GabrielBuragev** [comment]
Have you tried following this guide: https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance ?

**Comment by alessiogmonti** [comment]
This is how I did it
```
let { ethereum } = window;
    try {
          ethereum = await window.ethereum.providers.find(
          (provider) => provider.isMetaMask );
        } catch (error){
          console.error(error)
      }
```

**Comment by Tkelley325** [comment]
> This is how I did it
> 
> ```
> let { ethereum } = window;
>     try {
>           ethereum = await window.ethereum.providers.find(
>           (provider) => provider.isMetaMask );
>         } catch (error){
>           console.error(error)
>       }
> ```

**Comment by moondayli** [comment]
No fix yet 😮‍💨

**Comment by vandan** [comment]
This issue was due to a long-standing design flaw that was affecting all browser wallets (essentially the original solution wasn't designed for multiple browser extension wallets to work in tandem). However, this should now be resolved by our newly added support for Multi-injected Provider Discovery (EIP-6963) as long your dapp also supports EIP-6963 method of discovering providers with either custom code or a library that supports EIP-6963.

Our initial announcement:
https://metamask.io/news/developers/improving-the-multi-wallet-user-experience-with-eip-6963

We have also recently updated our documentation with a couple guidelines:
https://docs.metamask.io/wallet/how-to/connect/detect-metamask/
https://docs.metamask.io/wallet/concepts/wallet-interoperabilty/
https://docs.metamask.io/wallet/concepts/apis/
