### ISSUE TITLE
[Bug]: Address Pet name and currency conversion unavailable in "Edit" mode in the Send flow

### ISSUE THREAD

**Issue by SayaGT** [MetaMask/metamask-extension#13736]
### Describe the bug

After initiating a transfer, if a user clicks "edit" and goes back to the screen with recipients address and token. The inputs are broken. The contact pet name gets replaced by the address and it appears twice. As well as the token fiat value is unavailable. See the video below.

https://user-images.githubusercontent.com/87030673/155383141-77b3579e-c1e8-42ad-85a0-4e21a96057be.mov

 

### Steps to reproduce

1. Start a transfer with an asset
2. Select a saved contact (with a pet name) 
3. Select a token with a fiat value
4. Click Next 
5. Click Edit and the currency conversion rate isn't shown + the pet name is replaced by the recipients address

### Version

10.9.3

### Browser

Firefox

### Operating system

MacOS

**Comment by adonesky1** [comment]
@danjm sorry just seeing your comment here... No I am not working on it. @VSaric go for it!

**Comment by VSaric** [comment]
Hello @SayaGT, I will share you the video, that I made, of reproducing this bug below.

I noticed that you are reproducing this bug in `Ethereum Mainnet`, but unfortunately I don't have any balance in `Ethereum Mainnet`. Every token has `0` amount in `Ethereum Mainnet` and I can't go further in the `Send` flow in `Ethereum Mainnet`. 

I tried to reproduce this bug in `Ropsten Test Network`. I think I can reproduce address pet name, but I can't reproduce currency conversion because every token that I have in `Ropsten Test Network`, token fiat value is unavailable.

Do you have some suggestion how can I reproduce this bug in some test networks and whether it can be reproduced on the test network at all? @SayaGT @danjm

I understand what is the problem here, but I can't reproduce it to the end. 

**Screencast:**

https://user-images.githubusercontent.com/92527393/163981521-ac4fb683-54d3-430b-b902-9f3232ccf03b.mov

**Comment by SayaGT** [comment]
Hmmm I tried reproducing it on other test networks but I have the same problem. Not sure How to reproduce it on anything except main net. If it helps I can share my screen with you or inspect it?
