### ISSUE TITLE
[Bug]: Enhanced Gas Fee UI saves the same values regardless of network

### ISSUE THREAD

**Issue by PhiMarHal** [MetaMask/metamask-extension#13800]
### Describe the bug

Using the Enhanced Gas Fee UI and ticking the "Always use these values and advanced setting as default." option, the max base fee and priority fee values are saved regardless of blockchain used.

Expectation: values should be saved per blockchain, as different blockchains have widely different gas fees.

### Steps to reproduce

1. Start a 0 ETH transaction to your own address on Ethereum
2. Edit Max Base Fee and Priority Fee. Tick "Always use these values and advanced setting as default."
3. Reject the transaction
4. Switch to another blockchain (for example, Polygon)
5. Start a 0 ETH transaction to your own address
6. Edit gas fee. The gas values will be the same you saved on Ethereum

### Version

10.10.1

### Browser

Firefox

### Operating system

Linux

**Comment by danjm** [comment]
To reproduce this, you will have to turn on the eip v2 settings from the experimental tab of settings, the go into edit gas while confirming a transaciton

**Comment by danjm** [comment]
![Screenshot from 2022-03-18 09-12-37](https://user-images.githubusercontent.com/7499938/158997128-b04342c2-9cd4-474e-ade5-e0e9ce44882f.png)

**Comment by danjm** [comment]
To resolve:
- find where custom settings are saved in state
- set up chainId to settings map, so that we have settings per network

@bschorchit We should check with designers if there are any special indications they would want us to make before making this network specific

**Comment by bschorchit** [comment]
I've checked with the designers and we should only update the checkmark text to `Always use these values and advanced settings as default on <network>.` @EHaracic

**Comment by EHaracic** [comment]
### **User Story**
Using the Enhanced Gas Fee UI and ticking the _"Always use these values and advanced setting as default."_ option, the max base fee and priority fee values are saved regardless of blockchain used.

Expectation: **Values should be saved per blockchain**, as different blockchains have widely different gas fees.

### Figma/Notion links

No links

### Tasks

- Find where custom settings are saved in state
- Set up chainId to settings map, so that we have settings per network

### Acceptance criteria
1. Set up chainId to settings map, so that we have settings per network (Values should be saved per blockchain)
2. Update the checkmark text to Always use these values and advanced settings as default on <network>.
![image](https://user-images.githubusercontent.com/49436614/159440997-82302551-0f78-4bf6-84d6-27fe1acd1d29.png)
 
 
#### Steps to Reproduce the issue

1. Start a 0 ETH transaction to your own address on Ethereum
2. Edit Max Base Fee and Priority Fee. Tick "Always use these values and advanced setting as default."
3. Reject the transaction
4. Switch to another blockchain (for example, Polygon)
5. Start a 0 ETH transaction to your own address
6. Edit gas fee. The gas values will be the same you saved on Ethereum

**Comment by bschorchit** [comment]
I don't think we want this to be closed
