### ISSUE TITLE
[Bug]: No popup or confirmation shown in Chrome extension if "This can read and change site data" is not set to "On all sites"

### ISSUE THREAD

**Issue by n-whale** [MetaMask/metamask-extension#14066]
### Describe the bug

There is a bug in the Chrome extension since 2018:
If Chrome started when the MetaMask extension's option `This can read and change site data` is set to `When you click the extension` or `On <site>` then after clicking on the MeteMask icon and reloading the page or opening the site, where it's enabled, initiating `eth_sendTransaction` will not display the extension's popup neither is the confirmation shown if the extension popup is forced to open by clicking on the extension's icon.
Changing the option `This can read and change site data` to `On all sites` will instantly display the popup and all the confirmations are displayed.
When Chrome is started when the MetaMask extension's option `This can read and change site data` is set to `On all sites` everything works fine.

### Steps to reproduce

1. In Chrome navigate to a site, which has a working solution to initiate `eth_sendTransaction` via MetaMask
2. Set the MetaMask extension's option `This can read and change site data` to `On all sites`
3. Confirm that initiating the send transaction opens the MetaMask popup with the transaction confirmation shown.
4. Close the popup and set the MetaMask extension's option `This can read and change site data` to `On <site>`.
5. Restart Chrome and navigate to the same site
6. When the site connects to MetaMask the password popup shall be displayed
7. Initiate the send transaction ->
	- **The popup is not shown (regardless how many times it is initiated).**
	- **There is no error in the javascript console log**
8. Open the MetaMask popup by clicking on the extension's icon -> **There is no sign of any request confirmation!**
9. Close the popup and set the MetaMask extension's option `This can read and change site data` to `On all sites`. -> The MetaMask popup is displayed with the request confirmation(s)

The same happens with the option `This can read and change site data` is set to `When you click the extension`

### Version

10.11.1

### Browser

Chrome

### Operating system

Windows

### Additional context

Chrome 99.0.4844.74 (Official Build) (64-bit)
The bug exists since 2018

**Comment by AlexJupiter** [comment]
Thanks for the report @n-whale, however I just tried to reproduce this and didn't see the same problem, would you be able to provide a screen recording please?

**Comment by AlexJupiter** [comment]
@n-whale we did just manage to reproduce this, however would you be able to explain what the use case is for this functionality please?

**Comment by b-gyula** [comment]
> @n-whale we did just manage to reproduce this, however would you be able to explain what the use case is for this functionality please?

1. Since MetaMask is a "money" wallet I don't want it to be available to any unknown sites for safety measures (like I access my internet bank sites in incognito mode and all extensions disabled.) MetaMask is even more sensitive, since it actually stores my private keys not only gives access to an interface.
2. Cryptographic functions requires a lot of resources. Chrome is extremely memory hungry by itself. Loading unused extension in each tab is a unnecessary waste of memory
3. As a (web) software developer during development I like to make sure no other "unknown" injected javascript library interfere with my work.

So I set the option `This can read and change site data` to either `When you click the extension` or `On <site>` of all extensions in Chrome.

**Comment by MithrilMan** [comment]
I think it's something important for privacy and security concerns
