### ISSUE TITLE
[Bug]: Cannot send a transaction with Hex Data on Optimism

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14298]
### Describe the bug

If you try to send a transaction that contains Hex Data on Optimism the transaction fails immediately

https://user-images.githubusercontent.com/53189696/161073087-7d5725e9-8c08-4e28-8d32-ca3c7785fca5.mov

### Steps to reproduce

1. Settings -> Advanced -> Show Hex Data
2. Create a Send Transaction with Hex Data
3. Click Next
4. Click Confirm

### Error messages or log output

```shell
sentry-install.js:1 [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"invalid transaction: intrinsic gas too low"}}}'
```

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

### Additional context

You cannot increase the Gas Price anymore, but a Dapp can suggest a higher Gas Price

**Comment by danjm** [comment]
@PeterYinusa I believe this is only a problem if trying to set data to `0x0` (e.g. the error should not occur if setting data to `0x1` or `0xabcdef0123456789`), and for that scenario the error will also occur on v10.11.x unless the user edits the gas limit

Can you confirm?

If so, I think it is okay to not fix that at this time because:
- this only affects optimism
- This is a very rare edge case. I am not sure there is a use case for sending `0x0` data
- I believe this is a bug at the rpc provider / ethereum client layer. For us to resolve, we would have to dig in at that layer which could take some time.
- the only degradation here is that Optimism users can't edit the gas limit to work around the rpc provider / ethereum client bug, but the Optimism team explicitly asked us to prevent editing gas on that network (as doing so usually causes more problems than it solves, and their contract based estimation _should_ provide a correct+optimal estimate)

**Comment by nic-github-ux** [comment]
I ran into this problem and don't know how to edit hex data

**Comment by seaona** [comment]
@PeterYinusa @danjm for me it looks like it fails with all hex data values. I.e. tried with` 0x1` or `0xabcdef0123456789` and both failed

**Comment by suraneti** [comment]
This problem also occurred on Hop Protocol and Stargate Finance.

**Comment by markusbkoch** [comment]
I also encountered this problem, using 10.18.3
I'm trying to interact with a contract on Optimism through Metamask, so I'm passing some specific data. 
The txn value (amount of OETH sent) must be zero. This seems to be causing the gas price to also be set to zero. The transaction is not broadcast and the console outputs:
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"cannot accept 0 gas price transaction"}}}'`

**Comment by protocolwhisper** [comment]
Same error here!! I already update the data but it don't work at all.
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"cannot accept 0 gas price transaction"}}}'`

**Comment by protocolwhisper** [comment]
> It worked today maybe is a chain issue
