### ISSUE TITLE
[Bug]: Duplicated accounts when importing private key

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14601]
### Describe the bug

**Problem**: using 2 Metamask instances with the same seed, I can create an account and copy its private key to one instance and then import an account with that Private key, and create an account. This is going to generate a duplicated account and the 2 accounts (which in reality is 1) are displayed on Metamask as a duplicated.

![image](https://user-images.githubusercontent.com/54408225/166444065-9d5ad781-cf77-46ea-bc7d-36a9cf1032c0.png)

### Steps to reproduce

1. Open Metamask
2. Create an Account
3. Export Private Key (copy it)
4. Open a new instance of Metamask (same seed, in another browser)
5. Click Import Account
6. Paste private key
7. Click Create Account

### Version

10.15.0

### Browser

Chrome

### Operating system

Linux

**Comment by Almis90** [comment]
I'm not sure if this is the exact same issue, but since the error message is the same, I want to share how I fixed it. This might help others who encounter the same error for same reason with me. I faced this issue when I was importing my account but was on the wrong network. My account is on the BNB Chain, but the extension I installed defaulted to the Ethereum Mainnet. Realizing this, I switched to the BNB Chain, tried importing my account again, and it worked.
