### ISSUE TITLE
Capture data about initialisation time of modules

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15021]
Flag `const statsMode = false` can be enabled in `runtime-lavamoat.js` to capture data about time taken bu modules to initialise. Useful charts can then be drawn out of this data.

It will be useful to integrate this to CI.

**Comment by danjm** [comment]
We will want do these subtasks:
- modify metamask-extension/development/build/static.js to update `statsMode` in runtime-lavamoat.js when building in test mode
- create an e2e tests for initialization measurements
	- probably start by keeping MV2 and MV3 tests separate
	- we will need separate jobs for MV3, as a separate build will ne meeded
	- use driver functionality similar to what is found in `checkBrowserForConsoleErrors` to gather lavamoat stats from console
	- follow approach similar to benchmark.js for writing stats to file
- modify CI so that initialization stats are published by CI


Each of those can probably be a separate ticket and PR

**Comment by danjm** [comment]
We should be able to use the above described system for measuring loading as well, but we have to figure out where and how to add the console logs.
