### ISSUE TITLE
[Bug]: Ganache network may use a differnet currency symbol (CPAY)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15045]
### Describe the bug

**Problem**: when I'm using my local host Ganache node, I see an intermittent warning saying recommended Currency Symbol is CPAY

![image](https://user-images.githubusercontent.com/54408225/175547139-a09cbc5e-79a2-4266-ab02-7f701927b4c0.png)

### Steps to reproduce

1. Open a terminal
2. Initiate Ganache (`ganache`)
3. Open Metamask
4. Activate the option for showing test networks
5. Change to Localhost
6. Go to Settings // Networks
7. Click Localhost
8. Click Kovan Network
9. Click Localhost network again and check Currency Symbol

### Version

10.17.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Are you referring to the warning in the UI? This is intended to help users fill in the correct symbol in case they made a mistake. Maybe this is happening because you're using the same chain id as an existing network on chainlist. Does ganache always use this same chain id? If yes, then maybe we might want to make an exception for when the rpc url is localhost.

**Comment by seaona** [comment]
@bschorchit correct, ganache pre-default chain id is `1337` and I was expecting that "ETH" was the recommended symbol. Not sure where CPAY symbol comes from.
I didn't add any other custom network, so no repeated chain id's in this case

**Comment by bschorchit** [comment]
thanks, @seaona ! We should make an exception for when the rpc url is localhost then.
