### ISSUE TITLE
[Bug]: AVG Antivirus Detecting URL:Pishing

### ISSUE THREAD

**Issue by ldobreira** [MetaMask/metamask-extension#15081]
### Describe the bug

Not sure if this is a false alarm but my AVG is detecting a threat on metamask.github.io (URL: Pishing)

Threat Name: URL: Pishing
URL: https://metamask.github.io/pishing/watning/v1.1.0/lockdown-install.js
C:\Program Files\Mozilla Firefox\firefox.exe

### Steps to reproduce

1. I just opened the Firefox Browser and got the threat warning.

### Error messages or log output

```shell
Threat Name: URL: Pishing
URL: https://metamask.github.io/pishing/watning/v1.1.0/lockdown-install.js
C:\Program Files\Mozilla Firefox\firefox.exe
```

### Version

10.14.7

### Browser

Firefox

### Operating system

Windows

**Comment by bschorchit** [comment]
Thank you for this report, @ldobreira ! We have reach out to Avast and they confirmed it was a mistake on their side and fixed it.

**Comment by GalacticPrez** [comment]
I use AVG too and have been receiving this one: metamask.github.io/phishing-warning/v3.0.3/favicon.ico
<img width="462" alt="metamask avg report" src="https://github.com/user-attachments/assets/4e9e1751-10bd-42cd-9b9a-1139b9cff375">
... is this also a false positive? the URL brings up a blocked page all red with a big warning so I thought it was real and not sure what to do about the fact it is reported repeatedly ... is this caused by metamask plugin for firefox?

**Comment by Dentoo** [comment]
same warning here about the favicon
