### ISSUE TITLE
New metrics data for token approval transactions

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15152]
## Acceptance Criteria

The `type` property for `Transaction Finalized` and the `Transaction Submitted` events are now replaced by the below defined `transaction_type` property with the following values and additional properties:
    
    - if *transaction_contract_method* = *approve* **&** *token_standard = ERC20*:
      **transaction_approval_amount_type** (string): *custom | revoke | dapp_proposed*

        - if *transaction_approval_amount_type* = *custom* or *dapp_proposed*:
         **`transaction_approval_amount_vs_balance_ratio`** (number - [0.00, infinity)): *allowance_amount_in_relation_to_token_balance* - the allowance amount in relation to the balance for that specific token

        - if *transaction_approval_amount_type* = *custom*:
         **`transaction_approval_amount_vs_proposed_ratio`** (number - [0.00, infinity)): *allowance_amount_in_relation_to_dapp_proposed_value* - the allowance amount in relation to the dapp proposed amount for that specific token

**Comment by danjm** [comment]
Technical notes:

- the `tokenAmount` property passed to ConfirmApprove should be the dapp proposed token amount
- `customPermissionAmount` in ConfirmApprve should the `custom` amount
- if the selected amount (either tokenAmount or customPermissionAmount) is `0`, then `transaction_approval_amount_type` should be `revoke`
- to determine transaction_approval_amount_vs_proposed_ratio, we need to have both the originally proposed amount and the chosen amount (which will be the same as the original if the user does not edit the amount or will be a custom amount set by the user). `customTxParamsData` is passed from `ConfirmApprove` to confirm-transaction-base.container, we somehow also need to passed the original amount to the container and then the component so that it can be passed as part of txMeta in handleSubmit in ConfirmTransactionBase component. Probably add `originalApprovalAmount` and `finalApprovalAmount` properties to txData before calling sendTransaction in handleSubmit. Then those can be used in the transaction controller to calculate transaction_approval_amount_vs_proposed_ratio
- we should also put `currentTokenBalance` on the txData, which should be the balance of the token that is being send, and should match the balance that is rendered in the edit permission modal on the approve screen

**Comment by VSaric** [comment]
@danjm can you explain more what is the `originalApprovalAmount` and `finalApprovalAmount` properties who need to be added to `txData`?

**Comment by VSaric** [comment]
@danjm @bschorchit 

1. I saw that `tokenAmount` property passed to `ConfirmApprove` is `string`. Also, I saw `customPermissionAmount` property passed to `ConfirmApprove` is also `string`. Is it okay to pass that values as `string` in transaction controller or this values needs to be passed as `number`?
2. If the selected amount (either `tokenAmount` or `customPermissionAmount`) is `0`, then `transaction_approval_amount_type` should be `revoke`. What about if the user edit the amount to `0`? Than the `transaction_approval_amount_type` should be `revoke` and we will set `transaction_approval_amount_vs_proposed_ratio` and `transaction_approval_amount_vs_balance_ratio` properties to be `null`, because `transaction_approval_amount_type` would be `revoke`.
3. In the acceptence criteria, `transaction_approval_amount_vs_proposed_ratio` and `transaction_approval_amount_vs_balance_ratio` properties are `numbers`. If I follow the existing code in transaction controller for `quoteVsExecutionRatio` and `estimatedVsUsedGasRatio`, this values is `strings` at the end. It is okay to set `transaction_approval_amount_vs_proposed_ratio` and `transaction_approval_amount_vs_balance_ratio` properties to be `strings` or must to be `numbers`?
4. @bschorchit Is this description correct?
```
if transaction_approval_amount_type = custom or dapp_proposed:
transaction_approval_amount_vs_balance_ratio (number - [0.00, infinity)): allowance_amount_in_relation_to_token_balance - the allowance amount in relation to the balance for that specific token

if transaction_approval_amount_type = custom:
transaction_approval_amount_vs_proposed_ratio (number - [0.00, infinity)): allowance_amount_in_relation_to_dapp_proposed_value - the allowance amount in relation to the dapp proposed amount for that specific token
```
I asked this because If you can see in `2` question, if user edit the amount to be `0`, `transaction_approval_amount_type` should be `revoke` and than this `if` statement will be `false`?

**Comment by bschorchit** [comment]
1. I've checked how `estimatedVsUsedGasRatio` works on Mixpanel for the dashboards we're trying to build since it's also a string, but it doesn't work properly. I also tried converting it from string to number in Mixpanel, but it did not work either. Could we convert them to number before sending it to Segment/Mixpanel?

**Comment by bschorchit** [comment]
2. This is true and I agree. If the user edits the amount to `0`, `transaction_approval_amount_type` would be `revoke` and `transaction_approval_amount_vs_proposed_ratio` and `transaction_approval_amount_vs_balance_ratio` would also be `0`.

**Comment by bschorchit** [comment]
4. You're right! Good catch. Let's ignore the `if` statement and set the values to `0` or `null` as you said.

**Comment by bschorchit** [comment]
Waait. I might take 1. and 3. back. The issue I'm having on Mixpanel is because `estimatedVsUsedGasRatio` always has a `%` next to the number so when I try to convert it to number on Mixpanel, I'm not able to do it correctly (all data disappear as nothing can be converted to numbers). 
But I got it to work now with `completion_time` property from `Transaction Finalized`. So it's ok if we pass those as strings as long as the are only numbers in all strings. That way I correctly convert it directly in Mixpanel :)
