### ISSUE TITLE
Modify transaction type, and add contract method, data to metrics

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15150]
## Acceptance Criteria

The `type` property for `Transaction Approved`, `Transaction Rejected`, `Transaction Finalized` and the `Transaction Submitted` events are now replaced by the below defined `transaction_type` property with the following values and additional properties:

**`transaction_type`** (string): *send, contract_interaction, cancel*

- if *transaction_type* = *contract_interaction*:
    
    **`transaction_contract_method`** (string): *name_of_contract_method_here*

**Comment by danjm** [comment]
Notes on technical implementation:

Currently we have a `type` property on transaction meta, and that is used in `_buildEventFragmentProperties`, but there are many types https://github.com/MetaMask/metamask-extension/blob/develop/shared/constants/transaction.js#L50-L69

To convert those types to one of send, contract_interaction, or cancel:
- CONTRACT_INTERACTION, TOKEN_METHOD_APPROVE, TOKEN_METHOD_SAFE_TRANSFER_FROM, TOKEN_METHOD_TRANSFER, TOKEN_METHOD_TRANSFER_FROM types can all be tracked as `contract_interaction`
- TRANSACTION_TYPES.CANCEL can just be tracked as cancel
- TRANSACTION_TYPES.SIMPLE_SEND can just be tracked as send

name_of_contract_method_here should be available in the confirm screen state, and just needs to be passed to the transaction controller, this can be done in the handleSubmit method of ConfirmTransactionBase

**Comment by brad-decker** [comment]
@danjm what about retries? I assume if we are special casing Cancel we should do so with retry (speed up) as well?

**Comment by bschorchit** [comment]
@brad-decker we don't want to special case `retry` because by doing that the retry type would overwrite the actual type of the transaction - which is an information we want to preserve. 
Instead of doing that, we're tracking wether the new transaction is a retry here https://github.com/MetaMask/metamask-extension/issues/15151 .
The same doesn't apply to `cancel` as cancel transactions are always of the type `send` so we don't need to track both the actual type (send) and flag that as a cancel transaction. We directly special case that as a cancel type. 

After your comment we are adding though a `transaction_replaced` property to the original transaction (the one that gets dropped) so we flag that it was replaced and how (`cancel` or `retry` or `other`).
