### ISSUE TITLE
[Bug]: Edit Token Transfer displays mixed info with regular Send Tx (ETH)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15362]
### Describe the bug

**Problem**: when I am performing an ERC20 Token Transfer and I click Edit, I see that ETH is displayed as the default token, with amount 0 on that ERC20 token. Information is mixed up between a Send and a Transfer

https://user-images.githubusercontent.com/54408225/181301057-c8bdd7a5-a210-4156-8e92-d3ad2388c064.mp4

 

### Steps to reproduce

1. Deploy [an ERC20 token](https://remix.ethereum.org/?#code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC40OwoKaW1wb3J0ICJAb3BlbnplcHBlbGluL2NvbnRyYWN0c0A0LjcuMS90b2tlbi9FUkMyMC9FUkMyMC5zb2wiOwoKY29udHJhY3QgTXlUb2tlbiBpcyBFUkMyMCB7CiAgICBjb25zdHJ1Y3RvcigpIEVSQzIwKCJNeVRva2VuIiwgIk1USyIpIHt9Cn0K&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js) on Rinkeby 
2. Click Send tx
3. Click Edit
4. See mixed up info with ERC20 and ETH

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
It should not be possible to edit dapp suggested transactions since https://github.com/MetaMask/metamask-extension/pull/16498 .  Is this still an issue ?

**Comment by bschorchit** [comment]
Update: I was able to reproduce it in MM 10.23.3 (prod) following the repro steps above

**Comment by bschorchit** [comment]
Update: transfers should indeed be able to edited. See [thread for reference](https://consensys.slack.com/archives/GTQAGKY5V/p1674123797697109?thread_ts=1668473095.066049&cid=GTQAGKY5V). Besides fixing the bug above, we could also consider not allowing the user to change the token.

**Comment by segun** [comment]
Some more information about this issue.

I was able to replicate this behaviour on a new token.

But when I imported the token into Metamask, it starts behaving as normal.

So when 

1. you click edit (without importing the token first) - It goes to normal send page
2. you click edit (after importing the token first) - it goes to send token page


https://user-images.githubusercontent.com/44811/214638103-c41c8bfa-2c1b-4f31-bd9b-597d2edeadb7.mov

**Comment by bschorchit** [comment]
Oh interesting! Nice finding, Olu!

**Comment by seaona** [comment]
It seems that not having the Token added to the Wallet brings numerous problems. See also [this bug](https://github.com/MetaMask/metamask-extension/issues/17228) and comments.
Does it sound that we could have a generalized fallback that covers all theses cases for when the Token is not on the Wallet?

**Comment by segun** [comment]
[This method](https://github.com/MetaMask/metamask-extension/blob/30520a335256732073e09885581f1378713789a9/ui/pages/send/send-content/send-asset-row/send-asset-row.component.js#L139) is the cause of this bug

The logic is, it tries to read the address being sent to from state. If it's found, it displays the token, if not it displays native currency.

This is problematic because if the token has not been added, the address won't be in state.

One possible solution is to find a way to detect if the address is an ERC20 or ERC721 token without looking at the state. We already do this detection when adding the token to MetaMask, once you enter the address it fetches the Name, Decimals and Symbol. (I am not entirely sure if the same detection is done for an ERC721 token address).
