### ISSUE TITLE
[Ext] Create component: Modal

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15432]
### Description
Create a reusable UI component for `Modal` according to the insight report

Tasks
- [x] Merge https://github.com/MetaMask/metamask-extension/pull/18311
- [x] Merge https://github.com/MetaMask/metamask-extension/pull/18161
- [x] Merge https://github.com/MetaMask/metamask-extension/pull/18175
- [x] https://github.com/MetaMask/metamask-extension/pull/18979

### References
[Modal Audit FigJam](https://www.figma.com/file/hxYqloYgmVcgsoiVqmGZ8K/Modal-Audit?node-id=0%3A1&t=WcWEbEnjEkGuOdXr-1)
[Figma component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=3180%3A13642)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `modal.js`
- `modal.stories.js`
- `modal.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by Akatori-Design** [comment]
Im updating the `Avatar Icon` to `Icon/Xl` 
(*Note that `Modal` uses "`Icon/Xl`" while `Banner` uses "`Icon/Lg`")
cc: @georgewrmarshall @garrettbear  @NidhiKJha 

REASON
- Same as Banner. To avoid `Modal` from being a dependency of `Avatar Icon` since `Avatar Icon` is going through a change.
- Also for better readability.

BEFORE
<img width="493" alt="image" src="https://user-images.githubusercontent.com/55973039/204631130-0b7709ca-a43d-49a4-90bb-b09dbbc765ca.png">

AFTER
<img width="492" alt="image" src="https://user-images.githubusercontent.com/55973039/204631203-849a336e-d785-462c-a09c-309bb5e3270e.png">


Updated in a Figma branch : https://www.figma.com/file/2ne9CJkcAXfZXc15qxlfHy/Status-icon-updates-for-Banner-%26-Modal?node-id=8813%3A26030&t=8q6Mwt7VGViMIkRw-4

**Comment by georgewrmarshall** [comment]
@Akatori-Design that's fine.
