### ISSUE TITLE
[Bug]: Error "wallet must has at least one account" while trying to login via extension

### ISSUE THREAD

**Issue by SerejaSerjik** [MetaMask/metamask-extension#15651]
### Describe the bug

On a website debank i cannot login and get titled error message, while on opeansea i can't login because login function not working with hidden error message, but i think it's the same. 
I try to use chrome with metamask on new PC and i have 5 times try with reinstall extension and import my wallet through recovery phrase. Every time i get same error. What kind of cookies do store my PC? What should i do and why there is no google results about this error message.

### Steps to reproduce

1. Install metamask extension
2. Import account via recovery passphrase
3. Go to debank website
4. Try to login

### Error messages or log output

```shell
wallet must has at least one account
```

### Version

10.18.3

### Browser

Chrome

### Operating system

Windows

**Comment by kevinghim** [comment]
@SerejaSerjik can you provide video or screen captures?

**Comment by ckelechi** [comment]
Hey all,

I also started experiencing this issue early in August after changing PCs and re-importing my wallet via 
private key (mem.phrase). 
That is, the MetaMask extension stopped working on Chrome
and a few other browsers. While trying various dapps (and dexes), the app failed while returning that message 
to the screen.  'Wallet must **has** one account' ... 
Worrisome, because it seems the grammar is wrong 
and the error should be 'Wallet must _have_ one account' if English is the language meant.
But contributors are looking for screenshots and videos and let me post an instance. 

![image](https://user-images.githubusercontent.com/10385334/187075686-099afed4-8ec7-48fb-ac3f-e94a9c8aae95.png)
[A segment from Fantom's Wallet]. 

Got a read out like that also while trying to use PancakeSwap.

**Comment by cheshirrrcat** [comment]
I got same issue on the https://app.1inch.io
<img width="779" alt="image" src="https://user-images.githubusercontent.com/1543843/187378898-c73ee041-d38a-4309-bc53-57cff43ff15e.png">

**Comment by ckelechi** [comment]
While trying to use Facebook's new account connect feature ... 

![Untitled_WhileTrying](https://user-images.githubusercontent.com/10385334/199814135-a5a949ce-76a6-49f1-a6df-09b709724236.png)
