### ISSUE TITLE
[Bug]: Errors are no longer sent to Sentry

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15666]
### Describe the bug

Before sending an error to Sentry, we check if the user is participating in MetaMetrics.
If the user is not participating we do not send the Error.
However, errors are still not being send for users that have opted into MetaMetrics, `beforeSend` returns `null`

Link to thread: https://consensys.slack.com/archives/GTQAGKY5V/p1660825088262669
See: https://github.com/MetaMask/metamask-extension/pull/15313, https://github.com/MetaMask/metamask-extension/pull/15635

### Steps to reproduce

1. Upgrade from a previous version to v10.18.4
2. Ensure participate in MetaMetrics options is enabled
3. Perform an action that results in an Unhandled Exception being thrown (e.g. https://github.com/MetaMask/metamask-extension/issues/14893)
4. Check error is sent to Sentry

### Error messages or log output

```shell
beforeSend returned null, will not send event.
```

### Version

10.18.4

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment]
This was partially fixed by #15672. But there remains a problem with certain Sentry errors being ignored if you disable and re-enable MetaMetrics.

If an error is encountered when MetaMetrics is disabled, the Sentry Dedupe integration still thinks it was sent. It will prevent it from being sent again when MetaMetrics is re-enabled.

This last issue is solved by #15677
