### ISSUE TITLE
[Bug]: tx decoder failing

### ISSUE THREAD

**Issue by fredlacs** [MetaMask/metamask-extension#15674]
### Describe the bug

When attempting to bridge tokens from Ethereum to Arbitrum, the decoder isn't able to parse the [outboundTransfer function](https://github.com/OffchainLabs/token-bridge-contracts/blob/6fe821f187c47a3057900a51393f8e1ef1e0e436/contracts/tokenbridge/libraries/gateway/ITokenGateway.sol#L43-L50)

### Steps to reproduce

You can reproduce this by going to https://bridge.arbitrum.io/ and trying to bridge a token while connected to mainnet or rinkeby.
Here is the tx where this happened https://rinkeby.etherscan.io/tx/0x5309d0f7fa7b2b1f8c85617fbbbd22217d88eae2065ef555d46a3003cf6c8117

### Error messages or log output

```shell
"Cannot read property of undefined"
```

### Version

10.18.3

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Additional context

I also previously opened an issue with truffle (I thought it was a truffle decoder issue, but they said it may be related to metamask) https://github.com/trufflesuite/truffle/issues/5053#issuecomment-1111647863

**Comment by FrederikBolding** [comment]
For clarity I'm posting reposting this from Slack.

It seems like decoding of the transaction fails and doesn't return the expected arguments :
[https://github.com/MetaMask/metamask-extension/blob/7dc6a5feaabc4754bf73d4abaeb10e[…]ents/app/transaction-decoding/transaction-decoding.component.js](https://github.com/MetaMask/metamask-extension/blob/7dc6a5feaabc4754bf73d4abaeb10ee55570924d/ui/components/app/transaction-decoding/transaction-decoding.component.js#L80-L88)

Perhaps related to the fact that the contract in question is a proxy contract? Stepping through it, it seems that the functionAllocation is missing:
https://github.com/trufflesuite/truffle/blob/574798ee53c762e4bd02d7b635b776c8b13674d2/packages/codec/lib/core.ts#L96-L103

If that is the case, I'm not sure if there is ongoing work at Truffle to support proxies better. Otherwise, we should probably disable the feature for proxied contracts?

**Comment by FrederikBolding** [comment]
After chatting with our friends at Truffle we have decided that this can be fixed by checking the `kind` of the decoder result. If the kind is not `function` we should show an error explaining that decoding has failed.

@bschorchit

**Comment by bschorchit** [comment]
We won't necessarily know the reason of the failure (asked it in DMs to Frederik) so what about displaying a generic and broad message such as: `The decoding of this transaction has failed.` for such cases? Any suggestions, @coreyjanssen ?
