### ISSUE TITLE
Metamusk not working in Brave browser. slow transaction! [Bug]: 

### ISSUE THREAD

**Issue by sakilhasansaikat** [MetaMask/metamask-extension#15721]
### Describe the bug

Metamusk not working in Brave browser. slow transaction!

0x82Bcf49437dc29ec5Ebc3dCc4f5e8A7F8D2068DB

### Steps to reproduce

1.
0x82Bcf49437dc29ec5Ebc3dCc4f5e8A7F8D2068DB cheek this wallet!

### Version

MetaMask Version 10.18.3

### Browser

Brave

### Operating system

Windows

**Comment by sakilhasansaikat** [comment]
showing this : 

Error
×Close
Something went wrong: Approval failed

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"replacement transaction underpriced"}}}'

**Comment by panoplied** [comment]
This error could indicate that you have pending transactions. In this case try cancelling the oldest pending one in MM.

This also can mean that the gas price for the transaction is too low. Either caused by manual tinkering with gas or incorrect gas estimation from the front-end you're interacting with. Try increasing priority fee.

There are also possible solutions like resetting MM account etc.

In any case to be properly processed your issue requires more specific info on what is it you're trying to do.

**Comment by sakilhasansaikat** [comment]
ok thank you.
