### ISSUE TITLE
Create "view NFTs" modal

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15751]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14708)

## Acceptance Criteria
1. The modal displays the NFTs that are being requested allowance for (for individual NFT approval, it displays the specific NFT that the user owns; for setApprovalForAll it displays all NFTs that the user owns within that collection);
2. Total is number of NFTs that the user is being requested allowance for (for individual NFT approval, it's 1 ; for setApprovalForAll it's the number of NFTs the user currently owns within that collection);
3. Modal title should read "NFTs being accessed";
4. "When should I not give access to all my NFTs?" should link to https://metamask.zendesk.com/hc/en-us/articles/6174898326683-What-is-a-token-approval-#h_01GA1DZF6GH7EAJV86X6D839H6:~:text=setApprovalForAll%3A%20Making%20it%20easier%20to%20know%20what%20you%27re%20approving%20in%20MetaMask;
5. Clicking on "Got it" button closes the modal.

![Screen Shot 2022-09-06 at 22 26 47](https://user-images.githubusercontent.com/34968356/188768555-6d4defbd-97ed-45f9-a172-df5a658d3023.png)
![Screen Shot 2022-09-06 at 22 26 28](https://user-images.githubusercontent.com/34968356/188768563-19c9b779-0530-4e49-b328-e3be6358b7e1.png)

**Comment by ElvirCe** [comment]
Blocked due to missing design for SetApprovalForAll, once the design is ready we can continue with this ticket. 

Note: Also, the [PR](https://github.com/MetaMask/controllers/pull/1008) needs to be reviewed for the latest changes that were discussed [here ](https://consensys.slack.com/archives/C01V1L10W2E/p1668684685967009) before we can proceed further. 
CC: @bschorchit
