### ISSUE TITLE
[Bug]: [MV3] The Smart Transaction popup disappears before I can read it / close it

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15892]
### Describe the bug

**Problem**: when I click on Swap for the first time, I see the usual display for Smart Transaction, but this disappears after a few seconds, without me closing it or being able to read it.

[mv3-stx-disappearing-popup.webm](https://user-images.githubusercontent.com/54408225/191308502-b7aa4c0d-6122-4189-a15d-260a482ed3ad.webm)

### Steps to reproduce

1. Unlock MM
2. Select Goerli network
3. Click Swap -- wait

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by segun** [comment]
There's some sort of chicken and egg problem here.

The condition on [this line](https://github.com/MetaMask/metamask-extension/blob/22f07aefe31a5b07720c3204c1a5fa3116f730b8/ui/pages/swaps/build-quote/build-quote.js#L174) says show the popup if stx is enabled or if the popup has not been shown before.

On my first run, for one second before the selectors returned `smartTransactionsEnabled` is false and `smartTransactionsOptInPopoverDisplayed` is true,  which means the popup is shown for that one second...once the selectors returned, `smartTransactionsEnabled` is false and `smartTransactionsOptInPopoverDisplayed` is also false and the popup disappeared.

The issue is `smartTransactionsEnabled` can only be true if we click the button on the popup and the popup is not staying long enough for that to happen.

If I do this however
```
  const showSmartTransactionsOptInPopover = !smartTransactionsOptInPopoverDisplayed;
```

It works as expected. Popup is displayed and when we enable stx or close the popup, popup is not displayed again.

But that poses another problem. The only place to enable stx is on that popup, so this means the user can never change their mind to enable stx again unless they re-install MetaMask

I think we should do this

```
  const showSmartTransactionsOptInPopover = !smartTransactionsOptInPopoverDisplayed;
```

as well as add an option to settings somewhere to enable/disable stx.

**Comment by danjm** [comment]
Looks like this is a problem on MV2 as well, but only on the goerli network

The API seems to be returning false for the `liveness` property for smart transactions on goerli.

Meanwhile, we shouldn't show the smart transactions pop up while waiting for the fetch for the liveness state to resolve
