### ISSUE TITLE
[Bug]: [MV3] Upgrading from MV2 to MV3 instance throws error `document is not defined` and cannot login

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15923]
### Describe the bug

**Problem**: when I am upgrading from MV2 MM instance to MV3 I get the error `document is not defined` and I cannot login to MM anymore.

This seems it's what it would happen to users when we release and rollout MV3.

[mv2-to-mv3-update.webm](https://user-images.githubusercontent.com/54408225/191517285-f7eb2848-ac34-4d92-adbe-3413fd276508.webm)

### Steps to reproduce

1. Start MM MV2 `yarn start`
2. Add the extension on Chrome
3. Create an account
4. Start MM MV3 `yarn start:mv3`
5. Without removing the instance, wait until it loads
6. Click Reload Extension
7. Open MM
8. Enter password -- see error message `document is not defined`

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
should be fixed by our ledger and trezor fixes

**Comment by segun** [comment]
In MetaMask, when we install two key rings are added to the store

1. HD Key Ring
2. Ledger Key Ring

Ledger Keyring uses iframe in MV2 so it works well.

When we launch MetaMask (and try to login), we try to decrypt and unlock ALL the keyrings. Again, In MV2 this is no issue.

Now when we upgrade to MV3, we try to unlock all the keyrings as usual, but since ledger uses document.iframe, we get the error document is not defined.

But why does it work when we un-install and re-install: Because when we install, we try to add both keyrings above and the ledger keyring will fail. Which means only the HD Keyring gets added to store, therefore when we try to login, only the HD Keyring is in store and that's the only one we try to decrypt/unlock.

Closing this issue as the work on hardware wallets will fix it.

**Comment by seaona** [comment]
Great investigation!! Ty @segun @danjm
