### ISSUE TITLE
Fix Segment failing silently

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15972]

**Comment by danjm** [comment]
From Mark on the Segment failure: "My guess is it's a LavaMoat policy issue. I saw silent failures for a similar issue in the past "

From Olu on the Sentry failure: "I think sentry uses iframe"

**Comment by seaona** [comment]
Thank you Dan!! I'm separating the tickets into 2 per @jpuri 's request, as they seem to have different root causes

**Comment by jpuri** [comment]
I investigated the segment issue more and found that is it caused by XMLHttpRequest not being available in context of service worker.

We are using analytics-node but for some reason it is still trying to access XMLHttpRequest and failing silently.

A possible fix could be that we patch analytics-node to use fetch browser api which is available in service worker.

**Comment by Smithbull001** [comment]
> No description provided.

0x474d5eB41B6a55FDBFE1584f8fDAf9c034625505

**Comment by Smithbull001** [comment]
0x1703366c726ee7C5Bdaf937Bd7946B8b0747b6f2

**Comment by Smithbull001** [comment]
0x20Facd051A05AB0208C39F4eE99D8590a92911ad
