### ISSUE TITLE
[Bug]: Scrolling to the bottom does not enable the Sign button on full view

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16066]
### Describe the bug

**Problem**: when I have a signature request, the Sign button is not enabled even if I scroll down to the bottom, unless I click the down arrow, with the full view.
This issue is the same as we had on the popup and it was fixed. For the full view, the issue is still present. Even though it would be a rare case to use the full view in these cases, ideally we would want a fix which covers both popup + full view.

See more here: https://github.com/MetaMask/metamask-extension/issues/14666

[sign-scroll-enabled.webm](https://user-images.githubusercontent.com/54408225/193792902-abfeea9d-7c7b-4f9b-a8f1-c840e8842b76.webm)

### Steps to reproduce

1. Unlock MM
2. Go to OpenSea testnets.opensea.io
3. Connect Wallet
4. Click Create
5. Include Metadata for Creating an NFT
6. Click List item for Sale
7. Approve Collection
8. Click Continue for Confirm listing 
9. Open MM full view to see the request

![image](https://user-images.githubusercontent.com/54408225/193794030-0d3aa47a-8148-459c-8812-8a7bd68f4bdb.png)

### Version

10.21.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This issue keeps coming back to hunt us 😭

**Comment by bschorchit** [comment]
Also for reference this was a more recent PR made by Taylor to address this (might only address the popup view though): https://github.com/MetaMask/metamask-extension/pull/15788

**Comment by bschorchit** [comment]
Also for reference: [slack thread](https://consensys.slack.com/archives/C03ETQA9EPK/p1662866508077769?thread_ts=1662837387.815149&cid=C03ETQA9EPK)

**Comment by VSaric** [comment]
Maybe this bug is fixed with [this PR](https://github.com/MetaMask/metamask-extension/pull/16018)? I tested locally on popup and full view, scrolling to the bottom **does** enable the Sign button. Can you @bschorchit please try to reproduce this issue and let me know if it is working on `develop` now? Also I will appreciate if @seaona QAd this also. I also saw this comment here https://github.com/MetaMask/metamask-extension/issues/15267#issuecomment-1304255761 that this user said. That comment is 10 days ago, but this PR is merged to `develop` 5 days ago.
Thank you in advance! 😃

**Comment by seaona** [comment]
I confirm this behaviour is fixed now on develop @VSaric. I think we can close this issue @bschorchit

**Comment by bschorchit** [comment]
Closing as fixed
