### ISSUE TITLE
Investigate bundle size increase caused by #15889

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16270]
https://github.com/MetaMask/metamask-extension/pull/15889 caused a bundle size increase

We need to investigate to understand why this happened, and then try to reverse the bundle size increase

**Comment by FrederikBolding** [comment]
My guess would be because we rely on `metamask/controllers` in the snaps repos and sometimes are ahead of the extension with versions, this can cause extra dependency versions to be added. For example, looking at this PR there are multiple versions of `ethersproject` packages as well as `metamask/controllers` itself.

**Comment by FrederikBolding** [comment]
We currently have several versions of `metamask/controllers` due to snaps packages and `smart-transactions-controller`. Will make sure these get up to date with latest controllers

**Comment by danjm** [comment]
This investigation resulted in tickets being added to https://github.com/metamask/metamask-extension/issues/14884
