### ISSUE TITLE
[Bug]: [MV3] Cannot read properties of undefined (reading 'symbol'), after terminating service worker during a Swap

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16318]
### Describe the bug

**Problem**: if service worker is terminated when I am performing a Swap, I land into MM error page with the error `Cannot read properties of undefined (reading 'symbol')`.

![undefined-symbol](https://user-images.githubusercontent.com/54408225/198889492-cd833c7b-d311-40ba-95e6-0b3228cd1ce8.png)

### Steps to reproduce

1.Click Swap
2. Introduce amount
3. Introduce token
4. Click Review Swap
5. Terminate service worker -- you can proceed normally
6. Click Confirm Swap
7. Terminate service worker 
8. Click Swap -- you land on the error page

https://user-images.githubusercontent.com/54408225/198889696-bada605a-65c7-4d20-ad8b-9e96e85c1f19.mp4

### Version

Tested on top of this PR https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

**Comment by adonesky1** [comment]
So what’s happening when the service worker is terminated is that the `SwapsController` controlled `swapsState` is getting reset and so the quotes empty out along with other `fetchParams` causing a redirect:
https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/swaps/index.js#L505  . So if you don't quickly hit the `swap` button on the `view quotes page` you will see us redirected back to the `build-quote` page.

But if you hit swap button before the redirect we [hit this call](https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/swaps/index.js#L257) to `prepareToLeaveSwaps`, which clears the swaps state

But before the state clearing process is complete the `signAndSendTransactions` call - [that is initiated when](https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/swaps/view-quote/view-quote.js#L1018) you hit the `swap` button - goes through with the swaps state intact 
https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/swaps/index.js#L257

once you arrive on the `awaiting-swaps` page, though the swap has been submitted correctly, the token information that we use to tell the user which token they will be receiving is no longer accessible since it is accessed through the now cleared `swapsState` (from the `SwapsController` in the background)

**Comment by adonesky1** [comment]
Currently waiting for smart-transaction service on Goerli to get back online so I can test/debug the equivalent changes in the smart-transaction swap flow
