### ISSUE TITLE
[Bug]: [MV3] Token detection is caching results between accounts when terminating service worker

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16349]
### Describe the bug

**Problem**: when I terminate the service worker and I change accounts, I see that the tokens detected are cached.

https://user-images.githubusercontent.com/54408225/199470301-596396d3-e524-4097-9a1e-faaa98421993.mp4

### Steps to reproduce

1. Unlock MM
2. Get some tokens on the first account, so they are detected
3. Create a fresh new account
4. Change back to the account from step 2
5. Terminate service worker
6. Change back to the account from step 3 -- see that token detected are cached

### Version

Tested on top of this PR https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

### Additional context

There is another caching issue with Token Detection which might also be related? See this comment and issue on MV2
https://github.com/MetaMask/metamask-extension/issues/16057#issuecomment-1291129607

**Comment by adonesky1** [comment]
@seaona I'm having trouble reproducing... 🤔 

https://user-images.githubusercontent.com/34557516/200005217-0ea77747-83d0-477a-a5e4-c35fd6474e2e.mov

**Comment by adonesky1** [comment]
I have discussed with @seaona and neither of us are able to reproduce currently atop https://github.com/MetaMask/metamask-extension/pull/15558 (user is currently logged out). Nor am I able to reproduce on develop (with password saved as env variable). Considering this paused/blocked until #15558 is fixed.

**Comment by adonesky1** [comment]
@NiranjanaBinoy can you link video of your reproduction? Are you able to reproduce on top of #15558 or on develop?

**Comment by NiranjanaBinoy** [comment]
@adonesky1 I was able to reproduce the bug on top of #15558; I cannot exactly pinpoint the exact scenario when it is occurring. Every time it appeared only after multiple tries, as you can see on the recording, but I think it does happen after I got logged out of the app once or twice. 

It could be an issue with `this.selectedAddress` not getting updated on time, as `selectedAddress` and `tokenList` are the only properties we are passing into `getBalancesInSingleCall` while fetching the tokens with balance, and here tokenList is the same as the network is same. As we are not saving the balance in our state for `detected-token` page, we are using `useTokenTracker` to get the balance in `detected-token` page, so that page will showcase the list of tokens in`detectedTokens` prop in the state with the balance from `useTokenTracker`.

>       result = await this.assetsContractController.getBalancesInSingleCall(this.selectedAddress, tokensSlice);

https://user-images.githubusercontent.com/43930900/200441781-8a4f34a2-ef71-487b-9ee3-ff93ade81a0d.mov

**Comment by adonesky1** [comment]
@seaona ok I am now able to reproduce this on top of https://github.com/MetaMask/metamask-extension/pull/15558
