### ISSUE TITLE
[Bug]: Firefox seems broken when loaded in the browser. Importing a Wallet on Firefox causes error `this.state is null`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16484]
### Describe the bug

**Problem**: loading MM on Firefox throws `TypeError: Network Error` on the console.

When I use the Import Wallet onboarding flow, and I introduce the seed-phrase I stay in the same seed-phrase page after clicking Submit several times. If I then refresh the browser, I land into the next screen, with the console error `Uncaught TypeError: this.state is null` on the `import-seed-phrase.component.js`

I cannot create any Accounts with this Wallet and FF breaks at some point.

https://user-images.githubusercontent.com/54408225/201682997-8e64b462-3d7a-4687-8286-7d77772d8a18.mp4

### Steps to reproduce

1. Load MM for the first time on Firefox
2. Click Import Wallet
3. Enter a seed-phrase
4. Click Submit -- see you stay on the same page
5. Click Refresh -- see you land into Secure Wallet page with the console error `this.state is null``

### Version

10.23.0

### Browser

Firefox

### Operating system

Linux

**Comment by jpuri** [comment]
The issue appears to be caused in FF while sending backend updated to UI:

<img width="1213" alt="Screenshot 2022-11-16 at 11 55 25 PM" src="https://user-images.githubusercontent.com/2182307/202281161-75fde71d-db6c-4545-b477-d22904d7846d.png">

Breaking behaviour seems to have started since this commit: https://github.com/MetaMask/metamask-extension/commit/f3efe5a0bd4ff1bfaf46cb3a82f521a9881d4f01

**Comment by jpuri** [comment]
I spent much time on this issue again, but it looks weird. I am wondering if its really an issue or just some browser cache issue in development mode as e2e are also passing.
