### ISSUE TITLE
Investigate whether we can remove `eth-lattice-keyring > gridplus-sdk > eth-eip712-util-browser`

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16541]
size: 84kb

**Comment by brad-decker** [comment]
It is in fact being used. I was able to completely remove this package by patching in using @metamask/eth-sig-util instead of this package in gridplus-sdk. Technically this will *increase* gridplus-sdk dependency size. but it will reduce our bundle size because of the alignment between the dependencies. I did not test if this WORKS but its an option.

**Comment by brad-decker** [comment]
Alternatively gridplus or us could reach out to coinbase to produce a new build of the -browser version of eth-eip712-util OR have gridplus simply use eth-eip712-util as I dont' see why the -browser version was made in the first place.

**Comment by legobeat** [comment]
Resolved by: #27973
