### ISSUE TITLE
[Bug]: [MV3] Loading a detected phishing page for the first time does not show the phishing page warning

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#16551]
@seaona observed refreshing the extension from `chrome://extensions` and then opening a URL detected as a phishing page will not show the phishing warning page. 

Looking into this, it appears that the blocklist may not finish loading when the user first lands on a detected phishing page.

Observe breakpoint hit when list has not finished loading (`eth-phishing-detect/src/detector`):
![Screen Shot 2022-11-17 at 05.57.15.png](https://images.zenhubusercontent.com/61e704d1d91454c211838f69/b6537a5f-debc-4fca-a394-9baab4b7133f)

Observe breakpoint when list is loaded. 
![Screen Shot 2022-11-17 at 05.58.48.png](https://images.zenhubusercontent.com/61e704d1d91454c211838f69/79be0e98-fb8a-4167-acf7-573d947a9eb2)

Related Repos:
- https://github.com/MetaMask/eth-phishing-detect
- https://github.com/MetaMask/controllers

For some reason, I am only able to repro this issue on MV3 and not MV2.

**Comment by segun** [comment]
I've been testing this using this branch #15913 and I can't replicate the issue. I always get the phising screen after a refresh.


@seaona can you please check to see if this branch fixes the issue?

**Comment by seaona** [comment]
I still can reproduce @digiwand 's behaviour mentioned above on the branch you pointed out @segun. The issue is that the phishing list does not load completely at the first time.

![image](https://user-images.githubusercontent.com/54408225/203330310-ee7b8e34-3821-42f4-b9aa-45f88fb4769d.png)

**Steps to repro:**
1. Load MV3 MM
2. Add a breakpoint on `/detector.js` file on line 182 `return list.some...`
3. Open a phishing page
4. See list of blocked sites is smaller than expected

**Comment by segun** [comment]
@seaona Thanks. I'm now able to reproduce the bug and have a fix.
