### ISSUE TITLE
[Bug]: Cannot navigate through multiple Sign prompts for Signed Typed Data `V3` and `V4`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16848]
### Describe the bug

**Problem**: we cannot navigate through multiple Sign prompts for Signed Typed Data V3 and V4. The expected behaviour is the one we see for Signed Type Data, Personal Sign and Eth Sign.

https://user-images.githubusercontent.com/54408225/206234177-845cbb7e-8454-47c6-bcbd-4daedb292ebd.mp4

### Steps to reproduce

1. Connect to Test Dapp https://metamask.github.io/test-dapp/
2. Click 3 times on Sign for Typed Data V4 -- see you cannot navigate through the multiple prompts nor Reject them all at once
3. Reject one by one
4. Click 3 times on Sign for Typed Data V3 -- see you cannot navigate through the multiple prompts nor Reject them all at once

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by ElvirCe** [comment]
@bschorchit I believe that this is not a bug as it is currently how it works on the production. @bschorchit can you please confirm and if we need to change and add a switch option we will need to determine the steps and acceptance criteria.

**Comment by ElvirCe** [comment]
Expected behavior: 

1. Click 2 or more times on Sign for Typed Data V4: 
- The users should be able to navigate between multiple sign prompts back and forth 
- The users should be able to reject all sign prompts at once 

2. Click 2 or more times on Sign for Typed Data V3:
- The users should be able to navigate between multiple sign prompts back and forth 
- The users should be able to reject all sign prompts at once 

3. Both options, Reject All and Switching Between Sign Attempts, should be available in combination, i.e. user clicked 2 times on Typed Data V4 and 2 times on Typed Data V3. 

![Image](https://user-images.githubusercontent.com/98470173/207579957-9ec22361-d9d3-4916-9bbc-8a2a5076da0b.png)

![Image](https://user-images.githubusercontent.com/98470173/207580402-304d29be-4b45-42a2-b82b-5ec49f23c56b.png)

**Comment by bschorchit** [comment]
Thank you for adding the detailed description, @ElvirCe ! Small comment: could we do it for Eth Sign, Personal Sign and SignTypedData too besides SignTypedData_v3 and SignTypedData_v4?
Eth Sign, Personal Sign and SignTypedData already have the reject all part in the bottom, but they don't have the part to navigate between sign prompts at the top.
