### ISSUE TITLE
yarn lint:changed:fix stopped working

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17022]
I've noticed that at some point within the past 2 weeks, the `yarn lint:changed:fix` command stopped working. `yarn lint:fix` still works, but I rely on `yarn lint:changed:fix` a lot while developing because it is a lot faster.

**Comment by EresDev** [comment]
I have doubts about both `yarn lint:changed` and `yarn lint:changed:fix` not working. Even though results of `yarn lint:changed` appears to be correct but it is not the output of eslint but more of `git diff-index --name-only --diff-filter=d HEAD`.

**Comment by EresDev** [comment]
Ok, this is caused by current version 3.2.4 of yarn. I tried higher version as well 3.3.1 and it didn't work either. Yarn 3 appears to have problem with piping "|".

Yarn 3 was added to metamask 2 weeks ago  https://github.com/MetaMask/metamask-extension/pull/16232

Both scripts `yarn lint:changed` and `yarn lint:changed:fix`  worked when I have downgraded yarn to 1.16.0. 

Plus, both scripts work fine with npm as well.  So the scripts are correct.

**Comment by brad-decker** [comment]
The issue is with the `{ }` concatenating the output of the two commands within them, not sure why, but all I had to do was elevate these two commands into their own script file and call that script directly. https://github.com/MetaMask/metamask-extension/pull/17028

**Comment by TROUBLE4UALL** [comment]
How does this work?
