### ISSUE TITLE
[Bug]: MM is sending RPC requests to another custom network, aside from the one that's currently selected

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17040]
### Describe the bug

**Problem**: after adding a custom localhost network, if I change to another network and terminate the ganache server for localhost, I still can see how requests are being send to the localhost custom network together with the requests to the currently selected network.

https://user-images.githubusercontent.com/54408225/209115431-80f25d71-ef80-4ffc-98d3-fa05be22e1a9.mp4

### Steps to reproduce

[investigating]
1. Setup a ganache server with a different port number than the default `ganache port 8546`
2. On MM, go to Add Network
3. Add the new server pointing to localhost 8546
4. Change to another network
5. Terminate ganache server
6. Observe network requests on the background console -- requests to the localhost net are still being sent, alongside with requests to the current selected network

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

- This duplicate ticket also provides steps to reproduce: https://github.com/MetaMask/metamask-extension/issues/23415

**Comment by seaona** [comment]
Added 10.24.0 to have eyes on it, but cannot confirm it's an RC regression. Issue is hard to repro

**Comment by alirezahydary** [comment]
Hm_lpvt_b46777860a3e1d6895b3546afafc8b0f=1671909913

**Comment by alirezahydary** [comment]
https://github.com/MetaMask/metamask-extension/issues/17045#issue-1507891173

**Comment by alirezahydary** [comment]
#16830 
#17064 @alirezahydary 
@lastcanal 
@makoto

**Comment by alirezahydary** [comment]
[Uploading 1475284314671IANA_Naming_Function_Contract.PDF…]()

**Comment by alirezahydary** [comment]
[XE_Currency_Data_API_Non_Technical_Quick_Start_Guide-.pdf](https://github.com/MetaMask/metamask-extension/files/10304173/XE_Currency_Data_API_Non_Technical_Quick_Start_Guide-.pdf)

[1475276357609FINAL_-_PTI_Conflict_of_Interest_Policy_-_28_September_2016.pdf](https://github.com/MetaMask/metamask-extension/files/10304174/1475276357609FINAL_-_PTI_Conflict_of_Interest_Policy_-_28_September_2016.pdf)

**Comment by alirezahydary** [comment]
#17069 
https://mobidrive.com/sharelink/w/6MMLB47DZAqRorgt5BV33H56iYJD1yDn0eygeVnMLe9U

**Comment by alirezahydary** [comment]
@makoto 
@mcmire https://mobidrive.com/sharelink/w/6MMLB47DZAqRorgt5BV33H56iYJD1yDn0eygeVnMLe9U

**Comment by seaona** [comment]
Another example here:

https://user-images.githubusercontent.com/54408225/224253719-d3ea254d-81fb-4aca-a706-bb6ef8683a58.mp4

**Comment by seaona** [comment]
This issue is still happening. I just encountered it again in prod 11.10, having a Tenderly network selected, which was not working, then switching to Mainnet, and I still see failed requests being sent to Tenderly RPC



https://github.com/MetaMask/metamask-extension/assets/54408225/11e76f7f-287f-40ff-9374-926843b9f04c

**Comment by gauthierpetetin** [comment]
This duplicate ticket also provides steps to reproduce: https://github.com/MetaMask/metamask-extension/issues/23415

**Comment by Gudahtt** [comment]
This may be fixed by https://github.com/MetaMask/eth-block-tracker/pull/208, which is in eth-block-tracker@9.0.3

**Comment by mcmire** [comment]
I tested this and I wasn't able to replicate the behavior described here, so I think the PR mentioned above probably got rid of it. There are some improvements we should make, such as:

- Reducing the frequency that the "latest block" request is retried on an unavailable network. The fetch middleware, Infura middleware, and the PollingBlockTracker all have retry logic. For the fetch and Infura middleware, the retry interval is 1 second (see [here](https://github.com/MetaMask/eth-json-rpc-middleware/blob/1d61dc8f966bc23aa628a11f2250cec2ac1963ab/src/fetch.ts#L68) and [here](https://github.com/MetaMask/eth-json-rpc-infura/blob/de39c529faf38e12df5df9b8f319111a8f405551/src/create-infura-middleware.ts#L129)); for the PollingBlockTracker it's the polling interval / 10 (see [here](https://github.com/MetaMask/eth-block-tracker/blob/a2ad9e388ad831d68eb496c8d4c76c7d1bf1cdc8/src/PollingBlockTracker.ts#L84)). We can reduce the frequency of retries by passing both a `pollingInterval` and `retryTimeout` to PollingBlockTracker and making them the same.
- Stopping the PollingBlockTracker after a while if the network is truly down.
- Adding a timeout to `getLatestBlock` in PollingBlockTracker so that if the network is down, the promise that this method returns gets eventually rejected. Without this, if you are connected to an unavailable network and restart the extension, MetaMask will show a spinner forever, but with this timeout, MetaMask will eventually show a "could not connect" error and let you switch to an available network.

But, I think all of these problems are unrelated to this exact issue. Therefore, I am inclined to close this ticket. Any last thoughts before I do so?

**Comment by mcmire** [comment]
https://github.com/MetaMask/metamask-extension/commit/04c2e90094802b23b4265e2ad303978cd3e132c0 (from https://github.com/MetaMask/metamask-extension/pull/24861) is the commit that upgraded `@metamask/network-controller` to a new version that switched from `eth-block-tracker` to `@metamask/eth-block-tracker`, incorporating the fix made in https://github.com/MetaMask/eth-block-tracker/pull/208. I tested the commit before this and the commit after this, and confirmed that the problem went away with this commit.

Closing.

**Comment by mcmire** [comment]
I have confirmed that https://github.com/MetaMask/metamask-extension/pull/24861 will go into 12.0.0.

**Comment by Gudahtt** [comment]
Unfortunately I am still able to reproduce this bug even on v9.0.3 of eth-block-tracker. I was able to reproduce it using these steps:
* Add BNB and switch to it
* Block requests to that domain in the dev console
* Rapidly switch back and forth between networks until I see it get into a failing loop

It's inconsistent, it can take many attempts. Usually I just see 3 failures after switching, and then it stops. But it can get stuck in an infinite loop of failures still.

**Comment by desi** [comment]
Note: For reference weekly checkin recording for WF team - time 9:25 discussion around this issue.

**Comment by DDDDDanica** [comment]
Update: this issue is still occurring on 11.16.15 

https://github.com/user-attachments/assets/b6f73e2b-883f-4a59-a7f2-12b7875d8342

**Comment by mikesposito** [comment]
I'm unable to repro this on v12.1.2 - I'm trying to see if I can find the commit that potentially fixed it
