### ISSUE TITLE
[Bug]: Firefox becoming unresponsive and leaking memory with MetaMask extension on some pages

### ISSUE THREAD

**Issue by FLeXyo** [MetaMask/metamask-extension#17112]
### Describe the bug

It seems that something causes Firefox to become completely unresponsive and memory usage to go up to several gigabytes very quickly as soon as you load a page that has a Google Trends chart embedded for example.

### Steps to reproduce

1. Install MetaMask extension in Firefox
2. Go to https://trends.google.com/trends/embed/explore/TIMESERIES?req={%22comparisonItem%22%3A[{%22keyword%22%3A%22quake%22%2C%22geo%22%3A%22%22%2C%22time%22%3A%22all%22}%2C{%22keyword%22%3A%22unreal%20tournament%22%2C%22geo%22%3A%22%22%2C%22time%22%3A%22all%22}]%2C%22category%22%3A0%2C%22property%22%3A%22%22}&tz=-60&eq=date%3Dall
3. Your browser becomes unresponsive and you can't even open DevTools in the tab anymore.

### Version

10.22.2

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by John4266** [comment]
related #5871

**Comment by dvartic** [comment]
I can also attest that this is happening. In just a few minutes, it can eat up all system memory 32GB + swp. Also Metamask does not open.

**Comment by Snaddyvitch-Dispenser** [comment]
I'm also getting this issue, I actually ended up going to Firefox first about this as the task manager didn't specifically show it as Metamask. My memory logs are here in case it helps -> https://bugzilla.mozilla.org/show_bug.cgi?id=1817597

Every tab I open creeps up to 6GB of memory usage after around 30 seconds and after 5 or so tabs my entire PC freezes due to being out of 32GB of memory.

**Comment by KMikeeU** [comment]
I'm just now facing the same issue 3 months later. When will this finally be fixed? This is a massive problem. Fills up 32GB of RAM and 60GB windows pagefile in less than a minute.

**Comment by thetanaz** [comment]
Same issue on Firefox 112.0 64 bit on Windows 11 latest build. It's been happening since I upgraded to this version. Happens around 2-3 times a day where I have to close all browser windows and then reopen so that RAM would clear up. Last time the browser wasn't even able to restore my last opened windows and tabs which was not pretty to say the least.

**Comment by TheAquabat** [comment]
I have this bug too. And maybe it's not a metamask bug, because it happens with Phantom Wallet extension too. Or maybe both extensions share some code? I don't know but only way I can open that link is **disabling  both** extensions, also happens for me with the knowyourmeme site.

**Comment by mangl-auf** [comment]
Sadly, still not fixed.

**Comment by Kritnich** [comment]
Just encountered this by opening https://graphtreon.com/creator/inccel
Even closing the tab won't stop it from consuming more memory, only closing Firefox entirely helps.
