### ISSUE TITLE
[Bug]: Hardware wallet account name collision

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17358]
### Describe the bug

Users can still run into name collisions for hardware wallets

https://user-images.githubusercontent.com/53189696/214123902-b03f2061-c070-470d-9091-7c4d64aef48d.mov

### Steps to reproduce

1. Login
2. Create a new account
3. Rename the account `Trezor 1`
4. Click the account icon and then select the `Connect hardware wallet` menu item
5. Click the `Trezor` option
6. Connect a Trezor account

### Version

10.25

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Related to https://github.com/MetaMask/metamask-extension/pull/16752

**Comment by danjm** [comment]
@PeterYinusa is this a regression? If this is the same behaviour as before #16752, then I don't think it needs to be marked as a regression and release blocker.

It's true that #16752 does not fully prevent name collisions, but v10.25.0 will still be an improvement in that regard. We might want to update the changelog to clarify that name collisions are only prevented in the case of standard (non-hardware wallet) accounts.

Then, this bug regarding hardware wallet name collisions, could be fixed in the future. Let me know if there are any concerns with this.
