### ISSUE TITLE
[Bug]: Optimism Edit fees button does nothing on Token Approval Confirmation screen both for ERC20 and ERC721 tokens

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17427]
### Describe the bug

**Problem**: for some reason, the Edit fees functionality on Optimism was removed together with the Edit button (see [this issue](https://github.com/MetaMask/metamask-extension/issues/14735)). Now, when we are on the confirmation screen for Token Approval, we can see that there is again an Edit button for the fees, but when I try to change the values it's not possible.

https://user-images.githubusercontent.com/54408225/214814166-e9c7ccca-86e4-457b-8605-74e6830a1c4a.mp4

The solution should be:
- either support the Edit fees functionality on Optimism
- or remove the Edit button on the Approve Confirmation screen

### Steps to reproduce

1. Select Optimism network
2. Go to an ERC20 token contract https://optimistic.etherscan.io/token/0x94b008aa00579c1307b0ef2c499ad98a8ce58e58#writeContract
3. Click Connect MM
4. Click Approve function
5. Add a spender and an amount
6. Click Write
7. Add amount on MM
8. Click Next -- see Edit fees button is there
9. Click Edit fees
10. Click Edit -- see how you cannot change the amounts

For the ERC721, follow the same steps but change the etherscan address to an ERC721 token contract. I.e.

https://optimistic.etherscan.io/token/0xc36442b4a4522e871399cd717abdd847ab11fe88#writeContract

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by tayvano** [comment]
Additional context and commentary from Optimism and MetaMask on our handling of gas:

Original PR from 2021 here: https://github.com/MetaMask/metamask-extension/pull/11435

The lack of editability for Optimism's gas was mentioned today on twitter [here](https://twitter.com/0xngmi/status/1625986799389515776):

> why doesnt metamask allow me to change tx gasLimit on optimism?
> it allows this on other chains but not on optimism?

[Dan M](https://consensys.slack.com/archives/GTQAGKY5V/p1676526505229699?thread_ts=1676525556.667739&cid=GTQAGKY5V) shared historical context that this originally was something optimism requested of us because of the unique way they used to do gas. Changing it "should be pretty quick though." 

[Zain @ Optimism](https://consensys.slack.com/archives/C01KXHPU3C6/p1676508921259789) is on board with making this editable. (internal slack link, copied below)

> Can we enable Gas controls on Optimism with Metamask? I believe the language you're pointing to around gas limits not working on Optimism references an older version of Optimism, users are able to change the gas limit.

> Huge +1 here! This looks like it was leftover from a long time ago when we used to encode the L1 Gas price into our L2 gas limit, which was removed over a year ago!

Yet another reminder as to why we prefer to avoid one-off customizations on shared controllers whenever possible.

---

On the docs front, Zain specifically mentioned this article (I've already pinged to get the link update, sharing here in case other things need to be updated too)

> Can we update the link for "How Optimism works" on this article https://metamask.zendesk.com/hc/en-us/articles/4415758352667-Network-profile-Optimism to https://community.optimism.io/docs/protocol/2-rollup-protocol/?

**Comment by bschorchit** [comment]
I believe this will be addressed in https://github.com/MetaMask/metamask-extension/pull/18217

**Comment by bschorchit** [comment]
Close as fixed
