### ISSUE TITLE
Add list of owned tokens to account view

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#175]

**Comment by dskvr** [comment]
Any updates on this? Difficult to use MetaMask when token holdings have to be aggregated outside of MetaMask.

**Comment by flyswatter** [comment]
We currently haven't made this a huge priority, we have a lot of things we consider more important.

I think this mostly comes from the fact that we're injecting the web3 API, so our most important values are about supporting that API and improving its support.

Because we value injecting this support first, literally anyone who knows Javascript can write a new token managing UI that works with MetaMask, right there in the browser, and that's why I don't feel like it's really "outside of MetaMask" at all.

For example, you can use the ethereum foundation's wallet UI with MetaMask, by visiting https://wallet.ethereum.org/

There are other interfaces, too, like TokenNinja and TokenFactory, so you can choose the token managing UI you prefer.

When there are solid solutions like this, the value of us *also* listing the tokens within our popup seems dubious, and I would personally rather we reduce what the popup contains than add more complexity to it, as we've learned that web popups like we've been using have some serious limitations and even buggy behaviors.

I'd be happy to hear what difficulties you're having using tokens with metamask, I'd be happy to be proven wrong, but I think we might just need to encourage different practices.  I *do* think we should show token transfers on our transaction approval screen, but that's a different concern.

**Comment by flyswatter** [comment]
Tokens that have requested support:
- [mona.co](http://mona.co/).

**Comment by tmashuang** [comment]
Closing this issue for tokens. Users will need to manually add the tokens to their token list.
