### ISSUE TITLE
[Bug]: Incorrect balance shown in the signature request header

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17541]
### Describe the bug

Signature request header shows 15,589 GoerliETH instead of 15,589 USD

<img width="1501" alt="Signature request header balance" src="https://user-images.githubusercontent.com/53189696/216090321-ef13e0a6-4e36-4cb2-b61f-90563312d5e6.png">

### Steps to reproduce

1. Settings -> Advanced -> Show conversion on test networks -> ON
2. Settings -> General -> Primary currency -> Fiat 
3. Navigate to [test dapp](https://metamask.github.io/test-dapp/)
4. Click `Sign` in the `Sign Typed Data V4` section

### Version

10.24.2 develop fbbd7d0090271eb41ef36c26efdd114a5bc3e5cf

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Adding for reference: I'm not able to reproduce this in v10.24.2 that is in prod

**Comment by chloeYue** [comment]
Hello, i need to reopen the issue because the balance is still not correct when i set primary currency to fiat:
<img width="1269" alt="Screenshot 2023-03-06 at 17 38 18" src="https://user-images.githubusercontent.com/105063779/223177428-fabb0749-07ab-41cd-9b5d-ad1a0884891f.png">

Step to reproduce:
1. Settings -> General -> Primary currency -> Fiat
2. Settings -> Advanced -> Show conversion on test networks -> ON
3. Navigate to [test dapp](https://metamask.github.io/test-dapp/)
4. Click Sign in the Sign Typed Data V4 section and check displayed balance
