### ISSUE TITLE
Update and fix "Transaction Finalized" and "Transaction Approved" metrics event

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17886]
The capturing of this event was broken in December. We need to fix it. More info https://consensys.slack.com/archives/G01FXS64DFA/p1676487003385559?thread_ts=1672853401.810889&cid=G01FXS64DFA

The Transaction Submitted and Transaction Added events were fixed, but a basic read of some mixpanel graphs suggests that Transaction Finalized and Transaction Approved are not fixed.

The problem with the events that were already fixed was the duplication of id on both the anonymized and non-anonymized events. This was intended to be fixed with https://github.com/MetaMask/metamask-extension/pull/17080

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
I did some initial exploring, and another bit of info: The transaction events use the event fragment system. The event fragment system exists so that event payloads can be built over time from various points in the code base. The way that a fragment works is that you can specify an 'initial' a 'success' and 'failure' event -- The initial event gets fired when the fragment is created. 

The two events that were fixed by my prior work were the initial events of the two flows
1. Transaction Added -> Transaction Approved or Transaction Rejected 
2. Transaction Submitted -> Transaction Finalized

So Added and Submitted seem to work. We need to first identify if its an error in how we finalize the fragments in the transaction controller or if its the same issue as before (unique id issue). This can be tested by adding a segment write key to .metamaskrc and then doing a transaction on a test net / ganache and inspecting network tab of background / service worker and see if we get both events firing to segment. If we are then we can examine the ids and see if they are the same. if they are then segment is dropping one and we need to figure that out. If they are different then its a different, weird issue we'll need John to analyze with us. The most likely issue in my mind right now is that the fragment is NOT being finalized for some reason and we need to figure out why and fix that.

**Comment by dlefloch** [comment]
Hi @brad-decker great work would it tentatively be released in 10.27? or other version? Thank you!
