### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ss18ping** [MetaMask/metamask-extension#17911]
### Describe the bug

Trezor popup closes automatically

### Steps to reproduce

1. Use Trezor with Metamask

### Version

latest/any

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

I've been seeing this bug for years. The Trezor popup closes itself without any error messages, etc. I have to turn off the wallet, restart the browser and do it all over again. This is quite a frustrating thing. I contacted the Trezor team, but they say they can't do anything about it, because they released version 9 of the Trezor Connect a long time ago. And the version which Metamask still uses is deprecated and outdated. Could you please upgrade to Trezor Connect 9 as soon as possible, because the problem has existed for many years and has not been resolved.

**Comment by Phileicht** [comment]
Same Problem here when trying to sign anything on OpenSea. Pop up opens and closes immediately.  
MM Version: 10.25.0
Browser: Chrome
Operating system: Win 10
Hardware wallet: Trezor

Any updates on when you plan to update the Trezor Connect Version?

**Comment by ss18ping** [comment]
Team, please check this: https://github.com/trezor/connect/issues/784#issuecomment-1463516812 
we need to upgrade Trezor Connect version into the main repository of the extension

**Comment by mattwinans** [comment]
MetaMask Team: Please Upgrade to Trezor Connect v9 Immediately!

When I attempt to swap in Pancake Swap via Metamask, the window that pops up to initiate my Trezor device and asks for my PIN (https://connect.trezor.io/8/popup.html#loading) never finishes loading and closes about 3 seconds in.

This is a gigantic issue for me because my entire life savings of crypto is stored on my Trezor in small DeFi tokens. Right now I cannot even access these funds with this issue. I cannot buy or sell and it is VERY concerning!

40 second demonstration of the issue:
https://youtu.be/hEPm8GNOaas

I contacted Trezor Support and they wrote:
"Let's hope MetaMask will switch to Trezor Connect v9 soon and those issues will be resolved."

**Comment by mattwinans** [comment]
Can I please suggest a more descriptive title for this Bug? "Trezor Connect v9 Update Required to Function"
