### ISSUE TITLE
[UI Bug]: Broken UI on Sign In With Ethereum W/ Resources

### ISSUE THREAD

**Issue by StanislavBaraniuk** [MetaMask/metamask-extension#17913]
### Describe the bug

Text out of bounds when the user tries to sign a long message.

### Steps to reproduce

1. Go https://metamask.github.io/test-dapp/
2. Click Sign In With Ethereum W/ Resources.
3. Open the extension in full-screen mode.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/30075183/221606043-a04674d1-525c-4b40-8164-570210951dea.png">

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
Note to devs who investigate this: while the sign in with ethereum case will be correctly handled as of v10.26.0, it seems very possible that any personal sign request with a long message might run into this same error.

Next step should be to reproduce this issue with some message other than the SIWE message on the test dapp, and then the fix is likely a css fix

**Comment by digiwand** [comment]
Was this fixed with the recent fix for https://github.com/MetaMask/metamask-extension/issues/18224? 

@danjm

**Comment by digiwand** [comment]
confirmed this is no longer an issue in v10.28.2
<img width="792" alt="Screen Shot 2023-04-12 at 10 23 33 AM" src="https://user-images.githubusercontent.com/20778143/231471298-a909e459-c87b-4f34-8a10-d76e890c6655.png">
<img width="400" alt="Screen Shot 2023-04-12 at 10 23 16 AM" src="https://user-images.githubusercontent.com/20778143/231471281-2c37fefe-b4e4-4bf8-ae33-1d36a4bdbe9e.png">
