### ISSUE TITLE
[Bug]: ENS resolution address not updated when changing networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18045]
### Describe the bug

**Problem**: when I am performing a Send transaction, if I add an ENS domain on the recipient address and then change networks, I can see that the ENS is resolved to the other Network address.
If I proceed, then I can see how in the confirmation screen the old resolution is there, resulting in another domain (if that address is registered by someone else on the other network)

https://user-images.githubusercontent.com/54408225/223661608-6c066856-0ced-455c-9c43-9c8648398f69.mp4

### Steps to reproduce

1. Set Goerli testnet
2. Click Send
3. Add recipient `test.eth`
4. Proceed to the next screen
5. Change network to Ethereum Mainnet -- see how `test.eth`is resolved to the address from the other network
6. Proceed to the confirmation screen
7. See how old address is displayed, and since this domain is registered with another name, we are now seeing a different ENS domain as recipient `nauseam.eth`

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We should **not allow users to change the network** once the send transaction flow has been initiated.

Reasons for that:
1. It fixes this bug (other fixes are also possible for this, but this is preferred due to the reasons)
2. In a MM with snaps world, some address will be chain specific (e.g. bitcoin, solana) so a change in network during the send flow would also create complications and a reset of the send parameters would be needed
3. Right now, if you're trying to send a chain specific asset and you change networks during the flow you get to a broken state where MM is continuously loading (see video 1)

Preventing users from changing the network once the send flow is initiated fixes all 3 situations above and it's something we already do on the last confirmation screen of the flow (see video 2).

Slack thread for discussion: https://consensys.slack.com/archives/C04C0F6SSJH/p1678288514571559


## Video 1
https://user-images.githubusercontent.com/34968356/223772798-d5a1d74b-becc-4500-abe4-85d67ae6ce54.mov


## Video 2
https://user-images.githubusercontent.com/34968356/223772853-2112ece4-1e34-4fe2-8ca4-65e77b7bb381.mp4

**Comment by NiranjanaBinoy** [comment]
@bschorchit Should we disable the network change only from the draft send page, or should we disable the network change for add-recipient page as well?

**Comment by bschorchit** [comment]
> @bschorchit Should we disable the network change only from the draft send page, or should we disable the network change for add-recipient page as well?

We should disable it for the add-recipient page as well, @NiranjanaBinoy
