### ISSUE TITLE
[Bug]: Error retrieving NFT collection name with setApprovalForAll function on ERC1155 contract

### ISSUE THREAD

**Issue by gemscng** [MetaMask/metamask-extension#18133]
### Describe the bug

The token name is not being retrieved properly and instead displays the default wording 'NFT', which may cause users to mistakenly believe that we are requesting permission for all their NFTs. This can lead to confusion and insecurity when users are asked to approve it.

### Steps to reproduce

1. Go to https://polygonscan.com/address/0x482d4eE070aDBC35Aad4F4696f9aF3E11516Dc28#writeContract

2. Call the setApprovalForAll function using the Metamask Chrome extension.

3. Check the following screen that appears. The name displayed should be the specific token name instead of the generic term NFT:

![Screenshot 2023-03-14 at 12 07 18 AM](https://user-images.githubusercontent.com/7820794/224881521-59bc3c48-7c4f-4093-ade3-6c52ca437c1f.png)

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by VSaric** [comment]
Maybe this is related with [this ticket](https://github.com/MetaMask/metamask-extension/issues/17516)?

cc: @danjm @bschorchit

**Comment by gemscng** [comment]
> Maybe this is related with [this ticket](https://github.com/MetaMask/metamask-extension/issues/17516)?
> 
> cc: @danjm @bschorchit

Yes, this issue is related, but not exactly the same. Rather than updating the fallback, Metamask should be able to retrieve the correct collection name directly from the contract.

**Comment by jacobc-eth** [comment]
Thanks for sharing this @gemscng 

FYI @bschorchit , gem is one of the devs building games with HyperPlay! 

brainstorming here. in the past, I think we didn't display the collection name because self-declared names were a potential phishing vector. HOWEVER, in this instance, the self-declared name is actually useful since it is indeed the name of the collection that is being placed at risk through the token approval.

**Comment by bschorchit** [comment]
I think the underlying issue is actually on our current limited support for ERC1155. 
For ERC721 we should be retrieving the name correctly right now. 
We might already have logic for this for the NFT support feature we're developing and if we have already it should be a quicker fix for this. We'll investigate.
