### ISSUE TITLE
[Bug]: Deceptive site request. Domain mismatch when signing messages with matching domain

### ISSUE THREAD

**Issue by steddyman** [MetaMask/metamask-extension#18332]
### Describe the bug

Users have just started reporting that when they visit my site, and try to sign in via signing a message, that the domain does not match the one in the URI request (which it does). I do not get an RPC error, but see the UI warning about the domains not matching when they do match when the user goes to sign the login message.

As ou can see in the screenshots they do actually match. This only seems to have started this week, possibly only today with Metamask 10.26.2.  It does not relate to my site being flagged as malicious, but an incorrect flagging of the domain.

It seems related to this issue: https://github.com/MetaMask/metamask-extension/issues/17707

![image](https://user-images.githubusercontent.com/212404/227726609-213c2209-e832-4878-a29d-4aadeb177c49.png)

![image](https://user-images.githubusercontent.com/212404/227726623-d1d4128e-ae3f-4c96-886d-9eb007552bbb.png)

![image](https://user-images.githubusercontent.com/212404/227726634-09f7c6c8-4815-49f2-afa2-36d9a99b74cf.png)

### Steps to reproduce

1. Visit https://mintmonster.io
2. Connect Wallet
3. Click Sign-in button until you are promoted to sign the login message

### Error messages or log output

```shell
Deceptive site request. The site you're attempting to sign into doesn't match the domain in the request. Proceed with caution.
```

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Related with: https://github.com/MetaMask/metamask-extension/issues/18241

**Comment by danjm** [comment]
possibly addressed by https://github.com/MetaMask/metamask-extension/issues/18332

this is likely the same problem we saw here: https://github.com/MetaMask/metamask-extension/issues/18241

**Comment by steddyman** [comment]
> possibly addressed by #18332

This is #18332

**Comment by bschorchit** [comment]
He meant https://github.com/MetaMask/metamask-extension/pull/18296

**Comment by steddyman** [comment]
> He meant #18296

Thanks.  The port is not included in my URI in the message.  This is a regular HTTPS request on port 443.

**Comment by steddyman** [comment]
Is there any progress on these many issues with eroneous deceptive site requests?

**Comment by steddyman** [comment]
Still getting the same error  on 10.27.0

**Comment by digiwand** [comment]
Is this the latest version from the [webstore](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en-US) for you? I am receiving version 10.28.1. With this version, I'm seeing a warning modal. This is the current expected behavior as the subdomain, `www`, exists on one domain and not the other. More details found by searching "1B" and "1E" in this PR: https://github.com/MetaMask/metamask-extension/issues/18188#issuecomment-1499907598

**Comment by digiwand** [comment]
Hey @steddyman, 

Is this the latest version from the [webstore](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en-US) for you? I am receiving version 10.28.1. With this version, I'm seeing a warning modal. This is the current expected behavior as the subdomain, `www`, exists on one domain and not the other. More details found by searching "1B" and "1E" in this PR: https://github.com/MetaMask/metamask-extension/issues/18188#issuecomment-1499907598

**Comment by bschorchit** [comment]
Closing as this is the expected behavior as per Ariella's comment above. Let us know if this is not case or if you run into this or a similar issue!
