### ISSUE TITLE
[Bug]: Claim Button Greyed Out via/ Ledger Connection (with enough funds)

### ISSUE THREAD

**Issue by yukdotcom** [MetaMask/metamask-extension#18624]
### Describe the bug

When connecting metamask via ledger to https://portal.flare.network/

Claim button is greyed out when trying to click on any button to approve a transaction.  

Interaction with site worked as of 4/14 running 10.28.2 currently running 10.28.3 and it stopped working. 

Running metamask extension on mac via chrome.

### Steps to reproduce

1. log into metamask and connect ledger (eth)
2. connect to https://portal.flare.network/ 
3. Try to initiate a clam/wrap/etc that requires a claim button to highlight. 

### Version

10.28.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by Ophelia36** [comment]
Hi @yukdotcom  i suggest you contact a hardware wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by yukdotcom** [comment]
https://support.ledger.com/hc/en-us/articles/360020871157-Solving-a-MetaMask-connection-issue-

Followed these steps from ledger and everything pointed to a metamask issue.  Even loaded metamask on brave browser then tried to connect the ledger and a cloned ledger to metamask and it wouldn't even find my device when searching for it.  Ran the search for over 8 hours.

**Comment by plasmacorral** [comment]
We have been unable to recreate these connectivity issues, are you still experiencing this with v10.29.0?

If you still have the issue, please: 
1. Make sure Chome is updated to the latest
2. Make sure Ledger is updated
3. Check MetaMask>settings>advanced>preferred Ledger connection method and ensure that `webHID` is selected
4. Reboot your machine if you haven't done so very recently
5. Navigate to chrome://settings/content/hidDevices, clicking on your Ledger (if listed) and in the details please tap `Reset Permissions`
6. Close MetaMask and the browser
7. Relaunch and try to connect again


If you are still not able to connect, could you share some additional information:
1. What version of chrome?
2. What is the OS version on your mac?
3. What happens when you try to connect with Ledger live?
4. What was the last thing you remember successfully doing with the account in question?
5. Have you installed any other extensions recently?
6. Do you also have other wallet extensions installed? 
7. Are you using a protected/managed network like at work or school?
8. Have you had any connection issues?
9. When this occurred, were you using a VPN?

**Comment by plasmacorral** [comment]
Removing severity pending requested information

**Comment by plasmacorral** [comment]
Closing with out more information, please open a fresh issue if you can help further articulate on the concern.
