### ISSUE TITLE
Etherscan fail: Sorry, We are unable to locate the Transaction entry (thru etherdelta)

### ISSUE THREAD

**Issue by Clermont1** [MetaMask/metamask-extension#1876]
Having an epic Etherscan fail: 
I get error notice "Sorry, We are unable to locate the Transaction entry" 
(I'm going thru etherdelta on chrome with MetaMask which I'm completely new to)

You mentioned to someone on June 26, i believe, what to do but I did not understand your directions. 
Would you mind spelling them out for the layman?
I greatly appreciate it.
Clermont!

Hello, I've sent 4 transaction using MetaMask, and all I get is failed notices & on the Etherscan I get :"Sorry, we are Unable to locate the Transaction entry." 
Three of those transactions have a (failed) 
thanks NW
Clermont1
--

**Comment by tmashuang** [comment]
In order to properly diagnose your specific issue and give a detail explanation will require providing logs and your address. Since this is a public thread, we recommend going through our support page [https://support.metamask.io/new](https://support.metamask.io/new) to submit a new ticket. I will link a guide to how to provide these logs within Metamask. [Providing Metamask Logs](https://support.metamask.io/kb/article/15-copying-state-log). Please paste them into a ticket.
