### ISSUE TITLE
Remove the need to open the console on e2e tests for action queue metrics on mv3

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#18920]
**_TO BE DEFNIED !!_**
Currently, our e2e tests for action metrics rely on opening the dev tools on the test using

```jsx
await withFixtures({
  // ...
  driverOptions: { openDevToolsForTabs: true },
})
```

Otherwise, the service worker does not restart.

We should not need to do this, and we do not need to do this when testing manually.

The problem might be with mv3 support on Chromedriver or something related to the e2e testing setup.

**Comment by DDDDDanica** [comment]
This ticket can be closed because all the mv3 restart related tests are removed by https://github.com/MetaMask/metamask-extension/pull/21439, and we can keep the name `openDevToolsForTabs` from PR https://github.com/MetaMask/metamask-extension/pull/18347/files as it is more accurate than `responsive`
