### ISSUE TITLE
[Bug]: ERC20 Token - Fiat conversion is shown in ETH in some places

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18953]
### Describe the bug

**Problem**:  whenever we are sending a token, we can see how in the Edit and Confirmations screens the conversion values are displayed in ETH and not in Fiat.

https://user-images.githubusercontent.com/54408225/235692395-c7f8f4da-a886-4e97-9454-d746499e3c34.mp4

### Steps to reproduce

1. Import an ERC20 token
2. See how conversion is displayed in fiat
3. Click Send
4. Add recipient
5. Add amount -- see conversion is displayed in ETH instead of fiat
6. Click Next
7. See conversion is displayed in ETH instead of fiat

### Version

10.25.0 or earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Is this not the intended behavior due to this settings option:

![Screenshot 2023-05-02 at 19.56.52.png](https://images.zenhubusercontent.com/61e705ae78964374054c3ed0/26dbeaca-000c-4b0d-840c-e039902ab7f2)

**Comment by bschorchit** [comment]
hmm, my thinking was when your sending a token the primary value you see is the token amount and then you'd like to see the conversion in the primary value you set for the wallet (either ETH or Fiat) as it's the option you prioritized seeing per the settings copy - this seems to be what's happening now. 

But after seeing your second video, I think it would be less confusing if, for tokens, we mimic the behavior for native ETH - where, if fiat is selected, you input the amount in fiat and it converts to the token value and, if ETH if preferred, you input the amount in tokens and it converts to fiat. 

For that the settings would need to be broader as well and the option should not be called ETH. (In any case, actually, it should not be called ETH right now anyway due to custom networks)

Let me know if this makes sense to you. I'll also sync with core team on this - as there's an overlap with their scope on this too.

**Comment by salimtb** [comment]
this issue was fixed
