### ISSUE TITLE
[Bug]: Metamask in Chrome shows always "Connecting to network" backdrop

### ISSUE THREAD

**Issue by danail-vasilev** [MetaMask/metamask-extension#19002]
### Describe the bug

Metamask in Chrome shows always "Connecting to network" backdrop:
https://www.screencast.com/t/nSn2PfBHy8ny
https://www.screencast.com/t/ujrC8uVKA
Metamask version: 10.29.0

In FireFox I am with 10.28.0 version and it's fine, this backdrop is not show.

Things I have tried:
1) I have tried disabling Metamask in other browsers (currently have it in FireFox only) but the same issue
2) Restarting browser/PC - didn't help
3) Disabling metamask in Chrome - didn't helped
4) Reinstalling the plugin helped 

### Steps to reproduce

1. Open chrome
2. Try to open metamask

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by aspiers** [comment]
I have this too, with Chrome 113 on Linux:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/1b1a1c42-357f-4a8e-ba83-40853391f2e9)

Eventually after a long wait (perhaps one or two minutes) the connection times out, and I get this:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/4e75945f-a111-4a09-8735-c0b998f2d9a8)

However when I click "Switch Networks", I see this:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/901e1848-f434-427c-897f-0b2ea4efe928)

Notice how all the alternative networks are greyed out.  Clicking on one of them makes the dialog disappear, but MetaMask remains stuck on the hardcoded "Ethereum Mainnet".

I have used MetaMask for years on many different browsers and machines without seeing this problem.  It only started appearing in the last few days or week or two.  Clearly this is a huge issue because it makes MetaMask completely unusable!

**Comment by aspiers** [comment]
I found the cause for this in my case: limiting site access to the MM extension.  I've filed #19145 with the details.
