### ISSUE TITLE
Fix component-library storybook introduction MDX render

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19329]
### Description
The introduction to the component-library MDX document isn't rendering correctly.

<img width="1440" alt="Screenshot 2023-05-29 at 10 32 23 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/f79a2b05-bbd7-438c-ae4f-721cd83d647e">

### Technical Description
- Fix MDX document rendering `ui/components/component-library/COMPONENT-LIBARY.stories.mdx`

### Acceptance Criteria 
- Introduction document renders correctly

**Comment by dhruvv173** [comment]
hey @georgewrmarshall, please assign this to me. Thanks!

**Comment by dhruvv173** [comment]
hey @georgewrmarshall , for this issue, instead of importing the description from the `README.md` file I directly moved all the content into the `COMPONENT-LIBARY.stories.mdx` file and it fixes the bug. It also maintains the consistency for all the Storybook introduction files with respect to how they are being rendered. If thats fine I will go ahead and submit a PR.
Thanks!
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/5c2e43a3-ae1b-4f53-9f0e-10f9083aa6ce)
