### ISSUE TITLE
Lost seed and HDD Erased

### ISSUE THREAD

**Issue by CarlosRoldanx** [MetaMask/metamask-extension#1949]
Hello,
I accidentally erase my HDD including my seed phrase with Windows Restore. 
Now I do not have my previous Windows local settings with my previous wallet addres entered to only type my wallet password.
 What Can I do to recover my wallet?

Please Help!

**Comment by Zanibas** [comment]
There is unfortunately nothing you can do to recover your wallet at this point--the seed phrase would be the only way to restore access to your account. It's regrettable that you've lost your seed phrase, but there is nothing we can do on our end to assist, nor can anyone else.

**Comment by nko614** [comment]
Hi @Zanibas, I wanted to confirm that this is still the case? If the seed phrase has been lost - is there still nothing that can be done to revive the account?

Thanks,
Nick

**Comment by lazaridiscom** [comment]
@nko614 , The "Seed Phrase" **is** your account. Its a phrase-representation of the underlying encryption-keys.

So, your Seed-Phrase (or Account Seed) is more or less your classical Backup. If anything happens to your data (MetaMask installation, hard-disk, whole machine), then your account cannot be restored without a backup of the encryption-keys (either the keys themselves, or the Seed Phrase).

This is good so, because if there would be kind of a back-door, then the back-door could be abused to steal funds.

> is there still nothing that can be done to revive the account?

Wiped / crashed storage-media: you can try data-recovery-services, which sometimes can restore your account-data from the damaged media.

**Comment by jankalaco** [comment]
Hi , I stored only 11 of 12 words phrase . it's any chance to restore that account, even if I can see my account on ethertelda . Thank you

**Comment by bdresser** [comment]
@jankalaco email support@metamask.io and we'll do our best to help you out
