### ISSUE TITLE
On-chain errors not detected or rendered (OOG, Bad Jump, etc)

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#1952]
OS: macOS Sierra
Browser: Chrome, latest

Expected behavior: failed transactions should always display as failed in the MetaMask transaction list
Actual behavior: some transactions show as successful, even though they didn't pass.

Related tx (this one's on Ropsten, but it also happens on the main net): https://ropsten.etherscan.io/tx/0xde7ecb573790e4630c8522e91db2245614864bf7f08b39d1c916dc614cd55466

MetaMask representation:

<img width="349" alt="screen shot 2017-08-22 at 15 54 31" src="https://user-images.githubusercontent.com/12464061/29568933-37c5a5a4-8752-11e7-8e03-1dce22de1264.png">

**Comment by flyswatter** [comment]
Related to #1519 and #1809

The problem is that we do not currently parse on-chain failures, and so any successfully mined transaction is shown as successful.

I'll update the title here to reflect that larger goal, and treat this as the central issue for this problem, because it doesn't look like we have a good singular summary right now.
