### ISSUE TITLE
[Bug]: Trying to Send an ERC20 token that I've never owned causes MetaMask loading indefinitely

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19682]
### Describe the bug

**Problem**: whenever we add an ERC20 token which we've never owned, if then we click on Send we can see how MetaMask stays loading indefinitely.

[Screencast from 20-06-23 16:18:56.webm](https://github.com/MetaMask/metamask-extension/assets/54408225/e84e7353-6b85-4573-b423-3bb2d7089b31)

### Steps to reproduce

1. Go to https://docs.metamask.io/react-plugin/api-playground/wallet_watchasset/?type=ERC20&options[address]=0xb60e8dd61c5d32be8058bb8eb970870f07233155&options[symbol]=dsfge&options[decimals]=18&options[image]=https://foo.io/token-image.svg
2. Click Send Request for Importing the Token
3. Accept MetaMask prompt
4. Go to MetaMask
5. Click Send that ERC20 token
6. See MM stays loading indefinitely

### Version

10.31.1 possibly earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sahar-fehri** [comment]
The reason why it was loading is because the address in the docs was a wallet address, not a contract address; 
This issue was split into two separate fixes:
1- https://github.com/MetaMask/core/issues/1207
2- https://github.com/MetaMask/metamask-extension/issues/10565 and the fix for that one is here: https://github.com/MetaMask/metamask-extension/pull/21091

Both were merged, so i will close this one 🙏
