### ISSUE TITLE
[Bug]: Unknown Infura provider type "linea-goerli".

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#19906]
### Describe the bug

the user cannot switch networks to linea goerli

the following error appears in the console
`Unknown Infura provider type "linea-goerli"`

### Steps to reproduce

1. log in to the extension
2. switch networks to linea goerli

### Error messages or log output

```shell
Unknown Infura provider type "linea-goerli".
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
i.logErrorWithMessage @ ui-4.js:1
(anonymous) @ ui-11.js:1
await in (anonymous) (async)
(anonymous) @ ui-3.js:1
onClick @ ui-6.js:1
e.<computed> @ sentry-install.js:1
m @ ui-3.js:1
e.<computed> @ sentry-install.js:1
T @ ui-3.js:1
e.<computed> @ sentry-install.js:1
(anonymous) @ ui-3.js:1
k @ ui-3.js:1
C @ ui-3.js:1
S @ ui-3.js:1
j @ ui-3.js:1
_n @ ui-3.js:1
se @ ui-3.js:1
jn @ ui-3.js:1
Mn @ ui-3.js:1
Rn @ ui-3.js:1
n.unstable_runWithPriority @ ui-3.js:1
Jo @ ui-3.js:1
ue @ ui-3.js:1
Pn @ ui-3.js:1
```

### Version

10.34

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think it's the same as https://github.com/MetaMask/metamask-extension/issues/19805

**Comment by PeterYinusa** [comment]
> I think it's the same as #19805

It is indeed a duplicate. Will close the one you raised as closing this will give us inaccurate release metrics

**Comment by mcmire** [comment]
This bug seems to have arisen because prior to the network controller merge, we were using a newer version of `eth-json-rpc-infura` which has support for the Linea networks. The extension is now using `@metamask/network-controller` from `core`, and that package is not using the newest version of `eth-json-rpc-infura`. So this is indeed a regression. There is a PR to address this here: https://github.com/MetaMask/core/pull/1423. There is a pending comment on that PR, however, we would need to resolve in order to merge it.
