### ISSUE TITLE
Fix Button Alignment of Send Button in Nft-Details

### ISSUE THREAD

**Issue by NidhiKJha** [MetaMask/metamask-extension#20050]
### Describe the bug

In the popup view, the send button is not properly aligned
![Screenshot 2023-07-17 at 4 09 42 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/18733fd8-dfb7-4c76-9a8b-791a617246e4)

### Steps to reproduce

1. Go to the NFTs Tab
2. Go to any NFT detail in the popup view

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by MukulKolpe** [comment]
Hey @NidhiKJha, can I work on this issue?

**Comment by NidhiKJha** [comment]
Hey @MukulKolpe, @ducksblock has a PR opened for this issue. Hence, I am assigning it to him. You can look for more good first issue [here](https://github.com/MetaMask/metamask-extension/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), Thanks!

**Comment by SamarthBagga** [comment]
@NidhiKJha is this issue still open, I would love to contribute.

**Comment by harshbsharma** [comment]
Would like to work on it. Please assign

**Comment by georgewrmarshall** [comment]
I've removed the `team-design-system` label since this issue is about the implementation of styles added to the button, rather than the button component itself. The recommended fix is to use the style utility array props to apply these styles only on large screens.

![Screenshot](https://github.com/MetaMask/metamask-extension/assets/8112138/690637dd-97bd-42fc-91d5-543d57290a0a)

**Comment by Maliksb11** [comment]
Have a nice day 🥰🥰
