### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')[Bug]: 

### ISSUE THREAD

**Issue by linxin2020** [MetaMask/metamask-extension#20138]
### Describe the bug

During the plugin unlocking process, due to some reason, the connection to the network fails, and a retry and switch button will appear; Click 'switch' to jump to the error page. I will never be able to restore usage, I can only uninstall and reinstall the plugin.
![image](https://github.com/MetaMask/metamask-extension/assets/46699328/68a8ecab-36a5-41e1-9ade-768919e144c1)
![image](https://github.com/MetaMask/metamask-extension/assets/46699328/e2fa1cf4-9a24-43b4-8808-f1562748ff3d)

### Steps to reproduce

1. Download, install, and log in to this plugin
2. Restart the browser
3. Unlock plugin
It is not inevitable, but once it occurs, it will always be the case and can only be uninstalled and reinstalled.

### Error messages or log output

```shell
TypeError: Cannot read properties of undefined (reading 'id')
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:296537
  at Array.map (<anonymous>)
  at C (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:296456)
  at va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60111)
  at Mu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:105038)
  at Al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90901)
  at Rl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90826)
  at El (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88166)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46516
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:416038)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46461)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46396)
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:115076)
  at Pn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:29858)
```

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by danjm** [comment]
I believe the consistent repro steps for this bug are:

1. Install MetaMask v10.11.0
2. Add a custom network
3. Update the install to v10.34.0
4. Try to open the network selection modal

**Comment by danjm** [comment]
I believe this was caused by combination of two things:

1. When we started giving network configurations unique IDs, we didn't migrate the provider object that was in use at the time to all have an id . There are two migrations where we maybe should have done that: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/migrations/082.ts and https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/migrations/083.ts

2. Then we recently made a change that assumes all providerConfig objects in state will have an id [https://github.com/MetaMask/metamask-extension/commit/719d8a499b0cb557ec217a2c8fffd8b78315ef6c#diff-45ae84764c1d49a07813[…]a116d1e0cba06cR1173-R1179](https://github.com/MetaMask/metamask-extension/commit/719d8a499b0cb557ec217a2c8fffd8b78315ef6c#diff-45ae84764c1d49a07813a91adc3351d6ed96bf9ee8fa2ae4c9a116d1e0cba06cR1173-R1179)

So anyone who selected a network prior to the version that included migration 82 (I think that might have been v10.25.0), and then later upgraded to v10.34.0 without having switched networks in between, will hit this error when trying to open the network selector (and might hit other errors elsewhere) because getCurrentNetwork can return undefined for these users (edited)

**Comment by linxin2020** [comment]
> 

The problem cannot be reproduced at the moment, perhaps your analysis is correct.
This issue can be closed first, but it is best to have a fault-tolerant processing method, otherwise you can only reinstall this extension and import the wallet again, which is very troublesome.
