### ISSUE TITLE
Getting the 'Metamask - injected web3' log two times

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2024]
As in the title - I'm getting a double `Metamask - injected web3` log.

I'm using Chrome 60, macOS Sierra.

It started occurring suddenly - I didn't do any changes in my code that could cause the issue and it was fine like a week before.

**Comment by flyswatter** [comment]
Is there a problem associated with this log? If not, it's probably correct behavior. You'll see this log for each javascript context the page loads, because MetaMask injects web3 in each iFrame a page loads.

If there's a problem happening, let me know, and I'll reopen, otherwise this doesn't look like an issue.
