### ISSUE TITLE
Allow Deleting Accounts

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2028]
Maybe not seed phrase accounts, but at least imported accounts, and maybe other account types too. Sometimes users want to move on from an account.

**Comment by willnwhite** [comment]
My problem is I keep having to scroll through them all while developing. Being able to re-order them would help in the meantime.

**Comment by leafcutterant** [comment]
I propose being able to delete seed phrase accounts as well (=accounts which were generated with "Create account").

For this, we have to decide what happens when someone creates an account after deleting one. The simple and safe option is that the previously deleted account becomes regenerated. It probably won't do what some people (including me) want it to do, but it's still better than not being able to delete organic accounts.

There could be another option for organic accounts, "archiving", which would remove them from the account list, but they would stay reachable in a segregated section.

**Comment by bdresser** [comment]
@leafcutterant closing this, took your last comment to https://github.com/MetaMask/metamask-extension/issues/5078
