### ISSUE TITLE
[Bug]: Metamask identifies my ERC721 as ERC1155

### ISSUE THREAD

**Issue by tuancter1999** [MetaMask/metamask-extension#20641]
### Describe the bug

I use library ERC721URIStorageUpgradeable to deploy NFT, on etherscan still recognize the NFT as ERC721 but when I add it to Metamask it is recognized as ERC1155
Link library : https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC721/extensions/ERC721URIStorageUpgradeable.sol
My contract:  https://goerli.etherscan.io/address/0xc845fc63a5a69637ebe0d960fbfa33671a1e21e0
![Screenshot 2023-08-29 at 13 48 13](https://github.com/MetaMask/metamask-extension/assets/51197663/f4f8d68b-1d58-4e15-b708-c906a3663d68)
![Screenshot 2023-08-29 at 14 10 45](https://github.com/MetaMask/metamask-extension/assets/51197663/6ab35e8a-2807-4131-af12-1be252eeda38)

### Version

10.34.0

### Build type

None

### Browser

Microsoft Edge

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @tuancter1999. Thanks for reporting! I will pass this on to the team.

**Comment by sahar-fehri** [comment]
hello @tuancter1999,

If you try flipping the order of the inheritance in your contract and deploy again it will work.
Here is a version of your contract that works on goerli: 0x81340d336880989520819F5Df36a4c9929eDFbD2

The reason for the issue is that solidity's inheritance is linearized from right to left; in the case of your contract; the right one was AccessControl; so in your `supportsInterface `function it was looking for the function in `AccessControl `contract first; which was returning false giving the `interfaceId `of ERC721(0x80ac58cd).

Please let me know if you are still having an issue with this!

**Comment by tuancter1999** [comment]
Hi @sahar-fehri 
I tried reversing the order of inheritance in my contract and it worked out
Thank you so much
