### ISSUE TITLE
Move gas calculations to a VM

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2083]
Paying for the gas block limit (or at best, 80% of it) is ridiculous when the tx is doomed to fail.

**Comment by jtakalai** [comment]
Is this related to an issue we're having, namely, instead of reporting that a transaction would revert, Metamask would say "transaction is fine, but it will take 9.7M gas"? Metamask-generated transaction here: https://etherscan.io/tx/0xa0e773128a5b2e2b2008bbfa92885c90088fbb1c55cc098ae6b68329c5c17506 replaced with one where gas limit was lower (because that one would never got into a block)
