### ISSUE TITLE
[Bug]: Firefox import keystore JSON 

### ISSUE THREAD

**Issue by pociej** [MetaMask/metamask-extension#20837]
### Describe the bug

Importing password protected keystore JSON doesnt work in firefox. Once file selection window popus up metamask plugin widget disappears and there is no option to provide password.  

### Steps to reproduce

1. Open plugin widget in FF go to accounts -> imports -> JSON 

### Version

11.0.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @pociej. Thank you for taking the time to report this issue! Do you experience the same problem when trying to import in Metamask in Brave or Chrome, or does it work as expected? Thank you!

**Comment by pociej** [comment]
hi @anaamolnar yes Chrome and Brave works.

**Comment by plasmacorral** [comment]
Thank you for sharing your experience here, @pociej, I am sorry for the frustration.  This behavior and performance is not ideal.  If the issue is specific to having MM open in the pop-up view, I can recommend a potential work around to help you get this account imported into the Firefox extension.

1. Open MM
2. Select the kebab menu (3 dots on the right corner)
3. Select `Expand View` From this point forward you should have MM open in the full browser window
4. Hit the Accounts drop down menu
5. Select `Import account`
6. Hit the dropdown to select `JSON file`
7. enter optional password as needed
8. Select import
9. Be extraordinarily patient, and do not stop the page.
10. Account is imported and active

There is a [previously reported issue](https://github.com/MetaMask/metamask-extension/issues/17275) that impacts the ability to import from the pop-up (smaller) window.  I will add to that existing impact that we have impact on Firefox 117, as we can observe today.  

From within that report there is another issue cited about [poor performance when importing JSON](https://github.com/MetaMask/metamask-extension/issues/17274).  In my experience reproducing this today as far back as 10.34, Firefox would present the message `A web page is slowing down Firefox. To speed up your browser, stop that page`.  In my experience if you allow it to keep running, the account will be successfully imported.  In an observation I noted within one of these earlier tickets, if the browser crashed, the new account would appear on relaunch.

There is also a message that appears, but I notice that it is either partially or fully obscured by the `Import account` box. It says: `Expect this JSON import to take a few minutes and freeze MetaMask. We apologize, and we will make it faster in the future.`

**Comment by pociej** [comment]
@plasmacorral. Thx for quick reply. Yeah I noticed expanded view is kind of workarround. But its not an good solution IMO. 
While I or you or other dev can use workarround  end user of the app is customer not me. And posting inside the app such instructions is unacceptable UX. Do you plan to solve it?

**Comment by plasmacorral** [comment]
@pociej This is something that I too would like to see fixed and will work with the team to try and get it prioritized.

**Comment by pociej** [comment]
@plasmacorral is there any update in this issue? Do you need help in fixing the problem? Im open to PR.
