### ISSUE TITLE
[Enhancement]: Show Account Mismatch Warning on signature confirmations

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20893]
### Describe the bug

Only SIWE signature request shows the account mismatch warning

Show the account mismatch warning on the following signature confirmations:
Eth Sign
Personal Sign
Signed Type Data

https://github.com/MetaMask/metamask-extension/assets/53189696/24290bec-e852-4a92-8684-26391cf180c0

### Steps to reproduce

1. login to the extension
2. connect to the test dapp with Account 1
3. switch accounts in MM
4. trigger a Signature request with the newly selected account

### Version

11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by holantonela** [comment]
If the user already gave permissions to the dapp (connected x account) to initiate transactions, why should we warn in this case? 

I think this warning is not needed. What is happening in the home screen may be a user setting which is not relevant to the context that initiated the dapp request for the signature. 

What am i missing @PeterYinusa?

**Comment by PeterYinusa** [comment]
@holantonela, if you scroll to 0:39s in the video above, you will see an account mismatch warning on the SIWE signature confirmation. If you continue the video to 0:57s you do not see the account mismatch on the Signed Type Data signature confirmation. 

I believe we should either show the warning on all signature confirmations or remove it from all for consistency.

Let me know if you need any more information.

**Comment by holantonela** [comment]
> I believe we should either show the warning on all signature confirmations or remove it from all for consistency.

Agreed. We should remove that warning because:

- the user *already* gave permissions to the dapp. Nothing unexpected is happening.
- the user cannot switch accounts in the confirmation screen, for now.

I'm curious why we flagged this in the past tho. I bet we will discover it quickly.

**Comment by digiwand** [comment]
`ui/components/app/signature-request-original/signature-request-original.component.js`
- In `request-signature__body` <div> element, it does not display the account. Only for build-mmi, it may display mismatch account info if mismatch exists. 

`ui/components/app/signature-request/signature-request.js`
- In `signature-request-content` <div> element,  it does not display the account. Only for build-mmi, it may display mismatch account info if mismatch exists. 

SIWE → `ui/components/app/signature-request-siwe/signature-request-siwe-header/signature-request-siwe-header.js`
- In `signature-request-siwe-header` <div> element, utilizes AccountListItem which always displays the account. It hides mismatch account warning for build-mmi. Thing is... the same code for AccountListItem exists in SignatureRequestHeader which all 3 of these signature variations use. Since it's a duplicate, and for the reasons above, I think we can remove it. 

I agree we should remove the account under "This site is requesting to sign in with" since it does not exist on the other signatures. It's also duplicate UI from SignatureRequestHeader (top header, directly under network info and to the left of balance info) which is used in all of the signature pages. 

As we do not pass `fromAccount` to SignatureRequestHeader (top header), the warning does not display in the top header. I suppose we can keep this behavior to not show the warning based on @holantonela's [logic](https://github.com/MetaMask/metamask-extension/issues/20893#issuecomment-1739654436). Easy to add in if we decide it's helpful. 

---

_Working on removing the Account info under "This site is requesting to sign in with"  in SIWE_

**Comment by digiwand** [comment]
maybe, we also want to add the same `build-mmi` logic to display the mismatch account here. Question for mmi team
