### ISSUE TITLE
[Bug][Swap]: Blocked token with non-zero balance is not visible in swap token list

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#20906]
### Describe the bug

Related to Scenario 2 of #20625, if user has a non-zero balance for a blocked token, it should be visible in the swap list.

https://github.com/MetaMask/metamask-extension/assets/105063779/333d2630-f73e-47a7-b18a-2278648a9db3

### Steps to reproduce

1. Have a non zero balance for a blocked token
2. Click on "Swap from" in Swaps
3. Scroll and look for the blocked token (e.g. LUNC if you are in the US). See the token is not displayed.
**Expected:**
It **should** displayed in the list by default.

### Version

v11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dan437** [comment]
Hi, I believe this is as expected, because we sort the Swap To dropdown by [top tokens first](https://github.com/MetaMask/metamask-extension/blob/develop/ui/hooks/useTokensToSearch.js#L202). If you would open the Swap From dropdown, you should see it disabled there, because that one has owned tokens first.
