### ISSUE TITLE
[Bug]: SES_UNHANDLED_REJECTION when trying to sign typed data v1 with Trezor/Ledger/Lattice

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#20942]
### Describe the bug

When attempting to sign typed data that is not supported by a given hardware device, SES_UNHANDLED_REJECTION is produced.

### Expected behavior

Things to be handled

### Screenshots

Recording: https://recordit.co/dCIn6j3JU4

### Steps to reproduce

1. Configure an SRP and then add hardware
2. Connect to the test dapp https://metamask.github.io/test-dapp
3. Tap `Sign` CTA under `Sign Typed Data`
4. Observe SES_UNHANLDED_REJECTION

### Version

11.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor, GridPlus Lattice1

### Additional context

Originally encountered in RC v11.1.0, but confirmed present in both 11.0.0 (production) as well as 10.35.1

**Comment by vivek-consensys** [comment]
Able to replicate, error message displays as:-

> Result: Error: Keyring Controller signTypedMessage: Error: Ledger: Only version 4 of typed data signing is supported

See below:

https://github.com/MetaMask/metamask-extension/assets/106310394/04879c9d-bdc5-44ae-aad1-59f7f2963d5a

**Comment by dawnseeker8** [comment]
After dig into the code to different bridge library and confirm different hardware wallet only support specific version of typed sign data.
1. **Ledger** only support version 4 Typed signed data, `@metamask/eth-ledger-keyring` have code in `ledger-keyring.ts` line 469 have code to check whether version is version 4, otherwise, typedSignData will throw message. 
```
  async signTypedData<T extends MessageTypes>(
    withAccount: string,
    data: TypedMessage<T>,
    options: { version?: string } = {},
  ) {
    const isV4 = options.version === 'V4';
    if (!isV4) {
      throw new Error(
        'Ledger: Only version 4 of typed data signing is supported',
      );
    }
```

2. **trezor** only support version 4 Typed Sign data, in [@trezor/connect-web](https://github.com/search?q=repo%3Atrezor%2Fconnect%20Only%20version%204&type=code) library, following code check whether version is 4, otherwise, throw error message:
 ```
const transformTypedData = (data, metamask_v4_compat) => {
    if (!metamask_v4_compat) {
        throw new Error('Trezor: Only version 4 of typed data signing is supported');
    }

    const version = sigUtil.SignTypedDataVersion.V4;
```


4. **Lattic** only support version 3 and version 4 typed sign data. in [eth-lattice-keyring](https://github.com/search?q=repo%3AGridPlus%2Feth-lattice-keyring%20Only%20version%204&type=code) libary, following code check the typed sign version.
```
  async signTypedData(address, msg, opts) {
    if (opts.version && (opts.version !== 'V4' && opts.version !== 'V3')) {
      throw new Error(
        `Only signTypedData V3 and V4 messages (EIP712) are supported. Got version ${opts.version}`
      );
    }
    return this.signMessage(address, { payload: msg, protocol: 'eip712' })
  }
  ```
  
  From above investigation, look like this is not a bug and those hardware library have special code to make sure typed sign data version is what they supported, otherwise, it will throw errors to notify user as expected behaviour.

**Comment by angelcheung22** [comment]
@gantunesr could you review the comment from Leo above please?

**Comment by gantunesr** [comment]
Hey @angelcheung22 and @dawnseeker8, this is correct and the code validates Leo's observations. Given this information from Leo, why is the client throwing the error `SES_UNHANLDED_REJECTION` after trying to sign an unsupported method? At the moment we know that the hardware libraries are doing what's expected but what's happening on the client side?
