### ISSUE TITLE
Expand network list if test networks are disabled

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#21112]
## Background
While the account list will be expanded because the introduction of an [action button](https://app.zenhub.com/workspaces/metamask-extension-63529dce65cbb100265a3842/issues/gh/metamask/metamask-planning/1374), we often get requests (or complaints) about only showing 3 networks on a modal. We should show the maximum amount of networks if the user has disabled display test networks.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0xzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e69af1bea8472271358d44e3d6f5deb662e3056f/Screenshot%202023-09-28%20at%206.20.00%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1BzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d691b158e33f275f7ad36ce350352716d840e349/Screenshot%202023-09-28%20at%206.19.45%20PM.png)

## Acceptance criteria
- Given that the user is on the Select a network modal
- When the user user disables "Show test networks" on settings OR toggles off "Show test networks" in the Select a network modal
- Then display maximum height (568px?) with maximum amount of (6?) displayed networks
  - If the user has added more networks than the allowable display, then introduce scroll bar

**Comment by NidhiKJha** [comment]
@kevinghim This issue was resolved already when DS team increased the default Modal Size. Refer to the ss below:

## One user has more networks
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGp1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--85a801800cd3e512e2524718bfde347959fb4b1e/Screenshot%202023-09-29%20at%205.31.06%20PM.jpg)


## When user has only 7 networks
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDN1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb57844283ddda71380df2bc5c18521cc3d6bac7/Screenshot%202023-09-29%20at%205.32.18%20PM.jpg)

**Comment by NidhiKJha** [comment]
## Popup View
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTN1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--14eb22df8a11959926768d9f08dd7f0e14908b5e/Screen%20Recording%202023-09-29%20at%205.38.09%20PM.mov)

**Comment by kevinghim** [comment]
Fixed via https://github.com/MetaMask/metamask-extension/pull/20801
