### ISSUE TITLE
Transaction Data contract interaction vs creation.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#2130]
Recent ICOs have users inputting Contract bytecode to receive tokens. Some users have been inputting the bytecode without specifying a 'To', recipient, address resulting in contract creation. Is there a way to prevent users from preventing harm to themselves? Possible a warning screen/text for Contract creation or when a recipient address is not specified?

**Comment by flyswatter** [comment]
It sure would be nice if those dapps would just assemble the transactions for their users using the injected provider, since that's THE great thing that we do for our users. It's possible we're failing some developer outreach here.

But yeah, I guess add a warning if they have no recipient but contract data.

**Comment by masaruduy** [comment]
Since the To information is not kept when one has to switch tabs to retrieve the data info to send with the transaction, when one reopens metamask to enter the Data field info the To field is back to being blank.
