### ISSUE TITLE
[Bug]: Creating a second snap account without hitting OK on the confirmation/success message of the first account, creates out of sync

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#21448]
### Describe the bug

Uncertain if this is an issue with the Snap Simple Keyring v1.0.1 (SSK) or an issue on the extension side.  If I create or try to import a second account before I have engaged the CTA on the confirmation/success message from the first account, then both accounts are created in the extension but do not exist in the snap and errors are generated.

### Expected behavior

Should be able to create/import multiple snap accounts without having to take action on CTA in success message.  This was previously reported in https://github.com/MetaMask/accounts-planning/issues/108 but that did not include details about the errors and the user impact of getting the snap account list and the extension account list out of sync.  In this condition the created accounts are not usable in any async approval flows.

### Screenshots

Errors when second account is a private key imported through SSK:

<div style="display: inline-block"> <img width="160" src="https://github.com/MetaMask/metamask-extension/assets/32695229/a56c9dd9-cb5c-4dc4-8862-04f48ad70982"><img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/ebb8b6aa-d799-4878-86e8-b469b637d074"></div>

Error shown when both new accounts are created from the snap: 
<img src="https://github.com/MetaMask/metamask-extension/assets/32695229/643421f4-e2c6-4513-8205-7a55f5afbc40" width="200"/>`

Recording of creating 2 new snap accounts: https://recordit.co/zmxvDa5vGQ

### Steps to reproduce

1. Create a wallet
2. connect to and install the SSK v1.0.1 snap
3. Create a new account
4. tap `create` on extension
5. do NOT tap `OK` on the confirmation/success
6. Try to either import a private key through SSK, or create a new account in SSK
7. Tap `Ok` from the first account success message
8. Tap `Create` for the second account
9. Tap `Ok` on the success message for the second snap account
10. Note errors in the snap and no accounts shown, but 2 accounts do exist in extension

### Error messages or log output

```shell
See screenshots above
```

### Version

11.4.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

Edge case- sev 2

**Comment by ccharly** [comment]
Still an issue as of today.

Encountered this one using [this reference on `develop`](https://github.com/MetaMask/metamask-extension/commit/8ab063772a965aab1ea377a74856b065eb4cb039).

However, mine might be a variation of it, since the extension seems to "crash" (you'll get an infinite spinner).

For the sake of completeness, here's a quick transcript of it:

1. Create a new account (1)
1. Confirm the account (1) on MM
1. :warning: At this point, we do not hit "OK" to "finalize" the creation flow
1. Create a new account (again) (2)
1. :warning: At this point, we have 2 "pending" pages on MM
1. Hit "OK" for account (1)
1. Confirm the account (2) on MM
1. Hit "OK" for account (2)
1. :red_circle: MM is looping

**Comment by ccharly** [comment]
https://github.com/MetaMask/metamask-extension/assets/569258/9efa01e5-05a7-4c61-bcc9-680eadf7d5c8
