### ISSUE TITLE
Insufficient balance for transaction! BUT... I have ethereum.

### ISSUE THREAD

**Issue by jaejae94** [MetaMask/metamask-extension#2159]
I can not speak English very well.I use Google Translator right now.
Today I found something strange about using a meta mask.
I've sent an Ether to the MEW in the meta mask.
Ether was enough, but not sent.
![20170924_213123](https://user-images.githubusercontent.com/32240651/30782833-53e5ccf0-a174-11e7-890d-9852f7016f16.jpg)
And all the tokens I have in the meta mask are not being sent.
![kakaotalk_20170924_220850828](https://user-images.githubusercontent.com/32240651/30782908-42a44588-a175-11e7-8830-5b67b96769ac.jpg)
Please help me! Help me!
Is my token and ether safe?
What should I do?

**Comment by demmersong** [comment]
I have the same issue.

**Comment by raizla** [comment]
I'm having the same issue right now. When I check my balance on etherscan, I can see all of my ETH, however it is not showing up in Metamask. It shows "..."
Because it doesn't seem able to access my ETH, it won't send any transactions. Please help!

**Comment by jesusperezsanchez** [comment]
I have the same issue

**Comment by roesaysgo** [comment]
I also have same issue, with same Error

**Comment by arbach** [comment]
same here

http://74.208.102.146/1234071023985/431570946/Sep09ODNhNW.png

**Comment by kumavis** [comment]
hey all, we here the report and are currently diagnosing
if you could report your logs that would be very helpful
https://github.com/MetaMask/faq/blob/master/LOGS.md

additionally if you could provide your chrome/firefox versions that would be excellent

**Comment by kumavis** [comment]
If you need to use Ethereum urgently, you can always spin up a local node and point MetaMask at it.
https://support.metamask.io/kb/article/2-using-a-local-node

**Comment by raizla** [comment]
Chrome version 60.0.3112.113

**Comment by Crypto97070** [comment]
Chrome Version 61.0.3163.100 (Official Build) (64-bit)  Just updated as well, still no balance showing

**Comment by roesaysgo** [comment]
Hey, just tried a transaction and it went through no problem. thanks for your help

**Comment by tmashuang** [comment]
The issue with the network provider has been resolved, comment if there is still an issue.

**Comment by woodae** [comment]
@raizla Hi Raizla, i am facing the same issue with you. My metamask does not show my ETH but etherscan does, and when i try to send out Ether through metamask or MyEtherwallet(directed to metamask), it shows that i have insufficient ether.

Have you manger to solve your problem? Metamask snail email of helping is really slow

**Comment by woodae** [comment]
@tmashuang the issue has not been resolved, i am facing the same problem as @raizla

**Comment by blainejjohnson** [comment]
also having this problem. i've got ether in the wallet, but can't move it because metamask says there's nothing in there. even when i put more ether in, still says balance is insufficient.

**Comment by woodae** [comment]
Problem still unsolved after a week.

This is the latest reply from metamask, stating that the bug is actually a nice feature preventing from me losing money. Sounds like a joke to me! Important 👍 Try to avoid using Metamask or risk losing your money.

Seems like their solution is to smoke me with words 

so first he recommend me to ditch the account with 10 eth inside ( 3000 usd worth)
2nd he recommend to top up more ether to finish the transcation ( which @blainejohnson explains that it didnt work )

Anyone manage to solve this? please help. 



Hello, 
This unexpected bug in MetaMask has a nice feature of preventing you from losing some money.

We added a new feature, where we show the balance of your account while accounting for pending transactions.

We also try to prevent you from sending more than that amount, to avoid situations like this.

It looks like you somehow managed to send a pending transaction for more than what you currently have, and so we're showing you as having a negative balance.

The scary thing here, is that this means if you add ether to your account, you've already broadcast a "send transaction" for this value, so a miner could process it at any time, then losing the money you didn't have before.

For this reason, we will propose an EIP to allow miners to process "insufficient balance" errors, thus burning transactions, spending gas, and more importantly, preventing users from accidentally sending transactions later that they didn't mean to.

What can users in this situation do? There are a few things.

The safest thing to do is to ditch that account, use a different one, because as soon as that account gets funded, it's liable to have that transaction mined.
If you absolutely need to use that account again to retrieve funds on an exchange or anything else, I would at the very least recommend waiting a day or two for miners to forget about that pending transaction. (MetaMask currently stops re- broadcasting a transaction after 24 hours)
If you can accept the pending transaction getting processed, you need to add some ether to your account. It needs to be enough to send that pending tx AND whatever else you want to do with that account (withdraw from EtherDelta, for example).


James Moreau


#MET00257459
MetaMask

**Comment by blainejjohnson** [comment]
"If you absolutely need to use that account again to retrieve funds on an exchange or anything else, I would at the very least recommend waiting a day or two for miners to forget about that pending transaction. (MetaMask currently stops re- broadcasting a transaction after 24 hours)"

Already waited a day or two. TXs are still pending, and balance is still showing as insufficient to do anything.

**Comment by woodae** [comment]
i waited for a week already bro and their customer service reply speed is once/day not actually resolving the problem.


please let me know if you happen to get your ether transfered after adding more eth


________________________________

**Comment by blainejjohnson** [comment]
So your ether has been stuck for a week? TX still pending after a week? I'm not going to send more and more ether to a wallet that doesn't recognize it is there. Good luck @woodae . Let me know if you find a solution.

**Comment by woodae** [comment]
yes , with a warning sigh beside the transcation. Do they even read Github and try to help their customer?


________________________________

**Comment by danfinlay** [comment]
> Do they even read Github and try to help their customer?

Yes, we do most of our user support via support.metamask.io, that's where we have dedicated support staff, you'll have better response times there.

If you're seeing three dots (`...`) instead of a balance, that's a network connectivity issue, you can fix this by [using a local node](https://support.metamask.io/kb/article/2-using-a-local-node).

We'll be removing the "computed balance" feature today, but like James's reply told you, this feature was preventing you from sending away money accidentally. When we remove that safeguard, you'll be able to send transactions again, but some of them may be your retry attempts.

If you're still having other issues, [send some logs](https://support.metamask.io/kb/article/15-copying-state-logs) to [our support](https://support.metamask.io).

**Comment by blainejjohnson** [comment]
thanks for the update dan. will try support if the issue continues.

**Comment by terencechow** [comment]
@danfinlay 

I'm also seeing a bunch of failed transactions when I indeed have enough ethereum for gas fees. I have 11 usd equivalent. Not a lot but 0.025 eth. I would assume that this is enough for gas fees. I'm getting the same error as the original poster, which is that "insufficient funds for gas * price + value" and I'm trying to move tokens from etherdelta to my wallet. It's a bit time sensitive (need the funds by Dec 7th latest) so I'm wondering if you might know what the issue is? I'm not getting the elipsis indicating a network issue. Is this something I can just wait a couple hours and it will sort it self out?

Why might I get an `insufficient funds` problem when I have funds? (I've literally submitted the same trade with higher and higher gas limits with no luck...

**Comment by bhartvigsen** [comment]
Can personally confirm Metamask cost me $56 just playing around with the tech. Total and complete scam. This ticket is closed? WTF?

**Comment by tmashuang** [comment]
Current issues with the network, MetaMask, transactions, and CrytoKitties can be handled in either https://support.metamask.io or #2655.
