### ISSUE TITLE
[Bug]: CONTROLLERS MIGRATION - `Invalid transaction envelope type` when sending Legacy transactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21912]
### Describe the bug

**Problem:** wheenver I try to send a legacy tx I can see how gas is not correctly set (gas price is 0). Furthermore, when I re-load the wallet I see the background error `Invalid transaction envelope type: specified type \"0x0\" but including maxFeePerGas and maxPriorityFeePerGas requires type: \"0x2\"",` 

Seems that Legacy tx's are not correctly supported now

### Expected behavior

Legacy tx should be supported. This will also make fail all transactions in networks that use the transactions type 0x0 by default

### Screenshots/Recordings
![Screenshot from 2023-11-21 13-15-26](https://github.com/MetaMask/metamask-extension/assets/54408225/304ebac6-aa66-44b6-9d5d-746b953dea8d)

https://github.com/MetaMask/metamask-extension/assets/54408225/b059256c-b06a-41ee-8f94-8d5f44cb2a55

### Steps to reproduce

1. go to the test dapp
2. Try a Send Legacy tx
3. See gas price is set to 0
4. Confirm
5. Disable and enable the wallet
6. See error in the background console

### Version

https://github.com/MetaMask/metamask-extension/pull/21166

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
This should be fixed now, tested with legacy and EIP 1559 transactions, both showing gas values in the confirmation 🤞

**Comment by sleepytanya** [comment]
@matthewwalsh0 
Firefox works great:

https://github.com/MetaMask/metamask-extension/assets/104780023/283490de-734f-4830-a237-9354a7116227

Chrome:
1. Install MetaMask dev build
2. Send Legacy or EIP 1559 transaction - gas estimates correctly shown in the confirmation
3. See failed transaction with nonce value 0

https://github.com/MetaMask/metamask-extension/assets/104780023/63c16905-e874-44fe-93e5-3aa0000eee99

Subsequent transactions can't be performed because of this error message:
<img width="343" alt="Screenshot 2023-11-21 at 12 56 50 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/8402e0e2-6d00-426a-87f6-af02bccb35d3">
 Disabling and enabling the wallet transactions allows to send transactions with correct nonce values.
 If you try to disable/enable extension while having pending Legacy transaction the transaction gets stuck and can't be speed up or cancelled.

https://github.com/MetaMask/metamask-extension/assets/104780023/2f907458-46f0-40ee-a986-31a8370e156b

**Comment by sleepytanya** [comment]
`0 nonce` issue fixed, any transactions gets correct nonce value.
Chrome:
<img width="640" alt="Screenshot 2023-11-21 at 8 45 26 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/5ec25019-82ab-4c25-b18e-d94a3a2360bd">
Firefox:
<img width="574" alt="Screenshot 2023-11-21 at 8 48 09 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/52e785e8-d7a4-4d72-9112-9c71a00f72fb">

**Comment by seaona** [comment]
@matthewwalsh0 @sleepytanya I see the Legacy transaction issue fixed with the last changes. We can close the ticket
