### ISSUE TITLE
Tx failed "rpc error with payload" "replacement transaction underpriced"

### ISSUE THREAD

**Issue by Sajjon** [MetaMask/metamask-extension#2219]
I am using MetaMask chrome extension `3.10.6`

I try to buy order at EtherDelta. I am using standard gas limit `250.000` and trying to place orders with [recommended gas price of 4 gwei](https://www.reddit.com/r/EtherDelta/comments/6hrvwl/how_fees_work/)

@danfinlay [wrote that this has been fixed](https://github.com/MetaMask/metamask-extension/issues/1749#issuecomment-315546077) but I am using `3.10.6` and it is not fixed.

@danfinlay also wrote [here](https://github.com/MetaMask/metamask-extension/issues/1967#issuecomment-324539413) that is has been fixed, in PR #1966 but that is apparently not the case.

[This issue at EtherWallet](https://github.com/kvhnuke/etherwallet/issues/1050) seems related?

<img width="472" alt="screen shot 2017-09-29 at 14 03 26" src="https://user-images.githubusercontent.com/864410/31015384-26c97532-a520-11e7-81e8-660f9a8ab476.png">
<img width="472" alt="screen shot 2017-09-29 at 14 03 32" src="https://user-images.githubusercontent.com/864410/31015385-26c9c942-a520-11e7-9cbd-87f08dbe6eb5.png">

If I chose a higher gas price often works, somewher around 30-40 gwei.

**Comment by rust4545** [comment]
happening again on etherdelta, no matter how high the gas price

**Comment by danoelm** [comment]
Same issue here, latest version, every transaction gets me this same error

**Comment by frankiebee** [comment]
@rust4545 @danoelm do yours also say `replacement transaction under priced?`

**Comment by frankiebee** [comment]
@Sajjon can you get background logs for me and send it to are [support](http://metamask.consensyssupport.happyfox.com/home) including your issue number

**Comment by rust4545** [comment]
edit to my previous comment - it is totally unrelated to etherdelta, I just tried sending to a ledger nano s address and am getting the same error. Effectively I cannot do anything with my coins!

**Comment by Sajjon** [comment]
@frankiebee hmm I feel somewhat reluctant sending the Internal Storage of MetaMask to you given that this is not a testnet account and I have funds in it. How should we proceed?

**Comment by rust4545** [comment]
hi,

i was able to access the account outside of metamask and withdraw the funds

2017-09-30 13:36 GMT+02:00 Alexander Cyon <notifications@github.com>:

**Comment by frankiebee** [comment]
@Sajjon i just need the transactions they will not contain your private keys. But will reveal to me your public address:

instructions for only extracting your transaction history from MetaMask:
step one:
navigate to `chrome://extensions/`
check developer mode
open background console for metamask
enter this in the console:
```js
function getTransactions () {
  const transactions = JSON.parse(localStorage["metamask-config"]).data.TransactionController.transactions
  console.log(JSON.stringify(transactions))
}

getTransactions()
```
copy the out put 
and send off to are support system.


If you are still not comfortable with this i can try to reproduce on my own but it will take a lot longer to fix this bug.

**Comment by frankiebee** [comment]
sorry dont do the last thing

**Comment by frankiebee** [comment]
if you are uncomfortable with giving me state I'm not sure how I can help but also you could just give us your transaction history I dont need your hole state.

**Comment by Sajjon** [comment]
@frankiebee I created an account at support.metamask.io and a ticket, referencing this Github issue, including the logs, having removed my encrypted private key.

**Comment by frankiebee** [comment]
@Sajjon thank you so much!! Your txHistory will be a lot of help figuring out this bug.

**Comment by frankiebee** [comment]
@Sajjon have you ever put this account on another device or migrated into somewhere else?

**Comment by Sajjon** [comment]
@frankiebee Yes I have, I first installed MetaMask on my Macbook Pro. Then I installed MetaMask  on my Mac Mini - using same passphrase so it would be the same account.

I think I actually installed on a third Mac as well.

**Comment by frankiebee** [comment]
is it possible you sent a transaction on both your machines at the same time?

**Comment by frankiebee** [comment]
or that you tried sending on one machine and then went to the other to send

**Comment by Sajjon** [comment]
@frankiebee I did not retry a failing transaction on mac2 when failed on mac1 what I can recall.

But I specified 4 gwei for many transactions, that have been pending. I might have put another order on EtherDelta for same token on mac2, when I forgot about the same order made from mac2.

**Comment by Sajjon** [comment]
@frankiebee any progress? I mainly use MetaMask for EtherDelta, but now it is completely broken. Transactions I paid 50 gwei for over 3 days ago have still not been completed.

Thanks! <3

**Comment by danfinlay** [comment]
@Sajjon could you reference your MetaMask ticket number here, so we could look at what's going on for you?

I see you've referenced a couple other issues that I closed, and are claiming that this is the same issue. That is not the case. This error is coming from the backend node, and can be shown for a variety of reasons, so just because you see this message, doesn't mean it's the same underlying problem. You can help us best by focusing on your own situation, and describing it to us. Could you post your ticket number here, so we can look it up?

The network has been very congested, so one possibility is that your transactions were simply priced too low to be mined, and that MetaMask eventually gave up broadcasting them (currently at 1 day of retries). You might want to post a recent state log before sending us the ticket number, so we can get a recent view.

[Guide to copying state logs](https://support.metamask.io/kb/article/15-copying-state-logs).

I see you're expressing some reluctance about sharing state logs, and even claimed to have erased your seed phrase from it, but our state logs don't store any private keys or seed phrases, so I'm not sure what you removed there. Just follow the guide, and while we'll know what your accounts are, we will have no control of them.

We're going to add the ability to re-submit a transaction with the same nonce but higher gas price, that will probably allow you to work through this situation. In the meanwhile, if you want to submit some fresh transactions without waiting for your low-priced txs to process, you will have to back up your seed phrase, then uninstall & reinstall MetaMask.

**Comment by Sajjon** [comment]
@danfinlay Dan thanks for your prompt and thorough response, my ticket number is `MET00257482`, I have uploaded the **state logs** to the ticket

Regarding what I removed earlier, it was the data inside `vault` inside `KeyringController` in the **internal storage logs**

**Comment by abitrolly** [comment]
The same here with Metamask 3.12.1 on Firefox 57.

![image](https://user-images.githubusercontent.com/8781107/33578770-b6c20ffc-d958-11e7-8e06-8aacf95cad48.png)

If I remember correctly, gas price was 20 Gwei and I didn't change it when asking for new transaction at gitcoin.co. New transaction is still pending - https://etherscan.io/tx/0xb78d4524a46a7e34e5d077f7bd49f21b14fac183341f5e578ccc7ed54a2abcc8

**Comment by danfinlay** [comment]
We've now written a post about this issue, please see if it helps: https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147

In short, the gas prices are really high right now, so be patient or bid high, and maybe run a local node to avoid some more rare strangeness.

**Comment by helloMike** [comment]
I've came up the same problem ,maybe i setted the gas price too low ,what should i do now?
![2018-03-07 2 46 31](https://user-images.githubusercontent.com/6396282/37052633-d81acf14-21b4-11e8-8137-cf00363f6e72.png)

**Comment by danfinlay** [comment]
> I've came up the same problem ,maybe i setted the gas price too low ,what should i do now?

I'd say try again with a higher gas price, but it looks like this succeeded, based on your link, so it looks like another type of bug.

**Comment by danfinlay** [comment]
@helloMike Would you mind sending your [state logs](https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs) to support@metamask.io so we can try to debug this?  Tell them I asked for the logs here, and to assign me.

**Comment by danfinlay** [comment]
Like I said before,

> @helloMike Would you mind sending your state logs to support@metamask.io so we can try to debug this? Tell them I asked for the logs here, and to assign me. Include a link to this issue.

**Comment by cmaliwal** [comment]
![metamask error](https://user-images.githubusercontent.com/21885663/40307759-7402c808-5d21-11e8-8ea4-bfdc3a64a825.png)

I am also facing the same issue.

**Comment by Gudahtt** [comment]
This error can appear for a variety of different reasons, and in many cases it is not a bug. The extension has changed dramatically since this issue was opened, so I don't think this is actionable anymore.

If anyone is still encountering this issue, [please contact support](https://metamask.zendesk.com/hc/en-us/requests/new).
