### ISSUE TITLE
[Bug]: Unable to set low gas using Advanced Gas options on Linea Goerli.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#22257]
### Describe the bug

Using Advanced  Gas options to set low gas fee for the transaction always results in Failed transaction. I see this issue  on versions 11.8.0, 11.7.0, 11.6.1.

### Expected behavior

User should be able to set lower gas fee for the transaction through `Advanced Gas Fee` tab.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/adf2c1e6-7b1c-49bb-aedb-6c34049fcf99

### Steps to reproduce

1. Go to Linea Goerli testnet
2. Create regular `send` transaction
3. Try to set up low gas fee using `Advanced Gas Fee` tab
4. See `Failed` transaction in the Activity tab

### Version

11.8.0, 11.7.0, 11.6.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by vinistevam** [comment]
I managed to use an editable low gas but it's true if I replace the gas with a very low number the transaction fails and I see `transaction underpriced`, this might be due to a certain threshold that the network accepts, moreover: https://docs.linea.build/build-on-linea/gas-fees

https://github.com/MetaMask/metamask-extension/assets/45455812/5357ac7d-7289-4799-83b8-963b708c289d

**Comment by sleepytanya** [comment]
Thank you, @vinistevam! So it looks like Advanced Gas feature works as it supposed to on Linea Goerli.
