### ISSUE TITLE
[Bug]: Unable to deploy certain contract types on Linea Goerli testnet from test-dapp.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#22313]
### Describe the bug

ERC-20, ERC721, ERC-1155 and Multisig contract always fail on Linea Goerli. Failing contract and Piggy bank contract deployment work as expected.

### Expected behavior

All types of contracts should be created from test-dapp.

### Screenshots/Recordings

1. Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/705ca101-556c-44cf-8251-618ad9a64a36

<img width="477" alt="Screenshot 2023-12-18 at 12 32 24 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2736b79b-fcb4-4277-94f1-f5ff7a585b5a">
<img width="742" alt="Screenshot 2023-12-18 at 12 28 20 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/5798881e-205c-4ec4-ae50-c3aafa515b66">

 2. Firefox:
 

https://github.com/MetaMask/metamask-extension/assets/104780023/6fa0d418-1823-4367-81e2-d079b7af7bd6

<img width="470" alt="Screenshot 2023-12-18 at 12 21 12 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/fe36a267-bc90-4a26-b975-b350a6e0d177">

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Connect the wallet
3. Create ERC20, ERC721, ERC1155 or Multisig contract
4. See the transaction fail

### Version

11.8.0, 11.7.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by julien-marchand** [comment]
We have 2 issues hidden here:
- Infura duplicates all requests because of traffic mirroring that was requested to perform some tests. This is being addressed as part of https://infura.atlassian.net/browse/ONCP-260, and should be released soon.
- MetaMask doesn't process correctly idempotent requests @chloeYue  @sleepytanya you might want to track this issue to make sure `already known` is treated as a success and not a failure.

Related to https://github.com/hyperledger/besu/issues/6388 (cc @nkeywal @kshinn)

**Comment by julien-marchand** [comment]
@chloeYue First fix has been release on Linea/Infura part, the second fix in on MetaMask side

**Comment by sleepytanya** [comment]
I don't see the issue with contracts on Linea Goerli anymore, Metamask 11.7.3.
<img width="718" alt="Screenshot 2024-01-17 at 9 20 38 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/40348775-b7d6-40e1-9c81-9304dcbcb986">
