### ISSUE TITLE
[Bug]: Gas fix or default value not working in recent updates.

### ISSUE THREAD

**Issue by chendatony31** [MetaMask/metamask-extension#22333]
### Describe the bug

I've fixed the gas in a network, it works well in the old version. But not in the newest release. 

### Steps to reproduce

1. custom and fix the gas price
2. sendtransaction again it doesn't using my gas

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by raster21** [comment]
**Steps to reproduce this bug:**
- Initiate a transaction
- Select "Advanced" as the gas preset
- Check the checkbox "Save these values as my default for the Mainnet network."
- Cancel the TX
- Initiate a TX again

**Expected behavior:**
The "Advanced" gas preset is selected

**Actual behavior:** 
The "Market" gas preset is selected

**Comment by anaamolnar** [comment]
Hello, @raster21. Thanks for reporting! I will pass this on to the team.
