### ISSUE TITLE
[Bug]: Not WORKING correctly on ETHEREUM - Tokens NOT displayed, and NOT prompting for confirmation

### ISSUE THREAD

**Issue by 4u2hear3000** [MetaMask/metamask-extension#22388]
### Describe the bug

When switching to Ethereum balances (tokens) are not showing except for ETH, and MetaMask will prompt for confirmation - seems it is looping forever (tried on  newparadigm.manta.network / pancakeswap.finance)
MetaMask working OK on BNB, Polygon, ..

### Expected behavior

See balance (tokens) and confirm transaction

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/135171640/6cb42a14-6087-4203-b86d-6dc2f75d04ed)
![image](https://github.com/MetaMask/metamask-extension/assets/135171640/22ac5461-a24c-4994-ab05-446479bc8f9f)

### Steps to reproduce

Open MetaMask and switch to Ethereum
No error message displayed
MetaMask Version 11.7.2
Chrome Version 120.0.6099.129 (Official Build) (64-bit)

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by gauthierpetetin** [comment]
Hi @4u2hear3000  can you please check if this still happens if you go to "Manage Extensions > MetaMask > Site access" and select "On all site"?

https://support.metamask.io/hc/en-us/articles/360038139452-MetaMask-states-Balance-may-be-outdated-displays-in-orange-or-ETH-not-added-to-balance
cc @anaamolnar 

<img width="703" alt="Screenshot 2024-01-04 at 12 07 25" src="https://github.com/MetaMask/metamask-extension/assets/7071180/52df66aa-2889-4720-b382-f567a88f967c">
