### ISSUE TITLE
[Bug]: Metamask fails to load due to migration error

### ISSUE THREAD

**Issue by weiribao** [MetaMask/metamask-extension#22385]
### Describe the bug

The MetaMask window is stuck spinning. There wasn't a specific event on the user's end that led to this. It seems to have been caused by a failure in the MetaMask update, as indicated by a 'migration #88 error' in the console.

### Screenshots/Recordings

![Screenshot 2023-12-23 at 9 28 08 AM](https://github.com/MetaMask/metamask-extension/assets/1902327/37f3a128-0657-413f-af1f-d45e9d2f5dbe)

### Steps to reproduce

No particular event that led to this. I assume the corruption happened after an automatic MetaMask update.

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

Critical. The entire window does not load.

**Comment by EmjayGitHub** [comment]
Hi,

I'm not entirely sure that my issue is related, but it could be.
For about a week I haven't been able to use the Metamask extension for Firefox, as it's just spinning when I try to open it.
Furthermore when I try to log in on e.g. Opensea.com using Metamask, nothing happens - again it's just spinning. The extension isn't even opening.
I have allowed the extension to run in private windows, and on restricted sites (just to test). Nothing worked.

I have attached a console output from debugging the extension. The output is from me trying to open the extension manually. A window opens, with the Metamask logo, and a "loading spinner".

![image](https://github.com/MetaMask/metamask-extension/assets/80046851/56bed572-38bc-4b9a-a187-55411581e046)

If my issue is not related to this reported issue, please let me know, so that I can create my own.

**Comment by jonathan-35** [comment]
Hello, I have the same problem, how can I solve it?

**Comment by czajunia** [comment]
The same problem here. Is there a solution please?

**Comment by anaamolnar** [comment]
Hello, @weiribao. Thanks for reporting! I will pass this on to the appropriate team for review.
