### ISSUE TITLE
[Bug]: incorrect nonce from cache

### ISSUE THREAD

**Issue by shunjizhan** [MetaMask/metamask-extension#22630]
### Describe the bug

currently metamask infers nonce from cache (last tx), but it sometimes cause wrong nonce. For example:
- if I have sent another tx from another wallet/broswer/computer, MM doesn't know the nonce has increased
- on testnets, when the nonce has been reset, MM still uses cached nonce
- there are some other occasions where the nonce is bigger than expected, which causes tx to stuck since the nonce is too big, but I am not sure the exact cause. Clearing the cache resolves it so it's still a cache issue

### Expected behavior

there are many ways to potentially improve this
- fetch nonce from RPC directly
- validate cached nonce if it's been idle for X minutes/hours
- offer an option to disable cached nonce, to let users choose if they want cache (might be slightly faster) or fetch nonce every time (more accurate)

### Steps to reproduce

- send a Tx
- change the account nonce, by either sending another tx (elsewhere) or any other way
- send another Tx, now it will have wrong cached nonce

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @bschorchit , I added a sev2 label on this one, but feel free to update if not relevant.

**Comment by OGPoyraz** [comment]
Hi @shunjizhan 

I've opened the same account on two different sessions (left is Chrome, right is Firefox)
And as you described: (see recording) 
1. Send a transaction in FF
2. Send another transaction in Chrome without waiting
3. See that Chrome failed because the transaction that I send from FF is confirmed, and nonce is too low (as expected)
4. Then I am initiating another transaction on Chrome since I get that nonce error there. 
5. I can successfully create another transaction. 

https://github.com/MetaMask/metamask-extension/assets/7644512/dd6b0281-6b3a-4161-a31f-d5acd857a3a3

Please note that MM is looking at the active chain properly and updating nonce value already. There is a really small chance that mismatch nonce since these calls are async. But eventually it will start using correct nonce value once update happens.

If you have another specific issue with well defined reproducible steps, I will be happy to have a look at it.

**Comment by shunjizhan** [comment]
@OGPoyraz thanks for the test. I have experienced a couple times (very rarely) that the nonce is bigger than expected, which causes the tx to be pending forever. Clearing the cache solves it. 

But I am not sure how to reproduce that yet, I will re-open the issue or create a another one when I can reproduce it
