### ISSUE TITLE
Negative Balances Showing After Failed/Successful transactions

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#2270]
Ref: #MET00257495

> User: I sent ETH to Etherdelta , which was successful. However it says there is a pending transaction for the same amount and it says my account has  negative balance. I also cannot withdraw from etherdelta as it says I have insufficient funds.

State logs accompanied in ticket

**Comment by jrmoreau** [comment]
Additional state log ref: #MET00257477

**Comment by tomassutas** [comment]
I have exactly same issue, how can I solve it?

**Comment by danfinlay** [comment]
This unexpected bug in MetaMask has a nice feature of preventing you from losing some money.

We added a new feature, where we show the balance of your account *while accounting for pending transactions*.

We also try to prevent you from sending more than that amount, to avoid situations like this.

It looks like you somehow managed to send a pending transaction for more than what you currently have, and so we're showing you as having a negative balance.

The scary thing here, is that this means if you add ether to your account, you've already broadcast a "send transaction" for this value, so a miner could process it at any time, then losing the money you didn't have before.

For this reason, I actually think we might want to propose an EIP to allow miners to process "insufficient balance" errors, thus burning transactions, spending gas, and more importantly, preventing users from accidentally sending transactions later that they didn't mean to.

What can users in this situation do? There are a few things.
- The safest thing to do is to ditch that account, use a different one, because as soon as that account gets funded, it's liable to have that transaction mined.
- If you absolutely need to use that account again, I would at the very least recommend waiting a day or two for miners to forget about that pending transaction. (MetaMask currently stops re-broadcasting a transaction after 24 hours)
- If you can accept the pending transaction getting processed, you need to add some ether to your account. It needs to be enough to send that pending tx AND whatever else you want to do with that account (withdraw from EtherDelta, for example).
- You could try re-sending a competing transaction with the same nonce, but we don't have a feature to do this easily yet, so I don't really want to support it.

**Comment by tomassutas** [comment]
Hi, the thing is that the account is fine on etherscan, MEW, Imtoken etc, it does not show a negative balance and there are no pending transactions. Its only negative on metramask extention due to that "pending" transaction, but if you press on it - it does not exist on etherscan so it will never be processed

**Comment by tomassutas** [comment]
I also sent eth to this account yesterday which showed fine on etherscan and MEW but on metamask it just reduced the negative balance by that amount. I then could not use metamask for obvious reasons, as it thinks its negative balance, so I used ImToken instead to send it where I need to with no problems. However this is my main eth address so I dont want to ditch it and I like metamask, but seems like due to this large bug I wont be able to anymore

**Comment by Zanibas** [comment]
We have temporarily rolled back what was causing negative balances for now. Please reopen this issue again if the error still persists!

**Comment by DoubleDRAGAN** [comment]
Hi, 
Yesterday I deposited $100 worth of ETH into Metamask.
Tried multiple time to buy some tokens on Etherdelta....  it was so so difficult.
I tried to cancel the pending transactions.
Then when I finally was success full in buying 32 tokens of my choice, there was $75 value of the tokens I just bought. Started with $100, eventually bought the tokens, by the time I transferred them to my Metamask wallet I had 32 tokens valued at $75. And no they didn't drop in price. Where did the other $25 go?  Was it chewed  up in the multiple unsucessful transactions which had small gas fees attached ?   If so, then that is F**ked up!

**Comment by danfinlay** [comment]
@DoubleDRAGAN if you have a question about your account, please submit the question to support.metamask.io, this old closed issue is not our ideal place for tracking the conversation.

To tell what happened with your account we’d at least need your address.
