### ISSUE TITLE
Allow resubmitting pending transactions with higher gas prices

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2278]
I thought this was already documented, close if a duplicate.

We should raise the priority on this, we witnessed a spike in congestion recently, and lots of users got confused why their transaction queue got clogged up (behind a low-gas-price tx).

**Comment by danfinlay** [comment]
The initial design for this was that pending transactions had an "Edit" button that basically went back to the "Edit transaction" view, allowed revising params, and resubmitting.

Sending to Christian for any other design thoughts.

**Comment by variousred** [comment]
I need this!

**Comment by vicnaum** [comment]
That should be a NUMBER ONE priority now, I guess

**Comment by aribo** [comment]
Related to this, a clear indication of the status of the transaction would also help. If the tx is not confirmed after a determined period of time, Metamask presents the button to 'Resubmit' or 'Cancel' transaction.

'Resubmit' = same type of transaction to: and amount: being the same, with higher gas price and possibility of changing gas limit.

'Cancel' = transaction with same nonce but to: the same address as from: at higher gas price (at least 10% higher) 

The function is not exactly cancelling the transaction, because it doesn't remove it from the pool, instead it overcomes the previous one with more gas. But in practical matters for the user it actually cancels it.

More info about these two options: https://medium.com/@jgm.orinoco/releasing-stuck-ethereum-transactions-1390149f297d

**Comment by rappo** [comment]
btw, I put a $50 bounty on this to whoever submits a PR that gets merged as the solution: https://www.bountysource.com/issues/52252733-allow-resubmitting-pending-transactions-with-higher-gas-prices

**Comment by vicnaum** [comment]
I've submitted a pull request for #2679 - which is a good start and doesn't involve any design changes.
See: https://www.reddit.com/r/ethereum/comments/7i1nb4/eth_replacer_metamask_nonce_fix_replace_pending/

**Comment by Arachnid** [comment]
A really simple UI for this would be to show it only for the first pending transaction - otherwise users will get confused as to why bumping their later transactions isn't helping. Ideally just two options - 'cancel', which replaces it with a null-transfer, and 'accelerate' (or similar) which lets you set a new, higher gas price.

Also, ideally metamask should warn users when they're about to submit a transaction with higher gas price than a pending transaction that this won't help until the older transaction clears.

**Comment by danfinlay** [comment]
I like only showing "retry with higher gas" on the earliest pending tx.

Showing "cancel" on it can be dangerous: That tx may be replaced, but unless all the other ones are replaced, they can still be processed. Maybe that's fine, but we've seen users queue up invalid transactions, forget about them, and then have them go through when they didn't want them to, so I have some prior trauma making me resistant to that.

It's probably still fine.

I've opened some issues for those other suggested aspects. We have a retry button in master, and a fix to make it work correctly with Geth as an open PR.

**Comment by danfinlay** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/2684.

**Comment by rappo** [comment]
@danfinlay the $50 bounty I posted is up for grabs if you want to claim it: https://www.bountysource.com/issues/52252733-allow-resubmitting-pending-transactions-with-higher-gas-prices

**Comment by moodysalem** [comment]
I created an issue to discuss adding an optional attribute to a transaction that points to the hash of the previous transaction, so that transactions with this optional hash will only be considered valid if the previous transaction hash has already been included:
https://github.com/ethereum/EIPs/issues/932
