### ISSUE TITLE
[Bug]: PPOM - UI Warning for Signatures is cut when unfolding details which contain a long string (i.e. address)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22792]
### Describe the bug

**Problem:** whenever I trigger a malicious signature, I see that the warning is cut if I unfold it and it contains a long string (i.e. address)

### Expected behavior

Wrap the content?

### Screenshots/Recordings

![Screenshot from 2024-02-02 11-44-45](https://github.com/MetaMask/metamask-extension/assets/54408225/6babc61f-2656-4b26-8947-393a1462a5a2)

### Steps to reproduce

1. Enable Blockaid
2. Select Mainnet
3. Go to the test dapp
4. Trigger the Permit Signature
5. Click See details
6. See warning is cut

https://github.com/MetaMask/metamask-extension/assets/54408225/db0dba00-d57e-4b2a-8728-12805c6da7a3

### Version

11.7.5 and might be earlier (issue is in prod)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
This issue is already fixed in new designs, we need to fix it in old ones:

<img width="360" alt="Screenshot 2024-06-25 at 5 31 42 PM" src="https://github.com/MetaMask/metamask-extension/assets/2182307/e165c5bb-cf85-4c2e-b60a-0c36134d41ec">
<img width="360" alt="Screenshot 2024-06-25 at 5 30 33 PM" src="https://github.com/MetaMask/metamask-extension/assets/2182307/7fbfad8c-fb3a-49a5-9850-51b8655b5c56">

**Comment by bschorchit** [comment]
Closing as we have enabled the redesign signature confirmations by default already
