### ISSUE TITLE
[Bug]: PPOM - Blockaid Security Alerts appear under Experimental section in the Settings Search

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22870]
### Describe the bug

**Problem:** after moving the Security Alerts into the `Security and privacy` section, if we look for Security Alerts using the search, we still see that they appear in the `Experimental` section.

### Expected behavior

Searching for Security Alerts should return the new section Security and privacy

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/7e92a590-5622-4045-825b-0f154956f832

### Steps to reproduce

1. Open Settings
2. Search for `Security al...`
3. See it returns a result placed under `Experimental Settings`
4. Click the result
5. See nothing is there

### Version

11.11.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22870?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona

**Comment by digiwand** [comment]
Created a fix here https://github.com/MetaMask/metamask-extension/pull/22967, along with adding support to search for "Blockaid" or "OpenSea" as this wasn't supported before

During my investigation, I've found a couple of other, out-of-scope, concerns. 

1. Some search settings do not match their intended location. e.g.  searching for 
- "Show balance and token price checker"
- "Use Phishing Detection"
https://github.com/MetaMask/metamask-extension/assets/20778143/d7477fd1-de8b-4304-ae0b-df9ebdada198

2. I think there's been a regression. Sometime in the past, I believe we supported tabbed, multiple-line settings. Now, I think this feature has been removed. As a result, we have a shallow search for settings. I was unable to find matching styles for `settings-page__header__search__list__item__tab-multiple-lines`. This would need more investigation

3. tini style bug w/ background behind icon. I think the fix would be to remove the background here. I can spawn a minor cleanup PR tomorrow around settings for this

###### minor gray background bug
<img width="1667" alt="Screenshot 2024-02-14 at 10 20 41 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/4f5dd08a-fc85-446d-a8ea-78b5e5fb0400">

###### without background (potential fix) (ignore "Security" instead of "Security & Privacy" copy
<img width="1678" alt="Screenshot 2024-02-14 at 10 49 04 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/2c0d5f78-786f-40d8-ba42-03335570cde8">

###### minor background bug darkmode
<img width="1664" alt="Screenshot 2024-02-14 at 10 48 25 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/8958eecb-bd7a-4c7b-bd8e-76aa9a412de1">

###### without background darkmode (potential fix)
<img width="1672" alt="Screenshot 2024-02-14 at 10 48 31 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/864cec81-1bc1-4837-9da5-c6a6ff5cf800">

cc: @seaona

**Comment by digiwand** [comment]
#3 - icon background
issue: https://github.com/MetaMask/metamask-extension/issues/22981
fix: https://github.com/MetaMask/metamask-extension/pull/22982

**Comment by digiwand** [comment]
re:3 - icon background
issue: https://github.com/MetaMask/metamask-extension/issues/22981
fix: https://github.com/MetaMask/metamask-extension/pull/22982

**Comment by digiwand** [comment]
re:1 - fix other Security & Privacy searches
issue: https://github.com/MetaMask/metamask-extension/issues/22985
fix: https://github.com/MetaMask/metamask-extension/pull/22984

The fix includes other search bugs, cleanup, and improvements

**Comment by digiwand** [comment]
Related [Fix PR](https://github.com/MetaMask/metamask-extension/pull/22967) now includes searching for experimental "Nicknames" and "Snaps". Added these in to keep the experimental e2e working
