### ISSUE TITLE
Lost Account

### ISSUE THREAD

**Issue by jahu** [MetaMask/metamask-extension#2347]
Hello, colleague of mine has just called me that 2 days ago (10th of October) he started Chrome and it turned out that MetaMask extension had reverted it's state to default (I believe some update might have happen of your app or chrome).

Unfortunately, the only thing that he has backed up is password to his account, he does not have his private key backed up anywhere nor those "12 words" generated upon account creation.

As I am software dev he contacted me for any guidance, so I am reaching out to you - is there anything he can retrieve from hard drive or anything? Thanks in advance for any, literally any help or suggestions.

Regards,
Jacek Gralak

**Comment by danfinlay** [comment]
The 12-word seed phrase is the thing of the most importance here. We only store it on disk encrypted with the user's password, and if their hard drive is cleared for any reason, it is lost, unless they kept some kind of backup.

Some users have had luck because they had "Time Machine" backups, and were able to restore the chrome extension storage folder. Without that, or a backed up seed phrase, there isn't anything we can do.

If you are able to locate a backed up storage file, you could potentially just put it in the same place on a newer installation, or try manually parsing it. (The file is JSON, the relevant encrypted part would be the `state.metamask.KeyringController.vault`, and would be encrypted with [browser-passworder](https://www.npmjs.com/package/browser-passworder).

**Comment by danfinlay** [comment]
Closing as this isn't really an issue with the repository, but a user question. You can always ask personal support questions at support.metamask.io
