### ISSUE TITLE
Signature Redesign - add any required metrics to re-designed signature request pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23555]
Signature rest pages did not had any metrics events to be ported to new designed pages. (Typed sign V3, V4 pages has a legacy events that was re-redundant).

We need to check with @bschorchit and any new metrics events required for redesigned pages.

**Comment by bschorchit** [comment]
New metrics:
- tracking that it's the redesigned UI being used (while we have both new and old co-existing)
- tracking opening of account info modal

I'll add exact specs for this

**Comment by blackdevelopa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23555?planning-poker) with Zenhub @digiwand @jpuri @pedronfigueiredo @segun

**Comment by jpuri** [comment]
Hey @bschorchit : can you plz spec
> tracking opening of account info modal

**Comment by bschorchit** [comment]
done @jpuri !

**Comment by digiwand** [comment]
I began working on this ticket. I discovered there was a flaw in an existing metric I attempted to fix 2 months ago.
PR: https://github.com/MetaMask/metamask-extension/pull/22631
Issue: https://github.com/MetaMask/MetaMask-planning/issues/1756
[Example metric](https://mixpanel.com/project/2212883/view/2760759/app/events#aVxUP9fS65hJ)

The transaction event with key value 'external_link_clicked': 'security_alert_support_link', is only applied to transactions that are not signatures. We wanted to apply this to both transactions and signatures.

This is relevant because I attempted to use the same method, `useTransactionEventFragment`, and then realized this bug. 

---

It's a bit tricky to append the properties to the asynchronous transaction/signature events. 

Implementation Proposals:

1. 
> For this we can add the value redesigned_confirmation to the ui_customizations property of all signature events when the redesigned UI is being displayed

To handle this, we could extend similar createTransactionEventFragment to Signatures **or**  rely on the upcoming preferences setting. The implementation would be:
  a. add new setting (PR https://github.com/MetaMask/metamask-extension/issues/23554)
  b. import preferencesController as a new param to createRPCMethodTrackingMiddleware
  c. if the setting is enabled, then add the metric

2. 
> tracking opening of account info modal
new property within Signatures events:
account_modal_opened: true if user opened the account modal during the request

To handle this, again, we could extend similar createTransactionEventFragment to Signatures **or** we will need to implement a way to persist the value to createRPCMethodTrackingMiddleware

**Comment by digiwand** [comment]
ticket created to handle issue where external_link_clicked is not being called for signatures
https://github.com/MetaMask/metamask-extension/issues/23995

**Comment by digiwand** [comment]
re: redesigned_confirmation to the ui_customizations

- The related PR updates the "Cancel" and "Confirm" signature events
- The related PR **does not** update the "Signature <Approved,Failed,Rejected,Requested>" events

**Comment by digiwand** [comment]
re: 
> tracking opening of account info modal
new property within Signatures events:
account_modal_opened: true if user opened the account modal during the request

as discussed in earlier's standup, we'll not append the property to existing signature events. Instead, we will create a new event to be fired when the account modal is opened
