### ISSUE TITLE
[e2e]  PPOM - Re-enable all specs after cdn mocks have been implemented

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23642]
### What is this about?

Re-enable all specs after cdn mocks have been implemented.
If the task ends up being too big for 1 PR, it could be split in several PRs.

Once this is merged https://github.com/MetaMask/metamask-extension/pull/23062

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by digiwand** [comment]
Note:
- Tests were originally disabled because they were flaky. Run tests a few times before merging.

To address:
- remove duplicate tests
  - e.g. testing #maliciousTradeOrder in `test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.js` and `test/e2e/tests/ppom/ppom-blockaid-alert.spec.js`

**Comment by bschorchit** [comment]
Closing this as we'll be moving to security alerts API soon and these tests will no longer be needed.
