### ISSUE TITLE
Make metamask extension directly downloadable from metamask.io, in addition to chrome appstore link

### ISSUE THREAD

**Issue by manosamy** [MetaMask/metamask-extension#2369]
Was visiting shanghai recently, here is what went wrong:
1) Chrome browser works, but none of google services worked (and if you set google as your search engine, typing in search phrases in url box doesnt work either)
2) Metamask.io was working, not blocked. So were etherscan.io, etc. Was able to connect to Infura through web3.  Metamask chrome plugin seemed to be stuck, did the grave mistake of uninstalling, wanted to do  a fresh reinstall
3) Chrome appstore doesnt launch (since it is probably serviced from google sites, and hence blocked)
4) Many mirror download sites I reached from searching in bing eventually seem to point to chrome appstore, and hence the download failed. I ended up being unable to reveal my ens names in time.

Requests:
1) Please provide metamask as a standalone download hosted in metamask.io website, I think chrome store allows side loading of apps downloaded from elsewhere
2) Support at least one other browser that is whitelisted in china.

Thanks
Mano Samy

**Comment by danfinlay** [comment]
Another way you could've worked through this is with our published releases page:
https://github.com/MetaMask/metamask-extension/releases

**Comment by manosamy** [comment]
Oops, why didn't I think of that? Guess, I was having a meltdown without google. I see github link on the home page, so it is almost sufficient for dev folk. But since metamask is for general public, it may still make sense to add a direct link. Thanks.

**Comment by leafcutterant** [comment]
This is a bigger issue. I believe it would be beneficial to have an option to access the add-on outside Mozilla's and Google's gardens. I trust you and Github much more than anything from those companies.

I saw there are zips on the Releases page, but I can't install those, or at least not very easily. I too would like to ask for such directly downloadable and installable builds.

(And yes, unsigned  addons served outside the stores do have use cases, if you use i.e. Waterfox, you can install unsigned addons.)

**Comment by danfinlay** [comment]
> This is a bigger issue. I believe it would be beneficial to have an option to access the add-on outside Mozilla's and Google's gardens. I trust you and Github much more than anything from those companies.

The releases page is the easiest way to install MetaMask outside those walled gardens, I'm not sure it's possible to make it any easier, other than including better/easier to find guides on using those.

We have guides for Chrome & Firefox on our main readme here:
https://github.com/MetaMask/metamask-extension#other-docs

**Comment by leafcutterant** [comment]
@danfinlay thanks, I was unaware of this way of installing Metamask. I was looking for a .xpi file and I think that's what most people (in the case of Firefox) are looking for. I think serving an XPI would make the process easier.

Of course this introduces other complications. I can install whatever I want on Waterfox but I guess most people can only install signed releases. I'd very much like to have unsigned XPIs, but maybe that's not worth the effort for you for such a minority (having the zip and two XPIs just for Firefox).

I also fancy what Gorhill does in the uBlock Origin repo (if I understand the process correctly): he uploads the signed XPI to Github, essentially still being able to approve a release, even though it had to be run through Mozilla.

**Comment by leafcutterant** [comment]
@danfinlay the [presently available option](https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-firefox.md) is insufficient for non-experimental use because extension either gets deleted or downgrades to the Add-on store version after restarting the browser, and in both cases it loses all settings and accounts.

Google recently removed the extension from their store without saying a word. This yet again shows that you **can not trust** these entities with serving your software. They can remove or modify it in any way they want, without any accountability. Considering that your software is essentially *the* gateway to the Web3, this is especially ironic and dangerous.

I see an increasing value in serving XPI builds of Metamask on Github and I'd propose moving into such a direction.

Some of you may doubt how this would work, since Firefox has removed the users' ability to use any extensions not signed by Mozilla. Let me introduce you to [Waterfox](https://www.waterfoxproject.org/). An open source fork of Firefox focusing on privacy and freedom of user choice. No phoning home, no stats sent to servers, complete customizability, development happening [on Github](https://github.com/MrAlex94/Waterfox). It was well worth migrating to and if you are a Firefox user, you can import your existing profile.

**Comment by whymarrh** [comment]
I don't think there's anything more we can do on this—the GitHub releases page is the best way we have to offer releases for users that want to "side-load" the extension. Yes, "the presently available option is insufficient for non-experimental use because extension either gets deleted or downgrades to the Add-on store version after restarting the browser" but that's a likely outcome for the foreseeable future as browsers expect extensions to be signed, deployed, and installed through the official means (e.g. Chrome).

Additionally I (personally) don't think it would be wise to promote installing the extension outside of the official means for any given browser as that will likely increase phishing. I'm going to close this for now, but if there is a strong community desire for us to add a signed XPI to our GitHub releases, that's something we can consider in a separate issue.

**Comment by leafcutterant** [comment]
@whymarrh This is one of the many manifestations of the Ethereum community's complacency and forgiveness towards the likes of Google and Microsoft, and honestly, it makes me very sad. It's as if the idea of free software empowering the individual is totally forgotten here and we just go along with the majority perception and convenience. No, it's a despicable idea that we should get our "security" from these companies who shamelessly fuck us over even for half a cent if it's within the margins of not eliciting major consequences. These are exactly the central silos that we are supposed obsolete. If their signing key is compromised, everyone is so screwed that the masses used to this kind of software distribution won't be able to fathom.

There several browsers out there which don't require central extension signing. Even if these constitute a minority of the market share, you shouldn't ignore them and exclusively use the centralized solution rather (and add that you won't address this security hole, because you fear phising).

Sorry, I'm not here to single you out, but this *is* a problem, and with this attitude you are contributing to the worsening of this situation -- the fact that decentralization of trust becomes less and less significant to people and we are recreating the same structures that we promised to disrupt. This is also a path that leads to Ethereum's loss of significance. Why use a decentralized blockchain if some big company can just take care of our stuff?
