### ISSUE TITLE
[Bug]: Smart Transactions - Cannot perform a subsequent transaction until the pending one is confirmed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24159]
### Describe the bug

Whenever I have Smart Transactions enabled, if I perform a transaction and trigger a subsequent transaction, the Confirm button is disabled until the pending transaction is confirmed.
We should not block the user for performing more transactions, and queue them instead?

### Expected behavior

We should enable the Confirm button with a pending transaction, in the same way as we do for non Smart Transactions.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/4460133d-a617-4579-a1ed-0f3076784d74

### Steps to reproduce

1. Enable Smart Transactions
2. Trigger a tx
3. Accept
4. Trigger another tx
5. See the Confirm button is not enabled until the first tx is confirmed

### Version

11.15.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
This is expected currently, since the queueing behaviour for standard transactions is provided by the RPC provider and the node.

With smart transactions, we submit and poll against our custom API until we have a transaction hash, and while that happens the `TransactionController` is locked.

I previously discussed future UX with @dan437 such as falling back to standard transaction while a smart transaction is polling, or display a more specific alert for this use case.

**Comment by seaona** [comment]
thank you for the explanation @matthewwalsh0 :heart:  I guess we can leave this to the Transactions team to decide on how to follow up on this

**Comment by Gudahtt** [comment]
Just to confirm @seaona , were you able to cancel the smart transaction when it was in this state? That was discussed when this feature was first integrated as an acceptance criteria, so that users would never be completely "stuck". I believe it was possible for the initial release to cancel smart transactions.

**Comment by dan437** [comment]
Hi @seaona, we have user stories to handle multiple submitted smart transactions in the future or to fall back to a standard transaction while a smart transaction is polling, as @matthewwalsh0 suggested, so I believe we can close this ticket for now.

**Comment by dbrans** [comment]
Closing based on @dan437's last comment
