### ISSUE TITLE
[Bug]: Quotes are not being fetched during the 'Send' transaction following a fresh installation

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24464]
### Describe the bug

Quotes are not being fetched during the 'Send' transaction following a fresh installation. On the second or third attempt quotes become available.

I do not know any reliable way to reproduce it yet. It doesn't happen often.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/17413f09-55d7-43cb-9f2c-761d217e6e0b

### Steps to reproduce

1. Install MetaMask extension
2. Start Send transaction
3. Select any tokens
4. Notice that quotes are unavailable

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ejwessel** [comment]
Inconsistent reproducibility. Deescalating from blocker.

**Comment by ejwessel** [comment]
<img width="3120" alt="Screenshot 2024-05-16 at 12 40 11" src="https://github.com/MetaMask/metamask-extension/assets/3590816/bfc499c3-fe6d-4769-9df1-2765b4fb1a07">
<img width="3120" alt="Screenshot 2024-05-16 at 13 12 40" src="https://github.com/MetaMask/metamask-extension/assets/3590816/00d0f8b6-adec-4d63-9e13-588505295342">

It looks like  an error field within the is `null`, however the logic looks for a string fails validation otherwise.
When the validation fails `undefined` is returned, this gives us 0 quotes within MM

**Comment by ejwessel** [comment]
https://github.com/MetaMask/metamask-extension/pull/24570

**Comment by hesterbruikman** [comment]
@ejwessel it looks like you had a PR that fixes this issue. Can this be closed?

**Comment by sleepytanya** [comment]
I haven't seen this behavior on two latest send+swap builds. It seems to be fixed.
