### ISSUE TITLE
[Internal Bug]: Send - Sending a tx breaks the wallet with error `ConfirmationInfoComponentMap [(intermediate value) is not a function`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24510]
### Describe the bug

With the feature flag `ENABLE_CONFIRMATION_REDESIGN` , whenever I start sending a tx, I see MM breaks with errors:
-  `Message: ConfirmationInfoComponentMap[(intermediate value)] is not a function`
Once this happens, even if I re-start the wallet, I see the error. The only way to recover from this state is restart the wallet and change networks before login in.

### Screenshots/Recordings

![Screenshot from 2024-05-14 09-19-53](https://github.com/MetaMask/metamask-extension/assets/54408225/7dd615d4-8b89-42b4-95ec-27a027b3976c)

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/367353f4-629c-4405-953d-b1adc11e7ab1)

https://github.com/MetaMask/metamask-extension/assets/54408225/591e4a9d-6978-4a40-a880-4e63839edf18

### Steps to reproduce

1. Build the wallet yarn dist or yarn start with the feature flag on ENABLE_CONFIRMATION_REDESIGN
2. Start a tx
3. After adding a recipient and amount, proceed to the next screen
4. See how MM breaks

### Version

develop: both MV3 and non- MV3 builds

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I've seen this is only affecting the Confirmation Redesign builds, so I've updated the labels and sev accordingly

**Comment by digiwand** [comment]
since `ENABLE_CONFIRMATION_REDESIGN` will be turned off in production I don't think this would be a sev1 and I don't think it'd be needed for v11.17.0. Redesign Signatures no longer live behind the `ENABLE_CONFIRMATION_REDESIGN` flag  cc: @bschorchit @seaona

**Comment by benjisclowder** [comment]
Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @jpuri

**Comment by benjisclowder** [comment]
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> What PR fixed the issue? Can you pinpoint the commit from which the issue originated? Write a short explanation of the technical cause of the bug How could we have avoided merging this bug? What would have had to be different about our code, tests or processes? 4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue? 4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue? 4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged? Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: [@jpuri](https://github.com/jpuri)

Hi, @jpuri  , if you're not able to conduct RCA on this issue, is there anyone you can assign this to? I would very much appreciate it. Thank you!
