### ISSUE TITLE
[Bug]: MM crashes during confirmations with some currencies 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#24558]
### Describe the bug

MM crashes if user selects a currency that is not supported by the token api and starts a transaction that has simulation.

### Expected behavior

Not crashing and displaying "Not available" if we're not able to get a conversion. 

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/cf423207-85d5-4a98-91ec-652c71c3b9ba)

### Steps to reproduce

1. Go to Settings > General 
2. Change your currency to Storj
3. Start a send transaction on Ethereum with any value
4. Notice MM crash

The only way to recover from the crash is to disable and re-enable MM and changing the network before unlocking it otherwise you'll consistently unlock it and arrive at the crashed screen

### Version

11.15.2

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by benjisclowder** [comment]
Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @OGPoyraz

**Comment by OGPoyraz** [comment]
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> What PR fixed the issue? Can you pinpoint the commit from which the issue originated? Write a short explanation of the technical cause of the bug How could we have avoided merging this bug? What would have had to be different about our code, tests or processes? 4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue? 4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue? 4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged? Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: @OGPoyraz

What PR fixed the issue?
https://github.com/MetaMask/metamask-extension/pull/24563

Can you pinpoint the commit from which the issue originated?
This was an day 1 bug for simulations introduced in https://github.com/MetaMask/metamask-extension/pull/23529

Write a short explanation of the technical cause of the bug
Some currencies that we offer in the settings are not a valid ISO 4217, hence the formatter was throwing an error. For solution we added a fallback for unknown currency formats to render it `${amount} ${currency}` format.

How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
Unsupported currency unit test could've been added in to formatter. 

4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
TS enum with known currencies could be added to the MM code https://gist.github.com/PoOwAa/e189ee1c4bfec4dffe979c2c1b2c30f9
But it would be overkill so that's why we added callback.

@benjisclowder fyi
