### ISSUE TITLE
[Bug]: Simulation Details reports incorrect ERC20 amount if an NFT is minted

### ISSUE THREAD

**Issue by dbrans** [MetaMask/metamask-extension#24586]
### Describe the bug

Simulation Details reports incorrect ERC20 amount if an NFT is minted.
Reported here: https://community.metamask.io/t/unlock-protocol-support/28955

<img width="622" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/507015/e4e1f39d-5924-43d3-bf94-092784c3b321">

### Steps to reproduce

Have 66 USDC on Optimism and go through purchase flow on https://app.unlock-protocol.com/event/mcon-iii

### Version

Develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Fixed - when NFT is minted the simulation displays correct amount:
<img width="362" alt="Screenshot 2024-05-22 at 10 38 05" src="https://github.com/MetaMask/metamask-extension/assets/104780023/1382a3cb-b9f8-4b67-8444-b68173e2eaa0">

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @dbrans
