### ISSUE TITLE
[Bug]: Sentry 429 (Too Many Requests)  in 11.16.1 version

### ISSUE THREAD

**Issue by Ta-Tung** [MetaMask/metamask-extension#24859]
### Describe the bug

[Bug]: Sentry 429 (Too Many Requests)  in the 11.16.1 version
When I try to send a NFT. The wallet is thrown this error. The loading modal is not stop.

I use Mac M1 and Chrome.

Somebody has a solution to fix the bug.

![image](https://github.com/MetaMask/metamask-extension/assets/46585748/7785bc95-f6b2-4967-a063-df8e84ef28b4)

### Steps to reproduce

1. Open MetaMask in Chrome
2. Chose network
3. Click the NFT item
4. Click to send

### Version

11.16.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @Ta-Tung , can you please tell us more about what network you're using and what NFT collection this is?

**Comment by dbrans** [comment]
Hi @Ta-Tung I was able to reproduce this in a wallet with a lot of (~20) different ERC20 tokens and NFTs. Is that the case for you? Could you see if this still happens in a wallet with fewer NFTs?

**Comment by dbrans** [comment]
Let me explain what's happening with a wallet containing around 20 different ERC20 tokens and NFTs. I noticed this issue on v11.15.6, v11.16.0, and v11.16.1 using the [Orange Fox test account](https://etherscan.io/address/0x2990079bcdee240329a520d2444386fc119da21a) on Mainnet.

When displaying a list of tokens (like on the home page or in the asset picker), up to 3 calls are made to Infura for each token to get its details via `getTokenStandardAndDetails`. These responses aren't cached, so every time the asset picker is opened, dozens of calls are made—three times the number of tokens in the wallet.

If a user has many tokens, the server may start rate-limiting their IP address. While this isn't catastrophic for the token list (it just looks odd), it causes a bigger problem when a token is selected from the asset picker. The send flow makes [one more call to `getTokenStandardAndDetails`](https://github.com/MetaMask/metamask-extension/blob/797c5f/ui/ducks/send/send.js#L2582). This call is awaited but not wrapped in a try/catch, so if it fails due to rate limiting, the extension hangs.

**Comment by gauthierpetetin** [comment]
Interesting, thanks for the explanation!
So the recommended solution would be to setup a cache mechanism for list of tokens?
