### ISSUE TITLE
[UAT] Add Token Ux Suggestions

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/metamask-extension#2513]
When adding tokens:
- There is no way to remove tracking of a token without owning some of the token. May want to consider adding a way to remove tracking of tokens the user doesn't own any of.
- When attempting to add an already-added token, if it exists in `eth-contract-metadata`, it is greyed out. Some users may be confused by this if they forgot they added it already: it's not clear what disabled state means. May want to consider adding a tooltip or disabled text, along with the state.

![add-custom-token-2](https://user-images.githubusercontent.com/8230144/32205954-89560a56-bdaf-11e7-9c03-1ca36317db78.gif)

/cc @chikeichan

**Comment by cjeria** [comment]
@sdtsui 
> There is no way to remove tracking of a token without owning some of the token. May want to consider adding a way to remove tracking of tokens the user doesn't own any of.

The expected behavior after adding a token (even if I don't own any of said token) is that I'd like to at least see the token appear in my list of tokens with a 0 balance. 
If I have a 0 balance and I don't want to see the token any longer, let's show a "•••" with the option to remove the token from the list. 

![image](https://user-images.githubusercontent.com/597770/32479627-957b2db2-c33f-11e7-815e-787896d72369.png)


> When attempting to add an already-added token, if it exists in eth-contract-metadata, it is greyed out. Some users may be confused by this if they forgot they added it already: it's not clear what disabled state means. May want to consider adding a tooltip or disabled text, along with the state.

I see there's a form validation message that appears when trying to add an already added token.
![image](https://user-images.githubusercontent.com/597770/32479702-fc34f11e-c33f-11e7-9cb1-9f4f5482236c.png)

I agree there should be a better indication or message on the token that has already been added in the add token screen. I'll think of some options here for where to put this message.
