### ISSUE TITLE
[Bug]: Can not access wallet after unlock

### ISSUE THREAD

**Issue by legobeat** [MetaMask/metamask-extension#25256]
### Describe the bug

After unlocking the wallet and dismissing the call-to-action for enabling token autodetection, the wallet UI is perpetually blocked behind a loading-spinner.

### Expected behavior

Can interact with wallet UI

### Screenshots/Recordings

![scrot1-2](https://github.com/MetaMask/metamask-extension/assets/109787230/3b3b3c28-2ec6-4b08-af45-09206499dd5a)
![scrot2-2](https://github.com/MetaMask/metamask-extension/assets/109787230/f9e78615-b163-45f7-81f2-6c274983dda8)

### Steps to reproduce

1. Build: `rm -rf dist && yarn && yarn build:dev dev --build-type main --lockdown false --snow false --apply-lavamoat false`
2. Load build in Firefox
3. Unlock wallet
4. Dismiss token-autodetection modal

### Version

develop

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Additional context

Reverting #24281 makes the UI load as expected and resolves the issue.

### Severity

- Makes wallet completely inaccessible

**Comment by darkwing** [comment]
I've just tried this and after dismissing the modal, I cannot get past the seed phrase reminder:

https://github.com/MetaMask/metamask-extension/assets/46655/f890157d-5b5d-4043-85fa-6690fbcc3bcb

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

What PR fixed the issue?
Can you pinpoint the commit from which the issue originated?
Write a short explanation of the technical cause of the bug
How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @darkwing
