### ISSUE TITLE
[Bug]: Attempt to submit another transaction while having transaction in 'Pending' state, Smart Transactions toggle is ON 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25349]
### Describe the bug

I have limited knowledge around Smart Transactions feature and expected behavior so I will just write down steps.

When attempting to initiate a new transaction while another is in a 'Pending' state, with the Smart Transactions feature enabled, a series of chaotic behaviors have been observed:

1. A transaction is set to 'Pending' state using low gas for a direct **ETH->ETH** send (**nonce 1579**). 
2. Another direct send **ETH->ETH** transaction is created.
3. A red warning on the confirmation screen indicates 'A previous tx is still being signed or submitted,' and the 'Confirm' button is disabled.
4. After rejection and creation of a new transaction (**ETH->USDT**), the 'Confirm' button becomes available without warnings.
5. Clicking 'Confirm' creates 'Unapproved' transaction.
6. The user can edit recipient and destination token fields for the 'Unapproved' transaction, but the 'Confirm' button is inactive, and rejection does not function.
7. Modifying the 'Unapproved' transaction activates the 'Confirm' button, but clicking it generates another 'Unapproved' transaction.
8. I created 1 'Pending' and 3 'Unapproved' transactions. Once the transactions were confirmed, only two Failed transactions can be seen within the Activity tab:  **nonce 1579** and **1580**, marked as **ETH->USDC**. Popup notifying that the transaction was cancelled was displayed after some time.
9. Notice that the popup and Smart Transactions screen are only displayed for the first and for the last transaction.

Related bug: https://github.com/MetaMask/metamask-extension/issues/25356
### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/e59a7274-5c17-44cf-b242-004bcbf73e7f

https://github.com/MetaMask/metamask-extension/assets/104780023/5845bbc3-5763-426a-9b24-45ba3adeaa71

<img width="546" alt="Screenshot 2024-06-14 at 23 43 53" src="https://github.com/MetaMask/metamask-extension/assets/104780023/f8e21df4-1204-4d77-995c-9405515921ae">

<img width="332" alt="Screenshot 2024-06-14 at 23 43 25" src="https://github.com/MetaMask/metamask-extension/assets/104780023/014b1ab3-8f5f-4cad-afab-cfe616b05ea2">

<img width="331" alt="Screenshot 2024-06-14 at 23 44 10" src="https://github.com/MetaMask/metamask-extension/assets/104780023/eacaa13e-4dc3-4654-a744-e2b7c1b8cf81">

<img width="516" alt="Screenshot 2024-06-14 at 23 29 23" src="https://github.com/MetaMask/metamask-extension/assets/104780023/70851a53-6281-41b7-ada8-96e7be5deb1e">

<img width="515" alt="Screenshot 2024-06-14 at 23 29 09" src="https://github.com/MetaMask/metamask-extension/assets/104780023/b31f71d0-1c10-4c5f-9ef0-7465afeee071">

<img width="517" alt="Screenshot 2024-06-14 at 23 30 05" src="https://github.com/MetaMask/metamask-extension/assets/104780023/545cdd80-b7ff-431a-b955-202dc0ba50ba">

### Steps to reproduce

1. See the description

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
**Current behavior**
- Banner 'Transaction still pending to be signed or submitted' does not appear after a transaction has been rejected because a stx was still in progress
- Confirm button is enabled after a transaction has been rejected because a stx was still in progress


**Expected behavior**
- Banner 'Transaction still pending to be signed or submitted' should appear until original (stx) transaction has been submitted. Regardless of whether the user rejected a previous confirmation request
- Confirm button should be disabled until original transaction is submitted.

**Comment by BZahory** [comment]
Resolved **part of this** in #25468; we now prevent subsequent transactions from the send flow when an STX is pending. However, as @sleepytanya pointed out, subsequent transactions are still able to be submitted through dapp, which results in an infinite loading state.

**Comment by sleepytanya** [comment]
The issue is present in [the latest v12.0.0 build ](https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2196458627)

Multiple transactions can be created while the STX mode is ON which results in 'Unapproved' transactions. 'Unapproved' transactions can be modified.

1. Have STX transaction in 'Pending' state
2. Start Swap transaction, confirm swap
3. See 2 transactions within the Activity list
4. Transaction in 'Unapproved state' can be edited (the token and the recipient address can be changed), but can't be rejected
5. Select another token, click 'Confirm'
6. Notice how the original swap tx 'Swap BAT to SUSHI' changed to 'Send USDC'



https://github.com/MetaMask/metamask-extension/assets/104780023/59898811-47cc-4f2e-9a2b-da1a0c94ab07

**Comment by sleepytanya** [comment]
[v12.0.0 build ](https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2198759615)
 
The issue is present:


https://github.com/MetaMask/metamask-extension/assets/104780023/366d12a6-acc6-440c-8608-db82fda782d7

**Comment by danjm** [comment]
@sleepytanya can you test again on the latest build https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2198759615

**Comment by sleepytanya** [comment]
On the latest v12.0.0 branch queueing is disabled if there is STX in Pending state:


https://github.com/MetaMask/metamask-extension/assets/104780023/0b4c4e98-2a96-4dfd-a90e-a8d67dbca7f1

**Comment by forest-diggs-consensys** [comment]
Thanks @sleepytanya - this is expected behavior for now 👍

**Comment by sleepytanya** [comment]
Fixed by:
 https://github.com/MetaMask/metamask-extension/pull/25478 
https://github.com/MetaMask/metamask-extension/pull/25510

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

**Tagging eng. who added the fix:** @BZahory
