### ISSUE TITLE
[Bug]: Multichain - `Cannot destructure property 'balance' of 'K[Z]' as it is undefined.` and  `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25406]
### Describe the bug

Triggering a transaction on one chain, and without approving it, triggering a signature in another chain, whenever I reject/accept the first transaction, MM breaks with the error `Cannot destructure property 'balance' of 'K[Z]' as it is undefined.`

I've also seen it fail with this other message `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/08d09f66-7072-4847-823b-12c8d76d23aa

https://github.com/MetaMask/metamask-extension/assets/54408225/8a14acda-5864-4da9-aa3c-a48327121142

### Steps to reproduce

1. Connect to the test dapp with Sepolia
2. Connect to pancakeswap with Ethereum
3. Trigger a swap in pancakeswap https://pancakeswap.finance/swap?chain=eth
4. Without accepting/rejecting, go to the test dapp and trigger a signature
5. Reject the first tx
6. See how MM breaks

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
Will continue trying to reproduce but I had no issue with this case but will keep trying:


https://github.com/MetaMask/metamask-extension/assets/46655/90b5bc17-069c-4840-9277-460e9174628c

**Comment by darkwing** [comment]
I looked at the Sign In With Ethereum confirmation and the balance on the top-right is the only balance on the screen, so that piece needs to be the root cause:

<img width="357" alt="SCR-20240619-ndks" src="https://github.com/MetaMask/metamask-extension/assets/46655/7f7745d6-9a27-4d15-bb78-43b93aabad77">

**Comment by darkwing** [comment]
The actual error occurs in: `ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js` are accepting or rejecting the first swap transaction.  The error line is:

```
// FYI: This line was introduced 3 years ago...
const { balance } = accounts[fromAddress];
```

The problem is that `fromAddress` becomes `undefined` after (in this case) rejecting:

<img width="1285" alt="SCR-20240619-nljv" src="https://github.com/MetaMask/metamask-extension/assets/46655/bf117d5c-7cca-4efd-97e9-8c529dace657">

The `from` address comes from:

```
const {
    from: fromAddress,
    to: txParamsToAddress,
    gasPrice,
    gas: gasLimit,
    value: amount,
    data,
  } = (transaction && transaction.txParams) || txParams;
```

**Comment by dan437** [comment]
@matthewwalsh0 can you or someone from the Confirmations team have a look?

**Comment by jiexi** [comment]
Was able to reproduce `Message: Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

**Comment by sleepytanya** [comment]
[I think this is ](https://github.com/MetaMask/metamask-extension/issues/25397) the same bug? With different errors. We could combine them into one.

**Comment by sleepytanya** [comment]
<img width="751" alt="Screenshot 2024-06-24 at 11 47 34" src="https://github.com/MetaMask/metamask-extension/assets/104780023/50091908-8166-4a54-826c-493a8e27a9ee">

**Comment by digiwand** [comment]
Hi @benjisclowder,

1. What PR fixed the issue?
https://github.com/MetaMask/metamask-extension/pull/25506

2. Can you pinpoint the commit from which the issue originated?
Unknown

3. Write a short explanation of the technical cause of the bug
> In confirm-transaction-base.container.js, while the transaction is switching, the component may be in a state without transaction data. It is a race-condition.

4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
I think we are missing e2e tests. 
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
I don't think we are supporting multiple dapps in our e2e tests.
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
