### ISSUE TITLE
[Bug]: Notifications - Some accounts are loading and get the error `Failed to check accounts presence Error: Exceeds maximum number of requests waiting to be resolved, please try again.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25749]
### Describe the bug

Whenever I enable the notifications, when I go to the notifications settings, I see how some of the accounts remain with the loading spinner forever, and I can see this error in the background console `Failed to check accounts presence Error: Exceeds maximum number of requests waiting to be resolved, please try again.`

### Screenshots/Recordings

![Screenshot from 2024-07-10 18-12-01](https://github.com/MetaMask/metamask-extension/assets/54408225/73198172-1cfb-4eb5-99fe-ea3a41f819c4)

https://github.com/MetaMask/metamask-extension/assets/54408225/3706e6b4-ac8a-4d13-bc69-6cbba77a1110

### Steps to reproduce

1. Create several accounts
2. Enable notifications
3. Go to notification settings
4. See last accounts are forever loading and there is the background error

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Confirming the same behavior on v12.1.0:


https://github.com/MetaMask/metamask-extension/assets/104780023/9f2a2edf-5358-4ca8-b62e-f9ea6c051db8

<img width="612" alt="Screenshot 2024-07-10 at 18 15 55" src="https://github.com/MetaMask/metamask-extension/assets/104780023/ed120230-8d1a-4ff8-90ed-3fe1b4533a48">

**Comment by Prithpal-Sooriya** [comment]
TY. Jira Ticket created [here](https://consensyssoftware.atlassian.net/browse/NOTIFY-847). Our team will investigate.

**Comment by Prithpal-Sooriya** [comment]
This is interesting. Seems to come from queued requests to the snap controller. Our team will better manage/cache responses back from the pre-installed snap we are using (we don't need to realistically call this every time)

**Comment by sleepytanya** [comment]
v12.0.0 beta

<img width="687" alt="Screenshot 2024-07-15 at 21 36 39" src="https://github.com/user-attachments/assets/78f04412-8bd2-4b1e-a345-d1b00abc0dc6">

**Comment by sleepytanya** [comment]
I think it's the same bug because I see the same console messages when Notifications list appears empty:



https://github.com/user-attachments/assets/9659cbb4-bdc5-41a3-ba11-7b84376876c8


<img width="473" alt="Screenshot 2024-07-16 at 23 52 56" src="https://github.com/user-attachments/assets/be174bad-409d-43db-85d1-7944fa151439">


<img width="474" alt="Screenshot 2024-07-16 at 23 54 20" src="https://github.com/user-attachments/assets/66d6aac1-bd9f-469f-935d-ee193cf56de6">

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @Prithpal-Sooriya

**Comment by Prithpal-Sooriya** [comment]
@benjisclowder 

> 1. What PR fixed the issue?

https://github.com/MetaMask/metamask-extension/pull/25946

> 2. Can you pinpoint the commit from which the issue originated?

This is hard to pinpoint, as this was a new feature, not an existing feature.

> 3. Write a short explanation of the technical cause of the bug

Commit for the fix: https://github.com/MetaMask/metamask-extension/pull/25946/commits/5f76720a162031755ae1e8921f5c366f804b6574

When a user has many accounts, we were making many API calls. Also we were making many Snap requests. The snap requests especially were being queued and then failing. Reducing this to only make 1 call at the page level and caching resolved this issue.

> 4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?

We should have tested with multiple accounts (10+ addresses). We never hit this snap request issue during development.

> 4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?

Unit tests were covered, but the Snap Environment was mocked.

Integration tests (using the snap environment), or E2E may have spotted this - however it was a flakey issue.

More manual testing (at least during development) may have raised this early too.

> 4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?

Not particularly, most of the knowledge base around notifications were known.
The only unknown was the request queue the Snap Controller contains.

> 4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

N/A
