### ISSUE TITLE
Unable to paste two pieces of info without loosing the other

### ISSUE THREAD

**Issue by istmmi** [MetaMask/metamask-extension#2578]
Hello,
While participating in an ICO, I needed to paste the target address to send the funds to and some data. Each time I clicked anywhere else to copy my data, the Metamask plugin was hiding AND clearing the form, so I ended up concatenating the two pieces of data together and pasting the same piece of info in the fields, while deleting manually what wasn't needed. Frankly, it was hilarious :))

Please make a combination of the following: 
- make a toggle button to keep the Metamask window open
OR
- don't clear the form if the window hides and we're in the middle of a transaction

Thank you!
Istvan

**Comment by danfinlay** [comment]
We're aware of this issue, it seems to be a fundamental problem with using extension "action views" for form input. Soon we're going to add the ability to enter this form in a full tab, which will solve this issue.

Also, the ICO you're participating in could easily solve this issue for you by not requiring you to enter any `data` in the `send` screen, and instead use [the web3 API](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md) to allow their users to contribute with a simple on-page button. Please let them know this.

Closing because we're currently addressing this in all the ways we're able.

**Comment by danfinlay** [comment]
A bonus workaround in the meanwhile is that you can open MetaMask in a tab today by visiting `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html`.

**Comment by istmmi** [comment]
Hey,
Thank you! That was a fast reply and those are good solutions. Hats off to
you!

Cheers

On Nov 15, 2017 01:48, "Dan Finlay" <notifications@github.com> wrote:

Closed #2578 <https://github.com/MetaMask/metamask-extension/issues/2578>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/2578#event-1342019053>,
or mute the thread
