### ISSUE TITLE
Circle ci: e2e test improvement for retrying failed develop branch

### ISSUE THREAD

**Issue by DDDDDanica** [MetaMask/metamask-extension#25955]
Following the thread [here](https://consensys.slack.com/archives/CTQAGKY5V/p1721315695855259?thread_ts=1721038786.687959&cid=CTQAGKY5V) and suggested by @Gudahtt:

> Retry failed `develop` workflows, and alert immediately if `develop` is still broken after retries

**Comment by seaona** [comment]
About re-run failed tests, I've seen that there was a question in [circle ci forum ](https://discuss.circleci.com/t/rerun-failed-tests-with-api/51387/3) if this was supported in their API and they replied the following:

```
Hi [@unickq](https://discuss.circleci.com/u/unickq) tnx for reaching out! At this moment we don’t provide this functionality in our API. It’s being discussed internally though.
```

They do support an option for re-run jobs from failed, but this will re-run the complete job, meaning that if there is 1 failure in an e2e job which takes ~10mins, we'll re-run the complete job again taking another 10mins. Compared to what we do now manually, where we just re-run the failed test, which usually takes just 1-2 more minutes.

Not sure if the ci increase is worth it.
I'm personally fine re-running, it's a way for me to see which are the most recent failures/flakiness, but I understand not everyone might agree / be able to do so.

What do you think?

**Comment by Gudahtt** [comment]
I don't see the added costs here as significant. Even if `develop` fails fairly often (which it shouldn't), the number of workflows will be quite small compared to our total.

Our goal here is twofold: to determine whether failures on `develop` are persistent, and to get more insight for our "Flaky test" report. Re-running the entirety of any failed workflow accomplishes both (it provides even more evidence of flaky tests than "Rerun failed tests" would), so it seems more than suitable for this problem.

The consequences of choosing not to automate this are significant; this has been a significant burden for myself, Desi, and others who have taken on the work of triggering these re-runs manually. And we fairly often have poor response time to `develop` failures due to the sporadic timing of these re-runs.

**Comment by hjetpoluru** [comment]
I would prefer --> `OPT2: re-run from failed all jobs including the e2e` it would be easy to track.
