### ISSUE TITLE
Outstream on 'end' callback, in `setupControllerConnection` of MM controller, is not called on UI close

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#26002]
This problem was discovered when investigating https://github.com/MetaMask/metamask-extension/issues/25951

In `metamask-controller.js` there is a method `setupControllerConnection`. It sets up a listener for the end of the outstream like this:
```
    outStream.on('end', () => {
      this.activeControllerConnections -= 1;
      this.emit(
        'controllerConnectionChanged',
        this.activeControllerConnections,
      );
      this.removeListener('update', handleUpdate);
    });
```

As of https://github.com/MetaMask/metamask-extension/pull/24533, this callback is not called when the UI is closed.

To repro:
1. Checkout the commit of that PR 72d4b5265c
2. Add a debugger or console.log inside the aforementioned callback
3. `yarn start` and then install and onboard
4. Close the UI. The debugger or console log will not be hit

But if those steps are repeated on the prior commit, 928d30afcd, the debugger or console.log will be hit

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @danjm
