### ISSUE TITLE
[Bug]: Confusing popup / badge behavior (develop and latest 12.0.0 build)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26064]
### Describe the bug

1. There is one `Pending` transaction in the Activity list. 
2. After reloading / turning the extension OFF->ON popup appears automatically
3. Blue badge appears (I'm not sure if it should be shown because it is not an `Unapproved` transaction, it was confirmed by a user) 
4. Counter shows 3
5. After unlocking the wallet the blue badge disappears 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/beccadf3-3e54-4b02-9191-9580c7b75d9d

### Steps to reproduce

1. Have a transaction in `Pending` state
2. Reload the extension
3. Notice that popup opens automatically and blue badge is shown on MetaMask icon

### Detection stage

In production (default)

### Version

v12.0.0 beta, develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
@sleepytanya do you have snaps installed? Some snaps was causing this exact same issue in the past

**Comment by sleepytanya** [comment]
@bschorchit No snaps!

**Comment by Prithpal-Sooriya** [comment]
V12.0.0 does not have any notification related changes to the fox counter (this is only in v12.1.0). Happy to keep the `team-notifications` label or remove it.

**Comment by Prithpal-Sooriya** [comment]
Ok, our team has done some digging, this is semi-related to us.

> @sleepytanya do you have snaps installed? Some snaps was causing this exact same issue in the past
Although a user does not have a snap installed, they do have a pre-installed snap in the wallet.

It turns out that when the wallet is locked, we try to make a snap call which gets queued. For some odd reason this increments the lock screen confirmation count.

Ideally - we can try discussing with the snaps team if pre-installed snaps can be permitted to be called when the wallet is locked & also try to figure out the underlying issues with the confirmations counter.

Otherwise our team can add a hotfix when calling this pre-installed snap.

**Comment by Prithpal-Sooriya** [comment]
I will be proposing 2 fixes:
1. A confirmations count fix - ensure that the confirmation count (specifically the unlock request count) is bounded, so does not explode - and prevent seeing 1000+ on the confirmations counter.
2. A pre-installed snaps fix - where we add some checks before we call the preinstalled snaps (involves some additional logic/checks on controllers too)

**Comment by Prithpal-Sooriya** [comment]
Re-opening until the cherry-pick is merged.

**Comment by Prithpal-Sooriya** [comment]
This has been merged into v12.0.0
