### ISSUE TITLE
rpc error with payload

### ISSUE THREAD

**Issue by Bubbachuck** [MetaMask/metamask-extension#2676]
I use metamask on my computer 1 first, then I use metamask on my computer 2. After that, I use my computer 1 again, then this error happens and cannot recover. How to recover it to normal?

**Comment by myetherdomain** [comment]
I have the same error with metamask. Have been trying to solve this all day, but still not working. 
Isn't there a simple way to just reset your account?

**Comment by Bubbachuck** [comment]
I close Google Chrome and open Brave, then install metamask in Brave.
Finally, it can work.

2017-12-07 3:34 GMT+08:00 myetherdomain <notifications@github.com>:

**Comment by Jezren** [comment]
hi sir what is Brave?..I have same problem with my metamask...But Im not familiar with Brave..thank you..

**Comment by Bubbachuck** [comment]
It is another Browser. https://www.brave.com/

2017-12-07 16:12 GMT+08:00 Jezren <notifications@github.com>:

**Comment by myetherdomain** [comment]
I removed metamask extionsion from chrome, and reinstalled it. Unfortunately not the solution :( 
It's really bad that Metamask is not functioning well. because of these errors you cannot reveal bids, which means you loose your money which you paid for the bid. 
I hope metamask will take this seriously and work on better support. Simply, make it possible to restart metamask so that your account is clean and works good again, or make it possible to at least close a broken transaction and you do not get stuck. 

My account still has the same problems after 5 days. This way, it's no fun to use metamask.

**Comment by danfinlay** [comment]
These failures were related to the great kitty backlog of 2017. This issue should be mostly mitigated now, let us know if you have these problems again.

**Comment by wenshui** [comment]
I can't buy a kitty because it had so many RPC error.
Please solve it as soon as you can.
