### ISSUE TITLE
Error when peform transaction for cryptokitties

### ISSUE THREAD

**Issue by kripkrip** [MetaMask/metamask-extension#2689]

**Comment by kripkrip** [comment]
![image](https://user-images.githubusercontent.com/34336123/33707603-7ed2999a-db6a-11e7-9688-1ec47b214f26.png)

**Comment by sevku** [comment]
same issue

**Comment by enjikaka** [comment]
Same for me. Always getting "transaction underpriced" or a complaint on gas too low. Shouldn't MetaMask set a correct gas price and gas amount for me when attempting to make a transaction?

**Comment by brandoncurtis** [comment]
The network is under heavy load, and a higher gas cost than usual is needed for transactions to go through.  MetaMask relies on some backend infrastructure for gas price estimation, and due to a combination of factors these estimates have lately been too low (some of my other projects, which run their own backend node and rely on that node for gas pricing, have also been failing lately).

Until the MetaMask UI/UX are improved and the congestion issues are remedied, you can use https://etherscan.io/ to check your balances and pending transactions and https://ethgasstation.info/ for recommended gas prices based on realtime network traffic.

**Comment by danfinlay** [comment]
These failures were related to the great kitty backlog of 2017. This issue should be mostly mitigated now, let us know if you have these problems again.

**Comment by heybud1** [comment]
i cant even transfer ether back to my wallet from that sneaky little fox.  Very appropriate logo!

**Comment by danfinlay** [comment]
@heybud1 if you're having trouble using MetaMask, please email support@metamask.io

You can always export your ethereum private keys from MetaMask, so even if you can't figure out how to use MetaMask, you can always take your accounts elsewhere.
