### ISSUE TITLE
Unable to import JSON file in Firefox

### ISSUE THREAD

**Issue by theotherp** [MetaMask/metamask-extension#2722]
The same issue as described here: #1136

Unfortunately the workaround doesn't work on Firefox 

Running FF 57 on Windows 10.

**Comment by danfinlay** [comment]
Long term solution:
- Allow importing from new tab

Short term solution:
- Document this workaround in a non-closed issue.

**Comment by danfinlay** [comment]
This is fixed in the new UI, coming very soon, by allowing opening in new tab.

**Comment by tmashuang** [comment]
For Firefox the workaround to navigate to Firefox's MetaMask tab would be to:
- While MetaMask is open, right click anywhere in the application and click `View Page Source`
- This will open the html source, in the URL bar remove `view-source:`

**Comment by davidhinkley** [comment]
### This is the only way that works consistently in any browser on any platform:
1. Click on Metamask fox icon 
2. Click on the 3 vertical dots
3. Select Expand View
4. In the page that opens/popsup click on the circle in the top-right beside the network (usually Ethereum Mainnet)
5. Click "Import Account"
6. Where it says "Select Type", click on the words "Private Key" (on the downward facing arrow)
7. Select "JSON File" from the drop-down menu
8. Click the "Browse..." button find the file and double-click it (or otherwise select it and open it)
9. In the box below it, type the password/phrase/code you created when you exported the json file to your computer
10. Then, below that, click on the "Import" but and wait until it's complete
11. Close the page and you will now see that Metamask now uses "Account 2" which you just imported.

*To switch back to the original Metamask account, click the circle again (called the "My Accounts" menu) and simply select "Account 1"

**Comment by davidhinkley** [comment]
> 
> 
> Solution: https://github.com/MetaMask/faq/issues/38#issuecomment-345857245

**_This link is broken._**
