### ISSUE TITLE
Kovan block numbers behaving strangely

### ISSUE THREAD

**Issue by nt85** [MetaMask/metamask-extension#2728]
OS: macOS High Sierra Version 10.13.1 
Chrome: Version 63.0.3239.84
Metamask: 3.13.2

If you observe the block number, as reported by metamask, for Kovan network (all the other networks appear to be fine), they jump around strangely.

Here is a code snippet to reproduce the problem. 
```
window.addEventListener('load', function()
{
    window.web3 = new window.Web3(window.web3.currentProvider);
    var getBlock = function()
    {
        setTimeout(function()
        {
            window.web3.eth.getBlockNumber(function(err, block)
            {
                console.log(block);
            });
            getBlock();
        }, 5000);
    };
    getBlock();
});
```
Here is some sample output:
```
4716916
5036732
4973641
4716916
5036740
4973641
5036742
4716916
5036749
4973641
4716916
5036757
4716916
```
The correct block numbers (according to https://authorities.kovan.network/) are the 5,000,000 blocks. The other blocks make no sense?

Other information: if I setup my parity node to connect to Kovan, and then get metamask to connect to my local node. Everything works fine.

**Comment by brandoncurtis** [comment]
As you discovered, the problem was with the public Ethereum nodes run by infura.io that MetaMask connects to in order to access the Ethereum network.  The public infrastructure has been under record load this month and has occasionally failed.

The weird results you were seeing are due to the Infura architecture—a whole bunch of Ethereum nodes behind a "non-sticky" load balancer.  When your MetaMask client sends a request to Infura, the load balancer routes the request to an available node and makes no effort to route repeated requests to the _same_ node.  So, if one or more nodes are improperly synchronized or otherwise faulty, a series of requests will occasionally hit the bad nodes, resulting in transient errors in the reported state of the network.  This can result in fluctuating block numbers like you saw, or even fluctuating balances and contract states or incorrect nonces on newly-sent transactions.

Infura could fix this by automatically pulling faulty nodes out of rotation.

Barring that... this can be fixed by changing your network provider in the MetaMask network selection dropdown, either by finding another public Ethereum node and putting its address under "Custom RPC" (unfortunately there aren't many public node providers other than Infura), or by running your own Ethereum node locally using [Parity](https://www.parity.io/) or Geth/[Mist Browser](https://github.com/ethereum/mist/releases) and selecting "Localhost".  It takes some time (hours to days) to initially sync an Ethereum node, and depending on the type of node that you run (Light, Fast, Archive) the Ethereum blockchain will take up 1 GB (a Geth light node) to 500+ GB (a Parity full archive node) of hard drive space.

**Comment by nt85** [comment]
This makes sense. Thank you for the explanation
