### ISSUE TITLE
Chrome extension will not open

### ISSUE THREAD

**Issue by BernsteinB** [MetaMask/metamask-extension#2734]
*  Expected Behavior: Opening the extension when clicking on the icon
  *  Actual Behavior: Extension does not open when I click on the icon
  *  Browser Used: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
  *  Operating System Used: OSX Yosemite 10.10.5 (14F27)

 
From Extensions:

background.js:57972 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:57972
background.js:57978 console.trace
EventEmitter.addListener @ background.js:57978

![image](https://user-images.githubusercontent.com/34486968/33900350-c819bef2-df76-11e7-8955-1fffdc5d2152.png)

**Comment by owocki** [comment]
I am seeing the above also.

**Comment by owocki** [comment]
related: https://github.com/MetaMask/metamask-extension/issues/2736

**Comment by BernsteinB** [comment]
Also: did not receive an email with instructions to recover my password when requested on the Metamask website.

**Comment by brandoncurtis** [comment]
From your console logs, it looks like the problem was with [Infura](https://infura.io), a public Ethereum network provider that MetaMask uses to connect to the Ethereum network.  The public infrastructure has been overwhelmed with unprecedented traffic this month, and it looks like you were getting a [502 Bad Gateway](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) error response from the Infura server.  Are you still seeing this problem?

This can be fixed by changing your network provider in the MetaMask network selection dropdown, either by finding another public Ethereum node and putting its address under "Custom RPC" (unfortunately there aren't many public node providers other than Infura), or by running your own Ethereum node locally using [Parity](https://www.parity.io/) or Geth/[Mist Browser](https://github.com/ethereum/mist/releases) and selecting "Localhost".  It takes some time (hours to days) to initially sync an Ethereum node, and depending on the type of node that you run (Light, Fast, Archive) the Ethereum blockchain will take up 1 GB (a Geth light node) to 500+ GB (a Parity full archive node) of hard drive space.

**Comment by brandoncurtis** [comment]
@BernsteinB all MetaMask data is stored locally in your browser, so there is no "MetaMask wallet server" that can perform a password reset for you.  The "seed phrase" is the important piece of information used to generate your Ethereum addresses, and backing up your seed phrase is necessary and sufficient for recovering your account—you can set a new password after you import the seed phrase into MetaMask or another BIP-39 compatible Ethereum wallet.

If you have MetaMask installed and you know the password but you haven't backed up the seed phrase, you can reveal if by logging into MetaMask with your password and going to **Settings → Reveal Seed Words**.

Just knowing the password and account address (e.g. 0xf3b3d10dd712b7eb4bf300f70e160e0e0ee483ba) is insufficient to regain access to the funds at that address—you need a backup of the seed phrase or a backup of that particular address's private key.

In the future, please open a new issue if you question is unrelated to the current issue :)

**Comment by danfinlay** [comment]
I agree this was probably Infura being overwhelmed. We're addressing this in #2736 and #2552, closing for now as a duplicate.

To work around in the future, run a local node.

**Comment by BernsteinB** [comment]
Thank you.

FYI: The only way I have managed to get the pop-up to be visible is by right-clicking "Inspect Popup".

![image](https://user-images.githubusercontent.com/34486968/34145618-8f7911d2-e49f-11e7-9c3a-d678a6f80481.png)
