### ISSUE TITLE
Provide way for users to bypass phishing warning

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2784]
Obviously it should be hard to do, but some users are pros and know what they're doing.

Example: One user edited their local DNS to resolve etherdelta to the correct IP, so even when the DNS was hijacked, they wanted their resolution respected.

**Comment by 10a7** [comment]
> some users are pros and know what they're doing

Hard to do should be *really* hard to do. Users will just get socially engineered to following the override steps if Metamask puts this into the UI, so this may become a new attack vector on the plugin. [Self-XSS](https://en.wikipedia.org/wiki/Self-XSS) using the browser's "pro" developer tools was used in [a 2014 Facebook scam](https://www.tomsguide.com/us/facebook-self-xss,news-19224.html) and pages trying to phish will just make up a bullshit reason for the user to need to follow the override steps, such as saying "we recently changed hosts" which became a rumor in the EtherDelta DNS hijacking case today.

**Comment by bdresser** [comment]
It's time to make this happen 😄 

Let's follow the chrome pattern and include a small link that says `Advanced`

Clicking the `Advanced` link should show some text that says

`This site has been blocked because it is known to be dangerous. Visiting the website may permanently compromise your keys, track your account activity, or attempt to phish your funds. Proceed at your own caution; MetaMask is not responsible for support or any loss of funds that occurs on this site.`

And then a red button that says `Proceed Anyways` that actually takes them through to the next page.

**Comment by cjeria** [comment]
@bitpshr @bdresser @danfinlay Posting an updated design for feedback on the phishing warning page.
![image](https://user-images.githubusercontent.com/597770/46306725-e6401f00-c569-11e8-9c52-ff479cc36516.png)

**Comment by cjeria** [comment]
@bdresser This shouldn't take much time to implement if someone proficient in html/css picks this up. In my experience with front-end, it would take me ~30min max to build out the style for this. Getting the link to the domain being may take a bit longer but I'll let @whymarrh or @bitpshr be the judge of that.

WRT adding an advanced section, I don't think it's totally necessary as this page if very obviously communicating the message, but that's just my two cents.

**Comment by whymarrh** [comment]
#5406 doesn't include the redesign, but I'll implement that in a 2nd PR very soon
