### ISSUE TITLE
[Bug]: When an account is selected in the wallet but hasn't been connected to a dApp in the Permissions, any transaction initiated from this dApp defaults to using a different ( connected) account

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28015]
### Describe the bug

- The user has `Account 1` connected to the dApp
- the user switches to another account in MetaMask but does not connect it in the `Permissions`
- user initiates transaction from the dApp

    
1. When the` Improved transactions requests` toggle is enabled (which is the default setting), there currently isn't a clear notification within the Confirmation process indicating that the transaction is being created for an account different from the one actively selected in the wallet. 
  This situation results in transactions being initiated with a nonce that incorrectly matches the value of the account selected in the wallet. However, the transaction is ultimately submitted with the correct nonce, leading to a successful transaction being executed on an unintended account. [fix for the nonce issue](https://github.com/MetaMask/metamask-extension/pull/28272)

2. In the legacy Confirmations, there is a notification on the Confirmation screen that hints the account being used for the transaction is not the one currently selected in the wallet. 
    ******Transaction is created AND submitted with the incorrect nonce on a wrong account which results in the Failed low nonce or Pending hign nonce tx.***** - this nonce issue is fixed

    Given that` Permissions` is a relatively recent addition, enhancing the visibility of prompts or notifications that guide users to activate their chosen account via `Permissions` could decrease the chances of transactions being inadvertently conducted with the wrong account, thereby elevating the overall user experience.

### Expected behavior

-

### Screenshots/Recordings

RC 12.7.0

Redesigned Confirmation:

https://github.com/user-attachments/assets/bea00713-c41b-429b-8cc4-7db6b76fe2ef

 
Legacy Confirmation:

https://github.com/user-attachments/assets/94d979a6-49dd-4ced-95cf-36869d635b84

<img width="361" alt="Screenshot 2024-10-22 at 12 44 35" src="https://github.com/user-attachments/assets/1a2dfe97-5c52-4dc5-8708-25b5e67d7a7d">

<img width="347" alt="Screenshot 2024-10-22 at 12 44 45" src="https://github.com/user-attachments/assets/000697d0-bba1-4f70-ab4d-1e80e7e1ac94">

### Steps to reproduce

1. Switch to the account that is not connected to the dAPP
2. Switch to the dApp
4. Start a transaction

### Error messages or log output

```shell
No errors
```

### Detection stage

On the development branch, RC 12.6.0, RC 12.7.0

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
This looks like expected behavior, with the question being whether this design is effective. The behavior is a consequence of confirmation requests being permission based, rather than active account or network based. And so a request can occur for another account or network.

Note that this behavior already exists on Mobile.

Before assuming this is a `sev1`, I'd like to validate if this is actually confusing. Tbd on how we can do that.

Cc @mmragkandala @yanrong-chen in case this needs a design solution

**Comment by Gudahtt** [comment]
There is a mix of different issues in this report, which are worth differentiating:

* The incorrect suggested nonce (this is certainly a bug, but it has already been fixed since this report was made)
* When the test dapp transaction button is clicked, the account used is the one the dapp has permission for, not the current selected account (this is expected behavior)
* In the confirmation, the legacy confirmation designs had a warning icon, but the new confirmation designs do not (this is the problem that remains, and does not appear to be expected/as designed).

**Comment by pedronfigueiredo** [comment]
Current design exploration: https://www.figma.com/design/aHdSNvg9ahXZMtThzz3bUo/Github-issues?node-id=804-18875&t=kdcUUgGU0WG7jmbA-1
