### ISSUE TITLE
[Bug]: dapp initiated Approval is presented as Remove Permission for some tokens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28117]
### Describe the bug

When initiating an approval transaction from a dApp for certain tokens, it is unexpectedly presented not as the anticipated `Spending Cap request` but rather as a `Remove Permission` action. 
Possibly related - https://github.com/MetaMask/metamask-extension/issues/28096

### Expected behavior

- We should see the edit spending cap confirmation with the low decimal value.

### Screenshots/Recordings

https://github.com/user-attachments/assets/b0319ddf-b8aa-4180-b58d-d672c9e99deb

<img width="1429" alt="Screenshot 2024-10-27 at 21 57 48" src="https://github.com/user-attachments/assets/e78c2b4b-b7f0-4fac-a020-d83c60128ab0">

### Steps to reproduce

1. Connect to a dApp
2. Start a transaction with the token that needs approval

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
:information_source:  I've seen that this happens when we are approving an ERC20 token with lots of decimals and a small amount. Repro:
1. Go to the test dapp
2. Deploy a contract with 20 decimals
3. Change decimal input number to 1 
4. Approve tokens --> see revoke screen, though this will approve `0.0000000000000000007` amount of tokens
