### ISSUE TITLE
Connecting to main Ethereum Network...

### ISSUE THREAD

**Issue by Shumbro** [MetaMask/metamask-extension#2835]
Can't connect to my account, it says Connecting to main Ethereum Network... and nothing happens

**Comment by byrnecode** [comment]
same here..

**Comment by gromav** [comment]
Try connecting to Test network and then to Main Eth Network. THis worked for me.

**Comment by emkman** [comment]
Confirmed that @gromav has working solution. Curious why this just started happening a few days ago for multiple people.

**Comment by tmashuang** [comment]
Consolidating to #2636.

**Comment by rentol444** [comment]
С недавних пор не могу зайти в свой кошелек ClassikMask, именно в отдел Main Ethereum Classic Network.   На экране следующая надпись -  "Connecting to Main Ethereum Classic Network".
А в другие разделы, где ETH например, могу зайти. 
    Подскажите как исправить проблему?

**Comment by Mart-Bogdan** [comment]
Same issue here, claring cahce don't help.

I belive it's due to firewall in current public wi-fi hots-spot I'm using.

Belive Ether RPC endpoints are  using non standard ports

**Comment by nyashasachikonye** [comment]
So the metamask extension requires that you connect to the main network as a default, it will begin to function normally if you start there. In my case my local blockchain using ganache is running on port 7545  instead of the default port that metamask was expecting 8545. 

My solution involved going to the settings of the main ethereum network and then scrolling down to the custom URL portion, there i entered the full address my local blockchain was running on and clicked save. My Metamask automatically switched to that network and exiting the "settings" panel resulted in the expected behaviour :D 

Hope it helps!
