### ISSUE TITLE
Rejected Metamask transaction not refunding ETH

### ISSUE THREAD

**Issue by Krypit** [MetaMask/metamask-extension#2894]
Hi.
I've tried sending ETH to EtherDelta a few times but none of the transactions went through.
Now EtherDelta says I do not have enough funds to make a deposit into EtherDelta but the balance clearly shows on the MetaMask chrome window.
On Ehterscan (https://etherscan.io/tx/0x00583c5b83ac551fa9259dfa0d450691c7e857aadd94fcaec4668b9d61fd137d) the "rejected" transaction shows pending since 5 January but the timer keeps resetting to a couple of minutes.

I'm assuming this pending "rejected" transaction is why I cant use my ETH? What can I do?

**Comment by tmashuang** [comment]
https://etherscan.io/tx/0x00583c5b83ac551fa9259dfa0d450691c7e857aadd94fcaec4668b9d61fd137d. The transaction is still `pending`. We would like to know why the transaction was set to rejected, since a `rejected` transaction needs to be manually clicked. I also see that the transaction has been pending since Jan 8 on multiple block explorers. Please email [MetaMask Support](support@metamask.io) with your state/transaction logs. Here's how to obtain them, [State Logs](http://metamask.helpscoutdocs.com/article/9-how-to-copy-state-logs).

**Comment by Krypit** [comment]
mail and log sent! Thanks!

**Comment by devap1** [comment]
I have the same issue with Metamask/Etherdelta

0x4693eb01ea25896bbeabb4c015c1ac27d0768e67d30c06007cf44fa500c58448
