### ISSUE TITLE
Can the fox not look at my password when I'm entering it ?

### ISSUE THREAD

**Issue by paakjis** [MetaMask/metamask-extension#2921]
He/She is just blatantly looking down on my password.
How do I know that he/she cant see my password from the other side of the screen ?
Can the fox turn around or look somewhere else ?
![2018-01-10_18-30-41](https://user-images.githubusercontent.com/1484602/34783553-87ec992e-f634-11e7-8526-8b77af789cb9.png)

**Comment by tmashuang** [comment]
Since the code is open-source, if you able to view the code that enables the fox to follow input. 
Leaving this open for others to discuss.
https://github.com/MetaMask/metamask-extension/blob/941ea65af753be7f29c1d96f71ec2369c6e5454d/ui/app/unlock.js#L113-L122

**Comment by mhannigan** [comment]
Yes. Let's please get rid of the creepy fox head. It will also stop Metamask from hijacking my 3D GPU for the stupid thing and burning up my laptop.

**Comment by kumavis** [comment]
The fox does not use the gpu, it renders svg via js

**Comment by kumavis** [comment]
Really I think we just need a good winking animation upon successful password input

**Comment by bdresser** [comment]
@Grsmto we actually have had several conversations as a team about this particular issue. I personally agree with @kumavis' comment above. 

It's worth encouraging users to think about their relationship with the services and platforms they use. As an open-source project, trust and transparency are obviously very important to us. If the fox makes users consider _why_ they actually trust our project, I'm happy. But yeah, maybe that's too much for a first-timer.

And for the record, your password never leaves your machine – it is exclusively used to encrypt your "vault" locally, and is never sent to a server. Which is why we can't reset the password for you.

**Comment by jennypollack** [comment]
closing as I do not believe we have plans to remove this
