### ISSUE TITLE
After restart can´t login to my old account!

### ISSUE THREAD

**Issue by GTR7-77** [MetaMask/metamask-extension#2932]
Hi, after restart my pc missing my account on metamask. I don´t safe the private key only the seed words. I try to recovery my old account with this words but all what i see is a new account. Can anybody help me?

Thanks

**Comment by jazzinuf** [comment]
same thing happened to me my friend. We'll have to wait and see what happens

**Comment by GTR7-77** [comment]
shit. I hope you don´t loose to much money!

**Comment by jazzinuf** [comment]
Unfortunately there is a heft amount of money in it.. Did you end up getting your problem solved?

**Comment by GTR7-77** [comment]
No, it´s only 50 bucks but is also annoying. Did you write MetaMask?

**Comment by jazzinuf** [comment]
I emailed them, so far all I got was play around with your seed words. I’ve tried many different combinations with the words but didn’t find my original account. I have around 60,000 dollars worth of token and it is a big deal and issue. They also told me this bug was fixed last year, but clearly it isn’t. I just wish metamask actually takes action and try to help me out because it’s such a huge blow to me.
