### ISSUE TITLE
MetaMask is a Scam Wallet?

### ISSUE THREAD

**Issue by imonkey24** [MetaMask/metamask-extension#2951]
I tried a few times to send my ether from MetaMask to another wallets but every time it says "insufficient funds" or "invalid ether value" although I have enough Ether to send. You cant even scroll down in the menu to see all your tokens or Coins. There are many posts about bugs in MetaMask but the developers dont seem to do anything for the customers satisfaction. My tip, dont use Meta Mask yet cause its not bug free. But maybe in the future it will be a good wallet with no bugs.

**Comment by cryptokingca** [comment]
Same issue here and i cant get mt ETH out of Metamask

**Comment by Zanibas** [comment]
I apologize if it seems that we're not "doing anything for the customers satisfaction", but there are several issues that need work and only so many hands. If you can find a better wallet--please, go ahead, but do not insinuate that we don't do "anything". That is an insult to our team that works very hard for this community.

We are always welcome for constructive feedback, but we do not tolerate people who make absurd claims. You are free to reopen this issue if you can lay out exactly your problem is with insufficient funds.

**Comment by HostelAlouatta** [comment]
I have the same issue. I have 0.4 ETH in Metamask and trying to send 0.3, and it states 'invalid ether value' when I try. 
I find the answer up here (from Zanibas) quite rude. The OP clearly states his problem, and the answer is 'buzz of to another wallet'. Weird.
So now for my (same) problem: how can this be solved?

**Comment by HostelAlouatta** [comment]
Ok I have to get back at this. Ashamed I must say. 

I have type the amount like this: 0.3

This doesn't work. If you write it with a comma (0,3) it does work. So to OP; maybe try this?
It is a little confusing that your total amount is written with a dot and not with comma, but I jumped to the conclusion there was something wrong with Metamask too fast..
