### ISSUE TITLE
Filters/Events/Logs not working correctly

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2978]
There are lots of claims of events working inconsistently.
There may be multiple bugs at play here.
Some of them may have been resolved.
Some of them are associated with changing the provider.
Some of these are associated with resetting testrpc/ganache server without telling metamask.
This may involve getting results from an out-of-sync backend.

This ticket is for linking potential duplicate issues and discussing bounties

associated issues:
https://github.com/MetaMask/metamask-extension/issues/1261
https://github.com/MetaMask/metamask-extension/issues/2752
https://github.com/MetaMask/metamask-extension/issues/2742
https://github.com/MetaMask/metamask-extension/issues/2393 ✅fixed
https://github.com/MetaMask/metamask-extension/issues/2252 ✅fixed
https://github.com/MetaMask/metamask-extension/issues/2114 ✅fixed
https://github.com/MetaMask/metamask-extension/issues/2761 ✅fixed
https://github.com/MetaMask/metamask-extension/issues/2952 ✅fixed

**Comment by roehst** [comment]
Hello, I would like to ask for a quick comment on what are the alternatives that small application could use. It must refresh a model everytime the user changes it by clicking a button and performing an action, and ideally it could show other kinds of changes (from other users) in realtime.

I think of polling every n secs or triggering refreshes after specific UI cues. Are there other ways this could be done?

**Comment by danfinlay** [comment]
Some workaround options for devs that don't want to rely on events/logs when they don't work reliably:

- Write your own events/logs middleware and try pollyfilling it for your own backend.
- Simply store event-like data in a centralized database/index, and use that for serving your UI. That data can be regularly re-synced with blockchain data, but can be much faster for recall if it's exclusively caching your app's data.

**Comment by lazaridiscom** [comment]
@roehst @danfinlay , please look at #2393 , there is a possible fix.

**Comment by lazaridiscom** [comment]
https://github.com/MetaMask/metamask-extension/pull/3224/files

**Comment by lazaridiscom** [comment]
@danfinlay @kumavis - it seems we have a fix now for this quite critical issue:

#3224

3 confirmations (4 when you include mine)

**Comment by samid737** [comment]
I am still experiencing this issue on 4.1.0, using testrpc. It used to work consistently yesterday (4.1.0), but completely stopped working just now (firefox and chrome). I restarted testrpc once and since then eth_getLogs are not returned inside the console (restarted pc too). Network switching does not help anymore for me. I suspect this is not browser specific, because another client on the same LAN has the exact same problem. Is something going wrong in testrpc?

UPDATE: Using the new UI, the following error showed up (once, not sure how/why) below the password entry field:

NetworkController.setProviderType - cannot connect by type "rpc"

**Comment by lazaridiscom** [comment]
@danfinlay , this one can be most possibly closed (events/logs related stuff was fixed with #2393)

**Comment by victorwiebe** [comment]
Hi there,
Referencing #2742 , I'm running into an issue here as well. I have a dapp which is functioning just fine, and I have a more complex and gas intensive function I call to. This is a smart contract function which acts to bulk call to add a list of addresses. It behaves differently from the other function calls with the same web3 code.

The metamask transaction launches, I accept the transaction, after 5-10 seconds the block has been mined and the contract function called successfully.

But I seem to catch an exception with the contract call (weird) and in the console the error being presented is "Uncaught (in promise)"

Right now Im investigating a workaround for this and also what web3 1.0 has to offer.
All the best.

**Comment by danfinlay** [comment]
> Right now Im investigating a workaround for this and also what web3 1.0 has to offer.

Just a warning, MetaMask does not currently support Web3 1.0 or later.

If you could provide a reproduction use case, and provide it in a new issue, we could try to find the cause of your problem.

**Comment by victorwiebe** [comment]
Actually it was my mistake :( sorry!

**Comment by bdresser** [comment]
possibly handled in #4279

**Comment by lazaridiscom** [comment]
@bdresser , as this one is quite complex, a few comments:

This "collector"-issue lists issues which have different root-causes. Its a bit outdated.

From the list, you can remove (or group, and clarify as "fixed") the issues which were fixed by patch #3224 (see #3236 for some more info)

- #2393 (fixed, this was a bounty I claimed by providing the patch #3224)
- #2252 (issue can be closed, it's fixed by the patch for #2393)
- #2761 (again, most possibly same root-cause)

Those issues are fixed, can be removed from list (not related to patch #3224) :

- #2114 (fixed, not related to #3236)


Those issues seem to affect another root-cause (not the one that fixed #2393 and others) : 

- #1261
- #2742
- #2752 
- #2952 (a strangeness in itself, "when i try it in incognito mode it works, but when i try normal, it doesn't")

**Comment by bdresser** [comment]
Thanks for the detail @lazaridiscom. I've updated the original post accordingly and followed up on some of the remaining open issues. 

I'll check back in here after the provider rewrite (#4279) is merged to see if it has affected anything else.

**Comment by kumavis** [comment]
**If you encounter an issue with Filters/Events/Logs/Subscriptions, please open a new issue describing your situation and example code + reproduction steps**
