### ISSUE TITLE
lost private key

### ISSUE THREAD

**Issue by moanny** [MetaMask/metamask-extension#3040]
I usually use to just open chrome and click metamask and put in password to log in. But yesterday it was telling to create a new den. I created one but my old account didn’t appear. I have lost the private   key. I do still have my seed words and adress.

What are my options?

**Comment by abgar0168** [comment]
I have exactly the same issue. I wrote to support and followed the instructions in their email after which I now only see the first (originally created account and the new one I had ether in is gone.

**Comment by jazzinuf** [comment]
Same thing happened to me. Metamask support team doesn't even apologize for their mistake. I have big amounts of money, starting to question this company.

**Comment by abgar0168** [comment]
I’ve already written 16 emails to them and still the solution is yet to be found. It’s such a pain. I wish it would get solved somehow for both of us. I will keep you updated if anything changes with me. 

Sincerely wishing you luck

Ed



Sent from Mail.Ru app for iOS


Saturday, 20 January 2018, 19:22 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by jazzinuf** [comment]
Thanks my friend, feelings are likewise to you. Do you know if they are working on it of this case?

**Comment by abgar0168** [comment]
They are sending me standard emails. Totally useless. I am under endless stress because of it. One door closes, another one opens. Lost 20 % of my crypto investment. This is a great lesson to be learned for me though. 

will keep you updated

**Comment by jazzinuf** [comment]
Yeah my friend I feel you. I lost 30%of my portfolio on a ico project im really passionate about. It is a good lesson but let’s make sure to keep in touch with the dev because it is a legitmate problem users will face. Ik they say it’s a rare case but it seems like more and more people are experiencing the issue. I want the metamask project to be well, as it still is the beta version, it will be good for users like us to be passionately addressing our loss for a better cause in the future. Try to email the developers through email or twitter. This is a serious problem with potential of millions of dollars being lost.

**Comment by robroyman** [comment]
Just lost a wallet too due to remove and reinstall Chrome extension. It should be mandatory to backup your DEN when adding or removing the extension!

**Comment by martineezz** [comment]
@moanny 
@robroyman 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by darkwing** [comment]
Please do not contact the email cited, it is a scammer that will try to get your recovery phrase.
