### ISSUE TITLE
Support - Seed Phrase Support Flow

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3061]
When users report issues with their seed phrase, there are many possible root problems.
In order to help diagnose the problem we need a flow and series of questions.

**Comment by jrmoreau** [comment]
Q1 - So you don't see your Ether address. Did you originally have several Ether addresses created with a single seed phrase? 
If so, you must click "create account" within MetaMask to restore each additional address you created in its original order respectively. 
Q2 - What happens when you input your seed phrase and create a password? Does your MetaMask app go to a different address than you expected? Does nothing happen? Do you get an error message? Does the fox face loader just spin? 
If so, there's something wrong with how you input your seed phrase. This could be anything from a type to one of your seed words, capitalization of any letter, punctuation, or extra/absent spaces between words and at the beginning/ends of the seed phrase. 
Also, try going to https://www.myetherwallet.com/ -> Send Ether & Tokens -> paste your Mnemonic Phrase  **_WITHOUT_** a password. What happens when you do this? 
Q3 - When did you create your MetaMask account originally?
Q4 - What operating system and browser are you using? What versions, respectively?

**Comment by bdresser** [comment]
let's chat about this in support sync today @alacrity26 👍
