### ISSUE TITLE
Metamask fork for RSK

### ISSUE THREAD

**Issue by epavlenko** [MetaMask/metamask-extension#3096]
Hello,

Sorry if this isn't the right place for such a question. I've tried to submit a ticket to support.metamask.io a week ago but it's still unanswered.

I’m CTO of Proof of Toss - a decentralised betting platform (here is our website http://toss.pro/ but we haven’t published our WP yet).

We are planning to run our planform on RSK blockchain and we want to use MetaMask for some functionality. We decided that we need to make a fork of MetaMask and adapt it to work with RSK and SBTC.

We almost did it technically but we need some help from you to decide what should we do with some organisational and legal stuff.

We have to following questions:
1. How should we publish the plugin in Google Play? Should we publish it by ourselves or you would like to do it?
2. Should we make our own support website or should we send people to https://github.com/MetaMask/metamask-extension/issues?
3. If we publish the plugin by ourselves, what should we do with these documents?
- Licence - https://github.com/MetaMask/metamask-extension/blob/master/LICENSE
- Terms of Use - https://metamask.io/terms.html
- Privacy Policy - https://metamask.io/privacy.html
- Attributions - https://metamask.io/attributions.html

Thanks.

Best regards,
Eugene Pavlenko

**Comment by danfinlay** [comment]
Hi Eugene, sorry for the long wait.

MetaMask worked with RSK early on to ensure that MetaMask is compatible with RSK, as is, out of the box, users simply need to add a custom URL.

Since this is not an ideal UX, it's worth considering what is a better UX. Do you really expect users to install a custom extension for every blockchain in the future? That sounds pretty unpleasant for the user to me.

I think you should read what we replied to the PoA network regarding adding a network to our network menu:
https://github.com/MetaMask/metamask-extension/pull/2815#issuecomment-360570561

Ultimately, I think we need to make MetaMask easier to use with other networks, not encourage forking for every new chain, especially as side-chains, plasma chains, and shards become more common, we simply need to build for that future.

Check out this proposal here, it suggests a new API for sites like yours to define their own blockchain source:
https://github.com/MetaMask/metamask-extension/issues/2532

Closing because this is more a support/collab question than feature/bug, but please do chime in on those discussions, or add issues for proposed changes we could make.

**Comment by jooray** [comment]
@epavlenko did you solve this somehow, other than telling your users to install their own rsk node and configure custom RPC, which is a horrible UX?

**Comment by bdresser** [comment]
@jooray stay tuned for https://github.com/MetaMask/metamask-extension/issues/5101 which may help
