### ISSUE TITLE
Gas price must be greater than or equal to 4840 GWEI

### ISSUE THREAD

**Issue by SaturnusDJ** [MetaMask/metamask-extension#3166]
![jpeg image 365 x 518 pixels](https://user-images.githubusercontent.com/14320018/35692637-2dba83b8-077c-11e8-8471-3199b3754344.jpg)

Can anyone explain what went wrong here?

This was a snipe on an ICO. Similar transactions (probably made via other client software) did succeed. Why did the above fail?

**Comment by danfinlay** [comment]
To debug, we would need your [state logs](http://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs). These do not include private keys, but include the histories of your current accounts. If you aren't comfortable posting your state logs here, please submit them to support@metamask.io, and we'll help you as soon as we're able to.

One way I could imagine this happening:
- The Dapp that suggested this transaction hard-coded a gas price of `4400`, you submitted it, and then you clicked "Retry with higher gas price, creating a new enforced minimum gas price of 4840, about 10% higher, which is how our "retry with higher gas" logic works.

> Similar transactions (probably made via other client software) did succeed.

No need to make digs in your help request. Lots of people use MetaMask successfully. We're happy to figure out why it didn't for you.

**Comment by danfinlay** [comment]
Another thing worth noting is the `Transaction Error. Exception thrown in contract code` message. This means that our gas estimation encountered an error in the smart contract that you're sending to, maybe because the crowd sale had ended, and it is warning you to reject the transaction.

It could help to know what contract you were sending to.

Since smart contracts can hit errors and spend your gas if you enter a sale late (depending on that smart contract), sniping isn't always the best strategy to participate.

Another way I can imagine this happening:

You set a gas price of 4400 gwei on your snipe, you submitted it, and then you clicked "Retry with higher gas price, creating a new enforced minimum gas price of 4840, about 10% higher, which is how our "retry with higher gas" logic works at the moment.

I sure hope you didn't send a transaction with gas price this high, we might want to enforce a maximum gas price in the future, even though it might irritate some "snipers".

**Comment by SaturnusDJ** [comment]
@danfinlay 
Thank you for the nice explanation. Unfortunately, I was not the sender, but part of this pool, otherwise I would have included logs initially. I understand you are saying that a transaction of 4400 gwei might have been in progress, and that by retrying MetaMask automatically choose 4400+10%? If that is what you are suggesting, then that might very well be the case. Later I heard that 'nothing happened' after clicking the send button, yet many minutes later a transaction of 4400 gwei actually was executed, so apparently it was send out initially, I assume.

The only thing I don't get yet is why the transaction with such high gwei, send seconds after the contract opened, did not process in time.

**Comment by danfinlay** [comment]
> the only thing I don't get is why the transaction with such high gwei, send seconds after the contract opened, did not process in time.

The way a blockchain works is not perfectly straight forward. While a higher bid gives you a higher chance of a faster confirmation, in actuality, there are a couple steps involved, and random chance can cause a slowdown of even the highest bid.

I think [MEW did a great job of explaining it here](https://myetherwallet.github.io/knowledge-base/gas/what-is-gas-ethereum.html), except that their "MEW slide o fun" actually hides a step that can be confusing: When you broadcast a transaction, it goes to our nodes, who just start telling everyone they can about it, hoping that all the miners find out.

Miners draw from their own *personal pools* of transactions, which represent *the transactions they've heard about*, and if your transaction doesn't happen to get to the miner who happens to mine the next block, you might not be in the next block, but you're still likely to be in a soon one, since you've bid very high.

I'm not sure what you mean by "part of a pool" using MetaMask, I guess a number of people gave funds to one person who was trusted to use MetaMask to buy on behalf of everyone else? If that's the case, it definitely is important that the buyer know all these fine details about using Ethereum. You definitely don't want to pay a $30k transaction fee, that should never be necessary.

Closing, since it sounds like your question was answered, even though this still looks strange to me.

**Comment by SaturnusDJ** [comment]
Thanks again for the answer. And also a thanks from the pool host.

The pool consisted of people who had participated in ICO's before and are experienced with ETH transactions but there was no experience yet with delivering ETH on a very specific time/block.
