### ISSUE TITLE
NewUI: "Reveal seed phrase" password screen still using old UI

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3168]
Celine made an updated UI design for this.

**Comment by alextsg** [comment]
@cjeria Can you add a link to the design for this? Thanks.

**Comment by cjeria** [comment]
@celinepark94 can you add your designs for this screen here for review?

**Comment by cjeria** [comment]
@celinepark94  I found your designs and iterated on them.

Posting here for feedback. 

![image](https://user-images.githubusercontent.com/597770/36704099-a3f96440-1b13-11e8-9f18-f146a591deb5.png)

**Comment by alextsg** [comment]
Will the dual button Copy to clipboard/Save as CSV File component be used elsewhere in the app?

**Comment by cjeria** [comment]
@alextsg possibly. Right now, this is an ongoing discussion/critique of this design. Would like to get us providing feedback and get some iterations before committing. 

To address your question, we may consider using a similar component when accessing account private keys. 

Please feel free to share any thoughts/concerns.

![image](https://user-images.githubusercontent.com/597770/36746926-66f23d52-1ba8-11e8-8fd5-55407d6588d7.png)

**Comment by cjeria** [comment]
Or how about a component like this and use tooltips

![image](https://user-images.githubusercontent.com/597770/36747349-b0c41c7e-1ba9-11e8-8ba0-b42f47def8f7.png)

**Comment by lazaridiscom** [comment]
@cjeria , what about placing the warning right before(!) the buttons, adding a running thief, somehow  like this:

![image](https://user-images.githubusercontent.com/35095758/36976530-a440ed88-2086-11e8-88d7-d3720ebafdbc.png)

**Comment by lazaridiscom** [comment]
(actually, this being an animated one, and the fox running behind him would be even cooler. User complaint are then handled like this: "No, you can't have missed the warning we gave you within MetaMask!!!" )

**Comment by danfinlay** [comment]
I really like the idea of the animated 8-bit robber + fox. Definitely would grab the eye, help make the point. We should make a bounty for that animation and post it on some 8-bit art forum.

**Comment by cjeria** [comment]
@danfinlay I don’t know. This almost seems too playful. The illustration/animation would need to be very well executed and cohesive with the message we’re trying to convey. I’m Also concerned about the layout that @lazaridiscom is suggesting. The horizontal area under the seedphrase field is very narrow. Not sure that’s the best placement for an animation + message to be placed side by side. I believe using the area above the seedphrase (stacking the illustration above the warning message) makes more sense to give the ui more vertical breathing room and make it feel less cramped.

I do think we need to come up with well define illustration style (which is part of a bigger conversation around our branding, which I feel is underdeveloped aside from our beloved fox logo). In fact, I think we should contract a good illustrator that can be our go-to for our illustration needs, which ensures consistency because it's created by the same creator. If they know how to animate, that would be a plus, but not required IMO as we can outsource animators as well. 

I’d rather us be strategic about this and come up with a cohesive look and feel (throughout the app, website, social media) as opposed to a hodgepodge of different illustration styles with no clear art direction.

That being said, I’m open to doing something fun as @lazaridiscom is suggesting and I'm also happy to to research illustrators that fit the aesthetic we're going for (which we haven't really defined this as a team).

**Comment by cjeria** [comment]
https://github.com/MetaMask/metamask-extension/issues/3059
