### ISSUE TITLE
Taking too long? Retry with a higher gas price here.

### ISSUE THREAD

**Issue by codeworm68** [MetaMask/metamask-extension#3190]
I took part in ICO of arkblock 18 hours ago. I tried sending ether from my metamask wallet to the address provided on the arcblock website. After a few minutes, my dashboard on the website showed the number of tokens I bought. But, on metamask, transaction appears like this. 
![screen shot 2018-02-04 at 11 45 34 pm](https://user-images.githubusercontent.com/16037993/35780737-ebb1411e-0a05-11e8-839c-3c857be1d7db.png)

And when I click on the transaction, etherscan.io gives the following message. 
"Sorry, we are unable to locate this Transaction Hash"
My balance has been deducted from my metamask wallet.

**Comment by frankiebee** [comment]
on etherscan for your account does it syay that a transaction went through? also when you sent the transaction did you try to retry it?

**Comment by codeworm68** [comment]
When I access the wallet through MyEtherWallet, it shows the transaction as successful. I already got the ICO tokens on my dashboard. So, most probably, transaction went through. But metamask is not showing the transaction. And it looks the same even now.

**Comment by tmashuang** [comment]
There could be a couple nuances here and their deductions. If the transaction hash that was generated on MetaMask is different than the transaction that it was successful it will show the Etherscan message 'Sorry, we are unable to locate this Transaction Hash'. The only way I see this message is if the transaction was retried with a higher gas price, but the first transaction was successful. The retried transaction, that has the same transaction number, will be invalid since the first was successful. To ensure my suspicion, please provide your state logs to support@metamask.io of the transaction.
