### ISSUE TITLE
i forget my password

### ISSUE THREAD

**Issue by seahthomas** [MetaMask/metamask-extension#3199]

**Comment by frankiebee** [comment]
do you have your seed phrase?

**Comment by frankiebee** [comment]
you can restore from seed from the password screen if you do.

**Comment by Josefkey** [comment]
Hello! I forgot my password and I can't remember my seed 12 numbers, so how can I get a new pass?

**Comment by bdresser** [comment]
hey @Josefkey - because of the way MetaMask is built, we are unable to reset your password for you. You should *always* back up your seed phrase when using MetaMask or any other wallet! Without the seed, it's unlikely we'll be able to help you regain access to your account.

Still, there are sometimes a couple things we can try. Please email support@metamask.io and they'll be able to walk you through a couple things.

**Comment by rebroad** [comment]
@bdresser  how to I get metamask working if I want to set up a new account, but I don't have my seed or password for the last one I set up? How do I make it forget that I ever set it up previously?

**Comment by johnjames333** [comment]
@seahthomas @rebroad 
we have developed our own hardware for cracking Metamask wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by richardsonn09** [comment]
@Josefkey 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
