### ISSUE TITLE
geth/node server errors or timeouts while  estimating gas limit for a tx leads to a huge limit number autocompleting

### ISSUE THREAD

**Issue by ldanicel** [MetaMask/metamask-extension#3212]
I used a self hosted mew instance with metamask.

After setting up the tx and sending it from mew, i got a spawned metamask window which looked like fetching something and then the gas limit field got filled with a really huge number.

Auxiliary this triggered 2 other errors about really high gas cost that was supposed to follow if i'd post the tx and about lacking that amount of eth.

**Comment by tmashuang** [comment]
This bug sounds possibly related to the one described in #3285. For some reason many people are getting out of gas errors when estimating gas, both on geth and parity.

Closing this issue in favor of that one, because this issue dealt with a different problem that was fixed, and that one includes much more specific investigation into that issue.
