### ISSUE TITLE
Exceeding gas limit when trying to deploy a contract

### ISSUE THREAD

**Issue by travs** [MetaMask/metamask-extension#3232]
When I try to deploy a contract to kovan via browser-solidity, I get this error:
"Gas Limit Must Be Greater Than Or Equal To 21000 UNITS And Less Than Or Equal To 6643495 UNITS."

I am trying to use 6900000 gas to deploy, which is well under the [kovan limit right now](https://authorities.kovan.network/), so I'm wondering why this lower limit is being enforced by metamask, and whether I can circumvent it.

Using chromium on Arch linux.

**Comment by mimoo** [comment]
Same issue here

**Comment by armaneker** [comment]
Same issue!

**Comment by tmashuang** [comment]
This bug sounds possibly related to the one described in #3285. For some reason many people are getting out of gas errors when estimating gas, both on geth and parity.

Closing this issue in favor of that one, because this issue dealt with a different problem that was fixed, and that one includes much more specific investigation into that issue.
