### ISSUE TITLE
Post Mortem Analysis of Issue #2393

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3247]
(This affects additionally -or even more- the gitcoin.co bounty-system )

Edit:  Issue: #2393, Fix: #3224

### General Issue

Once a long bugging bug is solved, usually all folks goes on with daily work. Yet it is quite important to apply a "Post Mortem Analysis" in order to find out:

* what went wrong
* when did it go wrong
* why
* how to avoid similar problems in future

It is not that important to find things like "who" or "by whom". It is important to create guidelines and processes which avoid(!) human failure (and failure in general) in the future.

Like with plane-crashs.

### Examples

* Subsystem X is highly critical, needs to be better documented
* Process Y introduces high possibility of errors, needs to have for more strictness
* Code unit Z needs to be refactored (standard OO)
* Test cases should be produced to catch this and similar cases in future

And the hard ones:

* "Yes, we are the owners, but we must let some stricter folks join us to bring some discipline in."

### Bounties

Core developers are usually far to busy and far to close to the code-base. Thus an external(!) to the code-base person must execute this task.

The PMA must be executed from a high-level (bird-view), ideally from a person which can dive-in (to detail, code, process level) when needed. 

Managers, users  and developers which understand the importance of such a PMA can place a bounty to ensure that it's properly executed, and that the results are applied to the project - at least partially.

(gitcoin: this bounties should be categorized as "**C-level**", where "C" does not stand for the language "C", but for the Cxx as in CTO/CEO, which such an analysis would address).

**Comment by danfinlay** [comment]
Link to referenced issue for the lazy: #2393

**Comment by danfinlay** [comment]
The nature of the bug:

In the metamask-controller constructor, we initialize a provider, and then use that blocktracker to initialize the filter subprovider that is provided to every page:

https://github.com/lazaridiscom/metamask-extension/blob/58a554b1684fd78775b449b8f2b5d9635d30b69b/app/scripts/metamask-controller.js#L93-L94

The problem seems to be that the network controller allows this provider to be changed without notice. Sometimes it has listeners registered manually, like here:
https://github.com/lazaridiscom/metamask-extension/blob/58a554b1684fd78775b449b8f2b5d9635d30b69b/app/scripts/metamask-controller.js#L151-L153

For some reason, it seems like its old `blockTracker` reference was stuck on the old network, while a direct reference to the internal variable somehow was getting updated to the new network.

Frankly, this still doesn't make any sense to me at all. Just laying out some initial observations.

One post-mortem lesson I can draw is that we could isolate our network provider logic out of the metamask controller much more. This is going to become necessary soon anyway, when we allow dapps to be signed in on different blockchains, and so the sooner we isolate our instances of blockchain providers (instead of re-initializing them), the sooner we won't be prone to this kind of reference-swapping bug.
