### ISSUE TITLE
Metamask requiring new password

### ISSUE THREAD

**Issue by Column1** [MetaMask/metamask-extension#3271]
Love the product however why is Metamask asking me for a new password? The current password is fine. Am I being targeted? Im using Google Chrome with the latest updates.This happens with both computers I use even though I'm logged out.

**Comment by Zanibas** [comment]
If you're being asked for a new password, then it may mean that Chrome has cleared out your extension data. You are not being targeted most likely. Also, each chrome extension installation requires its own separate password per computer, since there is no central storage for these passwords (all local).
