### ISSUE TITLE
Onboarding Screen (New UI) Design Feedback

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3303]
Let's make this screen responsive. I would also argue that the fox and message on this screen is redundant. The user at this point has already installed MetaMask so we don't need to continue selling it this far into the experience. I would push for a welcome screen (See #3045 )before this screen if we want to showcase the moving head fox and description.

<img width="399" alt="screen shot 2018-02-21 at 11 03 27 am" src="https://user-images.githubusercontent.com/597770/36474168-f5faccb4-16f6-11e8-93bd-38429b60a9bb.png">

Let's change warning message to: 
Please be aware that this version is still in under development.

We can also add a "beta" label on the logo at the top:
![image](https://user-images.githubusercontent.com/597770/36478685-ecdb315a-1705-11e8-9030-c44690fd8083.png)

Also fix width body container to be consistent with app bar container width along with warning message: 
![onboarind new ui screen](https://user-images.githubusercontent.com/597770/36478351-af13ae16-1704-11e8-9c5a-00b885cc9b10.png)

**Comment by lazaridiscom** [comment]
(Stumbled on this by accident... now I have the chance to shoot him for good)

A bit "new user" "newcomer" feedback:

* I shot the fox (first with AdBlock, and then by code as he insisted). Cute, but **highly** annoying when you work with MM. There should be an **option to disable the Fox**, at least to disable the animation.
* Main Network... there is only **one** network for a simple end-user: ETH.
* If network-switching is to be kept: make an **"advanced" option**, which advanced users activate, so they can play with networks and other fancy stuff.
* Advanced or not: the Test-Networks should give a **clear & permanent visual feedback** "Testnet Without Value" or so. So that newbies cannot be lured to pay real-money for Test-Ethers. And experts do not accidentally evaporate real ETH during test-runs.

As a sidenote: I was forced to install MM to be able to use Gitcoin. But now I like this tool. I'm even a bit sad that the fox does not move anymore... but to lazy to change the code again!

**Comment by alextsg** [comment]
Thanks @cjeria. Adding this to our sprint.

**Comment by logicethos** [comment]
I don't like the fox watching my mouse all the time.  It's a distraction, and gimmicky IMO.  I wonder if he is going to steal my private keys.

**Comment by cjeria** [comment]
@alextsg just noticing the Beta label implemented is floating way above the wordmark. Let's make it so that it is vertically flush with the wordmark.

Implementation:
![image](https://user-images.githubusercontent.com/597770/36998627-6ada3388-2072-11e8-8787-0cf18c8541e1.png)

As designed:
![image](https://user-images.githubusercontent.com/597770/36998726-c3afd29c-2072-11e8-81c8-d17417a3b52e.png)

**Comment by txtechs** [comment]
Okay this issue is with beta is not showing certain erc20 s

**Comment by alextsg** [comment]
@cjeria the floating BETA should be fixed with https://github.com/MetaMask/metamask-extension/pull/3417

**Comment by txtechs** [comment]
For chrome not showing erc20 skrp
