### ISSUE TITLE
Meta Mask in Chrome using Ganache

### ISSUE THREAD

**Issue by jaypersanchez** [MetaMask/metamask-extension#3304]
I don't see any post similar to this so I apologize in advance if this has been solved already or if there is already a similar post.  Using Ganache to test my smart contract along with Metamask in current version of Chrome.  It took a bit for me to notice that when I have metamask enabled, I am not able to connect to the localhost:7545 and I don't see any of my accounts.  But when I have Metamask disabled, then I can see the first account in Ganache.  Am I missing a step here?  Thanks.

**Comment by danfinlay** [comment]
Is it possible that ganache is on a different port? This might be a question for the ganache team, they have lots of docs and tutorials here: http://truffleframework.com/ganache/

As for MetaMask, pointing at a local address should work if you have a server running on that port.

The reason you see that account when not connected to MetaMask, is probably because your app is checking for MetaMask's web3, and then defaulting to connecting directly to your local Ganache, which runs in "unlocked" mode, and allows transactions to be sent without signatures.

**Comment by rawadrifai** [comment]
@danfinlay - I'm able to connect to Ganache from metamask, but I'm unable to execute calls. It gives me this:

> Denying load of chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

**Comment by danfinlay** [comment]
@rawadrifai Please open a new issue or email our support at support@metamask.io

This issue is unrelated to what you are experiencing, so we'd like to give your issue the attention it deserves.
