### ISSUE TITLE
User feedback regarding network selection UX

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3305]
User commented in issue #3303

(Stumbled on this by accident... now I have the chance to shoot him for good)

A bit "new user" "newcomer" feedback:

* I shot the fox (first with AdBlock, and then by code as he insisted). Cute, but highly annoying when you work with MM. There should be an option to disable the Fox, at least to disable the animation.
* Main Network... there is only one network for a simple end-user: ETH.
* If network-switching is to be kept: make an "advanced" option, which advanced users activate, so they can play with networks and other fancy stuff.
* Advanced or not: the Test-Networks should give a clear & permanent visual feedback "Testnet Without Value" or so. So that newbies cannot be lured to pay real-money for Test-Ethers. And experts do not accidentally evaporate real ETH during test-runs.

As a sidenote: I was forced to install MM to be able to use Gitcoin. But now I like this tool. I'm even a bit sad that the fox does not move anymore... but to lazy to change the code again!

**Comment by danfinlay** [comment]
- Removing the fox? No thanks. Esp. since he eventually regrets removing it himself.
- Main network, correct. Not a question.
- What kind of fancy stuff? This isn't specific enough to be actionable.
- This is the same reason that Kirk refuses to use MetaMask. He's permanently terrified that he'll think he's on a test network, and send real ether. I think this is a developer problem, and for that reason is actually kindof fringe. The average user assumes every tx is real, and so they aren't prone to making this mistake. Open to designs for clarifying the network even more aggressively on the confirmation screen, though.

I would almost replace this issue with one about "Make network aggressively obvious on confirmation screen", and make that a discussion.

**Comment by cjeria** [comment]
@danfinlay I think the user was basically suggesting something we've already been discussing, which is to add more UI customization controls from within settings. In this specific case, he's suggesting hiding the network switcher for non-devs but giving devs the ability to turn it back on (in settings). We should always default to main-net. I agree with this.

Re: the fox - Just to clarify, I was talking about the fox head in the first-time user onboarding (see https://user-images.githubusercontent.com/597770/36474168-f5faccb4-16f6-11e8-93bd-38429b60a9bb.png), not at login screen (which is what I assume you were responding to above?).

What I commented in #3303:
I would argue that the fox and message on the first screen in the New UI onboarding flow is redundant. The user at this point has already installed MetaMask so we don't need to continue selling it this far into the experience. We could however...

**Suggested solution**
Let's add a welcome screen with a continue button (before the creating password step, see below png) to showcase the moving head fox and description.

See flow:
![image](https://user-images.githubusercontent.com/597770/36694678-fce67608-1af3-11e8-853f-a0ccf4c47a32.png)

**Comment by cjeria** [comment]
This issue is related to #4254 in the MetaMask Pro (Dev Version) project https://github.com/MetaMask/metamask-extension/projects/6

**Comment by danfinlay** [comment]
As we near the point where we need to support multiple networks natively (like Plasma chains), the request for "only main net" becomes increasingly obsolete.

I do think we should look for ways to not bother the user with the current network, but restricting the network usage seems like a short-sighted solution. Instead we should focus on ways of providing a network-agnostic experience that allows a user to easily understand what they're doing, regardless of the network.

**Comment by Gudahtt** [comment]
The suggested UI changes here seem partially outdated, since it has changed a lot.

Hiding the network switcher could still make sense, but I agree with Dan here; "normal" users are using alternate chains more than they once have, and it'll be even more common once the custom network RPC message work is merged. The network switcher still makes for a poor user experience, but we've since discussed alternate solutions to that. The most promising one I've heard is to make the current network state a property of the dapp connection, so that we let the dapp _suggest_ the network it wants to connect to, and the user can confirm that suggestion (or override it if necessary) during the connect flow.

I'm going to close this for now, as I think these continued discussions should probably happen elsewhere? But feel free to re-open this if you disagree.
