### ISSUE TITLE
lost my key to myetherwallet, but can connecting via metamask, is it safe?

### ISSUE THREAD

**Issue by olzhas1987** [MetaMask/metamask-extension#3307]

**Comment by abbasabba** [comment]
The eth is "safe" for a lack of better words yes... However it is either non accessible or on the verge of not being accessible if u do not either move it or take the steps to protect it with a password in a hot wallet environment im assuming its currently stored in.  I would suggest storing it on a trezor to keep it out of hands of "The Lost Boys of Bitcoin" to make truly safe as well as in your possession. ;)  I suggest you protect your sign in info to your browser as well as Meta-Mask password and keys in a place where you couldntlose it if you tried. This suggestion comes from learning the hard way and making what have turned out to be some of the biggest financial mistakes I have ever made while experimenting early on with mining amd purchasing eth and xmr at around 3$ and 1.50$. I still spend many hours trying to explore my online dump sites I should be calling my retirement fund for digital scraps of info that have not yet been found. Hope tou the best and I hope you hold on to what will turn out to be some of the most interesting and potential valuable online artifacts of our time. I can only hope my fossils will be found one day as well...

**Comment by kumavis** [comment]
yes its safe, it does not give access to your private keys to myetherwallet
