### ISSUE TITLE
rejected transaction but not refund my ETH

### ISSUE THREAD

**Issue by nsoia** [MetaMask/metamask-extension#3322]
hello.

rejected transaction but not refund mt ETH

txid : 0x101f990516e210718361037442908f0227e836255b0740c6368302b6fbad05c1 

please refund my ETH.

thanks.

**Comment by tmashuang** [comment]
If a transaction was sent and tried to retry a transaction with a higher gas price, but you selected reject instead of changing the gas price, this is not a feature to reject a transactions. Once a transaction was sent on the network, it can either fail or succeed. This transaction was successful and was sent to the recipient address.
