### ISSUE TITLE
Transaction sent to unintended recipient

### ISSUE THREAD

**Issue by iamjaime** [MetaMask/metamask-extension#3399]
I sent 0.25 ETH from one "Loose" account on meta mask to a regular meta mask account and about 30 seconds later the funds were forwarded to a completely different address!

**Comment by danfinlay** [comment]
Please email [your logs](https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs to support@metamask.io so we can investigate what might have happened here.

If this is as bad as you say it is, it sounds a lot like you may have caught a malware like this:
https://ethereumworldnews.com/careful-copying-pasting-ethereum-wallet-address/

You should be able to test this by copying an ethereum address, and seeing what happens when you try pasting again.

**Comment by bdresser** [comment]
hey @tchelolima, like Dan mentions above please email [your state logs](https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs) to support@metamask.io so we can investigate what might have happened here.
