### ISSUE TITLE
Design TX Retry For New UI

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3435]
Related to #3011, but for New UI.

**Comment by celinepark94** [comment]
@cjeria, took a quick first pass at the UI in the browser and extension. Changed some wording for the message, and included it in the header rather than as a pop-up. Also changed the "cancel" button to read "cancel overwrite" to make it more clear. Please give feedback if you have some time, otherwise, I'll keep working on it. 

Maybe, since the only thing they can overwrite is the gas, we can direct them to a page where the only thing they can edit is gas? Tried it in the extension. Let me know what you think.

![image](https://user-images.githubusercontent.com/4051426/37073937-e079ee5a-2197-11e8-93c6-4acfd502b683.png)
![image](https://user-images.githubusercontent.com/4051426/37074254-e778424a-2199-11e8-9a23-69b8d2d78801.png)

**Comment by celinepark94** [comment]
Also, please advise if I am using outdated/unused screens

**Comment by danfinlay** [comment]
I would replace the word `Overwrite` with the word `Retry`.

Also maybe revise the "Taking too long" wording, because you aren't really increasing the gas on that transaction. I like the current wording:

> Taking too long? Retry with a higher gas price.

**Comment by cjeria** [comment]
@danfinlay here's the final version of the retry tx button with specs. This one's ready for dev.

![metamascara - flat accounts 1 copy 4](https://user-images.githubusercontent.com/597770/37173217-d43101f2-22c7-11e8-88e5-ba4937eab5a9.png)
