### ISSUE TITLE
Nonce issues

### ISSUE THREAD

**Issue by tradedbytony** [MetaMask/metamask-extension#3442]
I have been using MetaMask to trade on different exchanges and all's been fine until tonight. Starting tonight I'm getting these and I can't send tokens/eth anywhere. 

I even tried switching to the Beta version, but still getting error messages. I tried switching to the Test networks and back to the main Network and still didn't work.

Any idea what may be causing this all of a sudden? This is the error message I'm getting:

Error: Error: Specified nonce may not be larger than account's next valid nonce. at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:37386) at t.n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:739834) at t.n.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:738650) at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:83908) at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:83510) at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:41146) at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957495) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957283) at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:957674) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:264337) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:264433 at <anonymous>

**Comment by Zanibas** [comment]
@danfinlay @kumavis

**Comment by danfinlay** [comment]
To investigate possible causes, we would need [state logs](https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs). Since those include some information like your address and transactions, you might want to submit them in privacy, maybe to us at support@metamask.io

I am closing this because there is nothing we can do without these logs. If you submit the logs to our support email, we will resume there. If you post the logs here, we will reopen the issue.
