### ISSUE TITLE
Few questions about getting signed data

### ISSUE THREAD

**Issue by etienneroudeix** [MetaMask/metamask-extension#3449]
Hi there,

I have some questions for which I could not find a clear answer.

When asking MetaMask to sign a transaction, is it possible to force a chain id ?
If yes, any documentation link ?
If no, is it for security reason or would you consider a PR doing it ?

Is it possible to sign a transaction through MetaMask and not send it but get the signed data back ?
If yes, any documentation link ?
If no, is it for security reason or would you consider a PR doing it ?

Is it possible to send MetaMask a RPL encoded transaction, ask MetaMask to sign it and get the signed transaction back ?
If yes, any documentation link ?
If no, is it for security reason or would you consider a PR doing it ?

Cheers

**Comment by kumavis** [comment]
> When asking MetaMask to sign a transaction, is it possible to force a chain id ?

we use the response of `net_version` https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version for the EIP155 chain id. this creates a problem for ETC as the `net_version` and `chainId` don't match. AFAIK there is no way to directly query the `chainId`.

As a work around, someone could add an override in the network config menu.

> Is it possible to sign a transaction through MetaMask and not send it but get the signed data back ?

no we don't allow this because it makes nonce calculation difficult. You should be able to use your metamask seed phrase in icebox https://github.com/ConsenSys/icebox

> Is it possible to send MetaMask a RPL encoded transaction, ask MetaMask to sign it and get the signed transaction back ?

no we don't support this but you could do it yourself by exporting your keys from metamask and using https://github.com/ethereumjs/ethereumjs-tx

**Comment by kumavis** [comment]
for chainId woes, feel free to +1
https://github.com/MetaMask/metamask-extension/issues/3453

**Comment by bdresser** [comment]
@leafcutterant check out https://github.com/MetaMask/metamask-extension/issues/3475
