### ISSUE TITLE
When sending txs via MyCrypto, changing the gas price in MM seems to invalidate the tx

### ISSUE THREAD

**Issue by Shrugs** [MetaMask/metamask-extension#3472]
### Steps to Reproduce:

- go to mycrypto
- create any transaction (sending 0 ether to yourself, for example)
- note the gas price selected
- generate tx and click the send tx button
- metamask pops up
- change the gas price in metamask from the gas price selected by MC
- press confirm
- tx send fails

![thing](https://user-images.githubusercontent.com/1535001/37119721-20477960-220d-11e8-89d0-c1950e517ab1.jpg)

### Expected Behavior:

I can change the gas price of my transaction in MM before signing and broadcasting.

**Comment by emkman** [comment]
I just had what may have been the same or similar issue. I was sending ETH to a contract (https://mycryptolambo.com/) with the new UI. I manually changed the gas price. The transaction sent but had no Input Data, so the contract failed and reverted. I disabled the new UI, started a new transaction, changed the gas price, and sent. The Input Data was preserved and the contract executed successfully.

Failed tx (new UI): https://etherscan.io/tx/0xa4f399cf2d4885a2c42f7fa36e71a609e8e6dc7133373f1a7be22e3f8732e4fc
Successful tx (old UI): https://etherscan.io/tx/0x457470519a39cde87070da7e2d13c8d00015f10608beeac29d99c9e33bbe9292

I am not sure if this was caused by just the new UI or the new UI and changing the gas price. It is not clear to me how to verify the contract input data in the new UI before sending.

**Comment by nanexcool** [comment]
We are seeing something similar on our [Dai Dashboard](https://dai.makerdao.com) with the new MM UI.

What seems to be happening is that contract call data is erased somehow, and ends up sending `0x`, so no method sig, and no parameter data.

**Comment by sbberk** [comment]
Can confirm, using the MM beta v 4.2.0 , if I send a tx without modifying the gas price it works and looks like: https://etherscan.io/tx/0x84d8bf388b8336683239bc03216d920d369e8224320fec8c3ed7111b3205d1cd
If I modify the gas price, the data is set to `0x` and looks like: https://etherscan.io/tx/0xd3a87c1897b978922ee358d23bdd81a3542fee428ecd0d2092b83351d8d19385

**Comment by kumavis** [comment]
possibly related https://github.com/MetaMask/metamask-extension/issues/3554

**Comment by danjm** [comment]
https://github.com/MetaMask/metamask-extension/pull/3489 should resolve this and is currently under review
