### ISSUE TITLE
Extension doesn't update account names while name editing is active when switching accounts

### ISSUE THREAD

**Issue by gorgos** [MetaMask/metamask-extension#3511]
When switching between accounts while the account name editing field is active, the names don't change.

  *  Chrome Version 65.0.3325.146 (Official Build) (64-bit)
  *  Mac OS
  * MetaMask version 4.2.0

Account 2:
<img width="352" alt="screen shot 2018-03-11 at 03 24 51" src="https://user-images.githubusercontent.com/659390/37248843-e0d21c96-24db-11e8-8ede-08bbc40cb923.png">

On account 1:
<img width="354" alt="screen shot 2018-03-11 at 03 25 24" src="https://user-images.githubusercontent.com/659390/37248845-e2de070c-24db-11e8-81aa-f89edba1bddf.png">

**Comment by tmashuang** [comment]
Pretty specific use case. I was able to save but not what was expected. I believe the proper reproduction steps are: 
1. Select Account 1
2. Edit account name, but don't save.
3. Switch account to Account 2. 
4. Click save.

This will produce the account name change on Account 2 since the placeholder edit field is selected on Account 2.

**Comment by bdresser** [comment]
This issue doesn't affect the new UI, and we don't plan to patch issues on the old UI anymore
