### ISSUE TITLE
Feature Request - Auto accept payments

### ISSUE THREAD

**Issue by aecc** [MetaMask/metamask-extension#3528]
It would be nice for DApps developers to have a feature to **"auto-accept"** all the payments. Maybe only using private networks, for security.

**Comment by Zanibas** [comment]
Can you please describe this spec in more detail?

**Comment by aecc** [comment]
As a developer (and possibly as a user) it's tedious to have to click on the metamask icon every time I submit a transaction to the blockchain and then having to click "accept" when the transaction details are not relevant to one. I think having an option that automatically accepts all the transactions (especially when we are talking about spending few gas and few Weis) would be ideal. You can think of it as an analogy to the Wireless credit cards, where no pin code (or no action from the user) is needed for transactions less than X amount per day. 
It could be a configurable option to be activated or deactivated if wanted to.

**Comment by Robbiekruszynski** [comment]
Hey @aecc  
I know it has been some time but please know this ticket was never lost! Hoping you've been enjoying the improvements the team has implemented since this ticket. We have migrated our conversations for support / feature requests to [ZenDesk](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas). Feel free to make a ticket / share your thoughts there! 

Going to close this ticket.
