### ISSUE TITLE
MetaMask drop-down display buttons not visible if ETH balance is too large

### ISSUE THREAD

**Issue by tinybike** [MetaMask/metamask-extension#3601]
I'm developing on a private chain with an account that has a very large amount of testnet ether.  In fact the amount of testnet ether is so large that it causes MetaMask's dropdown window to scroll the buttons and some of the text off the screen to the right, and the dropdown does not allow you to scroll horizontally or resize the dropdown, so there's no way to click on anything!

![metamask-screenshot-cropped](https://user-images.githubusercontent.com/2637020/37558632-dc2e24c6-29d3-11e8-8644-ff4b0eaacde9.png)

Note: the MetaMask popup window (the one that appears automatically when you try to submit a transaction, rather than the drop-down from the menu bar) has this problem too, but you can simply resize the popup window and see the transaction details that way.

Suggested fix: add a horizontal scrollbar.

Using Chrome 65.0.3325.162 (Official Build) (64-bit) on Xubuntu Linux 16.04

**Comment by kumavis** [comment]
#whaleproblems

**Comment by kumavis** [comment]
need to verify if this affects new ui

**Comment by WalterEg0** [comment]
Same or similar issue. Cant access buttons or see the display completely due to MMask window being too huge inside the borders of its window. Severely impaired. 
Changing resolution on pc seemingly does not effect the resolution to which MMask is displaying the grossly enlarged MMask UI inside its window .There is no way to scroll up/sideways or manipulate window borders also makes no significant change.  Tried to reinstal mmask- no avail. messed with display -no avail. Reboot no avail. Reinstal Brave and MMask no avail.
Being able to tweek the way Metamask displays would help solve the problem, slider bars would also help.
using a Dell inspiron win10 with brave browser.

**Comment by bdresser** [comment]
We're moving full steam towards the new UI - give it a spin by clicking the blue banner on the top of you extension, or by heading to settings (top-right menu, settings, Beta UI)

It includes much smoother handling of large values & overflows. Closing this as we aren't patching the old UI any longer.
