### ISSUE TITLE
EOS AIRDROP PHISING HACK

### ISSUE THREAD

**Issue by filtr0w** [MetaMask/metamask-extension#3645]
so i was part of this scam

https://www.reddit.com/r/CryptoCurrency/comments/83fk6n/warning_sophisticated_email_scam_regarding_free/

you can see screeenshots of the whole process. the email, the fake news coindesk article, the fake myetherwalleet link, etc. the only thing i did was enter the fake coindesk article, that's all.

all my funds from myetherwallet were transferred that same day to other addresses. i have searched all my history, and the only thing i did was google about this eos aidrop, this led me to the fake coindesk article. however once i was there i realised that they were using a look alike domain for myetherwallet.

at that point i realised it was a scam

1) I DID NOT ENTER THE MEW fake address
2)I DID NOT login to MEW or metamask.

however my funds are gone as you can see here.

https://etherscan.io/address/0xa8e4437feb66e320a76ad0aa9e398716962a5116

things i have done wrong too : 

1)i have used my private key to login to MEW wallet before. I DID NOT use it that day.
2)i have signed up for a fake ven airdrop google form where i provided my ethereum address and my email.

the only possible thing that i can think of is that somehow metamask was compromised by this site. however the person posting in reeddit was able to visit this sites without getting compromised. they just look like normal phising sites where they rely on the user providing the data.

**Comment by jrmoreau** [comment]
If you'd like us to help you review what happened you might want to open a ticket for this so your personal details about this are not discussed in public. support@metamask.io

**Comment by sqwilso** [comment]
I had the same issue as mentioned above - not sure if there is any feasible solution. All the contents of my ETH wallet were moved to this location - where they haven't been accessed since https://etherscan.io/address/0x98d67bc5ba8e43721972204e5e1e4eaef43cadb1

as a result of this transaction, plus the ones after moving over my tokens https://etherscan.io/tx/0x3b2f84fc6ecc2cdbc28cfa6238d3cc43024246d30faed61ef9f1fc0ee26d785e

I don't know if there is anyway of listing this ETH wallet as containing hacked funds......
0x98d67bc5ba8e43721972204e5e1e4eaef43cadb1

**Comment by filtr0w** [comment]
helloo stuart


i am not sure what happened.


basically i havent used metamask in a while, and i was travelling. i opened it again and it didnt ask me for a password as usual, but to create a new wallet.


i used my seed phrase to restore my den but


i cannot access this wallet now


https://etherscan.io/address/0xe9b20242a31b9058bf7a1855ac176a61e1637b2e

what did i do wrong here?

thank you

n.
________________________________
