### ISSUE TITLE
Add Selenium tests to test suite against a Dapp

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3698]
So that we're testing the entire extension end-to-end against Dapps.

**Comment by mryellow** [comment]
In here make sure you don't regress retry buttons.

**Comment by tmashuang** [comment]
@mryellow any particular way that the adding tests would regress the buttons?

**Comment by mryellow** [comment]
> make sure

Test for regression.

Related to a variation of #3374 appearing again. Think I'm getting a handle on what has happened.

Old transactions aren't triggering the retry button for whatever reason, but new ones are. So a test to catch this would need to have transactions created first in the old version and then in the new version under test.

This would ensure users with active transactions aren't left in a broken state as has happened here.
(Transactions can not be cancelled with MEW as it will now only generate a new nonce rather than accepting "dApp" specified one)
