### ISSUE TITLE
[RFC] Replace "Keyring" with "Wallet"

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3738]
I am at this point highly distracted by the term `keyring`.

The `eth-keyring-controller` manages `keyring-classes` which are nothing more than an thin layer above the `ethereumjs-wallet`.

The suggestion here is to use `Wallet` instead, in order to align with the common terminology.

This will become even more important as a future(!) rework-step will possibly change the 'keyring-classes` to inherit `ethereumjs-wallet` classes.

* ethereumjs-wallet => no storage etc.
* mm-wallet => same as above, but have storage and some more practical stuff

### Suggested Naming

* mm-wallet
* mm-wallet-provider

The `mm` is a shortcut, similar to the `eth` for `ethereum`.

MetaMask should not use the `eth` prefix, which should be reserved (by general agreement) for the Ethereum Organization.

### Importance

Is all this naming-stuff really so important?

For me personally, very much. I cannot operate on in-concise naming. And sometimes, bringing clarity into naming is the first step to understand things better.

You can see my overall "mental naming model" here: #3720 (which is more or less the "standard-terminology)

`Keyring` does not even exist, currently, and I was not able (with limited research) to find a concise description.

### Ongoing Work

In order to be able to continue work, I will use "wallet" anyway, but will replace it once i'm finished with the finally term by the team.

Edit: there is a tiny possibility that `ethereumjs-wallet` is miss-named.

**Comment by danfinlay** [comment]
I think in general, the ecosystem uses the term "wallet" to mean "software that manages a user's accounts".

This was reinforced by MEW's glossary:
https://myetherwallet.github.io/knowledge-base/getting-started/ethereum-glossary.html

I like the term "Keyring" because it very literally is a collection of keys, although that metaphor doesn't hold up as well once we start adding contract-based accounts.

All that said, I don't think it's awful to have multiple "wallets" in MetaMask. "Wallet" does have a certain portability to it, and so it might help people understand how a single wallet can be exported/shared, while the rest of the vault remains intact.

This would raise the question of what we use to refer to client software (maybe just "client", or "wallet manager").

**Comment by lazaridiscom** [comment]
The Trezor Hardware-Wallet provides a nice diagram:

https://blog.trezor.io/wallet-accounts-and-addresses-bdfa6b66b037

Trezor is in essence a "HW-Wallet-Manager", which is shortened to "HW-Wallet"

**Comment by lazaridiscom** [comment]
@danfinlay , I'll close this, as I've moved the development anyway over to an autonomous repo:

https://github.com/lazaridiscom/mm-vault

with the only requirement to stay api-compatible. So the overall terminology-thing can be seen on a live example, as a whole.
