### ISSUE TITLE
Add JSDoc documentation to all background scripts

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3941]
Multiple bugs were shipped last week, in part because interfaces to some files were not clear/understood.

Long term, this looks like a good case for strong types, but in the short term, strong documentation is something our codebase lacks, and could help alleviate this kind of issue.

JSDoc can generate nice readable documentation for a codebase, here is some docs added to our `KeyringController` (here called `mm-vault`):
https://github.com/lazaridiscom/mm-vault

Should be added to all scripts in `app/scripts`, especially `app/scripts/controllers` and `app/scripts/lib`.

**Comment by frankiebee** [comment]
i have transaction controller and all it's sub controllers

**Comment by danjm** [comment]
Here is a checklist with assignees, so that we can track who is working on docs for which file:

- [ ] app/scripts/background.js (Assignee: )
- [ ] app/scripts/chromereload.js (Assignee: )
- [ ] app/scripts/config.js (Assignee: )
- [ ] app/scripts/contentscript.js (Assignee: )
- [ ] app/scripts/controllers (Assignee: )
- [ ] app/scripts/edge-encryptor.js (Assignee: )
- [ ] app/scripts/first-time-state.js (Assignee: )
- [ ] app/scripts/inpage.js (Assignee: )
- [ ] app/scripts/lib (Assignee: )
- [ ] app/scripts/metamask-controller.js (Assignee: )
- [ ] app/scripts/migrations (Assignee: )
- [ ] app/scripts/notice-controller.js (Assignee: )
- [ ] app/scripts/platforms (Assignee: )
- [ ] app/scripts/popup-core.js (Assignee: )
- [ ] app/scripts/ui.js (Assignee: )
- [ ] app/scripts/ (Assignee: )
- [ ] app/scripts/controllers/address-book.js (Assignee: )
- [ ] app/scripts/controllers/balance.js (Assignee: )
- [ ] app/scripts/controllers/blacklist.js (Assignee: )
- [ ] app/scripts/controllers/computed-balances.js (Assignee: )
- [ ] app/scripts/controllers/currency.js (Assignee: )
- [ ] app/scripts/controllers/infura.js (Assignee: )
- [ ] app/scripts/controllers/network.js (Assignee: )
- [ ] app/scripts/controllers/preferences.js (Assignee: )
- [ ] app/scripts/controllers/recent-blocks.js (Assignee: )
- [ ] app/scripts/controllers/shapeshift.js (Assignee: )
- [ ] app/scripts/controllers/transactions.js (Assignee: @frankiebee)
- [ ] app/scripts/lib/account-tracker.js (Assignee: )
- [ ] app/scripts/lib/auto-reload.js (Assignee: )
- [ ] app/scripts/lib/buy-eth-url.js (Assignee: )
- [ ] app/scripts/lib/config-manager.js (Assignee: )
- [ ] app/scripts/lib/createLoggerMiddleware.js (Assignee: )
- [ ] app/scripts/lib/createOriginMiddleware.js (Assignee: )
- [ ] app/scripts/lib/createProviderMiddleware.js (Assignee: )
- [ ] app/scripts/lib/environment-type.js (Assignee: )
- [ ] app/scripts/lib/events-proxy.js (Assignee: )
- [ ] app/scripts/lib/extractEthjsErrorMessage.js (Assignee: )
- [ ] app/scripts/lib/get-first-preferred-lang-code.js (Assignee: )
- [ ] app/scripts/lib/getObjStructure.js (Assignee: )
- [ ] app/scripts/lib/hex-to-bn.js (Assignee: )
- [ ] app/scripts/lib/inpage-provider.js (Assignee: )
- [ ] app/scripts/lib/is-popup-or-notification.js (Assignee: )
- [ ] app/scripts/lib/local-store.js (Assignee: )
- [ ] app/scripts/lib/message-manager.js (Assignee: )
- [ ] app/scripts/lib/migrator (Assignee: )
- [ ] app/scripts/lib/nodeify.js (Assignee: )
- [ ] app/scripts/lib/nonce-tracker.js (Assignee: @frankiebee)
- [ ] app/scripts/lib/notification-manager.js (Assignee: )
- [ ] app/scripts/lib/pending-balance-calculator.js (Assignee: )
- [ ] app/scripts/lib/pending-tx-tracker.js (Assignee: @frankiebee)
- [ ] app/scripts/lib/personal-message-manager.js (Assignee: )
- [ ] app/scripts/lib/port-stream.js (Assignee: )
- [ ] app/scripts/lib/random-id.js (Assignee: )
- [ ] app/scripts/lib/reportFailedTxToSentry.js (Assignee: )
- [ ] app/scripts/lib/seed-phrase-verifier.js (Assignee: )
- [ ] app/scripts/lib/setupMetamaskMeshMetrics.js (Assignee: )
- [ ] app/scripts/lib/setupRaven.js (Assignee: )
- [ ] app/scripts/lib/stream-utils.js (Assignee: )
- [ ] app/scripts/lib/tx-gas-utils.js (Assignee: @frankiebee)
- [ ] app/scripts/lib/tx-state-history-helper.js (Assignee: )
- [ ] app/scripts/lib/tx-state-manager.js (Assignee: @frankiebee)
- [ ] app/scripts/lib/typed-message-manager.js (Assignee: )
- [ ] app/scripts/lib/util.js (Assignee: )
- [ ] app/scripts/platforms/extension.js (Assignee: )
- [ ] app/scripts/platforms/sw.js (Assignee: )
- [ ] app/scripts/platforms/window.js (Assignee: )
- [ ] app/scripts/account-import-strategies (Assignee: )

**Comment by danjm** [comment]
For now, I will take the following:
app/scripts/notice-controller.js
app/scripts/ui.js
app/scripts/controllers/address-book.js
app/scripts/controllers/currency.js
app/scripts/controllers/preferences.js
app/scripts/controllers/shapeshift.js
app/scripts/lib/buy-eth-url.js
app/scripts/lib/environment-type.js
app/scripts/lib/get-first-preferred-lang-code.js
app/scripts/lib/is-popup-or-notification.js
app/scripts/lib/nodeify.js
app/scripts/lib/util.js

**Comment by whymarrh** [comment]
Something to keep in mind, if we're interested, we can use the TypeScript type signatures in the docblocks we add (e.g. in [`@param`](http://usejsdoc.org/tags-param.html)s) and run the TypeScript compiler against them file by file. For example, in #3984 I was working locally with this config:

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": true,
        "alwaysStrict": true,
        "allowSyntheticDefaultImports": true,
        "checkJs": true,
        "jsx": "preserve",
        "lib": [
            "dom",
            "dom.iterable",
            "es7"
        ],
        "moduleResolution": "node",
        "noEmit": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "strictNullChecks": true,
        "target": "es6",
        "typeRoots": [
            "node_modules/@types/",
            "types/"
        ]
    },
    "include": [
        "app/scripts/lib/migrator/*",
        "app/scripts/lib/createLoggerMiddleware.js",
        "app/scripts/lib/createOriginMiddleware.js",
        "app/scripts/lib/events-proxy.js",
        "app/scripts/lib/hex-to-bn.js",
        "app/scripts/lib/local-store.js",
        "app/scripts/lib/random-id.js",
        "app/scripts/lib/stream-utils.js",
        "app/scripts/platforms/sw.js",
        "app/scripts/platforms/window.js"
    ]
}
```

The process for running TypeScript against the docs we write would be:

1. Adding the TypeScript package
2. Adding a `tsconfig.json` (as shown above) to the project root
3. Running `tsc --project .` to check the files

I both think that this is just a useful approach locally when writing JSDocs to make sure that I've covered everything, as well as a desirable check to add to CI (though I won't necessarily push for that).

@bitpshr might have thoughts on this option and whether or not it's a good idea/useful. [There are a lot of Salsa bugs](https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+label%3ASalsa+label%3ABug) but it does work for enough cases that I think it's worthwhile.

**Comment by danfinlay** [comment]
That's an interesting idea, @whymarrh, I'd be open to trying that out.

**Comment by lazaridiscom** [comment]
Folks, please!

* Focus to document / stabilize the existent stuff, don't introduce new constructs at this point (as mm-vault redesign goes on, I'll ask most possibly @whymarrh / @bitpshr  for a quick Typescript teach-in. But for now, I stay with "as-is".)
* Isolate the subsystems, clarify ownership(!)
* Then call: owners, please document your code.

Just **one** look at the lists says e.g.:

* @frankiebee owns the tx subsystem, which should go to `app/src/tx` It then gets a README, describing a bit the overall system, and declaring:

> frankiebee is the `Mistress of the Tx`. Don't touch this system, or bad things will happen to you!

Ownership, hierarchy => Start to introduce it, otherwise you're done.

(Actually you don't introduce it, ownership and hierarchy is already there. Its just not visible enough).

Me going away now, deeply hurt that I cannot even triage tickets here in this repo.

(relax, me joking)

**Comment by danjm** [comment]
Files which no one is yet assigned to document:

- [ ] app/scripts/background.js (Assignee: )
- [ ] app/scripts/chromereload.js (Assignee: )
- [ ] app/scripts/config.js (Assignee: )
- [ ] app/scripts/contentscript.js (Assignee: )
- [ ] app/scripts/edge-encryptor.js (Assignee: )
- [ ] app/scripts/first-time-state.js (Assignee: )
- [ ] app/scripts/inpage.js (Assignee: )
- [ ] app/scripts/popup-core.js (Assignee: )
- [ ] app/scripts/controllers/computed-balances.js (Assignee: )
- [ ] app/scripts/controllers/infura.js (Assignee: )
- [ ] app/scripts/controllers/network.js (Assignee: )
- [ ] app/scripts/lib/config-manager.js (Assignee: )
- [ ] app/scripts/lib/createProviderMiddleware.js (Assignee: )
- [ ] app/scripts/lib/inpage-provider.js (Assignee: )
- [ ] app/scripts/lib/port-stream.js (Assignee: )
- [ ] app/scripts/lib/reportFailedTxToSentry.js (Assignee: )
- [ ] app/scripts/lib/setupMetamaskMeshMetrics.js (Assignee: )
- [ ] app/scripts/lib/setupRaven.js (Assignee: )

**Comment by bitpshr** [comment]
I will start with the following:

```
app/scripts/config.js
app/scripts/contentscript.js
app/scripts/edge-encryptor.js
app/scripts/first-time-state.js
app/scripts/inpage.js
app/scripts/popup-core.js
```

**Comment by danjm** [comment]
I'll take these:

- [ ] app/scripts/controllers/infura.js (Assignee: @danjm)
- [ ] app/scripts/controllers/network.js (Assignee: @danjm)
- [ ] app/scripts/lib/config-manager.js (Assignee: @danjm)
- [ ] app/scripts/lib/inpage-provider.js (Assignee: @danjm)
- [ ] app/scripts/lib/reportFailedTxToSentry.js (Assignee: @danjm)
- [ ] app/scripts/lib/setupRaven.js (Assignee: @danjm)

**Comment by bitpshr** [comment]
I will take these:

```
app/scripts/controllers/computed-balances.js
app/scripts/lib/createProviderMiddleware.js
app/scripts/lib/port-stream.js
app/scripts/lib/setupMetamaskMeshMetrics.js
```

**Comment by bdresser** [comment]
Team is this still in play? Looks like a bunch of pieces have been merged, any outstanding?

**Comment by whymarrh** [comment]
I _think_ everything in Dan's comment above 
https://github.com/MetaMask/metamask-extension/issues/3941#issuecomment-380497049 has been done

**Comment by bdresser** [comment]
nice! are we exporting the summary documentation? if not, we should 😄
