### ISSUE TITLE
Enforce data hashes to the expected hash to sign

### ISSUE THREAD

**Issue by PhABC** [MetaMask/metamask-extension#4007]
Very primitive proposal, but I couldn't find something similar yet. Until we reach a consensus on [#712](https://github.com/ethereum/EIPs/pull/712), would be possible to enforce showing that the *about to be signed* hash is indeed composed of the expected data?

For instance, 

When trying to call `web3.personal.sign(hash, web3.eth.defaultAccount)`, metamask could request that the message that hashes to `hash` be provided. For instance ; 

```javascript
if ( hash == web3.sha3(message) ) {
  web3.personal.sign(hash, web3.eth.defaultAccount);
} else {
  throw "Hash to be signed is invalid given the provided message";
}
```
Then metamask could present the actual message to the users (or the hash to be signed, could toggle between each) knowing that the hash *to be signed* was indeed generated from `message`. 

The question would then be  whether there is a way to guarantee that metamask would not allow users to sign if `hash != web3.sha3(message)`? If so, this simple approach could provide an extra security layer to users signing hashes via metamask. 
 
 This approach assumes that most data to be signed are hashes of actual messages. Could skip this process and display a caution message if the data to be signed is not `bytes32`.

**Comment by bdresser** [comment]
@bitpshr @PhABC is this still relevant once support for EIP 712 is merged?

**Comment by Gudahtt** [comment]
I'll close this for now, since there was no reply.

Though I should point out that in general, we don't make any provider changes without a draft EIP being written first. It might be worth exploring this idea on Ethereum Magicians, or in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics), or in an EIP first if you still think it's worth pursuing. Thanks!
