### ISSUE TITLE
Question - what is the best way to detect 'loading' network?

### ISSUE THREAD

**Issue by zulhfreelancer** [MetaMask/metamask-extension#4126]
Hi,

This is not a bug related issue. More to question actually.

As for MetaMask version 4.5.5, I'm able to get the 'loading' network using this:

```
web3.currentProvider.publicConfigStore._state.networkVersion
```

I'm just curious, is there any better way to check if the user's MetaMask is in 'loading' state? I'm currently stuck at the point of checking if the user is actually connected or not connected to blockchain (via the MetaMask extension).

Thank you.

**Comment by frankiebee** [comment]
I would not recommend that as those are internal use and not standard and could change. I would instead recommend `web3.version.getNetwork(cb)` which will return the network version.

**Comment by zulhfreelancer** [comment]
Thanks @frankiebee. Seems like it's gone in web3.js v1.0.0-beta.34
https://github.com/ethereum/web3.js/issues/1353

**Comment by zulhfreelancer** [comment]
According to the file inside 'v1.0.0-beta.34' branch, it doesn't handle 'loading':

https://github.com/ethereum/web3.js/blob/v1.0.0-beta.34/packages/web3-eth/src/getNetworkType.js

So, I think using `web3.currentProvider.publicConfigStore._state.networkVersion` is the closest possible method to check 'loading' network in MetaMask now.

**Comment by Gudahtt** [comment]
We don't currently provide a way for dapps to know whether the network is loading, and I'm not sure we want to. Ideally we'd remove the internal "loading" state entirely, and track that separately rather than as a network type.

Instead I'd recommend using the [`isConnected` provider method](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-isconnected). See [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193#connectivity) for further details about that method, and how connectivity is represented by the provider in general.
