### ISSUE TITLE
Clear Restore Vault Form when MetaMask losses focus

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4261]
Reproduced #3127.

TLDR;
Pre: Have a preloaded vault with seed phrase 1
1) Lock/Logout & Restore from seed
2) Enter seed phrase 2
3) Reload extension from extension list
4) Should have locked after reloading
5) Restore From Seed shows seed phrase 2

Clear the restore-vault-form when users click out of extension. Or persist the Restore Vault screen when data is loaded. Clearing seems to be the logical approach.

**Comment by danfinlay** [comment]
After step 5, does the vault revert to seed phrase 1? Where is the surprise here?

**Comment by tmashuang** [comment]
The main takeaway is that the Restore Vault Form will persist data when closing the extension. This doesn't necessarily need to have a loaded vault to begin with. Users will enter first time flow, enter a seed phrase in Restore From Seed, click out of the extension, and return to the extension that shows vault creation. The surprise would be that when restoring a seed phrase any time after would show a different seed phrase since the form is persisted.

**Comment by danfinlay** [comment]
I'm not sure this qualifies as a solution to #3127, because it requires that a person already has a different seed phrase backed up. It just doesn't resemble the reports we've had, which were first time users.

That said, I can see it could potentially be confusing. This form persistence was always just a band-aid for the fact that the extension "action-view" (the fox menu) collapses whenever you click out of it.

We could alleviate this in another way with the New UI, by forcing users into full screen mode for the restore flow.

**Comment by danfinlay** [comment]
We need to remove the form-persisting-id from the seed phrase box.

**Comment by bdresser** [comment]
fixed in #4648 and #4735
