### ISSUE TITLE
Storage sometimes not working correctly

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4287]
We've had a variety of user reports that resemble our storage strategy intermittently failing:
- New accounts suddenly not existing
- New transactions disappearing from the list
- New nicknames reverting to an old state.

We should investigate how storage failures are handled, make them less likely, and maybe fail more gracefully.

**Comment by danfinlay** [comment]
This could be related to a stream break we saw in the past. If so, this could be reproduced by removing the debouncer from our `background.js` disk writing stream.

**Comment by danfinlay** [comment]
Aaron has seen the first two bullet points happen live, with the app open, which suggests it may not be a storage bug at all, since we only read from storage when starting up the application.

**Comment by danfinlay** [comment]
Could this be related to #4145?

**Comment by MM263** [comment]
Hi, I've discovered a behaviour that might be related to this, but might as well be it's own issue.
We were creating a sign-in page, which utilized Metamask for logging in. That means that we were creating a very large amount of accounts daily (30-100) for testing purposes and after that we were deleting them.

We have discovered that after deleting an account it can be saved by Metamask and instead of generating new wallet when creating a new account Metamask uses an old wallet, that has been removed. Reinstalling Metamask extension removes this behavior, old wallets do not appear when creating a new account after reinstall.

Yesterday I've encountered a bug where 6 accounts just disappeared and after that when I was creating new accounts they had the same wallet addresses.

**Comment by bdresser** [comment]
@danfinlay several user reports of adding tokens then having them disappear regularly. is that the same storage mechanism, or handled separately?

**Comment by danfinlay** [comment]
@bdresser Yes, this is almost definitely a storage failure of some kind.

**Comment by danfinlay** [comment]
Reproduction steps:

- Add log to our disk writing logic.
- Remove the `debounce` from the storage stream in `background.js`, and go about using the application.
- Extension seems to silently fail writing to disk.

**Comment by kumavis** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/4570
