### ISSUE TITLE
Wallets gone

### ISSUE THREAD

**Issue by keybro** [MetaMask/metamask-extension#4302]
Yesterday I created several wallets with the help of MetaMask, and today they disappeared from the account. Why did this happen and how can I restore them? Browser Used: Chrome, Operating System Used: Windows 10

**Comment by nickreynolds** [comment]
I believe I experienced the same bug. I created a 2nd account in MetaMask and transfered ETH to it to make a few transactions a few days ago. When I wanted to make some more transactions today, I checked and noticed that my 2nd account was not there anymore.

Eventually, I figured out that by creating a 2nd account again, I could recover that account, since it creates one at the same address. 

Still, this is a pretty frightening bug that would terrify the average user.

Browser: FIrefox
OS: MacOS 10.13

**Comment by nik5504** [comment]
Nick ,what do u mean by "creates one at the same address " as it doesnt .so how could u recover your original account even im stuck there

**Comment by bdresser** [comment]
hey @keybro, @nickreynolds - please email support@metamask.io with a description of your issue and a copy of your state logs. [here's an explainer](https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue) on how to pull your logs if you need.
