### ISSUE TITLE
My MetaMask does not work at all!!!

### ISSUE THREAD

**Issue by DSdasaBVS** [MetaMask/metamask-extension#4371]
hello!   yesterday i  was trying to send out my ETH from MetaMask and all the time which amount i was trynig to sent it was not enough ETH to send due that fucking GWEI or 21000 or 22000 or even 2500000 i was paying for trasaction...now my wallet does not oppening at all! WHY???? i'm tired about such problems with that usless ETH..
please help me and i need my money

**Comment by DSdasaBVS** [comment]
and right now even can not open my META MASK ...
whats happening???

**Comment by DSdasaBVS** [comment]
it solved!!!!

**Comment by EAR74** [comment]
I have tried to add to chrome,never have seen that little orange fox in upper right.The problem with cryptocurrency is that many can simply buy bitcoin,eth,but it seems to be a lot harder buying any new coin,altcoin.It is mostly because half the exchanges dont have access for the U.S...Some exchanges have a few,yet there is not one that is decentralized when u have to give ur first born to deal with them.
