### ISSUE TITLE
ENS Subdomain Eager Resolve

### ISSUE THREAD

**Issue by BKDaugherty** [MetaMask/metamask-extension#4380]
Metamask is a little to eager in trying to resolve my ENS subdomain! It works great when I copy and paste the ens name in, but doesn't do too well when I type it!

![metamaskbug](https://user-images.githubusercontent.com/18391567/40581927-a0f793b4-611a-11e8-9b06-2d4a18011c1f.gif)

* Expected Behavior : Resolved ENS Subdomain after I finish typing it in.
* Actual Behavior: Eager resolve before I have finished
* Browser Used: Chrome
* Operating System : MacOS High Sierra 10.13.3

**Comment by danfinlay** [comment]
I agree, we could save the validation for either:

- on submit
- once the string ens with a tld (should have a period between two non-zero length strings)

**Comment by danjm** [comment]
> once the string ens with a tld (should have a period between two non-zero length strings)

We already do this. So perhaps we just need to increase the delay on the debounce.

**Comment by briansoule** [comment]
It seems to work properly in the old UI

**Comment by Arachnid** [comment]
Could you just leave it as the name? Replacing it with the address in the input field isn't ideal.

**Comment by lyricalpolymath** [comment]
the resolution should be verified when you are done entering the .eth or any other TLD (since now ens supports .xyz and will soon support more)

also agree with Nick that the name should stay visible 
and as I wrote here https://github.com/MetaMask/metamask-extension/issues/4616#issuecomment-422763803
.... probably ALSO display a greyed out and shorhand version of the address

**Comment by Gudahtt** [comment]
Our UI has changed quite a bit since this was first reported; this now appears to be fixed
