### ISSUE TITLE
Document Adding Custom Networks

### ISSUE THREAD

**Issue by GOOGZHOU** [MetaMask/metamask-extension#4381]
https://github.com/MetaMask/metamask-extension/blob/develop/docs/adding-new-networks.md

app/scripts/config.js  this file doesn't exist with the latest version. 
would appreciate if there is an example showing the details of the changes!

**Comment by mdranger** [comment]
It seems the document is for the old ui. For the new UI, the following files need to be changed.
```
ui/app/app.js
ui/app/components/buy-button-subview.js
ui/app/components/dropdowns/network-dropdown.js
ui/app/components/network.js
ui/app/components/pages/settings/settings.js
ui/app/css/itcss/components/network.scss
ui/lib/account-link.js
ui/lib/etherscan-prefix-for-network.js
```

You need also add variables in these files
```
app/scripts/config.js
app/scripts/lib/buy-eth-url.js
app/scripts/lib/config-manager.js
app/scripts/controllers/network/enums.js
app/scripts/controllers/network/util.js
```

To display the message on the screen, the info needs to be added in this file 
`app/_locales/en/messages.json`

After these steps, it seems to me that I need to modify the eth-keyring-controller package to add the URL, otherwise it won't work.
The URL values are defined in eth-keyring-controlle/test/lib/config-manager.js
and config.js

```
const MAINET_RPC_URL = 'https://mainnet.infura.io/metamask'
const ROPSTEN_RPC_URL = 'https://ropsten.infura.io/metamask'
const KOVAN_RPC_URL = 'https://kovan.infura.io/metamask'
const RINKEBY_RPC_URL = 'https://rinkeby.infura.io/metamask'

```
After all these changes, I can see the new custom network showed up in the dropdown menu. 
However, the new custom network didn't connect at this time. I am still figuring out the problem. The same URL works well if I put it in the custom URL. 
When I get it connected, I will put more detailed documents here.
Hope these helps.

**Comment by whymarrh** [comment]
Hey, I've deleted this stale doc in #7999, apologies for the long-standing confusion it has caused. Going forward, we really don't need _more_ networks in the network list. (We will hopefully be able to expose some of this functionality via plugins in the distant future.)
