### ISSUE TITLE
Can I detect when resubmit in MetaMask?

### ISSUE THREAD

**Issue by aifirst** [MetaMask/metamask-extension#4620]
I am developing ethereum application with MetaMask.
After sending ethereum transaction to server, I should send hash of transaction to server for confirmation.
But, in MetaMask, there is "resubmit feature" when too long pending.
Then, new transaction(different hash from before) is made. but application cannot detect it nor cannot send hash of new transaction to server.
Is there solution which application can detect resubmitted transaction automatically?

Thank you.

**Comment by bdresser** [comment]
hey @aifirst - there's no solution to detect a resubmitted transaction, but in general it's best practice to rely on contract events (rather than the tx hash) for this exact reason. [This piece](https://media.consensys.net/technical-introduction-to-events-and-logs-in-ethereum-a074d65dd61e) has a bit more detail.

**Comment by aifirst** [comment]
Thank you @bdresser, I would use contract event.
