### ISSUE TITLE
Send Token - Formatting and UI issues on Firefox / Apple Mac (BETA)

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#4645]
I created a custom 'MART' token to test this. Go to the Send Token screen on Metamask BETA.

See attached screenshot #1.

a) It says "insufficient funds", I don't know why - if there is zero, it should say zero - infact there are 1000 MART tokens (which it determined correctly on the screen previous to this).

See attached screenshot #2. -- Once I click "up" arrow on amount field the "insufficient funds" message goes away, and is replaced with 0. 

b) There is not width to display the number, the number should say 22, but as you can see, it only shows part.

c) There is a USD amount under the token amount - does this make sense - I guess you are dynamically looking up the price somehow, maybe if you can't find a price, it should say that - idk.

d) In screenshot #1) the Gas Fee section it has calculated 0.0152 ETH to do the send ($7.08), don't know how it got to that, but obviously that is waaaaaay too high. In screenshot #2) it has (inexplicably halved that estimate - still waaaaay too high. Strangely once I pasted in the destination address, it recalculated to 0.000000004 ETH / $0.14 and I sent the transaction without problems. screenshot #3.

<img width="346" alt="screen shot 2018-06-22 at 14 38 35" src="https://user-images.githubusercontent.com/11575008/41780589-0a48e15c-762d-11e8-9c7d-7d3bc1f25bbe.png">
<img width="344" alt="screen shot 2018-06-22 at 14 43 51" src="https://user-images.githubusercontent.com/11575008/41780587-0a223296-762d-11e8-9bbd-9758f07a8109.png">
<img width="328" alt="screen shot 2018-06-22 at 14 56 58" src="https://user-images.githubusercontent.com/11575008/41780585-09f39206-762d-11e8-8711-525321eba911.png">

  *  Browser Used
Firefox
  *  Operating System Used
Apple Mac

**Comment by bdresser** [comment]
thanks @prographo. we're in the process of refactoring the confirm screen on the new UI so this may be addressed as part of that work (#4404). heads up @alextsg

**Comment by danjm** [comment]
@prographo Thanks a lot for filing these issues. You are correct that there are a lot of improvements that can be made here:

(b) Is fixed by an already in review PR: https://github.com/MetaMask/metamask-extension/pull/4647

For the other issues you've addressed I have created tickets that outline solutions:

(a) https://github.com/MetaMask/metamask-extension/issues/4660
(c) https://github.com/MetaMask/metamask-extension/issues/4661
(d) https://github.com/MetaMask/metamask-extension/issues/4662

(d) is probably also partially a result of a gas price estimation bug that will likely be resolved with https://github.com/MetaMask/metamask-extension/issues/4615

**Comment by bdresser** [comment]
various issues mentioned here have been broken into separate tickets, outlined above. closing this one~
