### ISSUE TITLE
Design for web3 opt-in dialog

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4761]
#4703 implements the first step towards log-in per site, where a dapp requests access to web3 all at once. Current implementation looks like this:

<img width="370" alt="screen shot 2018-07-09 at 4 51 08 pm" src="https://user-images.githubusercontent.com/1016190/42475334-55275e74-8398-11e8-96ac-7adc63238ee2.png">

Note that we're not yet at the point of requesting access to a specific account, just access to the web3 API in general. 

Basic interaction is right, but this could use some design love. 

Could also add a touch more detail to the second sentence, like "Exposing the web3 API will allow the site to see your public Ethereum addresses, so always make sure you're on the right site before approving access."

**Comment by bdresser** [comment]
@cjeria pulling in to this sprint if you have time - should be a small one yeah?

**Comment by cjeria** [comment]
@bdresser this may need to go through a few iterations and some light user testing, but should be a fairly quick one.

Question for @bitpshr. How will this window be triggered? User action or automatically upon user visiting a dapp with MetaMask unlocked (no user action)? 

Also, I know this is MVP and the main copy/language here is placeholder for this feature which most technical users will understand but will likely confuse non-technical users. So I'm thinking we go with a traditional "login" metaphor since the goal of this feature is to let users login to dapps via this web3 request. So on the surface it's "Login into https://bitpshr.net"? but under the hood it's allowing the dapp to request access to the web3 api. Does that make sense? Am I missing anything here?

**Comment by bitpshr** [comment]
@cjeria, unfortunately, we can't always know how this window is triggered. Dapps programmatically trigger the window itself, but there's no mandate as to _when_ they trigger it. For example, some dapps may ask for approval after a user clicks some sort of a sign in button, whereas other dapps may trigger it on page load with no action at all. Dapps can implement any UX they desire around requesting approval.

To that end, I think your point about verbiage is valid. I think we should make it more approachable, but still general enough to work with any UX flow that may lead to a user seeing it.

**Comment by cjeria** [comment]
I think in the article announcing this new change, we can suggest the ideal ux design pattern which would be for dapps to add include a ``LOGIN`` button. This could also be used to set a new and dapp interaction standard across the space.

**Comment by bdresser** [comment]
https://github.com/MetaMask/Design/issues/36
