### ISSUE TITLE
New MetaMask UI, wrong token amount displayed

### ISSUE THREAD

**Issue by jchittoda** [MetaMask/metamask-extension#4780]
Wrong ERC20 token amount is displayed and sent different amount of ERC20 tokens.
I actually entered 2791 COSS in MetaMask, and when I clicked "Confirmed" it showed as below screen shot.
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior : Token amount must be exactly same.
  *  Actual Behavior : New MetaMask UI shows different amount and sent different amount
  *  Browser Used : Chrome Version 67.0.3396.99 (Official Build) (64-bit)
  *  Operating System Used: MacOS High Sierra 10.13.5

  Screenshots are very helpful and will expedite your issue being resolved!
<img width="593" alt="screen shot 2018-07-12 at 19 29 09" src="https://user-images.githubusercontent.com/2144050/42638131-83b1b3b0-860a-11e8-998e-4dcbf1e6f7fd.png">

Tx: https://etherscan.io/tx/0x7eafdbc4d9a4ea77f854382ee9e299e6d6e09c8ea032beb10809778b7dd30c04

**Comment by Gudahtt** [comment]
Thanks for the report @jchittoda!

I am very sorry for our lack of response here. Please let us know if you're still experiencing this issue, but I'm going to close it for now because of how old this issue is. The UI depicted here has changed quite a bit, so it seems unlikely we're still affected by this bug.
