### ISSUE TITLE
(developer) Getting 'undefined' as the result of calling methods on the web3 object created by Metamask?

### ISSUE THREAD

**Issue by roschler** [MetaMask/metamask-extension#4807]
I'm trying to get the network ID from the Web3 object injected into web pages by the Metamask extension in Chrome on the client side (i.e. - while running Javascript code in the browser).  I have code that confirms that the object exists and it does.  I definitely have the Metamask extension installed and configured in Chrome.  I have clicked on the extension and I am definitely connected to the Ganache network client (Localhost 8545).  However, every time I call `web3.version.getNetwork()` the result is `undefined`.  Does anyone know why this is happening and how I can fix it?  I am using version **^1.0.0-beta.34** of the web3 Node.JS package.

Note, I tried the same test with **web3.eth.getAccounts()** and that too is coming back *undefined*.  I'm guessing I'll get the same result with any of the Web3 methods/properties I try.

		// Make sure the Web3.js object has been defined.
		web3_helpers.web3AndMetamaskCheck();
		
		if (typeof gameDetailsObj == 'undefined' || gameDetailsObj == null)
			throw new Error(errPrefix + 'The game details object is unassigned.');

		if (typeof currentUserObj == 'undefined' || currentUserObj == null)
			throw new Error(errPrefix + 'The current user object is unassigned.');

        // >>>>> getNetworkCall is ALWAYS 'undefined'.			
		var getNetworkCall = web3.version.getNetwork();

**Comment by Gudahtt** [comment]
The `web3.version.getNetwork` function requires a _callback_, because it is an async function.

Please refer to our [documentation](https://docs.metamask.io/guide/) for further information about how to use MetaMask. We don't recommend using web3 anymore (and we will soon stop injecting it automatically), but it should still work if that's what you want to use.

Check out our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics) if you have any further questions. Thanks!
