### ISSUE TITLE
Support multiple vaults

### ISSUE THREAD

**Issue by cowpig** [MetaMask/metamask-extension#4828]
I installed metamask a while ago on brave. I want to use it now, but have no idea what the vault password or seed phrase were. There's no option to reset the vault or create a new one. 

After some googling the only option seems to be to remove/reinstall the extension. Brave doesn't support this: you can only disable extensions, not delete them. So I have no way to use metamask without removing and reinstalling my entire browser.

**Comment by danfinlay** [comment]
Interesting point, we should probably have a "create new vault" option on the lock screen. A downside is this means that anyone with access to your browser (even without your MetaMask password, while locked) would have the ability to wipe your MetaMask instance.

**Comment by cowpig** [comment]
Could the existing vault be archived instead of deleted?

**Comment by danfinlay** [comment]
Sure, but then we'd have to build the UX around recovering it, etc, too.

**Comment by Matthalp** [comment]
@danfinlay I am also having this issue.

**Comment by bdresser** [comment]
From #5305, some users just want to delete their current vault and create a new one (which is sort of a subset of this feature)

**Comment by jackpot311** [comment]
i also are having a issue with getting my vault data for my old metanask, i had my browser chash, when i visited megatopois city, a game in which my chrome book could not handle the site.
at first i thought i came across the vault data, but it had some different ones there. becuase i had delete my old extension, and reloaded a new one, as i thought i had been hacked, because it was all crashed..
now i can not find that vault data, i have had it developer mode on.. so i dont understand why. i can not bring anything back.. i have also have emailed metamask asking for help. they also ask if i have tried the vault. but i not sure how. as it is confusing for me

**Comment by bdresser** [comment]
sorry to hear @jackpot311. please email support@metamask.io and we'll do our best to help out.

**Comment by pr0toshi** [comment]
bump

**Comment by Robbiekruszynski** [comment]
Hello! 

I'm going to go ahead and close this ticket and would encourage this conversation be ported over to [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics) so we can continue to look into related issues.
