### ISSUE TITLE
NewUI: Contract method calls showing "New Contract" incorrectly

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4836]
Posting a bounty on GitCoin is resulting in this view:

<img width="361" alt="screen shot 2018-07-18 at 6 41 37 pm" src="https://user-images.githubusercontent.com/542863/42961666-3d6f8e56-8b44-11e8-8f96-20b11879a2ab.png">

We should only show "New Contract" if there is no recipient for that tx, and there is data.

**Comment by bdresser** [comment]
@alextsg

**Comment by alextsg** [comment]
@danfinlay "New Contract" is incorrectly being shown because we were looking up the recipient address within `state.metamask.identities`, so we can instead display the sliced address (`0xabcd...defg`) if the recipient address isn't found there. Will that be a good solution?

Regarding
> We should only show "New Contract" if there is no recipient for that tx, and there is data.

In that case, we will show "Contract Deployment" as the action. Here we're showing the action "Confirm", which I believe is correct, and the issue here is just about displaying the recipient.

**Comment by danfinlay** [comment]
> Will that be a good solution?

Showing the sliced address is a good fallback, but in this case, [the StandardBounties contract name is in our eth-contract-metadata repo](https://github.com/MetaMask/eth-contract-metadata/blob/master/contract-map.json#L527), so we should default to that `.name` property first.

**Comment by alextsg** [comment]
Sounds good. We'll check for the recipient address in the the contract map, then fall back to the sliced address.
