### ISSUE TITLE
RLC ERC20 token logo out of date

### ISSUE THREAD

**Issue by sulliwane** [MetaMask/metamask-extension#4891]
Hello,
The logo displayed when adding RLC ERC20 token is not correct:

![download](https://user-images.githubusercontent.com/1733686/43265049-ff953a1e-90e7-11e8-8b5b-1993f8409046.png)

Correct logo can be downloaded from the official iExec RLC website: https://iex.ec/press-kit/press-kit-iExec.zip

Thank you for your help!

RLC CMC link: https://coinmarketcap.com/zh/currencies/rlc/

**Comment by estebanmino** [comment]
Hi @sulliwane, please submit the updated logo here https://github.com/MetaMask/eth-contract-metadata in order to change it

**Comment by Maayu2415** [comment]
Thank you.

ส่งจากสมาร์ทโฟน Samsung Galaxy ของฉัน
-------- ข้อความดั้งเดิม --------จาก: Esteban Miño <notifications@github.com> วัน​ที่: 26/7/18  20:56  (GMT+07:00) ถึง: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> เรื่อง: Re: [MetaMask/metamask-extension] RLC ERC20 token logo out of date (#4891) 
Hi @sulliwane, please submit the updated logo here https://github.com/MetaMask/eth-contract-metadata in order to change it

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/metamask-extension","title":"MetaMask/metamask-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/metamask-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@estebanmino in #4891: Hi @sulliwane, please submit the updated logo here https://github.com/MetaMask/eth-contract-metadata in order to change it"}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/metamask-extension/issues/4891#issuecomment-408106100"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/issues/4891#issuecomment-408106100",
"url": "https://github.com/MetaMask/metamask-extension/issues/4891#issuecomment-408106100",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [MetaMask/metamask-extension] RLC ERC20 token logo out of date (#4891)",
"sections": [
{
"text": "",
"activityTitle": "**Esteban Miño**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@estebanmino",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"MetaMask/metamask-extension\",\n\"issueId\": 4891,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"MetaMask/metamask-extension\",\n\"issueId\": 4891\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MetaMask/metamask-extension/issues/4891#issuecomment-408106100"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361186153\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sulliwane** [comment]
@estebanmino thanks, DONE => https://github.com/MetaMask/eth-contract-metadata/pull/116

**Comment by Maayu2415** [comment]
Close to be block.


ส่งจากสมาร์ทโฟน Samsung Galaxy ของฉัน
-------- ข้อความดั้งเดิม --------จาก: Victor <notifications@github.com> วัน​ที่: 26/7/18  21:04  (GMT+07:00) ถึง: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: mjaniam2415@gmail.com, Comment <comment@noreply.github.com> เรื่อง: Re: [MetaMask/metamask-extension] RLC ERC20 token logo out of date (#4891) 
Closed #4891.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/metamask-extension","title":"MetaMask/metamask-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/metamask-extension"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4891."}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/metamask-extension/issues/4891#event-1755109140"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/issues/4891#event-1755109140",
"url": "https://github.com/MetaMask/metamask-extension/issues/4891#event-1755109140",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [MetaMask/metamask-extension] RLC ERC20 token logo out of date (#4891)",
"sections": [
{
"text": "",
"activityTitle": "**Victor**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sulliwane",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MetaMask/metamask-extension/issues/4891#event-1755109140"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361186153\n}"
}
],
"themeColor": "26292E"
}
]
