### ISSUE TITLE
Developer question: 30 second delay before Tx hash received when using Rinkeby test network?

### ISSUE THREAD

**Issue by roschler** [MetaMask/metamask-extension#4928]
When I call the  _<prepared method>.send();_ from Web3.js based browser Javascript code, there is a 30 second delay right after I submit payment via the Metamask extension before the call returns with the Tx hash.  Note, I am _not_ referring to the time it takes for the block to mine.  I'm saying it takes 30 seconds just to get the Tx hash back from the Rinkeby network, letting me know my transaction is pending in the mining pool.  In other words:

- I make the  _<prepared method>.send();_ call
- Metamask extension pops up
- I submit my payment
- 30 seconds passes before the **.then()** block attached to the _<prepared method>.send();_ call is triggered.

Is this normal?  If not, what could be causing this problem and how could I fix it?  I have done hundreds of trials with different smart contract methods, and it's always the same.  This doesn't happen when running with Ganache.  I know that's a local network, but the fact it's always a 30 second delay with Rinkeby indicates something suspicious.  I see the same problem on my server side code when signing and sending transactions on the server side using the Infura API.  Does Metamask use Infura?

**Comment by Strernd** [comment]
Yes Metamask uses Infura. 
If I'm not mistaken the issue is following: The transaction hast to be mined, so it is completed, when it is included in a new block. Resulting from this, the transaction takes until the next block is mined. On Ganache this is near instant, because it mines only when transactions come in and on the testsnets and main nets, this may take a while, because only around 6k blocks are mined per day (https://etherscan.io/chart/blocks) .
