### ISSUE TITLE
MetaMask shows, that it is connected to custom RPC, but is still connected to prior selected RPC

### ISSUE THREAD

**Issue by Strernd** [MetaMask/metamask-extension#4944]
MetaMask Version 4.8.0
Chrome 68 on macOS (High Sierra)

Tried restarting and reinstallation a few times.

Steps to reproduce:

![image](https://user-images.githubusercontent.com/2428581/43649559-c00cf40c-973d-11e8-951e-5174d4f013a2.png)
Connected to Rinkeby. Account balances are correct.

![image](https://user-images.githubusercontent.com/2428581/43649601-d8638322-973d-11e8-8455-d9dc7e3cea59.png)
Enter custom RPC and click Save. Nothing happens. Close popup.

![image](https://user-images.githubusercontent.com/2428581/43649626-ea0aa948-973d-11e8-966e-1b1c08642fc1.png)
Shows connection to custom RPC, but balances from Rinkeby. My dapp fails to find the contact address, since it uses the wrong network.

Expected behavior:
MetaMask connects to custom RPC and shows balances of custom RPC, or at least is connected to the custom RPC and injects the according provider.

**Comment by bdresser** [comment]
@Strernd I've encountered the same. I think what you're specifically seeing is related to https://github.com/MetaMask/metamask-extension/issues/4253 where our custom RPC field doesn't handle uppercase HTTP very well. It shows a connection, but actually remains connected to the previous network. 

Trying changing `HTTP` to `http`, that should resolve your issue. This will be fixed in the next release, hopefully early next week.

If you enter an otherwise invalid RPC URL, you may hang on the spinner as described in https://github.com/MetaMask/metamask-extension/issues/4604

Closing for now, please re-open if the above doesn't fix your issue, or if this isn't the same as #4253.
