### ISSUE TITLE
Update Logo Wordmark

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4953]
We have an updated wordmark, let's update in the app https://github.com/MetaMask/brand-resources

![image](https://user-images.githubusercontent.com/597770/43734272-3029ea8a-9985-11e8-9909-c7fd5c5b3198.png)

**Comment by alextsg** [comment]
@cjeria The updated SVG looks good, but can we crop the the image to remove the extra outer space so that the BETA label doesn't look so detached from the logo? Or if you could create another SVG that includes the BETA label that would be great.

![image](https://user-images.githubusercontent.com/8051479/44293044-81d93280-a23d-11e8-8c57-2f9d0ef9b6c0.png)
