### ISSUE TITLE
Link to increase gas price transactions gets buried beneath attempted resends

### ISSUE THREAD

**Issue by edmundedgar** [MetaMask/metamask-extension#5093]
**Describe the bug**
Link to increase gas price transactions gets buried beneath attempted resends

**To Reproduce**
Send a series of transactions with low gas price
Bump the transactions, but still to prices that are too low to immediately get mined
The link to resent the blocking transaction ends up buried several scrolls below the default view

**Expected behavior**
Expect a link on most recent resend, or, since the stuck transaction affects all the subsequent transactions, at the top of the page, allowing me to raise the gas price and get things unstuck.

For screenshot etc, see the issue I opened before I accidentally scrolled down for cat-related reasons and discovered the link
https://github.com/MetaMask/metamask-extension/issues/5088

**Comment by bdresser** [comment]
@edmundedgar since transactions must be processed sequentially by nonce, only repricing the first slow transaction will help the others land faster. 

In 4.9 we started showing the "reprice" option on the earliest transaction only, since that's the one actually blocking. We had a lot of users repricing later transactions and getting frustrated when they still wouldn't confirm.

All that said, I agree it's easy to lose track of the "Reprice" link if you're submitting a lot of transactions quickly. We're working on redesigning the whole transaction detail view – more detail here: https://github.com/MetaMask/Design/issues/25. You're not the first person who's mentioned this, so I added a couple thoughts, but more feedback is welcome!
