### ISSUE TITLE
Failed transaction is showing up as confirmed

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#5117]
**Describe the bug**
A transaction that Etherscan shows failed is showing up as confirmed.

**To Reproduce**
1. Create a minime token send transaction with gas limit at 41245
2. Wait for confirmation
3. See that it confirmed 
4. See error in Etherscan even though MetaMask shows it as confirmed

**Expected behavior**
Failed transactions should show up as failed in MetaMask. Confirmed implies success.

**Screenshots**

![fail-confirm](https://user-images.githubusercontent.com/9424721/44427648-03370a80-a547-11e8-85a3-332910ad63ca.png)

![etherscan-fail](https://user-images.githubusercontent.com/9424721/44427699-2497f680-a547-11e8-8366-c02c89918936.png)

https://etherscan.io/tx/0x2c823004fde9406c288c06ef4fe1113be63ba62dbbe27eede331b739cea91775

**Browser details (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser: Chromium
 - MetaMask Version: 4.9.3
 - Old UI or New / Beta UI? New

**Additional context**

Was sending ANT to an EOA, with too little gas it seems.

**Comment by bdresser** [comment]
hey @john-light - this is actually some non-intuitive expected behavior. MetaMask is displaying whether or not the transaction was confirmed on-chain, not whether it was ultimately successful. I realize this is quite confusing, you're not the first person to bring it up. 

Since we're now getting txReciept data, we can finally begin to distinguish on-chain failures from other successful transactions (discussed on https://github.com/MetaMask/Design/issues/46)

Closing this for now

**Comment by trx2042** [comment]
Please reopen this issue. It still isn’t fixed since 2018.  Today I missed out on a valuable NFT purchase on Eth chain because it showed as confirmed in MM but had actually failed on Etherscan and I didn’t know it.  I tried to buy a 2nd NFT right after the 1st but it failed for lack of gas fees.  Possibly this error could have happened due to my doing 2 of the same transactions as quickly as possible and there not being enough for gas on the 2nd transaction.  Regardless MM falsely showed a transaction as successful when it had failed on the blockchain.  A BIG bug that should have been fixed long ago.  BTW, I’ve worked in Tech for 20 years and never have I seen as irresponsible coding as on the part of blockchain coders.  Y’all suck, are so unprofessional and irresponsible with your code at the expense of the users you exploit.  Good job on making the blockchain a piece of sh*t!
