### ISSUE TITLE
Warn users if submitting transaction when several tx already pending

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5126]
**What problem are you trying to solve?**
Users often submit multiple transactions in a row and are confused / frustrated when they don't confirm, especially if they submit a transaction with high gas while something else is already pending. Many folks don't realize tx need to be processed in nonce order. See https://github.com/MetaMask/metamask-extension/issues/5113 and https://github.com/MetaMask/Design/issues/25#issuecomment-404889603

**Describe the solution you'd like**
When a user has several pending tx and is about to confirm another tx, we could show a dismiss-able warning that says something like. 
>You have X pending transactions that must be confirmed before this transaction will confirm. If you'd like to speed up those transactions, click here.
Open to discussion whether we should show this warning if the user has as few as 1 pending tx, or if we should only show it if the user has several (>3) backed up.

**Comment by danjm** [comment]
Some further suggestions/details:

The warning can look like the cancel modal (but with only title, text and buttons; not the highlighted eth amount):

![Screenshot from 2019-03-13 14-03-25](https://user-images.githubusercontent.com/7499938/54297166-43201680-4599-11e9-9fa2-ea9848549960.png)


Clicking the yes option should take the user to the main screen with the speed up sidebar opened as is done here:

![Screenshot from 2019-03-13 14-02-25](https://user-images.githubusercontent.com/7499938/54297298-8f6b5680-4599-11e9-8ab3-3ed804503823.png)

This should be opened for the blocking transaction. That transaction should be highlighted in some way so that the user can know which transaction they are speeding up.

**Comment by graemeblackwood** [comment]
I'd like to upvote this – it's even more critical now with gas prices the way they are.

**Comment by bschorchit** [comment]
Closing this as we now have:
<img width="222" alt="Screen Shot 2022-06-13 at 18 32 22" src="https://user-images.githubusercontent.com/34968356/173448963-9cfe77c6-6b63-4a05-8474-96c5d23bea78.png">
