### ISSUE TITLE
Transactions are not being submitted

### ISSUE THREAD

**Issue by anonymoous** [MetaMask/metamask-extension#5146]
Win10
Chrome browser

Whenever i submit transactions through metamask, most of them don't get submitted.  When i click on the hash to find on blockchain, blockchain explorer doesn't find the hash, so its not getting submitted properly.  Very frustrating issue for me, can someone help?

**Comment by grafx77** [comment]
Hey bud...did you ever find a solution to this? I'm having the same issue.

**Comment by anonymoous** [comment]
No, same still

**Comment by Weljo156** [comment]
same here.  I'm quite new to this so at first I thought it was something about ethereum network. now, after 3 unsumitted transactions in 9 days I'm crazy since I need to do token swap.

**Comment by beachncryps71** [comment]
I have the same problem.  I received some ETH without any problems 2 days ago, but I've tried to send 3 transactions since then and although Metamask says they have been submitted none of them have shown up on Etherscan.  Very frustrating.

**Comment by beachncryps71** [comment]
Just to add to my previous post about my problem sending transactions using Metamask... I am able to receive ETH when I send it to my Metamask address from another website without any long delays or problems.  I have also tried using the new and old versions of Metamask over the last two days to send transactions but even though Metamask says the transactions have been submitted when I check for them on Etherscan I get the message "Sorry, we are unable to locate this transaction hash".  Both the new and old versions of Metamask are running extremely slow on my computer and since Metamask use to run well on my computer I'm thinking that my problem is being caused by the Metamask extension itself.   Now I'm not a computer whiz and I'm pretty new to the crypto world so I'm not sure what will happen if I try deleting and reinstalling the Metamask extension on my Chrome browser.  If I do so will I forever lose the ETH balance and any token balances that currently show on my Metamask extension?  Any help I can get here will be very appreciated!

**Comment by bdresser** [comment]
@anonymoous do you have several pending transactions? if you have an older transaction that's waiting to confirm, it will prevent future transactions from confirming no matter how high you price the gas.

Transactions sent from the same account must be mined in the order they were submitted - this is enforced by each transaction's "nonce." So if I have a transaction that's still pending from yesterday, any transactions I submit today won't confirm until yesterday's transaction confirms, since they have a higher nonce.

In MetaMask (both UIs) you're able to "reprice" a transaction with a higher gas price. If you have a number of tx that are pending, I recommend you find the earliest pending tx and reprice the gas so it gets confirmed. This should allow your later tx to confirm as well.

We realize this isn't intuitive for beginners and plan to reformat the way we show pending and stuck tx in #4786.

**Comment by bdresser** [comment]
@beachncryps71 as long as you back up your seed phrase, you'll be able to uninstall and re-install with no problem.

**Comment by beachncryps71** [comment]
Thanks for the help!

**Comment by danielschonfeld** [comment]
This is happening to me now, metamask 7.1.1. Both Chrome and Firefox on mac.

If after I submit a transaction I can't see it on etherscan it'll never show up.  More gas, less gas its all the same.  Once this starts the only way to go back to operational status is to uninstall metamask and reinstall.

This is happening with a hardware account not a metamask native one.

**Comment by saszer** [comment]
i have a tx, im trying to submit a new one with higher gas price, same nonce. On trying that, I can see on metamask activity UI its trying to submit with a rotating loader but on etherscan " ..unable to locate this TxnHash" . Tried it multiple times and gave it enough time.
