### ISSUE TITLE
Display & send individual collectibles

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5230]
@estebanmino is working on the extension's ability to pull custom images for users' collectibles / ERC 721 tokens. These need a home in the extension. 

MVP idea we could keep them on the side-menu with other tokens, then display individual tokens in a scrollable list - either as vertical scroll in a tab next to History, or as a horizontal scroll where the centered icon is? 

Longer-term we can consider whether the side-menu should be a feature of the home screen itself (as discussed in Slack) etc.

Collectibles will each have a "name" and an image to start.

<img width="356" alt="screen shot 2018-09-10 at 4 33 33 pm" src="https://user-images.githubusercontent.com/1016190/45329886-7533bb80-b517-11e8-84be-b4229c080cee.png">

**Comment by bdresser** [comment]
@estebanmino will we also support sending NFTs like any other token?

**Comment by estebanmino** [comment]
yeah that's the idea

**Comment by bdresser** [comment]
@estebanmino what data is available per token? We have an image - do we have a name or any other data?

Any other things we should be aware of as @bahnju starts thinking about design?

**Comment by estebanmino** [comment]
@bdresser @bahnju we have:
- Collectible contract name
- Collectible specific name
- Collectible specific token ID
- Collectible specific image

**Comment by bdresser** [comment]
Might be worth looking at https://alphawallet.com as well!

**Comment by bdresser** [comment]
The send flow also needs to be designed for mobile. Separate but related issue https://github.com/MetaMask/MetaMask/issues/282

**Comment by aakilfernandes** [comment]
Hey, just wanted to pipe in here to give my thoughts since we're working on NFTs for GuildCrypt.

1. In general, no-one knows what the symbol of NFTs are. Using the Name instead of the Symbol would be better.

2. "1 CK" is confusing to users. Should be "CryptoKitty #1"

3. Not all NFTs implement an image. There's a Metadata standard for the URI of off-chain data, but AFAIK no standard for the form of that data (i.e. JSON, or the keys in the JSON). There's a defacto standard which is implemented by OpenSea

4. IMHO, the ERC721 metadata standard is pretty broken, since it can't be upgraded to work with decentralized storage providers (such as IPFS or Swarm).

**Comment by bdresser** [comment]
partially blocked by #5806

**Comment by bdresser** [comment]
@estebanmino which GABA controller would make this possible in the extension?

**Comment by estebanmino** [comment]
@bdresser NetworkController and PreferencesController. When we have that we could integrate assets related controllers.

**Comment by Garito** [comment]
Any advance on this issue?

**Comment by bschorchit** [comment]
Closing this as it's fixed with NFT support on extension
