### ISSUE TITLE
Bug: Hide ethereum USD value for custom RPC

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#5327]

**Comment by bdresser** [comment]
@eosclassicteam expected behavior in #5134 is to lookup the asset on the balanc3 API, then look up on the cryptocompare API (or CMC as per your last comment), then if nothing is found simply don't show a conversion. That sound reasonable?

**Comment by eosclassicteam** [comment]
@bdresser Not for #5134 , but also for test networks like ropsten or rinkeby

![testcoin](https://user-images.githubusercontent.com/39383087/46120467-c7304d00-c24a-11e8-9193-2162c8d07c62.PNG)

Some people think they are spending real ETH on test networks due to this fiat value conversion for testnet coins

**Comment by hackmod** [comment]
> @eosclassicteam expected behavior in #5134 is to lookup the asset on the balanc3 API, then look up on the cryptocompare API (or CMC as per your last comment), then if nothing is found simply don't show a conversion. That sound reasonable?

that was a bug in PR #5134 and fixed for customRpc now.

**Comment by bdresser** [comment]
this work is being tracked in https://github.com/MetaMask/metamask-extension/issues/4775
