### ISSUE TITLE
sent ETH from Coinbase to MetaMask says successful but ETH not showing in METAMASK wallet .... 

### ISSUE THREAD

**Issue by Jaypantera** [MetaMask/metamask-extension#5341]
I sent ETH from Coinbase to MetaMask says successful but ETH not showing in METAMASK wallet have done this before with no issues,   etherscan says "successl" ....... can anyone help? please.

TX HASH: 0xf81af01c337bed498c6dc02fcd84d3704fc3c79e119d77634849fcba504b9ed2

Using MS Windows
Chrome 
metamask 4.10.0

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by tmashuang** [comment]
Screenshots?

**Comment by tmashuang** [comment]
Screenshot of MetaMask not rendering the correct balance.

**Comment by danjm** [comment]
@tmashuang I'm the balance is just lower than expected, by an amount equal to that sent from coinbase.

This sounds like a provider rewrite bug. Somewhat similar to others we've seen where updates from polling get interupted somehow...

@Jaypantera now, after this much time having past, is your metamask balance updated? If not, what happens if you refresh the page or close the extension and then open it again?

**Comment by Jaypantera** [comment]
![helpfromtmshuang](https://user-images.githubusercontent.com/43555413/45983007-ee0f3900-c028-11e8-81a1-2b3844e7b4a8.png)

**Comment by Jaypantera** [comment]
I have tried that nothing happens no update
even tried reopening with seed phrase still no update

**Comment by Jaypantera** [comment]
wowwwwww did you do something?? 
@tmashuang and @danjm 
you guys are the THE BEST!!!  
thank you so much for your help!!!
