### ISSUE TITLE
Able to sign transaction with Ledger Nano S for Address in Trezor

### ISSUE THREAD

**Issue by ncsolar** [MetaMask/metamask-extension#5364]
**Describe the bug**
I'm able to sign a transaction and send ETH using  a Ledger for a address that belongs to a Trezor

**To Reproduce**
1. Select "Connect Hardware Wallet"
2. Select "Ledger" click "Connect"
3. Select "Ledger Live" (notice balance does not belong to first ledger address, but 1st Trezor address that I use before upgrading Metamask 4.11.1)
4. Select first account, click unlock
5. Send ETH to any address, when the sign message appears on the Ledger click yes

**Expected behavior**
I was expecting not able to send a transaction when the Trezor is not connected to the PC

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac OS X 10.13.6 
 - Browser Chrome Version 69.0.3497.100 
 - MetaMask Version 4.11.1
 - Beta UI

**Additional context**
Both Trezor and Ledger are using the same seed words

**Comment by brunobar79** [comment]
Hi @ncsolar, thanks for reporting.

Trezor and Ledger itself doesn't know anything about the other devices and MetaMask only works as a proxy sending a raw transaction signing request to the hardware wallets.  
Signing happens inside the hardware wallet itself so If you were able to sign the transaction with a ledger it's because that address is valid on that device (and that's probably because you're using the same seed words on both).

If you really thing there's a bug on our end please reopen and would be great if you can provide screenshots of the list of accounts of your Trezor and Ledger (for both of your HD paths - Legacy and Ledger Live).  That would be really helpful to understand the issue.
