### ISSUE TITLE
Why do you need to create a new password when adding a new browser?

### ISSUE THREAD

**Issue by BradyDale** [MetaMask/metamask-extension#5382]
**Describe the bug**
When "restoring" a wallet to add Metamask to another browser, it asks to create a new password. 
There's a lot of UX problems here. One: I don't need to "restore" anything. I just need Metamask to work on more than one computer and more than one Browser (Gods Unchained breaks on Brave, for example). 
It doesn't seem like it should be necessary to create a new password each time you add Metamask on a new device. 
A) it adds a lot of friction to users
B) it's just a new login. It's not a restoration (which implies something was lost)

**To Reproduce**
Get Metamask set up on one site then go to set it up on another. 

**Expected behavior**
Let me input my seed phrase and my existing password.

**Browser details (please complete the following information):**
First browser: Brave.
Browsers requesting new passwords: Chrome and Firefox. 

I had Metmask running on multiple browsers on older PCs but something has changed since I got this new one and now I can only log in on one.

**Comment by bdresser** [comment]
hey @BradyDale - your MetaMask password doesn't work the same way as most passwords you're used to. 

In most log-in flows (Gmail, for example), your password is sent to a server, checked against the password on record for your account, and if they match, you're allowed in. This is a simplification, but the principle stands.

In MetaMask, we don't store any of your secrets on our servers. We don't even have servers! Instead, your seed phrase has the ability to generate your private key, no matter what browser you enter it into, using an algorithm called BIP-39. The password is simply used to encrypt your MetaMask data locally, in your browser, so things like your private key aren't stored in plaintext. 

This means your password never leaves the browser you've installed MetaMask on. It means you could have the same seed phrase on two different browsers, with a different password in each browser! It also means we can't help you reset your account, recover your password, or recover your seed phrase.

Hope this makes sense. 

@JSON-LEE13 @rdymac we should probably get something to this effect up in the support center to save some time.

**Comment by BradyDale** [comment]
I definitely understand all of this. I'm telling you that you need to communicate this differently to users.
"New password" is the wrong way to put it. 
"Restore" is also not the right way to describe it.

**Comment by bdresser** [comment]
duly noted. I agree! thanks for the feedback

**Comment by mimoYmima** [comment]
couldn't agree more, which is why i'm here reading this thread, and I'm a web developer, how are normal people supposed to figure this out?

Also your answer above @bdresser doesn't say if you can just use the same password on all browsers, but I'm assuming you could, it's just used as an encryption key for the pass phrase right?

the UI in this case should be the same as what people are use to, -enter your password-  or create a new password right?

**Comment by eervin123** [comment]
Could simply be solved with @bdresser 's comment above on the new browser setup screen.  Then change the text "New Password" to something like "New password for this browser"

**Comment by BradyDale** [comment]
> Also your answer above @bdresser doesn't say if you can just use the same password on all browsers, but I'm assuming you could, it's just used as an encryption key for the pass phrase right?

You totally can, yes

**Comment by Vvavuum** [comment]
Just wanted to note that this is still and issue and the language in MetaMask hasn't been updated. Also, this information is not on the MetaMask support page. FWIW, I have not seen an option to retain my current password when I use MetaMask on a new browser. It really would have been helpful.

**Comment by httpJunkie** [comment]
Having a small question mark icon with a brief note something like: your password is not kept on our servers, therefore each browser you import a wallet has a dedicated password, be sure to note any differences you may have from one device/browser to the next.

I don't know something that gives a little more context to newer users. I'm sure you guys could come up with something better than what I just suggested, but it would be nice not to have to look this up. I'm here trying to understand that as well.

**Comment by estarossa0** [comment]
4 years after this issue was created, I'm here reading why I need a new password, I understand it's kinda my fault for using meta-mask for my wallet and not searching how it works internally, but this local password thing could've been communicated in a better way. 
PS: not complaining it's just feedback ❤️.

**Comment by paupedrals** [comment]
I'm here for the same reason,"New password"? Huh... Why? Well. After reading this, I understand the reasons and all, but if I may, I would like to suggest to change/add a couple of words:
- Instead of "New Password" -> "New Password for this browser"
Everything would be very clear then. Anyway, thanks for the good work on MetaMask!

**Comment by witee-star** [comment]
https://cyberbump.net/metamask-ronin-and-binance-wallet-password-recovery-using-btcrecover-lost-or-forgotten-password/
