### ISSUE TITLE
Add a feature to "toggle to transparent mode"

### ISSUE THREAD

**Issue by stellarmagnet** [MetaMask/metamask-extension#5430]
**What problem are you trying to solve?**
When making crypto payments on websites that accept them, they usually supply you with two pieces of data: 
* an exact amount of ETH you need to send (~6 digits)
* the wallet address 

The problem is that I can only copy and paste one of these and metamask doesn't remember what I pasted into the field if i go back to the browser & copy the other field. Memorizing 6 digits can be annoying and I can possibly make a mistake.

**Describe the solution you'd like**
I'm not sure if there is a technical limitation for MetaMask remembering what i input into the "Send" fields (if there isn't a technical limitation... then please enable this). 

The alternative solution is to add a "transparent mode" toggle to metamask, so I can see the browser behind me in addition to the metamask fields. This way, in the common use case where the metamask extension is covering up the ETH amount (see below), I would copy & paste the address, then be able to see the exact ETH amount that I could type in.

A transparent mode will also help with double checking you have put in the correct address as well.

**Additional context**
![image](https://user-images.githubusercontent.com/2584493/46507606-392a0880-c7ee-11e8-8f37-01a3f8093c70.png)

**Comment by danfinlay** [comment]
One simple solution is to use the full screen mode, which you can access with this button:

![46507606-392a0880-c7ee-11e8-8f37-01a3f8093c70](https://user-images.githubusercontent.com/542863/46507836-5e6b4680-c7ef-11e8-842b-4b77b6a2d654.png)

Another solution is that the site you're visiting could interact with MetaMask and suggest the transaction with a single click using the ethereum provider API. 
https://medium.com/metamask/calling-a-smart-contract-with-a-button-d278b1e76705

There are hacks we can use to keep fields filled in, but because we support the other two items listed, I'm closing this for now. I hope the tips help.

**Comment by stellarmagnet** [comment]
> One simple solution is to use the full screen mode, which you can access with this button:
Thanks, I will keep this in mind for the future. But I think a transparent mode will be better user experience. Less clicks and easier to double check all of your values without having to remove your new tab and resize it to be side-by-side.

> Another solution is that the site you're visiting could interact with MetaMask and suggest the transaction with a single click using the ethereum provider API.

I don't think this is a solution

**Comment by danfinlay** [comment]
Also, the browser doesn't give us any way to make the popup partially transparent, so this is out of our hands.
