### ISSUE TITLE
In EIP 1120 build, closing "connect" screen via window controls hangs .enable() promise

### ISSUE THREAD

**Issue by derrickpelletier** [MetaMask/metamask-extension#5680]
**Describe the bug**
Build: EIP 1120 build (https://github.com/MetaMask/metamask-extension/pull/4703)
When opening the approval/connect dialog, if the user closes the window via the window controls or a shortcut (like cmd + w), the `.enable()` promise never resolves or rejects.

This is critical ux for some flows.

**To Reproduce**
1. privacy mode **ON**
2. trigger `.enable()`
3. close with window shortcut (cmd + w on osx)
4. Notice the promise never rejects as it does by clicking "cancel"

**Expected behavior**
Expect promise to `reject`

**Screenshots**
<img width="224" alt="screen shot 2018-11-05 at 12 03 41 pm" src="https://user-images.githubusercontent.com/833426/48023546-f9a75280-e0f2-11e8-8ddc-098d31bcd49d.png">

**Browser details (please complete the following information):**
 - OS: osx
 - Browser chrome
 - MetaMask Version 4.17.0 (EIP1120 build)
 - New / Beta UI

**Additional context**

**Comment by bitpshr** [comment]
Hi @derrickpelletier, thanks for taking the time to file this issue. When a dapp calls `ethereum.enable()` and an approval popup is shown to the user, the user _must_ respond to the popup before using MetaMask again, similar to transaction requests. Specifically, if the user closes an approval request via the chrome without approving or rejecting it, they will still see the approval request waiting for their response the next time they open MetaMask. This means that when a user closes an approval request rather than responding to it, it's the same as if they minimized it: the `Promise` will continue to hang, waiting for either an explicit approval or rejection.

**Comment by derrickpelletier** [comment]
> This means that when a user closes an approval request rather than responding to it, it's the same as if they minimized it

This seems like unexpected UX—it's a very explicit action to close a window. Also, if i dismiss the window in this way, and leave the dapp, that approval state is still blocking metamask, now without any context of where I was (could be much later).

Closing popups can be very impulsive and i think this makes a bit of a jarring experience.
Why isn't closing the window consider a rejection? If the user closes the popup via window chrome or shortcut, and the promise rejects, they are in a safe state because they rejected the connection. The dapp can then respond appropriately, maybe show some UI to explain if they way. If the user decides to interact again in a way that requires approval, it would just be up to the dapp to call `.enable` again restart that approval flow.

**Comment by bitpshr** [comment]
Hi @derrickpelletier. This is related to #3124. We're discussing the idea of rejecting transactions (and also approval requests) when the associated popup is closed. Thanks again for reporting this, feel free to track that issue for updates.
