### ISSUE TITLE
Warning messages to upgrade

### ISSUE THREAD

**Issue by elie222** [MetaMask/metamask-extension#5707]
Please remove the annoying console warnings on page load. I’m seeing like 5 yellow messages each time I load a page when doing development on other projects.

<img width="1657" alt="screen shot 2018-11-08 at 16 54 05" src="https://user-images.githubusercontent.com/3090527/48229729-eefcef80-e376-11e8-93e0-c67d03ef934e.png">

**Comment by bitpshr** [comment]
Hi @elie222. Since we just released such a breaking change, we plan to keep this warning in the console for some time for developers who may be wondering why their dapp is broken. Note that the message only shows once per page load, so four messages implies that your site's using four separate frames.

We'll consider adding a settings option that allows experienced users to disable warnings.
