### ISSUE TITLE
IPFS hash not resolving (violation the following Content Security Policy directive)

### ISSUE THREAD

**Issue by jdetychey** [MetaMask/metamask-extension#5714]
**Bug**
tried to resolve https://chateaud.eth, was redirected to the IPFS portal but was stuck at
![image](https://user-images.githubusercontent.com/15610681/48281684-9a7d7100-e457-11e8-94b6-44fbb587add9.png)
JS console indicate: 
`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-76HQ0XNbhAPPnN6Fdpnq4KB3niRZg6NS1fpXF/0NZng='), or a nonce ('nonce-...') is required to enable inline execution.`

**To Reproduce**
1. Go to https://chateaud.eth with Metamask version 7 Nov
2. Right clic 'inspect'
3. See error in Console

**Expected behavior**
load this page: https://ipfs.io/ipfs/QmaDwqZm4GTmHY7MwuGZoWnQSgpSmwb8nKDZZPQgthSzDF

**Screenshots**

**Browser details (please complete the following information):**
 - OS: ubuntu 16
 - Browser : chrome
 - MetaMask Version 5.0.1
 - Old UI or New / Beta UI?

**Additional context**
<3 <3<3

**Comment by jdetychey** [comment]
Thx a lot Dan 
I don't think I am requesting a script from a different domain
Do you have examples to share where IPFS + ENS loads ? I am very curious to test them.

**Comment by bdresser** [comment]
@jdetychey try https://phyrextsai.eth or https://portalnetwork.eth

**Comment by jdetychey** [comment]
@bdresser @PhyrexTsai 
maybe I am trying that the wrong way, mapped the getContent of the resolver to my IPFS hash instead of "https://gateway.ipfs.io/ipfs/QmaDwqZm4GTmHY7MwuGZoWnQSgpSmwb8nKDZZPQgthSzDF/"

**Comment by PhyrexTsai** [comment]
@jdetychey sorry for the late reply.

### First
The resolution of the IPFS hash is `QmTpWUAmvivP6dN32QMdQX8uJt7qVHct8pARhWDgNGZi8F`
But you provide IPFS hash is `QmaDwqZm4GTmHY7MwuGZoWnQSgpSmwb8nKDZZPQgthSzDF`, so they represent different files, it seems that the one you want to show has not been set correctly to the contract.

You can checkout IPFS hash of your ENS through this website: https://explorer.portal.network/

### Second
We will look into this error, thanks for telling us this issue.
`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-76HQ0XNbhAPPnN6Fdpnq4KB3niRZg6NS1fpXF/0NZng='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by jdetychey** [comment]
Hey @PhyrexTsai thanks for the help.
I got some support from your telegram channel. It seems like the ens domain manager somehow refactored the hash that I pasted (from Qma to Qmt) or that I pasted the wrong hash in the first place (most likely). I changed the content to the right Hash using https://resolver.portal.network and reset to the default resolver.
It is now properly showing the picture.
My issue is solved but maybe you want to keep it open to investigate the security error message? @danfinlay
