### ISSUE TITLE
"Speed up" button should ignore cancellation attempts

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5732]
Right now the "speed up" shows on the most recent tx with lowest nonce.

If that most recent tx is a cancellation attempt, the "speed up" button shows on the cancellation attempt.

So, if I submit a tx, it takes a long time, I try to cancel, then I decide I should just speed up the original tx, I'm unable to do so since the "Speed up" button is now on the cancellation attempt and not on the original tx.

If a user tries to cancel, we should probably show the "Speed up" button on both the original transaction AND the cancellation attemp

inspired by [this comment](https://github.com/MetaMask/metamask-extension/issues/1410#issuecomment-437717020)

@alextsg

**Comment by bdresser** [comment]
@cjeria what do you think? a community member might take this on once we agree on an acceptable behavior.

**Comment by bdresser** [comment]
Or, put more simply, we could keep the "speed up" button on all pending tx with the lowest nonce.

**Comment by mehmeta** [comment]
Thanks @bdresser, as discussed, happy to work on this once the design of the feature is agreed upon. I think it makes sense to display the button on all lowest nonce transactions.

**Comment by danfinlay** [comment]
This is definitely addressed in a design we already have by Christian, where we bundle all cancel/speed-up attempts under a common tx attempt history entry. This should be treated as an extra reason to increase priority on completing that design.

Previously I'd lowered the priority of completing that full design because we already had another feature on the roadmap which would make it easier to implement: A data-layer abstraction around groups of related changes to a single "intended" transaction. #4260.

Maybe I need to get out of the way with this roadmap-optimization, though. That feature would be great for devs, but could probably be built on top of however the txs are grouped otherwise (Ideally by adding a new metamask-unique "intention ID" to new transactions, and copying it to retries and cancellations). @alextsg

**Comment by alextsg** [comment]
Yeah I can start working on implementing the new grouping. I'll add questions to #5544 to verify some things with the new design. We can probably add this Speed Up button change first.

- We don't want to keep the "speed up" button on all pending tx with the lowest nonce because we want to allow the user to speed up only the most recently sped up transaction right? Ie. If I create a tx (A), speed it up (B), then we want to show the Speed Up button only on B and not A right?
- We currently show the Cancel button on all pending transactions, but in the same sense as the previous point, should we only show the Cancel button on the most recent Cancel Attempt? (in case the user wants to increase the gas price on a cancel attempt?)

**Comment by cjeria** [comment]
This is a reasonable feature request, however I must ask, besides one user wanting to the ability to retry the original transaction (and essentially cancel the cancel tx attempt), is this a commonly requested feature? 

Regardless of the answer to my above question, here are my initial thoughts on how this could work:

When we group tx's by nonce (which we currently don't do), the most recent tx with lowest nonce should always have a speed up button no matter its latest state (by "tx state", I mean the latest user action + highest gas price attempt).

Here's how I'm thinking this UX could work.
![image](https://user-images.githubusercontent.com/597770/48372255-1233e180-e68c-11e8-9ca7-0fdfeec9085b.png)

The new step to the speed up flow (which would only be initiated when a cancel attempt has been made) would be a modal that asks the user what does they want to speed up with two options:

- Speed up original transaction
- Speed up cancel attempt

@bdresser @alextsg @danfinlay @omnat thoughts?

**Comment by danfinlay** [comment]
> If I create a tx (A), speed it up (B), then we want to show the Speed Up button only on B and not A right?

Right.

> should we only show the Cancel button on the most recent Cancel Attempt?

Yeah, for MVP that makes sense.

Eventually it should only show as one tx, of course, so it becomes moot.

Also for mvp, worth keeping in mind:

Since `speed up` is never on a `cancel attempt tx`, if you try to `speed up` a tx with multiple `cancel attempt txs`, it needs to increment its gas over _their_ gas price values.

**Comment by danfinlay** [comment]
Oh hey I just now saw Christian's awesome sketchwork. I like it. Minimal sketches ftw.

**Comment by alextsg** [comment]
@cjeria @omnat @bdresser  I'm working on grouping transactions by nonce and I just have the Speed up/Cancel flows left to add. Have we reached a decision on which UX to go with?

**Comment by cjeria** [comment]
Since I don't know which option will test the best, would it be too much to include both options? 
- Speed up button on the top area of the of the details area > modal
- and inline "speed up" per tx attempt within the activity log? 

I do think the inline option is a clever solution, but I'm just not sure if by itself is enough for users to see it and therefore know to use it. 

CC @bdresser @omnat @danfinlay 

![image](https://user-images.githubusercontent.com/597770/49162355-77810700-f309-11e8-984d-31d8219fd19e.png)

**Comment by bdresser** [comment]
I like the inline option! It's explicit, simple, and lets us deal with edge cases well. 

With the inline options present, I think the initial buttons up top become confusing/redundant

If the user has sped up multiple times
* we should probably only show *one* inline `speed up` link (on the most recent attempt) - multiple links would all do the same thing basically.
* show no `speed up` up top
* still show `cancel` up top

If the user has attempted cancel, we should only show `speed up` 
* on the most recent (highest gas) cancellation attempt 
* on the most recent (highest gas) tx submission attempt
* and remove the `cancel` button up top.

Maybe the text link can be more explicit? `Speed up this transaction` / `Speed up this cancellation`

Also happy to take this to slack if we wanna discuss there @cjeria @alextsg

**Comment by alextsg** [comment]
Just a comment about the inline solution, but we also include the time and date for each activity in the Activity Log, so the line item is a bit longer than what's shown in the mock. Will that make things look too cluttered?

![image](https://user-images.githubusercontent.com/8051479/49171941-8a3d1100-f2f4-11e8-9d56-da5fc136a7a0.png) (Don't mind the outdated colors/styling - will fix that up)

And sure, we can discuss this further in slack.
