### ISSUE TITLE
I have a bunch of pending / dropped tx's, how do I clear them?

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5739]
**Describe the bug**
I have a bunch of pending / dropped tx's, how do I clear them?

![screen recording 2018-11-12 at 01 29 pm](https://user-images.githubusercontent.com/513929/48373444-1279b000-e67f-11e8-85b6-0ccf95d59625.gif)

**To Reproduce**
1. I'm not sure how I got the pending / dropped tx's.  Maybe they were low gas tx's that dropped?

**Expected behavior**
A clear description of what you expected to happen.
I can clear the pending tx list for each tx that does not have a nonce

**Screenshots**
See above

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] Mac OS X
 - Browser [e.g. chrome, safari] Chrome
 - MetaMask Version [e.g. 4.9.0] 5.0.2
 - Old UI or New / Beta UI? Beta UI 

**Additional context**
I <3 metamask

**Comment by bdresser** [comment]
sounds similar to https://github.com/MetaMask/metamask-extension/issues/5687, we're investigating

**Comment by tmashuang** [comment]
Quick follow up question, 

> `I'm not sure how I got the pending / dropped tx's`

Could these have been a custom rpc txs showing up on Mainnet transaction history?

**Comment by owocki** [comment]
i dont think so.. i haven't used a non-infura node on this metamask installlation

**Comment by CryptoDave111** [comment]
I had the same thing.  Go to settings. First clear transaction history.  2nd REVERT to Old UI
You can send again.  The beta has bugs -

**Comment by danfinlay** [comment]
Old and new UI both use the same TX submission logic, so this is not a beta UI issue, that's just a popular rumor/theory.

It would help if you could send me state logs to debug with. I'll message you on Slack.

**Comment by owocki** [comment]
@danfinlay just sent u my state logs

**Comment by danfinlay** [comment]
## Workaround For Users

Restarting your browser should re-submit all approved transactions to Infura. Please try this.

## Internal Notes

Inspecting the logs, these transactions are not submitted to infura, they are merely `APPROVED`.

This is a known symptom when there is an internal crash in our Transaction Controller, since the error in an event listener can crash the emitter too (hence the creation of [Safe Event Emitter](https://www.npmjs.com/package/safe-event-emitter)), which I'm surprised to see we aren't yet using in our [TransactionController](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/index.js).

I can't find the issue related to that right now. I think @kumavis and @frankiebee were handling this, maybe they have tips or a fix path.

### The Good News

It looks like these aren't interfering with subsequent attempts, so submitting another transaction seems to work.

### The bad news

These are indistinguishable from mere pending transactions.

### Immediate action item for us

We should make APPROVED transactions display differently from SUBMITTED transactions.

### Fix goals

Make the TransactionController not crash, or recover from tx errors gracefully, and resume resubmitting.

**Comment by bdresser** [comment]
@owocki going to close this - we've tried to clear folks' unsubmitted transactions in https://github.com/MetaMask/metamask-extension/pull/5765 and will prevent this from happening again in https://github.com/MetaMask/metamask-extension/issues/5749

We're still looking in to your issue with the block tracker described in #5764
