### ISSUE TITLE
UI/UX Button functionality is not intuitive and confusing

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#5753]
There are too many icons which will open some menu and the standard icon for menu (3 bars), is not the one for the global standard menu with general commands and setup options.

**Comment by whymarrh** [comment]
Hey @SvenMeyer, thanks for bringing this up! The design team is working at making the UI more intuitive and less confusing through user research & iteration, and I'm sure that this will be addressed in that process.

I'm closing this for now—this issue is quite broad and isn't particularly actionable. There are also a lot of issues in the design repo that describe inconsistencies with the UI. Please do continue to open up issues with your design feedback.
