### ISSUE TITLE
Blank Display with No Errors

### ISSUE THREAD

**Issue by tomtom87** [MetaMask/metamask-extension#5755]
**Describe the bug**
I build the extension and add to opera, it loads up and displays in the extensions but when I click on the fox metamask icon to open the extension its just giving me a grey box where normally metamask would display, if i right click > inspect > no errors or js problems

**To Reproduce**
1. clone the develop branch
2. install deps, build dist
3. load opera extension
4. voila, grey box of death

**Expected behavior**
It should work as 'normal' e.g display the metamask extension and give me the GUI

**Screenshots**
![screen shot 2018-11-14 at 18 33 34](https://user-images.githubusercontent.com/2025975/48480085-d3dd2480-e83b-11e8-8da3-9af76d4d2a9f.png)

**Browser details (please complete the following information):**
 - OS: OSX 
 - Browser Opera
 - MetaMask Version develop branch

**Additional context**
I commented out sentry as my fork is not using it. Before this I was getting an error from sentry dns.

**Comment by bdresser** [comment]
@tomtom87 we have a standing bounty for this blank screen issue (https://github.com/MetaMask/metamask-extension/issues/4894). It's quite challenging to reproduce and we haven't had luck identifying the root cause. If you can find reliable reproduction steps, please let us know.

Also note that MetaMask on Opera is far behind our current production builds (5.0.1) - at this point I'd recommend you use a different browser until we can get Opera up-to-date.

**Comment by tomtom87** [comment]
Ahhh ok, thanks for enlightening me! I will see if I can get it to
reproduce on another machine. So far it seems just clone develop branch,
run npm install with the required node and npm and then npm start, load the
unpacked extension into opera and voila. Grey blank screen.

I'll switch over to some other branches and see if i can get this to play
ball for what i'm working on, let me know if you need any more info or any
debugging my side. Would love to help fix the bounty on it

**Comment by tomtom87** [comment]
Build works in Chrome, this bug is isolated to Opera currently it seems
