### ISSUE TITLE
transaction failed and lost 1.0 Eth

### ISSUE THREAD

**Issue by 2tall2actsmall** [MetaMask/metamask-extension#5772]
Hello I'm writing this request because i have lost some funds using metamask and am not sure what happened. Would like some assistance on hopefully some how recovering these funds. Below I will detail the events leading up to the loss of funds.

- I attempted to send .5 Eth to the address 
-When i sent the Eth, I got a message from metamask telling me that the payment had "failed to 
send". I then waited maybe 5-10 minutes and attempted to send the 0.5 Eth again only to receive 
the same failed to send message.
- Attempting to fix this problem, I then went to the metamask settings and clicked on the "reset 
account" button. After this i then logged out of my metamask account.
- Upon logging back in to my account, I then noticed that approximately 1.0 Eth was missing from 
my metamask wallet. (which i assume is the summation of the two 0.5 Eth transactions i 
attempted).
- I then went to etherscan to see if I could identify what happened to my lost funds. Etherscan 
showed no history of any transactions taking place. It was not recorded by the blockchain and I
have no Idea what happened to the 1.0 Eth.

If there is a solution or any way you guys can help me figuring out what happened it would be greatly appreciated.

**Comment by tmashuang** [comment]
Thanks for the summary of your issue. To investigate further, we would like your Ethereum address of the account in question, the exact transaction transaction failed message, the exact transaction details that your sent (gas, value, time, dapp used, etc.). All this information can be found in your MetaMask state logs, [How To Download State Logs](https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-New-UI-). Unfortunately, since you've reset your transaction by clicking Reset Account, those transactions will not be in your transaction history. Please email the information to the best of your knowledge to support@metamask.io.
