### ISSUE TITLE
Signature request popup closes instantly

### ISSUE THREAD

**Issue by b-mueller** [MetaMask/metamask-extension#5814]
**Describe the bug**

When implementing Metamask login we found that the signature verification popup either closes after a few seconds or does not appear at all, even though the request are stacked and visible when clicking the Metamask extension item.

**To Reproduce**

I verified that the same thing happens on MyEtherWallet and made a couple of recordings:

- [MyEtherWallet ENS](https://www.dropbox.com/s/dd5vynw2vfmmbjp/metamask-popup1.mov?dl=0)
- [Mythril Staging](https://www.dropbox.com/s/hxfsgy0nje3u3bt/metamask-popup2.mov?dl=0)

To reproduce, follow the steps shown in the videos or simply click "LOG IN WITH METAMASK" [here](https://mythril-staging.atchai.com/#/plans).

**Expected behavior**

I would expect the popup to persist until the user has confirmed or cancelled.

**Browser details (please complete the following information):**
* Chrome Version 70.0.3538.102
* Metamask 5.0.3
* Mac OS Mojave

**Comment by jurosh** [comment]
Same issue on https://idex.market when doing trades. So far I identified it being caused by calling `.enable()` periodically - because we are checking if user didn't switched account using pooling.

So maybe it's similar on your mentioned services, and calling `enable()` is hiding existing opened MM popups. It's def bug of MM, but kind of can be workarounded - on IDEX will be releasing more async way of getting account soon.

**Comment by bitpshr** [comment]
Thanks for the report @b-mueller, we’ll check into this.

Hi @jurosh. A provider should only be enabled once for each page load. Thereafter, to poll for account change, just check `eth_accounts` or another similar RPC method instead of calling `enable` each time. This probably isn’t related to this issue, but may still help your specific use case.

**Comment by bdresser** [comment]
hey folks, I can no longer reproduce this on Idex or MEW and can't load OP's example dapp. Are you still experiencing this issue?

**Comment by b-mueller** [comment]
Nope, I can't reproduce it anymore either.

**Comment by jurosh** [comment]
@bdresser Hey, on IDEX we switched to model where we ask for Metamask permission only before doing actions. Eg. we ask only before user unlocking wallet, trying to trade, deposit.

But just tried to call `enable()` multiple times and MM popup worked fine = looks like issue is fixed. :+1:
