### ISSUE TITLE
Update eth_signTypedData to the new EIP-712 specification (eth_signTypedData_v3)

### ISSUE THREAD

**Issue by leroldary** [MetaMask/metamask-extension#5996]
Update `eth_signTypedData` to the new specification (`eth_signTypedData_v3` instead of `eth_signTypedData_v1`)

This would allow other wallet developers to update/implement the EIP-712 specification and 
be compatible with MetaMask.

**Comment by 1blockologist** [comment]
We handle this with a variety of conditional statements to match how various wallets coded this method name

**Comment by BrendanChou** [comment]
This is now `eth_signTypedData_v4` in `eth-sig-util`. Please update in order to match your RPC calls to the standard of every other provider. Developers intending to use `eth_signTypedData_v1` explicitly have had ample time to hardcode that call for just MetaMask

**Comment by 1blockologist** [comment]
hard for me to follow @BrendanChou what changed?

is there no "eth_signTypedData" method and they all have _v suffixes now?

**Comment by BrendanChou** [comment]
RPC call `eth_signTypedData` aliases to `eth_signTypedData_v1` rather than the newer `eth_signTypedData_v3` or `eth_signTypedData_v4` functions in `eth-sig-util`

Other providers simply have `eth_signTypedData` perform the most up-to-date signing of the EIP712 specification rather than using a deprecated method.

The MetaMask team seems to deem this a breaking change, however:
1) the change is moving away from an incomplete specification that was never widely used.
2) developers who want to use the old (v1) specification have now had sufficient time to explicitly use that RPC call instead.

**Comment by 1blockologist** [comment]
Just great. If other wallets aren't conforming to this then our logic gets broken. We aren't trying to detect user agents because wallets come and go.

**Comment by Gudahtt** [comment]
I'll close this for now, since `eth_signTypedData_v3` and `eth_signTypedData_v4` have been updated. If anyone feels that some change is still warranted, then I'd encourage you to open a new issue or a thread on our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics) to discuss it.
