### ISSUE TITLE
Should allow you to cancel txs without a transaction if queued

### ISSUE THREAD

**Issue by James-Sangalli** [MetaMask/metamask-extension#6004]
My understanding is that queued transactions are not broadcasted, therefore cancelling them should not require a cancel tx to be added to the queue as it can simply be deleted as it is not in the blockchain yet or in the tx pool.

**Comment by bdresser** [comment]
Hey @James-Sangalli - transactions in your queue are most likely already submitted to the blockchain. They're marked as "submitted" in the UI, but are still "pending," since they won't confirm until the transaction with the lowest nonce confirms. So the short answer is no, we can't allow cancellation without another transaction, since we can't un-submit a submitted transaction. 

See more about the various transaction states [here](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/tx-state-manager.js#L14). They don't quite match to the language the UI uses, which we've simplified.
