### ISSUE TITLE
Is that possible to change password which controll access to metamast

### ISSUE THREAD

**Issue by zyfrank** [MetaMask/metamask-extension#6032]
currently, after install metamask and set the password, seems no place to change this password

**Comment by daddyfatstaks** [comment]
Im not sure how to answer that? I guess you would just have to find out for
yourself and open a metamast.

On Jan 16, 2019 11:31 PM, "zyfrank" <notifications@github.com> wrote:

currenlt, after install metamask and set the password, seems no place to
change this password

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/6032>, or mute the
thread

**Comment by zyfrank** [comment]
what I mean is：
when you open meta-mask plug-in， it will will prompt you provide password to proceed, but currently we have no way to change this password

**Comment by bdresser** [comment]
You can click the "restore from seed phrase" link, use the seed phrase for the account that has a password you want to change, and enter a new password when prompted.

Feel free to reach out to support@metamask.io for more info

**Comment by bdresser** [comment]
see also https://github.com/MetaMask/metamask-extension/issues/4781 which is a feature request for this functionality (without having to restore from seed)

**Comment by zyfrank** [comment]
thanks for the information

________________________________
发件人: bobby dresser <notifications@github.com>
发送时间: 2019年1月17日 16:48
收件人: MetaMask/metamask-extension
抄送: zyfrank; Author
主题: Re: [MetaMask/metamask-extension] Is that possible to change password which controll access to metamast (#6032)


You can click the "restore from seed phrase" link, use the seed phrase for the account that has a password you want to change, and enter a new password when prompted.

Feel free to reach out to support@metamask.io<mailto:support@metamask.io> for more info

―
