### ISSUE TITLE
Add Trezor hardware wallet support

### ISSUE THREAD

**Issue by mcgravier** [MetaMask/metamask-extension#605]
Trezor Ethereum support has been included in the latest firmware upgrade, however, there are no wallets supporting it avialiable - AFAIK there is work on Mist support being in progress, but MetaMask would be far better suited for average user

**Comment by flyswatter** [comment]
We definitely want to support various signing methods long term.  We're hoping to implement a signing plugin system to make this sort of thing easier, hopefully we'll get to that soon!

**Comment by flyswatter** [comment]
Related to https://github.com/MetaMask/metamask-plugin/issues/328

**Comment by mcgravier** [comment]
Any progress on hardware wallet support? I see that multiple account type support has been merged - any chance for picking up Trezor/Ledger/Keepkey anytime soon?

**Comment by flyswatter** [comment]
Hopefully fairly soon.  We'll be doing Ledger first probably, since I have one, but none of us have a Trezor (and they didn't get back to me about a dev device ;) ).

**Comment by woodydeck** [comment]
Have you acquired a Trezor yet for testing?  These are currently much more available than the ledger s nanos. 

Try the /r/Trezor subreddit if email doesn't go through. They have pretty good documentation available for integrations, but it is a bit steep the first time.

**Comment by flyswatter** [comment]
I have, thanks! Very much looking forward to adding this.

**Comment by woodydeck** [comment]
Great! There's a wonderful woocommerce plugin someone developed with metamask in mind, https://www.paywithether.com. This shows why HW wallet support is so vital.

Their solution for callbacks to woocommerce, since ethereum isn't great for HD walleting, is to add a tx ID to the send so their API can do a callback for the right order. Metamask makes this operation a one-click jobby, but I just don't see people sending hundreds of dollars worth of ether to metamask to checkout. We are currently stuck with MEW or the exchanges (coinbase doesn't have good ethereum support), and this plugin isn't exactly ideal for use this way.

Mist is also still stuck on the HW wallet issue, so this is a good way to get a leg up on them. Most of my friends can figure out how to buy a Trezor and install a Chrome plugin, but when you start talking about geth, downloading the blockchain with --light, and browsing through a specialized browser, they start to blue screen. I personally would never crypto for more than grocery money unless I had the peace of mind from a HW wallet.

Finally, I don't know if there is an issue to this, but Macbooks with the touchbar have biometric support now. This could be a cool way to get some attention from that crowd if integrated. Apple for better or worse is a great litmus test for high value consumers.

**Comment by bbozo** [comment]
> I personally would never crypto for more than grocery money unless I had the peace of mind from a HW wallet.

This

**Comment by kilimchoi** [comment]
Any progress on this?

**Comment by danfinlay** [comment]
Yes, this has been set back very far, but I think other pieces are now in place that will allow us to pursue this in the next few months.

**Comment by danfinlay** [comment]
MetaMask integration has nothing to do with Geth support. For a recent update on our blockers, [refer to this thread](https://github.com/MetaMask/metamask-extension/issues/717#issuecomment-357322117).

**Comment by bdresser** [comment]
@brunobar79 @cjeria when you can, report back on the results of your design convo!

**Comment by bdresser** [comment]
design fixes: https://github.com/MetaMask/Design/issues/33

generally tracking progress in the PR (https://github.com/MetaMask/metamask-extension/pull/4625) for those following along
