### ISSUE TITLE
Annoying warning on every page, please stop

### ISSUE THREAD

**Issue by bradennapier** [MetaMask/metamask-extension#6062]
I am fairly surprised no one has brought this up yet but why do you log to console MANY times on EVERY site with your warning?  Please remove this, it's extremely annoying when working with ANY app including those having to do with ethereum in any way to have to look at those warnings non stop.  It is distracting.

Perhaps instead only show the warning when/if initialized AND if it is done incorrectly?

I **especially** dont need to see it 5+ times every single page load... it is clearly listening for the wrong thing in the first place.  If you are going to do these things at least give a way to turn them off please.

Here are just a few that occurred one after another...

![image](https://user-images.githubusercontent.com/15365418/51718769-a19a3100-1ffb-11e9-9e8b-eea6a3046c75.png)

**Comment by bitpshr** [comment]
Hi @bradennapier, thanks for reaching out. This message will only show in the console once-per-frame, so seeing it multiple times implies that the current site is using multiple iframes and you're seeing logs for all of them at once. Your suggestion of only showing the message if `ethereum.enable` is not called is difficult since it's impossible for MetaMask to know when (and thus if) a site will call this method without code introspection.

We plan to remove this message in the future, but for now, you can always temporarily disable MetaMask if you're debugging a site with multiple iframes and the logs annoy you.
