### ISSUE TITLE
Custom RPC makes account switcher unavailable

### ISSUE THREAD

**Issue by codyborn** [MetaMask/metamask-extension#6094]
**Describe the bug**
Adding custom RPC results in account switcher (identicon) missing.

**To Reproduce**
1. Add custom RPC (example: http://ethls6zh7-dns-reg1.westus.cloudapp.azure.com:8540)

**Screenshots**
![image](https://user-images.githubusercontent.com/11261382/52150828-0110c600-2626-11e9-8854-444787876404.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - MetaMask Version: 5.3.4

**Comment by bdresser** [comment]
@cjeria @chikeichan cool to just set a max-width on the network display and show a `...` on the right side?

**Comment by cjeria** [comment]
Yep! Ellipsis the network name. Let's also make sure the account image doesn't get pushed out of view as well!

**Comment by cjeria** [comment]
Another idea just came to me. Would developers like a "name your network" option when creating new custom networks? That way instead of showing a long annoying url, we'd be able to show them a shortened readable option chosen by the developer.

E.g.

![image](https://user-images.githubusercontent.com/597770/52635504-308ac280-2eb1-11e9-924b-57320116708a.png)

**Comment by bdresser** [comment]
@cjeria i think we will solve this in #5790, especially if we make Network Options its own sub-menu so we can expand all the form fields

**Comment by bdresser** [comment]
closed via https://github.com/MetaMask/metamask-extension/pull/6494
