### ISSUE TITLE
web3.eth.defaultAccount still being exposed without enable

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#6105]
I'm on Metamask 5.3.4, and account addresses are still being injected into every page.

I was under the impression this was fixed in 4.14

<img width="1495" alt="screen shot 2019-02-03 at 3 36 36 pm" src="https://user-images.githubusercontent.com/1577353/52182293-add77880-27c9-11e9-87f4-94ae3c16c7d1.png">

**Comment by aakilfernandes** [comment]
I figured out I have to enable privacy mode, cmon guys, this is not acceptable. It's been almost two years. Please fix this.

https://incoherency.co.uk/blog/stories/metamask-identification.html

**Comment by danfinlay** [comment]
We were planning to make this a breaking change, but since we designed our rollout process, we found a revised approach (#6110) that will allow implementing this feature without breaking previous sites, which we consider an important virtue of the web.

You're that we hadn't been actively developing it, but we have been working on some strong improvements to privacy and security long term, so please understand we are constantly working towards a strong platform long-term.
