### ISSUE TITLE
Add convenience wrappers for webdriver methods

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6155]
For example:

we should be able to replace
```
  describe('Going through the first time flow', () => {
    it('clicks the continue button on the welcome screen', async () => {
      const welcomeScreenBtn = await findElement(driver, By.css('.welcome-page .first-time-flow__button'))
      welcomeScreenBtn.click()
      await delay(largeDelayMs)
    })

    it('accepts a secure password', async () => {
      const passwordBox = await findElement(driver, By.css('.first-time-flow__form #create-password'))
      const passwordBoxConfirm = await findElement(driver, By.css('.first-time-flow__form #confirm-password'))
      const button = await findElement(driver, By.css('.first-time-flow__form button'))

      await passwordBox.sendKeys('correct horse battery staple')
      await passwordBoxConfirm.sendKeys('correct horse battery staple')
      await button.click()
      await delay(regularDelayMs)
    })
```

with something like
```
// TODO: Create schema for the IDs
    await driver.click('welcome-button', 'clicks the welcome screen continue button')
    await driver.typeInto('create-vault-password', 'password', 'error message')
    await driver.typeInto('confirm-vault-password', 'password', 'error message')
    await driver.click('continue-button', 'error message')
    // clicks through unique image screen
    await driver.scroll('tos-screen', async (driver) => {
      // express end condition
    })
  })
})
```
Such method calls would be extensions we add to the driver. They may be available from an existing library, although it would be fairly cheap to roll our own.

**Comment by Gudahtt** [comment]
This has been mostly completed as of #7798. We still don't have "typeInto" though - that's a good idea.

Also, I decided to stick with the `selenium-webdriver` locators for now (e.g. `By.css`, `By.xpath`, etc.), instead of just... passing a string and inferring the type of locator, or having an "XPath" version of each method, or something like that. Not happy with this solution, but using `By` seemed like the best solution for now, until a compelling case could be made for switching (e.g. if we wanted the webdriver to be compatible with Puppeteer, for example) or until someone had a better idea for what the API should be.

**Comment by Gudahtt** [comment]
Since this was mostly completed, I'll close this for now. Further work on this overlaps with other high-priority goals like switching to Playwright, so this might be accomplished as a step toward that.
