### ISSUE TITLE
Wrong size view on Android

### ISSUE THREAD

**Issue by Copinmalin** [MetaMask/metamask-extension#6178]
**Describe the bug**
The size of the panel don't show all the windows as you can see in attachment

**To Reproduce**
Each time you open app
**Expected behavior**
See all the windows to have access to menu, parametres and see détails

**Screenshots**
![screenshot_20190216-090114](https://user-images.githubusercontent.com/4174888/52910193-3fe48400-3294-11e9-8bb8-825821e494cb.png)
![screenshot_20190217-091406](https://user-images.githubusercontent.com/4174888/52910202-686c7e00-3294-11e9-8894-4bb0572a40d4.png)

**Browser details (please complete the following information):**
 - OS: Android 7.0
 - Browser Firefox  Nightly 67.0.a1

- MetaMask Version 6.0.1

**Additional context**

**Comment by Copinmalin** [comment]
After reinstall all is OK !
It was just a bug with update to new version i think

**Comment by Copinmalin** [comment]
In fact it's not working :-)
When i reopen the app in pop-up, the bad view coming !
The problem is with the pop-up view

**Comment by chikeichan** [comment]
Hi @Copinmalin !

How did you open `/popup.html`? That page is not designed to work in full width, that's why when you click "Expand View" in metamask, it would open `/home.html` instead.

Based on my understanding, the only way to open `/popup.html` is if the user go to the url bar and type in `moz-extension://1a2b3c4s-5e6f7a8b#/popup.html`. In that case, I think it's expected behavior.

**Comment by Copinmalin** [comment]
Thanks @chikeichan  !
Thishappen when i open metamsk from right panel option firefox nightly.
And yes in the url it is popup.html.

**Comment by tmashuang** [comment]
This might be an issue with the OS and/or browser and might not support popup/extension view. The [mobile app](https://play.google.com/store/apps/details?id=io.metamask) has launched for Android systems since this issue report which might be a better MetaMask experience. You can manually change the url from `/popup.html` to `/home.html`. I do not have a Android 7 system to reproduce this issue, and I consider it low priority issue to close with all the other aforementioned workarounds.
