### ISSUE TITLE
ALERT: No keyring found for the requested account.

### ISSUE THREAD

**Issue by robertwilliamallen** [MetaMask/metamask-extension#6207]
**Describe the bug**
When trying to send ETH from the wallet to any address, I am seeing the following error: "ALERT: No keyring found for the requested account."

**To Reproduce**
1. Installed MetaMask in Chrome.
2. Deposited ETH funds to the wallet.
3. Tried to send from the wallet to another address.
4. Error occurred: "ALERT: No keyring found for the requested account."

**Expected behavior**
Funds should send.

**Screenshots**
<img width="351" alt="screen shot 2019-02-25 at 1 17 54 pm" src="https://user-images.githubusercontent.com/7582733/53369706-a60a8000-3900-11e9-96c2-56e92f353bdb.png">

**Browser details (please complete the following information):**
 - OS: macOS Mojave 10.14
 - Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask Version 6.1.0

**Additional context**

**Comment by bdresser** [comment]
sorry for the trouble @robertwilliamallen. could you please email your state logs to support@metamask.io and reference this issue number?

**Comment by kumavis** [comment]
@robertwilliamallen do you use a hardware wallet with metamask?

**Comment by itinance** [comment]
Any news on this?

**Comment by freedomengineer** [comment]
I am getting this message too. Using metamask chrome extension.

**Comment by JamesTheAwesomeDude** [comment]
Getting this on Firefox

\>bug opened 15 months ago

this is deeply disturbing; I hope others were as cautious as I in only transferring the bare minimum for the transaction off of the exchange

**Comment by CanadiancryptocaribouJer** [comment]
DISTURBING IS CORRECT IM FREAKING OUT IM HAIVING THIS ISSUE BUT ALONG WITH OTHER WEIRD ISSUES

**Comment by kumavis** [comment]
user reported restarting the extension (eg by restarting the browser) fixed the error

Do not uninstall the extension if you do not have a seed phrase backup

**Comment by Dragendave** [comment]
Hey, I face this exact same issue on the Android App.

**Comment by Gudahtt** [comment]
I have reviewed our Send flow error handling, and I believe this case is now impossible to encounter as-shown. The send flow has undergone many changes and refactoring since this was originally reported, so it's unclear when this changed. It's possible this was a bug that we fixed, or that it's still an error that we're now handling differently. But, absent any further information we can't really investigate any further, and the lack of activity on this issue suggests that this isn't a problem anymore.

Please create a new issue if you see something like this again. Thanks!

**Comment by 8hadow8** [comment]
Hi I am currently having the same issue with mobile wallet.

**Comment by 8hadow8** [comment]
Hi I am currently having the same issue with mobile wallet. Did anyone find a way to resolve it? Or it just resolves itself and everyone forgets that they have commented like I probably will?

**Comment by JamesTheAwesomeDude** [comment]
> Hi I am currently having the same issue with mobile wallet. Did anyone find a way to resolve it? Or it just resolves itself

@8hadow8 Yes, if you read the immediately-previous comment to yours you'll see that this particular _instance_ of the bug is “now impossible to encounter”.

If it's returned, you'll need to (again **as per the immediately-previous comment**) create a new issue.

Let this thread serve as a reminder to us all never to give some untested JavaScript toy exclusive access to your private keys. Never gamble more than you can afford to lose.

**Comment by gregmcgolf** [comment]
I have the same issue. I am using Android mobile phone. I sign in to metamask, can see all the accounts in the wallet, can receive eth, but when I try to send tokens, it says "No keyring found for the requested amount." Please make this a new support issue if necessary.

**Comment by gabkov** [comment]
> I have the same issue. I am using Android mobile phone. I sign in to metamask, can see all the accounts in the wallet, can receive eth, but when I try to send tokens, it says "No keyring found for the requested amount." Please make this a new support issue if necessary.

I have the same issue. Please fix it.

**Comment by gregmcgolf** [comment]
In my case, I discovered that it might have been because that the Metamask account/wallet was locked on the android. I also had the same Metamask account/wallet on my desktop. I opened the phone wallet, then scanned the barcode from my desktop wallet, and voila, it unlocked and I could withdraw funds from the phone wallet, that were previously on an address not on the desktop wallet. Prior to that, I could only receive, although the desktop wallet worked fine. I think the scanning added or modified something in one or both the desktop and phone wallets that then correctly aligned them, but I don’t know. I just know that it works now and both have the correct amounts of funds. The strange thing is that they have different passwords to open, yet hold the same addresses and crypto, and have the same seed phrase. Very strange. The workaround saved me about 10,000$ worth of crypto.

**Comment by TheBadListener** [comment]
Seems like this bug still exists.

![](https://i.imgur.com/DZNQVAW.jpg)

**Comment by Marguelgtz** [comment]
Having the same problem
![Screenshot_20210507-002918_MetaMask](https://user-images.githubusercontent.com/17017482/117402055-4d18d800-aecb-11eb-9329-006ae7b4bf62.jpg)

**Comment by mdm3z** [comment]
![Screenshot_2021-05-14-08-26-01-828_io metamask](https://user-images.githubusercontent.com/78347161/118230495-0ceac400-b48e-11eb-97e1-c13ef120ca96.jpg)

Shows when I try to put NFT for sell

**Comment by OneEdVenturer** [comment]
This happened to me switching to different accounts.  I exited the Metamask android app, relaunch, refresh, invoked transaction and it went through without this message.

**Comment by ampersandi** [comment]
![image](https://user-images.githubusercontent.com/68250498/122865147-34745c80-d369-11eb-8afa-149fb5023959.jpeg)

it's alive and well on iOS

**Comment by matiu** [comment]
Still having this issue on Metamask Mobile Android, using Curve.finance.

**Comment by germanllop** [comment]
I got it too, maybe because I have too many accounts (50)?

**Comment by zlcolin** [comment]
me too, sometimes it's work.

**Comment by jonathancoach** [comment]
On mobile, try force closing the app then restart, it worked for me.

**Comment by Smithbull001** [comment]
> This happened to me switching to different accounts. I exited the Metamask android app, relaunch, refresh, invoked transaction and it went through without this message.
