### ISSUE TITLE
Deceitful MetaMask broadcasts user addresses to every single tracker, iFrame, contained in a page [more than just a window object]

### ISSUE THREAD

**Issue by projectoblio** [MetaMask/metamask-extension#6212]
This is a ginormous invasion of privacy, and frankly, unnecessary. If I need to broadcast a user's Ethereum address to Twitter / Facebook / Google Plus trackers, I'll do it myself. The average web developer only needs the `ethereum` object, window messages is a huuuuge invasion of privacy, and deceitful.  The only reason I can think to do this is to be submissively providing this information to other tech giants.

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 -- The title of this post "Private Mode Enabled By Default" is objectively false, as this is my first time using MetaMask and this is happening.  The title of your linked blog post is deceitful, as default users WILL have their addresses exposed. The blog post mentions nothing about window messages, which are like a fucking loudspeaker, compared to a window object, which is basically nothing.

It's really incomprehensible, this is is a loud, repeated blaring of user addresses once every 15-60 seconds.  Just take higher gas and node feeds if you need more money @jmlubin

Test code: 

```
window.addEventListener("message",function(e){
       console.log(e.data);
});
```
---> E.data will be "inpage", "publicConfig":{"ethereumAddress":"0xsadfasdlkjfs"};
---> This message will be broadcast to any embedded iFrame / tracker (G+ like buttons, FB like buttons, twitter retweeters, etc)
---> Messages will begin about 45 seconds after page loads

**Comment by danfinlay** [comment]
You're right, we haven't enabled this by default yet, because it would break previous dapp behavior, and we realized if we add the manual ability for users to "log in" to legacy applications, we can add this privacy feature without breaking older sites.

We are currently actively working on greatly improving the privacy and isolating it per-page, but you're right that even once we do this, the message stream to the application is visible to the scripts that site includes.

We are very open to alternative methods of providing an API to sites, as we have also submitted proposals to browsers requesting this as a special browser permission, but until that time, there are definitely ambient authority issues in the browser that allow included scripts to access global variables like `window.ethereum`, whether or not it's using `PostMessage`.

We're starting to work with Agoric to help promote the [Realms](https://github.com/tc39/proposal-realms) proposal that could allow dependencies to be properly isolated from global scope like this, which is a general problem with modern JavaScript, not just with our architecture.

Closing & locking this thread for the inflammatory and accusatory language.
