### ISSUE TITLE
Can we please stop broadcasting user addresses? You can't use MetaMask for a health or porn based dApp

### ISSUE THREAD

**Issue by projectoblio** [MetaMask/metamask-extension#6325]
At the most basic level the fact that you have an ETH address which is broadcasted to every single site and tracker can be used to increase the prices you see on sites like Amazon, Google, and others. 

At the middlemost levels it tracks what kind of porn you watch on SpankChain and any other dApp that requires privacy to function, like a  health or neuroscience based dApp. Even transferring ETH between accounts still links you back to your last known identity (which is linked to your MetaMask account) and can be used to change your rates on  employment opportunities, health insurance, loan risk factors, etc based on your proclivities or health metrics.

At the highest levels it prevents you from being able to convert ETH to fiat without significant delays.  

At the inception levels it sacrificies the privacy of everyone in the system because sites like Amazon, Google, PayPal, and others can link your blockchain transactions to credit card payments, thereby your identity, and the identity of the last person you transacted with -- a person who wants to remain anonymous. These identity networks can be used to identify you based on social circles.  Just enabling `private mode` doesn't do very much at all to prevent this. 

I am talking specifically about **message broadcasts**, not the window object which has been brought up by others. To see the message broadcasts, go to any page, open the console, and type in this code: `window.addEventListener("message",function(e){console.log(e.data)})`. About every 40 seconds, you'll see a message with `target:inpage` that contains a data object which contains your ETH address. These message broadcasts are worse than window objects because they can be picked up by any advertisement or tracker or youtube player (facebook like buttons, etc) and otherwise serve no purpose. There are plenty of other ways to interact with a chrome extension aside from communicating unique identifiers to these other companies, and they do not have anything to do with injected web3. 

For example, if there really are any legacy dApps that rely on these message broadcasts (highly doubtful, would love to see), new installations of MetaMask could by default send the burn address: `0x00000000000000000` instead of a unique identifier in these message broadcasts. As suggested in a recent recent issue, users can enable their address to be broadcasted on a per-site basis (per dApp), which would change the address from the 0 address to their personal address. 

These message broadcasts will significantly decrease the value of ETH over the long-term.

**Comment by projectoblio** [comment]
Aight i was trying to be polite but let me be frank: 

Using window messages in this way is *fucked up*. It's not just a cryptocurrency problem. MetaMask is communicating unique identifiers to every website no matter if you're using a VPN. You can track users across VPNs, firefox private windows, even different devices. This is a *major security hole* in metamask that should not be ignored.

**Comment by projectoblio** [comment]
(sent from my phone)

MetaMask violates the terms of humans subject research set out by the U.S. Department of Health and Human Services

Please see earlier issue which was much angrier and filed 22 days ago and still ignored https://github.com/MetaMask/metamask-extension/issues/6212 . the deceitful medium post is linked to there

Even asking MetaMask not to track you still does not turn off these broadcasts.

**Comment by danjm** [comment]
@projectoblio So are you seeing your address in the data logged by `window.addEventListener("message",function(e){console.log(e.data)})` even after private mode is enabled?

I just did the following:
- freshly installed metamask (and noticed that privacy mode is not enabled by default)
- opened the console here on github and entered `window.addEventListener("message",function(e){console.log(e.data)})`
- saw the data logged as you described, with my ethereum address and selected network
![Screenshot from 2019-03-21 13-06-12](https://user-images.githubusercontent.com/7499938/54764141-2360a200-4bda-11e9-9a62-53f609340623.png)


Then I:
- turned on privacy mode
- refreshed the tab where github was open 
- opened the console on the github tab and entered `window.addEventListener("message",function(e){console.log(e.data)})`
- saw that the logged data no longer contains my address
![Screenshot from 2019-03-21 13-04-24](https://user-images.githubusercontent.com/7499938/54764151-28bdec80-4bda-11e9-8b2c-81efe1536cbb.png)

Are you seeing something different when you do the same @projectoblio? If so, would you be able to go to the info tab of the settings screen and tell us what version of MetaMask you are on?

If you are seeing the same behaviour, and privacy mode does cause the address in the message data to be `undefined`, then am I correct in concluding that your concerns will be addressed by having privacy mode enabled by default after a fresh install?

**Comment by projectoblio** [comment]
Wow. That's a non-answer if i've ever seen one. 

You don't even have an example dApp, or technical reason for doing these message broadcasts.

**Comment by danfinlay** [comment]
The primary security feature that MetaMask offered Ethereum users was to allow them to stop leaving keys in websites that they don't trust. We did this by using the WebExtension API to store the keys in the background.

In order to provide an API to websites, have to communicate via a per-page [content script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Communicating_with_the_web_page). Content scripts can unfortunately only communicate via the [Post Message API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), which can be heard by all elements in the connected site.

We do agree that:

- We need to enable privacy mode by default, and have been slow to do that. We'll be doing this soon, but are making sure to do it in a non-site-breaking way.
- PostMessage does expose the messages to all elements within a signed-in iFrame, and that could be more private. However, we depend on browser developers to make a more private communication channel for providing an API to sites.

We definitely reject all your claims that this is some weird malicious act on our part. That would be the craziest move we could ever make on a totally open source crypto project.

Our action items are the same they were the last time you posted: To get to privacy mode by default sooner.

If you have a proposed mechanism for providing an API to a site from an extension that is more private than PostMessage, we would be happy to see it. By all means let us know if you find a better way for your own wallet, we are being completely transparent about our reasoning here.

**Comment by projectoblio** [comment]
`
if(window.ethereum!="undefined"){

}
`

**Comment by projectoblio** [comment]
I have a dApp ready to go that doesn't use ads but does require a third-party iFrame. It requires an Informed Consent form where I describe to each user the ways they're being tracked. This Consent form is where I describe all the ways a user could be made non-anonymous based on my site, to my knowledge. Anonymity is part of the U.S. Department of Health and Human Services Guidelines for human subject research put out in 2019. When users who are used to accessing my site with MetaMask try to visit, what am I going to say? I'm going to have to say that, like the iFrame, MetaMask addresses can be easily linked to a much larger global identity as well as the third-party iFrame. Probably, a responsible researcher would require MetaMask to be uninstalled entirely. If you're okay with that kind of PR I guess I can do it. But it's going to cause a rub if I launch a dApp, it's extremely popular, and it deliberately excludes users who use MetaMask because it isn't private enough. Users using this dApp will receive cognitive enhancement scores based on their memory skills, which if not made anonymous, can greatly affect their health insurance rates. I'm only interested in pursuing the dApp as a research project (not as a corporate enterprise) so that's that.

**Comment by danfinlay** [comment]
> There's literally no reason for these unique identifiers to be posted on every single website by default, for any dapp.

We agree, this is what we call "privacy mode", and you can enable it in settings now as danjm wrote above, and we are working to make it default without breaking existing sites.

> There's like a billion other ways to communicate messages (e.g. time-dependent encryption) that can be used to communicate this value so that it's unique every time or at least doesn't link at all to an Ethereum address

I'd love to hear more about these billion other ways. Communicating these proposals would probably be easier than building a wallet from scratch.

One way we're considering improving this privacy story is by generating a single-purpose key per app, but this is still in an early proposal phase:
https://ethereum-magicians.org/t/eip-erc-app-keys-application-specific-wallet-accounts/2742

We aspire to make MetaMask not just hold up to any legally-enforced privacy standards, but to raise the bar of privacy.

We'll be enabling privacy mode by default soon(er), the criticism that we've been slow on that is valid and we take it seriously. (we will allow backwards compatibility for users who want to manually enable the old behavior)

We will still require a way to communicate with logged-in apps, and that means over PostMessage, and that means all your dependencies will still be able to listen to post messages to hear update messages. It's an interesting question of whether we could establish a secure communication channel with an application that excludes other scripts it loaded in the same domain. I'm not clear why a time-generated key would not be prone to a dependency generating the same key. It probably requires the site generating its own key, and then at log-in time somehow validating that the site currently requesting sign-in permission is in fact the key generated by the app you intended to connect to, not by any of its dependencies which also have access to this global `ethereum.enable()` method. Maybe either a CA or Web of Trust type infrastructure could do, but then either the log-in requires the site to host a live server with the key (which eliminates statically hosted Dapps), or the key is publicly known, and in turn available to dependency or other-site phishing attacks.

Anyways, we're all ears on how we could make that communication channel more private, although it still seems like the privacy mode we keep talking about, that you keep dismissing, might satisfy your criteria.

**Comment by projectoblio** [comment]
The post message function includes an input to specify which domain receives the message. It is a field called cross origin research sharing. It is designed for exactly this issue an

**Comment by nsjames** [comment]
One of the ways we are doing this is by creating appkeys, nonces and internal user-approved permissions with origins that are specific to apps themselves and requiring "logins" to websites before exposing any private data like keys and such. We're also using local socket layers for connections which helps go from `app -> wallet` instead of `wallet -> app`.

However, @projectoblio I think you're missing one of the more important parts that @danfinlay is mentioning here. We had the benefit of learning from MetaMask's journey and implementing that kind of stuff off the bat at the core of the interaction.
MetaMask is an existing project with a vast number of applications that tie into it already and doing things on such an integrated stack requires lightly treading to make sure that applications that rely on it don't break.

Making drastic changes that might break functionality of accustomed user flows could end up costing both businesses and users tens of millions of dollars, and those decisions can't be taken lightly.

**Comment by ashaffer** [comment]
> In order to provide an API to websites, we have to communicate via a per-page content script. Content scripts can unfortunately only communicate with individual pages via the Post Message API, which can be heard by all elements in the connected site.

I believe his point is that the postMessage API allows you to restrict the target origin of the messages that you are broadcasting, but you are not taking advantage of that to narrow the scope of availability of those messages. This would, e.g. prevent tracking iframes from intercepting these messages.
