### ISSUE TITLE
MetaMask times out too quickly when signing with a ledger.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6345]
**Describe the bug**
When signing with a ledger, if you take the time to read through all of the transaction details on the Ledger Nano X, by the time it cycles through the last bit of information MetaMask will have timed out the transaction.

**To Reproduce**
1. Connect a Ledger to MetaMask.
2. Send some ETH to yourself from the Ledger.
3. Wait for Ledger to prompt for confirmation.
4. Wait until Ledger cycles through all of the transaction details and back to the "click to confirm" message.
5. Confirm the transaction on the ledger.
6. Notice that MetaMask doesn't respond to the confirmation.
7. Wait a while for MetaMask to time out.
8. Notice the error message in MetaMask:
> ALERT: TransportError: Failed to sign with Ledger device: U2F TIMEOUT

**Expected behavior**
To be able to review the transaction I want to sign before confirming.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

**Comment by brunobar79** [comment]
I'm pretty sure this issue is the same as this: https://github.com/LedgerHQ/ledgerjs/issues/306

From what I know, it wasn't happening on Brave because they are a few versions behind than Chrome in terms of Chromium.  See https://twitter.com/BrendanEich/status/1101543129205956608

I'll follow up with the Ledger team to see if there's any news on their end.

**Comment by uhhuhthatkate** [comment]
This is definitely still an issue. Unable to transfer from Ledger using MetaMask without the ALERT: TransportError: Failed to sign with Ledger device: U2F TIMEOUT error. This is with the latest version of Chrome.

**Comment by uhhuhthatkate** [comment]
For clarification, this is Ledger Nano S.

**Comment by brunobar79** [comment]
After reaching out to Ledger and testing it myself on the latest Chrome and Brave I can confirm the issue is fixed by upgrading to the latest firmware (1.5.5) AND installing the latest version of the ETH app (v1.2.4) through the ledger live app

![Screen Shot 2019-04-02 at 12 33 22 PM](https://user-images.githubusercontent.com/1247834/55420608-6cebae00-5545-11e9-8e40-c0dcb1d2d919.png)

**Comment by milo223344** [comment]
Hi all, the issue is still not resolved. using 1.5.5 and Eth V 1.2.7 (5th June) and getting the time out through Chrome, Brave and also tried Opera (which doesnt allow to connect to Nano s). Anyone still struggling also with this issue??

**Comment by shawnholt** [comment]
Same issue as milo223344 and MicahZoltu as of 6-20-19 running latest everything on nano s. tried brave / firefox and same issue. can see wallet.  not only timeout but freezes the ledger so can't accept tx on device.  Seems related to windows 10 May 1903 update and U2F Timeout. https://pasteboard.co/IklfNCM.jpg

**Comment by nyetwurk** [comment]
Same on Windows 10 with chrome ff and brave

**Comment by nyetwurk** [comment]
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/

**Comment by KPrasch** [comment]
Can confirm this issue still happens with the following versions:

Ledger Firmware 1.6.1
Eth App 1.3.7
Chrome 85.0.4183.102

Transaction appears in MM UI then disappears after 5-10 seconds.

**Comment by amadeobrands** [comment]
This still happens for me as well.
Please let me know when a fix is found?

**Comment by clesaege** [comment]
We still have the same issue and it makes it very hard to verify transactions on the ledger in time.

**Comment by epheph** [comment]
Since the recent wNXM hack, I have switched my ledger to verifying all data in the fields and signature. However, the metamask/browser timeout for interacting with the ledger is WAY too short to verify even a few fields. Even before switching to verifying fields, I've still failed when being very thorough about recipient and values. 

MetaMask should give users ample time to fully verify their transactions or else we will create a culture of not fully verifying what we are signing, leading to more hardware-wallet-based exploits.

**Comment by dave-dm** [comment]
> MetaMask should give users ample time to fully verify their transactions or else we will create a culture of not fully verifying what we are signing, leading to more hardware-wallet-based exploits.

It should give at least 5-10minutes. For example the uniswap router has like 6 arguments to verify.

**Comment by AlexJupiter** [comment]
There's been some recent improvements with the MetaMask/Ledger integration (https://consensys.net/blog/metamask/metamask-and-ledger-integration-fixed/). Is anyone still experiencing this problem now? Otherwise I will move towards closing this issue.
