### ISSUE TITLE
inpage.js:1 MetaMask - RPC Error: The method personal_listAccounts does not exist/is not available {code: -32601, message: "The method personal_listAccounts does not exist/is not available"}

### ISSUE THREAD

**Issue by tnlthanzeel** [MetaMask/metamask-extension#6516]
i get this error all the time in chrome inpage.js:1 MetaMask - RPC Error: The method personal_listAccounts does not exist/is not available {code: -32601, message: "The method personal_listAccounts does not exist/is not available"}

**Comment by bdresser** [comment]
could you give us reproduction steps that lead to this error?

**Comment by industral** [comment]
Have the same on [remix](https://remix.ethereum.org)
**Enable Personal Mode** on **Settings**

<img width="1679" alt="Screen Shot 2019-05-02 at 8 58 19 PM" src="https://user-images.githubusercontent.com/331772/57096112-22647980-6d1d-11e9-9953-8e2fbc23eeb4.png">

Pay attention, that account list couldn't be fetched.

**Comment by tnlthanzeel** [comment]
> Have the same on [remix](https://remix.ethereum.org)
> **Enable Personal Mode** on **Settings**
> 
> <img alt="Screen Shot 2019-05-02 at 8 58 19 PM" width="1679" src="https://user-images.githubusercontent.com/331772/57096112-22647980-6d1d-11e9-9953-8e2fbc23eeb4.png">
> 
> Pay attention, that account list couldn't be fetched.

go to settings, untick "enable personal mode"

**Comment by industral** [comment]
Thanks @tnlthanzeel! It did a trick. Disabling privacy mode fix it. But I googled a little bit, and found, that remix app just doesn't **EIP-1102** compatible. So, instead of disabling privacy mode, which is unsecure and open your data to all sites you browsing, just open Console on remix page and execute `web3.currentProvider.enable()`. That will bring popup from metamask to connect to that page. And after accept - you account will appear in a list.

**Comment by bdresser** [comment]
This is an issue on Remix's side - please feel free to thumbs up this issue! https://github.com/ethereum/remix-ide/issues/1590
