### ISSUE TITLE
Implementing MetaMask on Electron app

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-extension#6597]
Well, that isn't exactly like on the title.
It isn't simply a Electron app, but a platform to run Electron apps in just one binary; technically, yes, it is just a Electron app.

@danfinlay 

How could I implement MetaMask on a Electron app?
And when this app is exported to Cordova (which doesn't uses Chromium), how it can be possible?
I'm open for answering your doubts about [HTML5Apps Platform](https://github.com/html5appsplatform/HTML5Apps-Platform).

I see Dapper is taking place of MetaMask on browsers, so I want to take MetaMask to a new level.

**Comment by danfinlay** [comment]
It would be fairly easy to import MetaMask's current internals and wallet interface in an electron app, and this could allow us to provide our web3 APIs to other native desktop apps.

Previously, the Mist browser tried building a standalone wallet browser, and demonstrated that Electron is not a secure environment for that purpose, because its version of Chromium lags too far behind the latest.

But for simply managing a wallet, it has many advantages:
- Ability to use native system APIs (secure enclave for key storage, TCP/UDP for p2p networking are particularly exciting)
- Ability to serve other native apps
- Ability to run a single wallet across multiple browsers.

Doing this right _would_ require a solid lowest-level understanding of MetaMask's construction as an app. A few starting points are:

- [this architecture diagram](https://github.com/MetaMask/metamask-extension/raw/develop/docs/architecture.png)
- The [Extension API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)'s [manifest.json file](https://github.com/MetaMask/metamask-extension/raw/develop/docs/architecture.png)
- The entry points: [background](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/background.js), and [UI](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/ui.js), which could live in the same environment, as well as the [inpage script](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/inpage.js) we run in every "untrusted" context.

**Comment by Gudahtt** [comment]
Closing, as this question seems to have been adequately answered. If you have further questions, I'd recommend asking in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics). Thanks!
