### ISSUE TITLE
Create separate entry point for a notification.js build

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#6644]
- [ ] add new `notification.js` build to create new bundle for `notification.html`
- [ ] replace `ui.js` with new bundle in `notification.html`

**Comment by danfinlay** [comment]
closing this for now, since we have done some of this refector work.

**Comment by Gudahtt** [comment]
We didn't actually make any headway on this after, as the performance improvements were negligible due to how we're generating our bundles. The last time I looked into this, my conclusion was that we needed to omit more unused code from our bundles for this approach to be effective.

Great strides are made towards this in https://github.com/MetaMask/metamask-extension/pull/8170 - so a natural follow-up to that PR might be to re-introduce this separate notification entrypoint.
