### ISSUE TITLE
Metamask stops working if gas is passed as an object

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#6707]
**To Reproduce**
1. Open https://codepen.io/rstormsf/pen/qzBRBe?editors=1010
2. Click `Click me` button

```js
window.ethereum.sendAsync({
                    method: 'eth_sendTransaction',
                    params: [{
                        from: acc,
                        to: "0x0039f22efb07a647557c7c5d17854cfd6d489ef3",
                        gas: {}, // provide Gas as an Object
                        gasPrice: "0x77359400",
                        value: "0x0",
                        data: "0x0"
                    }],
                    jsonrpc: '2.0'
                }, (err, response) => {
                    window.alert(JSON.stringify(err))
                    console.log(response)
                })
```

**Expected behavior**
It should not break metamask

**Screenshots**
![image](https://user-images.githubusercontent.com/9360827/59244755-a0dcf280-8bca-11e9-955c-5d730deb11a2.png)

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - MetaMask Version 6.6.1

**Additional context**
![metamask_big](https://user-images.githubusercontent.com/9360827/59244783-b81be000-8bca-11e9-921a-3d33c7b7c74a.gif)

**Comment by rstormsf** [comment]
I can't even reset an account for metamask, I can't use this account anymore. It's showstopper issue

**Comment by akshitkrnagpal** [comment]
Hi
I am new to MetaMask project and would like to work on this.
I already have a local build of metamask extension and I am able to reproduce the bug.

After some investigation, I found that this problem is arising because the transaction is being added in the `unapprovedTxs` without validation of `txParams`. Validation of `txParams` in only done in `TransactionStateManager.updateTx()` and not in `TransactionStateManager.addTx()`.
