### ISSUE TITLE
Unable to import account using seed phrase halfway through new account creation

### ISSUE THREAD

**Issue by MarkOSullivan94** [MetaMask/metamask-extension#6774]
Note: This bug isn't affecting me as I have been able to import my seed phrase to regain access to my account after removing and reinstalling the plugin.

**Describe the bug**
Whenever going through the first time flow it seems that you can end up getting stuck halfway through the process of creating an account if you change your mind and want to recover an old account using the seed phrase. 

**To Reproduce**
1. Go through the first time flow account creation process
2. After entering a password you should be shown the secret backup phrase screen
3. Click 'Next' after revealing the seed phrase
4. Now you should see the 'Confirm your Secret Backup Phrase'
5. Refresh this webpage
6. Click on the 'Import using account seed phrase' hyperlink on the 'Welcome Back!' screen

**Expected behavior**
I should be able to exit the account creation process and be able to start the process of importing an old account.

**Screenshots**

![Screenshot 2019-06-29 at 11 57 33](https://user-images.githubusercontent.com/6950843/60383135-1c60ef80-9a65-11e9-8894-fbcf9969e8fb.png)

**Browser details (please complete the following information):**
 - OS: MacOS Mojave version 10.14.5
 - Browser: Chrome
 - MetaMask Version: 6.7.1

**Comment by tmashuang** [comment]
On v8.1.5, after step 5 now the confirm seed phrase screen will rerender without the seed phrase showing since the component doesn't store the seed phrase by default or in state. To complete the seed phrase confirmation after a refresh, on needs to go back to reveal the seed phrase again and proceed to confirm. 

This doesn't seem to be intended but I do not believe we should keep the seed phrase on screen after refreshing the window for safety reasons. 

If there's a disagreement to my statement and can provide a fix, or alternate solution/approach, the issue can be reopened.
