### ISSUE TITLE
Cancel tx cancels wrong transaction if there is more than 1 pending

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#6844]
**Describe the bug**
Might be related to #5780

Basically if I have more than 1 pending tx, and I try to speed up a tx, it tries to speed up only most recent pending tx, but not the one that I actually selected.

**To Reproduce**

1. Send a tx `X`
2. Send a tx `Y`
3. Notice you have both txs as pending in metamask
4. Try to cancel tx `X` and then speed up cancellation
Result: Tx `Y` is sped up, not the `X`
**Expected behavior**
New tx with the same nonce as X should be generated to **cancel** it, instead it speeds up latest tx for some reason

**Screenshots**
![speed_up](https://user-images.githubusercontent.com/9360827/61100698-eab03700-a41b-11e9-9f17-fdfdddbc2ec6.gif)

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - MetaMask Version 6.7.2

Hint: 
Ropsten doesn't accept 1 gwei tx for now, so it's good to reproduce this issue

**Comment by dpazdan** [comment]
User experienced similar but with cancellation attempts.  When canceling the oldest tx, it would broadcast with a higher nonce, not canceling the intended tx.

Adding a custom nonce field would help fix issues like this manually: #1410 or maybe allowing a dapp or site to set nonce.

**Comment by Gudahtt** [comment]
That gif doesn't seem to match the description. In the gif two transactions were created: 402 and 403. It was the second transaction - 403 - that was cancelled, and then sped up. This speed-up attempt was fruitless because the first transaction had a lower nonce, and is blocking the completion of the second transaction.

I don't think the wrong transaction was cancelled or sped-up. I tried to reproduce something like that, but came up empty. I do think it's a bug that we allow speeding up anything other than the lowest pending transaction though - that button shouldn't be there. We'll fix that.
