### ISSUE TITLE
Use main-net ENS even when on other networks.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6916]
The ropsten ENS deployment uses the `.test` suffix, and so using `.ens` is a safe way to fetch a recipient address, even when on another network, and so we should allow it.

Inspired by this comment on StackOverflow:
https://ethereum.stackexchange.com/questions/32804/can-metamask-read-ethereum-name-service-ens-addresses/32970?noredirect=1#comment88744_32970

**Comment by wighawag** [comment]
This is actually a critical security issue.

An attacker can easily register a ENS name on a testnet.
Have a another website that request the user to switch to that testnet and then have a normal link to a valid ens link that the user believe is secure.
With current metamask, that link will go to the attacker registered ipfs hash (since now the user is on the testnet)

In that attacker version of the website, the user is vulnerable to a phishing attack as the website could look exactly the same and will have the same ENS name in the url.

That website could then request to switch to mainnet and do something malicious

**Comment by danfinlay** [comment]
@wighawag we have opened an internal issue for tracking this, deleting comment to to prevent reduce spread of possible phishing strategies while we address the issue.

**Comment by Gudahtt** [comment]
In #7944 we ensured that `.eth` addresses are only resolved on Mainnet. We could still add support for resolving them on Mainnet while another network is selected globally, but this is already tracked in #6708

I'll close this now, and we can track progress on the remaining work in #6708
