### ISSUE TITLE
Errors should not break CSS

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6973]
Sometimes an error can cause our CSS to break.

> libs.js:1 Uncaught (in promise) RangeError: Maximum call stack size exceeded

![broke-css](https://user-images.githubusercontent.com/542863/62642957-aa00ec00-b8fb-11e9-9152-16465c699a5b.jpg)

While I don't see a specific reference to `libs.js` in our Sentry, that might be because our source maps are identifying the actual files. There are [several possible candidates in Sentry](https://sentry.io/organizations/metamask/issues/?groupStatsPeriod=14d&project=273505&query=is%3Aunresolved+RangeError), and ideally none of them would result in broken CSS.

**Comment by Gudahtt** [comment]
I suspect this might already be fixed already in v7.0.0,  as a result of #6894

Because the CSS was loaded dynamically, any JavaScript error prior to that injection would presumably prevent the injection. I doubt an error would have that affect anymore, though surely it would still have other negative affects.

**Comment by danfinlay** [comment]
Great, thanks! I'll close this for now, and reopen if we see it again post-release.
