### ISSUE TITLE
user: Windows build failing

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#706]
submitted by @haiqu

> Build fails due to missing eth-store in Windows 7. I have the correct versions of the tools and followed the instructions to the letter but I get a failure due to secp256k1 crashing on rebuild. It has been reported to their devs but a workaround is to use npm rebuild and continue. The final build is also missing two files, background.js and background.js.map which I've been swiping from the plugin installed from the Google store.

**Comment by Zanibas** [comment]
secp256k1 is indeed causing issues, trying to figure out how to get it to play nice on Windows 7. tl;dr it's a nightmare though, will continue work on this.

**Comment by flyswatter** [comment]
That same dependency is failing building with node 7, too.

I ran an `npm ls` to see if it was used by a dependency we could remove/update, and got this:
```
├─┬ eth-store@1.1.0
│ └─┬ web3-provider-engine@5.1.1
│   ├── array.prototype.find@1.0.0
│   ├── es6-promise@3.3.1
│   ├─┬ eth-lightwallet@1.0.1
│   │ ├── bignumber.js@2.0.7 (git://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
│   │ ├─┬ elliptic@3.1.0
│   │ │ └── bn.js@2.2.0
│   │ └── web3@0.14.1
│   ├─┬ ethereumjs-account@1.0.5
│   │ └─┬ ethereumjs-util@2.3.1
│   │   ├── bn.js@4.11.6
│   │   ├── browserify-sha3@0.0.0
│   │   └── elliptic@6.3.2
│   ├─┬ ethereumjs-tx@0.6.14
│   │ ├── ethereum-common@0.0.13
│   │ └─┬ secp256k1@2.0.10
│   │   ├── bn.js@4.11.6
│   │   └── elliptic@6.3.2
│   ├─┬ ethereumjs-util@2.6.0
│   │ └── bn.js@4.11.6
│   ├─┬ ethereumjs-vm@1.0.4
│   │ ├── bn.js@4.11.6
│   │ ├── es6-shim@0.33.13
│   │ └── ethereum-common@0.0.10
│   ├── ssl-root-cas@1.2.3
│   └─┬ web3@0.15.3
│     └── bignumber.js@2.0.7 (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
├─┬ ethereumjs-tx@1.1.2
│ └── ethereum-common@0.0.17
├─┬ ethereumjs-util@4.5.0
│ ├── bn.js@4.11.6
│ ├─┬ keccakjs@0.2.1
│ │ ├─┬ browserify-sha3@0.0.1
│ │ │ └── js-sha3@0.3.1
│ │ └── sha3@1.2.0
│ └─┬ secp256k1@3.2.2
│   ├── bip66@1.1.4
│   ├── drbg.js@1.0.1
│   └── elliptic@6.3.2
```
As you can see, we actually have two copies of `secp256k1` installed, one is an older copy because eth-store relies on an old version of `provider-engine` which relies on an old version of `ethereumjs-tx` which relies on an old version of `ethUtil` which brings n the old version of `secp256k1`.

We might be able to solve this by updating `eth-store`, although I *think* it may have undergone breaking API changes.

**Comment by tmashuang** [comment]
I have been using Metamask on a windows machine for some time now. Will reopen this issue if there still an issue.
