### ISSUE TITLE
We should catch Matomo errors

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7106]
Instead of throwing them to Sentry:
https://sentry.io/organizations/metamask/issues/1204724647/?project=273505&query=is%3Aunresolved

**Comment by Gudahtt** [comment]
I think these errors did represent genuine problems in most cases, as it meant the metric wasn't being sent before the window closed.

I believe this has been fixed by #9857 though. Now that all metrics are sent from the background instead of the UI, the window being closed no longer interrupts the process.
