### ISSUE TITLE
Unable to sign a transaction with Ledger

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#7118]
I am experiencing intermittent issues with two different Ledger Nanos when trying to sign transactions with Metamask. I unfortunately have not figured out what exactly can get be done to reproduce the behavior. However I'll add as much detail as I can:

1) Neither the Ledger nor Metamask show anything when being asked to sign the transaction. There is no feedback to the user. 
2) Trying to get Metamask to recognize the Ledger, I tried to re-import it, nothing happens when I select Import Hardware wallet >  "ledger" > Connect
3) After coming back to my computer a few hours later, I got the following notifications: <img width="338" alt="Screen Shot 2019-09-06 at 09 32 45" src="https://user-images.githubusercontent.com/31727/64409771-d68a5e00-d089-11e9-8b6b-bbf0fdc84594.png">
4) I had the same behavior both in Chrome and Firefox, I tried to add the Ledger in Chrome. I also tried it with two different ledgers and I tried disconnecting them.
5) I resorted to using Brave with Metamask which worked at the first attempt.

OS: mac OS
Metamask 7.1.1
Firefox 68.0.2

**Comment by fairdrop** [comment]
I have the same problem.

**Comment by Lord-Luvat** [comment]
I'm having the same issue/error message, except this is happening for me on Brave browser too. It is persistent with me, not intermittent, but the error message and behaviour are the same. I have found no way around this bug for the moment and so my Metamask is unusable with my Ledger Nano S. 

I'm using:
Browser - Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Extension - MetaMask Version 8.0.5
Hardware - Ledger Nano S
Hardware's Firmware - Secure Element Version 1.6.0, Microcontroller Version 1.12
Hardware's Ethereum App - Version 1.3.7

It seems that the issue is not the hardware, as I can still access my wallet and send transactions from Ledger Live interacting with my ledger nano, but metamask does not send transactions through to my ledger for signing and I receive the same error message as above. These error messages are only received after changing my wallet off the mainnet and then back onto mainnet, as until that point metamask views the transaction as pending. Obviously, though confirming my hardware wallet still seems to be working properly and signing transactions as expected when interacting with Ledger Live, I did not have both metamask and Ledger Live open at the same time when trying to get Metamask to work, as I didn't want these 2 applications to possibly interfere with each other.

Please fix/help :)

**Comment by ArtiVin** [comment]
Same issue here.. Do not get transaction confirmation dialog on my ledger device. "Contract data allowed" enabled in Eth App settings.

**Comment by mudgen** [comment]
Has this been fixed?    @Gudahtt ?

**Comment by Lord-Luvat** [comment]
@mudgen I'm no longer having this problem. Can't remember how I fixed it though. Did a whole lot of rebooting, uninstalling, and reinstalling things with regards to ledger live, metamask and my browser. Can't remember what did the trick, but haven't had this issue since.

**Comment by danjm** [comment]
Last comment indicates the error was resolved for the reporter. We have solved multiple ledger issues over the ellapsed time frame as well.

If anyone experiences problems signing with ledger, feel free to open a new ticket.
