### ISSUE TITLE
#5146 is happening again

### ISSUE THREAD

**Issue by danielschonfeld** [MetaMask/metamask-extension#7166]
Seems like #5146 is happening again consistently on mac (Mojave) both chrome and firefox

**Comment by bdresser** [comment]
reopened 5146

**Comment by danielschonfeld** [comment]
Okay I'm confused, we reopened, then closed it? This problem still happens and it makes MM completely unusable

**Comment by tmashuang** [comment]
Please provide a details to your issue, #5146 was archived and your issue is not the same as your since you mentioned it was a hardware wallet. Please open a new issue with adequate information to solve/reproduce your issue. Information that can be useful can be brand of hardware wallet, firmware, OS version, browser versions, and/or screen capture of issue. All of which are briefly mentioned on our issue template when submitting a new issues [here](https://github.com/MetaMask/metamask-extension/blob/develop/ISSUE_TEMPLATE).
