### ISSUE TITLE
Spinner without anything happening when trying to connect new HW Wallet

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#7548]
When I try to connect a new HW wallet, I just receive an endless spinner and nothing happens. There are no errors in the console.

I'm running Firefox 70.0.1 on Linux with Metamask 7.6.1

![screen_2019-11-24-18-17-14](https://user-images.githubusercontent.com/31727/69499120-cb0b3e00-0ee6-11ea-93fa-ba61357d0d41.png)

**Comment by livnev** [comment]
I am able to reproduce this with Ledger Nano S on Firefox with Metamask 7.6.1. This issue seems to have been present for many previous versions though.

**Comment by bdresser** [comment]
@lucasvo @livnev what hardware wallet are you using and what firmware version is it running? cc @tmashuang

**Comment by livnev** [comment]
@bdresser Ledger Nano S, with `Secure Element 1.5.5`, `MCU 1.7`, Ethereum app version `1.2.7`.

**Comment by jpritikin** [comment]
I often run into this problem. I suspect it is taking a long time to grab the account balances. In my opinion, you should show all the addresses immediately and grab the account balances in the background. I often know which account I want without having to see the account balances.

**Comment by ynaciri** [comment]
I can confirm the same kind of issues, support on latest ledger software version has been broken. And that nothing works for me on firefox.

Details :

Working configuration :

* Google Chrome v79.0.3945.130 (official 64 bits build)
* Metamask v7.7.2
* Ledger firmware v1.5.5
* Ledger MCU v1.7
* Ethereum ledger app v1.2.0

In this configuration, metamask will flash several times the Windows security popup (only on updated Windows 10 versions) :

![working1](https://user-images.githubusercontent.com/8029435/72627381-b2e6f680-394c-11ea-888d-d62de158d707.jpg)

And after a few flashes (about 5~6), I finally get a list of ethereum addresses to pick :

![working2](https://user-images.githubusercontent.com/8029435/72627439-cc883e00-394c-11ea-8b9b-800b147e496d.jpg)

Same configuration but on Firefox v72.0.1 (64 bits) fails with the loading indicator always spinning and zero windows security notification (left it spinning for 10 mins) :

![notworking1](https://user-images.githubusercontent.com/8029435/72627633-21c44f80-394d-11ea-8b1d-335a800f2811.jpg)

Trying with an updated ledger and nothing works at all. Here is the detailed configuration and screenshots for Chrome :

* Google Chrome v79.0.3945.130 (official 64 bits build)
* Metamask v7.7.2
* Ledger firmware v1.6.0
* Ledger MCU v1.11
* Ethereum ledger app v1.2.12

This time the windows security popup changes and loops until it ends on the spinner indefinitely like with firefox :

When the ethereum app is not opened on the ledger it asks to insert the security device in any usb port :

![notworking1 5](https://user-images.githubusercontent.com/8029435/72628865-7ff23200-394f-11ea-81e7-5422eced68b8.jpg)

After opening the ethereum app, or when it's already opened when connecting it to Metamask, I get the following popups.

Here it asks to "touch" the security device, might mean it's expecting a user action but the ledger doesn't give any prompt :

![notworking2](https://user-images.githubusercontent.com/8029435/72628973-b465ee00-394f-11ea-998f-1029b3e09187.jpg)

So logically, after less that 1 second, it fails :

![notworking3](https://user-images.githubusercontent.com/8029435/72629044-d0698f80-394f-11ea-85d3-b81823174fad.jpg)

The message says "Couldn't complete the connection. Please try again and make sure you proceed with the action."

Then, less than 1 second after it tries again with asking to insert the security device again :

![notworking4](https://user-images.githubusercontent.com/8029435/72629155-09096900-3950-11ea-8bd5-7d1f1417fa9e.jpg)

It does that loop for a few tries before simply stopping and returning to the eternal spinner. Same thing if I leave it that way for 10 mins.

So, my guess is that some compatibility was broken between then and the latest firmware/ethereum ledger app updates vs MetaMask v7.7.2.

**Comment by zexxlin** [comment]
@lucasvo @bdresser Any news on the issue? Just encountered it today, all of a sudden.

**Comment by PatrykLucka** [comment]
Does it still happen on Linux or MacOS? I just tested it on MacOS using Ledger Nano S both on chrome and firefox and it works. I'm asking about Linux and MacOS, because Windows 10 is a little more tricky...

In the [ledgerjs repo](https://github.com/LedgerHQ/ledgerjs) we can find such table:
<img width="505" alt="Screenshot 2020-09-04 at 12 48 24" src="https://user-images.githubusercontent.com/5708018/92231503-1eb2ab00-eead-11ea-967c-5980ba1a18f7.png">

As we can see **U2F channel** (which is the only one supported by Firefox, Safari and IE) has "ISSUE" on windows. I think it's the issue with popup reported above. 

Of course we can try to differentiate channel based on the browser, so this is what I tried to do. However:
- WebHID is supported by Chrome only as a flagged feature, there's no default support yet
- WebUSB also has known issues, which I can confirm - I was not able to connect my Ledger Nano S using this channel, because of [No compatible device found error](https://github.com/LedgerHQ/ledgerjs/issues/484)
- WebBluetooth is supported only by Nano X version, so it's also not an option for us

It looks like a Ledger/Windows issue, which we can't do much about at the moment.
