### ISSUE TITLE
Is this possible to port metamask to mobile broswer without react native?

### ISSUE THREAD

**Issue by devzyf** [MetaMask/metamask-extension#7729]
I try to build a project which can use metamask within mobile's browser without react native, that's  means the user don't need to install the app, just use web browser.
so far , i haven't found any demo which does that.
BTW, is this possible to use metamask without install the browser extension? just use it from the website?
hope someone will help!!!

Many thanks

**Comment by tmashuang** [comment]
I have limited experience in mobile development, but from what I understand we are supported in Firefox Browser on Android, since it allows the use of Addons in their mobile browser. We've considered building full size apps via website, electron, etc., but found that the extension platform allows dapp devs to easily develop on, and not a whole lot of benefits on limited time. Hope this answered your question.
