### ISSUE TITLE
Feature Request: Add an option to temporarily disable Metamask timeouts

### ISSUE THREAD

**Issue by josephj11** [MetaMask/metamask-extension#7732]
## **What problem are you trying to solve?**

I  am currently buying HEX (smart contract via web page). When I display the page, it doesn't show me much that's useful until I enter my password  into Metamask. Everything works fine, but Metamask keeps timing out on  me. When that happens, the data I'm looking at disappears. Then, I have  to enter the password again and it takes awhile for the website to get  the data back.

This  is especially an issue if I am watching the "price" right before close  of day (buying interval) to decide if I want to buy more at the last  minute and suddenly all the data goes away and takes a minute or more to  restore once I enter the password again.

## **Describe the solution you'd like**

I would like an option to tell Metamask not to timeout automatically or to set the timeout interval to something a lot longer.

For security reasons, I wouldn't want this as a permanent setting. The timeout is usually a good thing.

## **Additional context**

I am using Vivaldi 2.10 on kubuntu 18.04 (KDE).

**Comment by Gudahtt** [comment]
MetaMask shouldn't "timeout" by default; we stay unlocked unless the extension is reset (i.e. when MetaMask updates or when the browser resets), or unless you're using the "Auto-Lock Timer" option under the Advanced Settings. You can disable this timer by setting it to zero.

I'm going to close this for now since the requested behaviour is already supported, but please let me know if I've misunderstood something. Thanks!

**Comment by josephj11** [comment]
I didn't know about that setting. Thank you! It was driving me crazy.

**Comment by josephj11** [comment]
If I it set to zero or a large value, how do set it so that authorization
is required for the next use?

**Comment by Gudahtt** [comment]
If you mean you want to require the password for the _immediate_ next use of the extension, there is a "Lock" button in the account menu that can manually lock the account so that the next use requires a log-in. Let me know if that answered your question - I wasn't 100% confident I understood what you meant.

**Comment by josephj11** [comment]
Exactly what I needed. Thank you.
