### ISSUE TITLE
Provide ability to export an account as standard json file

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#780]
Many wallets allow a standard-format json format of an ethereum wallet, password encrypted.  It would be nice for us to allow exporting accounts in this way.

**Comment by kennyrowe** [comment]
+1

**Comment by flyswatter** [comment]
Since we're asking users with mis-generated accounts to export those accounts in the dev-> master 3.0 bump, it would be nice to give them some format options.

The screen should allow private key, or JSON file.

JSON file will require a password, should include a confirmation box & warning text, and export only that account.

**Comment by Zanibas** [comment]
Could I get a link to what the format of a standard JSON file would look like?

**Comment by flyswatter** [comment]
Ethereum JS-wallet provides a method for generating this format:

toV3(password, [options])
https://github.com/ethereumjs/ethereumjs-wallet/blob/master/README.md

You can see an example in our tests where they test exports: https://github.com/ethereumjs/ethereumjs-wallet/blob/master/test/index.js

**Comment by Tadasu85** [comment]
Any idea on when this feature will be completed?

**Comment by flyswatter** [comment]
No, unfortunately this is not a very high priority feature at the moment, even though it would be fairly simple to implement.

Since we already allow exporting private keys, most users we've talked to are already able to transport their accounts to other clients, and so this has met the immediate demand.

Also, we're in the middle of some heavy design thinking, so we're a little hesitant to add features that we might then have to re-design right after.

If you'd like, feel free to make an appeal for us to raise the priority, I'm aware of the security benefits. Any others?

**Comment by licklake** [comment]
I would love this feature too.

**Comment by killua99** [comment]
I would love to have this feature

**Comment by danfinlay** [comment]
Sorry, it's just not very high priority. We're busy protecting users' funds, not caving to the latest snarky post on Github. We'll get to this when we have the bandwidth. Also, pull requests are welcome, this would be a pretty easy one to add.

**Comment by danfinlay** [comment]
Closing in favor of #1232.
