### ISSUE TITLE
It simply does not work at all despite many tests

### ISSUE THREAD

**Issue by BlockChainCaffe** [MetaMask/metamask-extension#7847]
**Describe the bug**
It just does not work. I tried it on linux mint with different browsers (Chrome, chromiun, firefox, brave) and it does not work in any of them. 
Sometimes opens a white/black window, sometimes asks for a password, but afther the password it asks for a nother one but stands still.
When I had the chance (no white window) I tried using the password or restoring or creating a new one. No luck.
Tried updating the browsers, all of them, updating the OS, reboot and such. No different result in NO situation.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:
Can't do any step

**Expected behavior**
should at least start...

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Linux Mint 19.2 tina 
 - Browser: Chrome, Firefox, Brave, Chromiun
 - MetaMask Version 7.7.2

**Additional context (Error Messages, etc.)**

**Comment by Jetsoanalin** [comment]
Facing similar issue 
![Uploading 20200121_103629.jpg…]()

When click on all done it doesn't move forward and shows blank screen on extension

**Comment by dpazdan** [comment]
@BlockChainCaffe Do you mind sending in your console logs to us at support@metamask.io?  Reference this github issue #, thanks!  https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

**Comment by Jetsoanalin** [comment]
**Problem :**
The Screen which you see below occurs when you try to deploy a transaction in the testnet the confirmation screen doesn't appears, instead a white screen displays.

**After effects of that one problem :**
1. Once that error is caused if you try reinstalling it again then you cant move beyond the final ''All Done" screen once you click on all done there is no response but the white screen comes in.
2. After this happened with my latest version of my Firefox 72.0.1, I tried this with all my browsers Chrome, Chromium, Opera, Brave latest version still cant move beyond the welcome screen, it simply goes white in all browsers.
3. **This White screen occurs in 3 conditions :** 
- When You Deploy a contract in Testnet
- If the Contract is deployed once sometime then during a transaction with the contract it goes white again.
- If after the above 2 error occurrence try to reinstall metamask in same browser or different browser it will simply not go beyond the welcome "ALL DONE" screen and plus it wont run in any browser whatever method you try its a recurring error.


**Metamask Version** : 7.7.2
**OS** : Ubuntu 18.04.3 LTS
**Browser** : Firefox, Chrome, Chromium, Opera, Brave ( All Latest Version )
 

@dpazdan i'm sharing this screenshots and message at support@metamask.io as well, i hope this issue is solved soon, have to use **CLI implementation** till then. 
@BlockChainCaffe it would be great if you could also share your error in the mail so that it can be solved ASAP.

**Hope to get support soon and a new update that solves this issue !**

![Screenshot from 2020-01-22 11-25-13](https://user-images.githubusercontent.com/25575282/72869308-c6a6aa00-3d0a-11ea-90fa-cf4161de7454.png)
![Screenshot from 2020-01-22 11-25-28](https://user-images.githubusercontent.com/25575282/72869309-c73f4080-3d0a-11ea-8a6a-21fb306f56ac.png)
![Screenshot from 2020-01-22 11-35-17](https://user-images.githubusercontent.com/25575282/72869531-9c092100-3d0b-11ea-8fcc-f30ff7a17efe.png)

**Comment by dpazdan** [comment]
additional information from op:
I've tried the following steps and found no success. 
Steps I have tried: 

1. Tried old versions of metamask - tried 7.1.1 and also tried some versions later 6.0 around 5 versions were tested but found no success.

2. Tried old versions of browsers - Firefox , Chrome, Opera but no luck came across same issue.

The Console log errors were in the screenshot attached. 

Do let me know if you need more information from me.

**Comment by tmashuang** [comment]
Fixed in latest version 7.7.3
