### ISSUE TITLE
Cannot edit send value when new address is detected

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7966]
When sending a token to a new address, MetaMask recognizes the new recipient and suggests saving it to the address book.

During that time, the token value field is non-responsive. After saving the address, the field seems to populate with what was typed while it was non-responsive.

**Comment by tmashuang** [comment]
Unable to reproduce on 
Firefox 72.0.2/MetaMask 7.7.8/Ubuntu 18.04
Chrome 80.0.3987.163/MetaMask 7.7.8/Win10

**Comment by Gudahtt** [comment]
I was also unable to reproduce this, using Chrome and MetaMask v8.1.11.

I'm guessing that this was yet another manifestation of the bug where CSS transitions aren't handled correctly by external monitors on Chrome on macOS. I'll close for now since we don't have a repro, and because if it is that macOS external monitor issue the effort to mitigate would be quite extensive.
