### ISSUE TITLE
eth_requestAccounts doesn't comply with EIP.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#7970]
**Describe the bug**
According to https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md#eth_requestaccounts, `ethereum.send('eth_requestAccounts')` should return a `Promise<Array<string>>`.  However, that method in MetaMask extension returns `Promise<JsonRpcObject<Array<string>>>`.  FWIW, MetaMask mobile app correctly returns a promise of a string array.

I have not tested other methods called via the new `.send` interface, but it seems reasonable that they should all return the result directly, not the JSON-RPC object.

**To Reproduce (REQUIRED)**
1. `window.ethereum.send('eth_requestAccounts').then(console.log)`
2. Notice that an object is logged.

**Expected behavior**
`.send(method)` returns a promise of a result, not a JSON-RPC object.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 72.0.2 (64-bit)
 - MetaMask Version: 7.7.4

**Comment by rekmarks** [comment]
Hi Micah, thanks for creating this issue. The inpage provider used on our `develop` branch is fully compatible with EIP 1102 and 1193. Since we are expecting to ship that provider very soon, I'm closing this issue.

Current behavior on `develop`:
![image](https://user-images.githubusercontent.com/25517051/73869153-ad1f5b00-47fe-11ea-9f0d-baf686a5dfc4.png)
