### ISSUE TITLE
Trying to send arbitrary hex encoded data string with transaction fails

### ISSUE THREAD

**Issue by pRoy24** [MetaMask/metamask-extension#8021]
Steps to reproduce
```
web3.eth.createTransaction({
...
data: "0x6869"
})
```
Expected result-
The data should be sent along with the transaction.

Actual outcome-
```
code: -32603, message: "Error: [ethjs-rpc] rpc error with payload {"id":59…method":"eth_sendRawTransaction"} [object Object]", stack: "Error: Error: [ethjs-rpc] rpc error with payload {…method":"eth_sendRawTransaction"} [object Object]"}
code: -32603
```

**Comment by pRoy24** [comment]
Also adding that even adding the data string in the docs https://metamask.github.io/metamask-docs/Main_Concepts/Sending_Transactions
fails.
I am currently on Ropsten testnet and have tried with other testnets as well.

**Comment by rickycodes** [comment]
@pRoy24, I think I've encountered this one before... are you _only_ adding `data` to the `transactionObject`? I think the problem here is that the gas needs to be a bit higher to send encoded data in the transaction. Does the transaction go through if you bump `gas` to something like `21000*2`? I believe the offset is relative to the amount of hex data that's being sent in the transaction.

**Comment by pRoy24** [comment]
No during my last tests a month or so ago, the transaction was failing regardless of the amount of gas added.

**Comment by tmashuang** [comment]
Reproduction of this issue with limited information has not reproduced this issue. This is the snippet I used

```
var transactionParameters = {
  to: ethereum.selectedAddress,
  from: ethereum.selectedAddress,
  gasPrice: '0x3b9aca00',
  gas: '0x55f0',
  data:
    '0x6869',
};

var txHash = await ethereum.request({
  method: 'eth_sendTransaction',
  params: [transactionParameters],
});

```
