### ISSUE TITLE
Blank windows after typing wrong password on account import

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#8057]
Firefox 72.0.2 
Arch Linux
MetaMask : latest 

I tired to import an account from a JSON-file, but used the wrong password.
Metamask just displayed a spinning logo "forever".
When I killed the firefox window and opened another window (without shutting down firefox altogther), Metamask window is jusz blank.

![MetaMask - Screenshot](https://user-images.githubusercontent.com/25609/74600905-d5a33100-50eb-11ea-9d17-8e8d1d316036.png)

**Comment by tmashuang** [comment]
Unfortunately, I am unable to reproduce on three different operating systems (MacOS, Win10, Ubuntu 18.04). Where all three have slightly different issues with their respective flows for account importing a json keystore, I couldn't pinpoint your issue. 

What I've noticed on Ubuntu that the addon view would lose focus and open the file selector tool, reported many times before,  #5029 #5952 #1136 #1536. Are you able to reproduce this in the full screen mode?

What are the background/ui developer tools error logs showing? In my instances of reproduction the error would show on the UI as `Key derivation failed - possibly wrong passphrase` instead of a blank, white screen.
