### ISSUE TITLE
How to use Transfer Token without "transfer" function ?

### ISSUE THREAD

**Issue by kypanz** [MetaMask/metamask-extension#8128]
Hello i have a question of a lot time and i dont know how to do this, i need to run a function in solidity calls "function exaple" but i wanna this function when run in metamask show transfer in tokens , let me explain

what i got using transfer function with metamask : 
- 1 run transfer function in solidity with web3 of metamask
- 2 result : metamask show me transfer tokens

what i got using any other function with metamask : 
- 1 run "function example" with web3 of metamask
- 2 result : metamask show me gas cost without show tokens

what i wanna do : 
- 1 run any function with metamask
- 2 result : show me transfer in tokens for run this function, like in "transfer function"

i trying to do something like this in solidity
```

function example () public {
 // run transfer here
}

```
the problem of this example code : when i run this code in metamask , this show me a gas cost and not transfer token because runs first "example function" before transfer function

what i need to do to show me a transfer token with any functions i want ? , not only with transfer function

please i search for a solution for a long time but nothings works for me , if i do something bad say me what please , i really wanna learn how to do this

**Comment by Gudahtt** [comment]
Thanks for the question! Unfortunately I don't think it's possible to do what you're asking. We show a generic "contract interaction" UI for any contract interaction that we don't have a custom UI to support. We have a custom UI for an ERC20 transfer, which is why you can see the amount of tokens transferred shown prominently on that confirmation page. The best you can get with a custom function is for the name of that function to appear on the confirmation page.

This is something we might consider addressing with [our upcoming snaps system](https://medium.com/metamask/introducing-the-next-evolution-of-the-web3-wallet-4abdf801a4ee); ideally you could develop a snap for customizing the confirmation page for your function, and let the user install it. I'll close this for now, but I'd recommend checking back when the snaps system has been released. We'll know more then about how feasible this type of customization is.
