### ISSUE TITLE
The event "chainChanged" does not work

### ISSUE THREAD

**Issue by OsoianMarcel** [MetaMask/metamask-extension#8226]
**Describe the bug**
The event "chainChanged" does not work.
But the event "networkChanged" and "accountsChanged" works fine.

**To Reproduce**
1. Open Chrome Console, paste this code and press Enter:
```js
ethereum.on('chainChanged', chainId => console.log('chainChanged', chainId));
ethereum.on('networkChanged', network => console.log('networkChanged', network));
```
2. Open metamask extension (logged in and enabled for the site), and change the Network.
3. The event "chainChanged" does not fire, but the event "networkChanged" fires as expected.

**Expected behavior**
When I change the network, I expect to receive an "chainChanged" event.

**Browser details**
 - OS: MacOS Catalina 10.15.3 (19D76)
 - Browser: Chrome Version 80.0.3987.149
 - MetaMask Version: 7.7.8

**Comment by rekmarks** [comment]
@OsoianMarcel due to a bug in the MetaMask inpage provider, it emits `chainIdChanged` instead of `chainChanged`. In our next release - step **1.** in #8077 - it will emit `chainChanged`. Please follow #8077 for details.

**Comment by OsoianMarcel** [comment]
Subscribed, thanks.

**Comment by snatvb** [comment]
Still doesn't work
MacOS Monterey 12.0.1 (21A559)
Chrome 97.0.4692.71
MacbookAir M1

**Comment by LizanLycan** [comment]
The expected behavior does not work. A certain response is achieved after a certain number of consecutive subscriptions, but it is not always. It also depends on a certain cache in the browser, because when clearing the cache it works only once, then when reloading the app, it stops working.

MacOS Monterrey 12.3

Microsoft Edge
Version 99.0.1150.46 (Official build) (arm64)
