### ISSUE TITLE
Clean up ui/app/components/app/permission-page-container/index.scss

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#8281]
ui/app/components/app/permission-page-container/index.scss has a number of unused styles and incorrect use of BEM styles. This should be cleaned up.

**Comment by Gudahtt** [comment]
The unused styles that sparked this issue ([in this comment](https://github.com/MetaMask/metamask-extension/pull/8078#discussion_r401978602)) have since been removed. And it looks like it was then re-added, but now it is used. I don't see any invalid BEM classes anymore either.

I'm sure there is still room for improvement in that stylesheet, but I'll close this for now since the original issue was addressed, and this one isn't particularly noteworthy anymore.
