### ISSUE TITLE
"Send" form hangs when specifying Amount and Transaction Fee

### ISSUE THREAD

**Issue by dtp5** [MetaMask/metamask-extension#8324]
When specifying an amount and/or transaction fee, the "Send" form will hang for upwards of 2 minutes before the inputs update. With respect to the amount, this applies when clicking the Max button as well as typing in a value.

Browser details:
OS: macOS 10.15.3
Chrome version: 80.0.3987.149
MetaMask version: 7.7.8

**Comment by Gudahtt** [comment]
Thanks for the report @dtp5! Are you still able to reproduce this on the latest version of MetaMask?

I tried reproducing this and was unable to. I have a theory as to why though - are using MetaMask on an external monitor by any chance? There is a Chromium bug that causes CSS transitions to be delayed/laggy on macOS while on external monitors; this affects _all_ Chrome extensions unfortunately. If you were using an external monitor, that was likely the culprit. As a workaround, I'd suggest using your primary monitor instead.

**Comment by dtp5** [comment]
@Gudahtt that does indeed appear to be the culprit. I'm able to reproduce the issue on MM v8.1.11 on my external display only, not my primary display.

**Comment by Gudahtt** [comment]
Great, thanks for following up!

We've investigated this before and had trouble thinking of any way to workaround or mitigate the issue. I've opened another ticket to track this problem specifically: #10173. I've opened that to track the issue instead of using this issue because this problem can have many different symptoms.

The Chromium bug in question is here: https://bugs.chromium.org/p/chromium/issues/detail?id=971701. Maybe starring the bug will help incentivize the Chromium team to prioritize this? My only suggestions for now are to use the primary display for MetaMask if possible, or use Firefox, and to star this bug and hope they manage to fix it.
