### ISSUE TITLE
Speedup sometimes fails

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8453]
Metamask attempted to replace a tx with gasPrice `2001000001` with tx with gasPrice `2201100001` which is 1 too little to be accepted by a geth node with the default settings.

**Comment by wjmelements** [comment]
Version 7.7.8

**Comment by wjmelements** [comment]
The tx enters the failed state when this happens. It can be retried.
<img width="359" alt="Screen Shot 2020-04-28 at 7 15 43 PM" src="https://user-images.githubusercontent.com/799573/80555268-a9761d00-8984-11ea-9852-a690add1bc95.png">

**Comment by wjmelements** [comment]
Another input that causes failure is 18.150000121 gwei

**Comment by wjmelements** [comment]
This also affects cancellations

**Comment by wjmelements** [comment]
After cancel fails in this way you can no longer cancel.

**Comment by wjmelements** [comment]
speedup also fails for MAX transfer transactions

**Comment by wjmelements** [comment]
Still seeing all of these; incredibly inconvenient

**Comment by wjmelements** [comment]
Still seeing these

**Comment by wjmelements** [comment]
Still seeing this in 8.1.6, very annoying

**Comment by Gudahtt** [comment]
Related: #9689

**Comment by wjmelements** [comment]
That is a separate issue. This is an off-by-one error.

**Comment by Gudahtt** [comment]
Oh I see now, I think I misunderstood. So you're saying that in the example in the OP, the price `2201100001` failed because geth requires replacement transactions to have at least a 10% higher price (where 10 is the default value for `txpool.pricebump`), and 10% higher in this case would be `2201100001.1`. So maybe we're truncating/disregarding the decimal here, which would make the resulting price _slightly less than_ 10% higher. Instead we should round up to the nearest whole number.
