### ISSUE TITLE
Meta mask extension will not open when clicked on

### ISSUE THREAD

**Issue by KeltonMad** [MetaMask/metamask-extension#8544]
**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by vittominacori** [comment]
Maybe I have the same problem (also if it is not clearly explained here).

I can't understand if it is my own issue or extension related issue.

When I click on MetaMask icon or when I use a Dapp it is really slow to render the popup details.

![image](https://user-images.githubusercontent.com/8151143/81270608-4737af00-904b-11ea-88d1-e6977a2f4747.png)

After rendered, it is unusable because of it makes my Mac Pro CPU going to 200%+.

Below the inspect popup screenshot.

![image](https://user-images.githubusercontent.com/8151143/81271052-df359880-904b-11ea-881d-45ed2cbb49f8.png)

I'm on MacOS 10.15.4 using Chrome 81.0.4044.138 and MetaMask v7.7.9.

**Comment by whymarrh** [comment]
@KeltonMad what version of MetaMask are you using? Would you mind filling out the issue description so that we can help?

**Comment by Gudahtt** [comment]
We did fix a variety of bugs recently that could have resulted in a crash upon initialization of the popup, as described here. I'll close this for now, since this issue was never correctly filled out anyway.

If anybody reading this is still experiencing this issue, please create a new issue.

**Comment by as0crypt** [comment]
My metamask on my firefox just suddenly stopped opening.
