### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by infinitepower2020** [MetaMask/metamask-extension#8603]
Hello Metamask Team,

I wanted to give you guys a nice feature to add to the site.

As a marketer who uses your system very often, some programs I am not using any more but can't delete the account.
which is okay. But I was thinking maybe you can add a show and hide feature so that way if I am not using it I can hide
it until I decide to use it again.. 

Another feature would be able to put the in the order I would like to have them from top to bottom.

And another would be to add a "scroll slider" above the "go to end arrow." so we are not trying to speed read the accounts
to try and stop it around the account we are looking for.  or at least an alphabet search system going by first letter of account
label.

Just wanted to throw these ideas at you.
Thanks for consideration in advance!

Marcus Miller.

**Comment by Gudahtt** [comment]
Thanks for the suggestions!

>As a marketer who uses your system very often, some programs I am not using any more but can't delete the account.
which is okay. But I was thinking maybe you can add a show and hide feature so that way if I am not using it I can hide
it until I decide to use it again..

If you want to hide specific accounts that you generated within MetaMask, this is a request that we have received before. It's being tracked under #5078 - feel free to follow that issue for updates.

If you want to disable MetaMask itself entirely, you'll need to do that via the browser by disabling the extension. You can disable the extension by clicking "Manage this extension" in the context menu of the toolbar button, and clicking disable.

>And another would be to add a "scroll slider" above the "go to end arrow." so we are not trying to speed read the accounts
to try and stop it around the account we are looking for. or at least an alphabet search system going by first letter of account
label.

We do already support scrolling the account menu with a scroll wheel. It's just that the scrollbar itself is hidden. There is a related ticket for making this list more easily scrollable for users without a scroll wheel: #8905


>Another feature would be able to put the in the order I would like to have them from top to bottom.

So you want to re-order the account list? :thinking: That makes sense - I don't recall hearing that idea before. I don't know exactly what you mean by "from top to bottom" though.

**Comment by Gudahtt** [comment]
For now I'm going to close this issue, as the only suggestion made here that wasn't covered in other tickets already is the one about account list order. I wasn't clear precisely on what the suggestion was there, and it's unlikely to receive immediate attention anyway as we have a few redesigns in-flight that affect the account menu that we'd want to land first before adding re-ordering functionality. But I'd encourage you to raise the idea again in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) - that's where we're trying to gather feature requests from now on.
