### ISSUE TITLE
Treat custom RPC networks with mainnet chainId as mainnet

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#8668]
If a user adds a custom RPC network `chainId` `1` or `0x1`, we should indicate that it is a Mainnet network. This includes:
- Using mainnet contracts, services, balance checkers etc.

**Comment by MysticRyuujin** [comment]
Please, please, please do this

**Comment by Gudahtt** [comment]
Related: #9297

**Comment by Gudahtt** [comment]
Also related: #9558, #9870

**Comment by Gudahtt** [comment]
Here are all of the cases where we treat built-in and custom Mainnet differently in the background:

* In the preferences controller, we key tokens by "providerType", which is "mainnet" for the built-in Mainnet, but is "rpc" for any custom RPC endpoints.
* Reverse ENS resolution in the ENS controller is based upon network ID, not chain ID
* Balances are cached by network ID, not chain ID
* In the transaction state manager, we retrieve and wipe transactions according to whether they match the current network ID, not chain ID
* The ENS IPFS resolver is enabled according to network ID, not chain ID
* The `Add Ethereum Chain` handler uses `getCurrentNetwork` and expects an object with a `chainId` property, but it instead returns a string network ID.

**Comment by Gudahtt** [comment]
Here are all of the cases in the front-end where we treat built-in and custom Mainnet differently, or where we incorrectly use network ID rather than chain ID:

* `tx-helper` will filter transactions by network ID (as does `incomingTxListSelector`, `unconfirmedTransactionsCountSelector` and `confirm-transaction-base.container.js`)
* `getEtherscanNetworkPrefix` uses network ID rather than chain ID
* `getAccountLink` uses network ID rather than chain ID
* Cached balances are accessed via network ID (this needs to be fixed in the front-end and background simultaneously)
* The ENS input component uses network ID rather than chain ID to determine whether the network supports ENS
  * Possibly related, the error handling in the Send flow (`getToErrorObject`) checks whether the current network is an "ETH network" using the network ID rather than chain ID
* The token asset page uses the network ID to generate the Etherscan link
* The deposit ether modal uses the network ID to determine which faucet to show, and to determine the network name
* See all uses of `getCurrentNetwork` and `getCurrentNetworkId` and `isEthNetwork`

**Comment by brad-decker** [comment]
All listed issues are either resolved or in the process of being resolved by open PRs.
