### ISSUE TITLE
if i switch to a site that isn't connected and click "don't show this again" i can't click connect

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#8732]
![](http://g.recordit.co/Ry4qWvEC3q.gif)

**Comment by Gudahtt** [comment]
This is intentional, as by connecting you're implying that you did find the alert useful. It would be strange to disable this type of alert completely and also connect. The button was disabled in this case so that a user wouldn't check that checkbox for the wrong reasons, e.g. to prevent the alert on _this specific site_. By connecting, you're already ensuring the alert won't show up for this site.

**Comment by brad-decker** [comment]
I think, though, from a user perspective I expect to have to "submit" my desire to not show this again. It isn't clear from the gif that my preference has been recorded, imo.

**Comment by rekmarks** [comment]
For the new design, see #8802, the "Connect" action is performed by clicking a link in a completely different part of the modal.

Clicking "Connect" will close the modal, but ignores the state of the "Do not show this again" checkbox. Only the "Dimiss" button will act on the "Do not show this again" state.

I think that's perfectly fine, and that we should close this issue. Thoughts?

**Comment by rekmarks** [comment]
I'm going to say that #8802 fixed this.
