### ISSUE TITLE
Reset password within settings and make it easy to backup imported accounts

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-extension#8855]
**What problem are you trying to solve?**
Make it easy for users to reset their MetaMask password and stop them from loosing any accounts they have imported. 

**Describe the solution you'd like**
From the settings menu, allow users to reset their password. If they have any imported accounts, prompt them to back up those keys before resetting their password so they don't loose them. 

**Additional context**
This may look like: Settings > Reset password > Enter current password > Backup imported accounts > Change password
See: https://github.com/MetaMask/metamask-extension/issues/8729

**Comment by Gudahtt** [comment]
We should be able to reset the password without clearing any imported accounts. That would make this process simpler.

We need to clear the accounts if the user forgets their password and the extension is locked, because the accounts are encrypted with the _old_ password. But if the extension is currently unlocked, there's no need to clear them.

**Comment by Gudahtt** [comment]
Closing this in favour of #7661, which is an older issue requesting essentially the same thing.
