### ISSUE TITLE
License - move to a standard license

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#886]
Move to a standard license. This requires OK from the Ethereum foundation.

Also need a contributor agreement. Parity does a good job of this with their bot + form.

**Comment by apotheon** [comment]
As I noted in [the discussion following the PR](https://github.com/MetaMask/metamask-plugin/pull/885), that PR would not actually constitute a change of license -- only changes in whitespace and removal of non-license notes within the license file that are, in fact, misleading descriptions of the license.  Please read my comments there for further information.

**Comment by s-a-m** [comment]
Hi, so I'm a license geek and I would strongly support @apotheon arguments in the PR thread. **It has been a year** since that discussion, and MetaMask continues with a license that is non-standard, which is causing derived issues, since multiple forks (from the 200+ forks) replicate the same non-standard license by default. In practice, googling for the "Ethereum Project Contributor Asset Distribution Terms", throws only MetaMask derived software. Obviously Ethereum's DevGrants [funded also other projects](https://blog.ethereum.org/2016/01/08/d%CE%BEvgrants-update-new-funding/) and yet none appears to have that license currently (e.g. [syng.io, now renamed](https://github.com/status-im/status-react). As @apotheon pointed out, the license terms are the same with the modification, so I would move forward to the change (especially if after contacting the Foundation a year ago you received no reply... most probably they don't actually care if it's changed to the standard MIT).

**Comment by apotheon** [comment]
I'm glad to see this has been resolved.  I'm a little disappointed that a pull request that essentially did the exact same work was discarded, leaving the person who initially did this work without any credit in the project's commit history.
