### ISSUE TITLE
Validate gas parameters

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#905]
@wighawag writes:

> Hi all, Does metamask has some check on parameters like gasPrice for accepting tx ?
> Just now I was playign with gasPrice and tx were refused with erro message : invalid param, the gasPrice was unusually low or high

We should definitely make sure our estimates are never outside of acceptable gas ranges, but I think we do that (but let's make sure just in case, probably with automated tests).

Seems like there are two ways to approach this, to me:
- Sanitization (force parameters within acceptable bounds, which may violate user intent)
- Better error messaging (Tell the user whether the gas estimate was too low or too high)

@wighawag: Do you know what gas parameters threw this error?  Was it on our send page?

**Comment by wighawag** [comment]
Hi @flyswatter 
My message was a bit ambiguous.
the error was something like "invalid param.." and NOT "invalid param, the gasPrice was unusually low or high"

The thing is that I get this error message when the gasPrice was unusually low (or high)

I was playing with using high gas price as well as very low gas price on the testnet

So the issue is that metamask was rejecting transaction due to this error

I was testing it on my game, not metamask sending

**Comment by Zanibas** [comment]
I think we've addressed this? Reopen if wrong.
