### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by gitbugsbunny** [MetaMask/metamask-extension#9122]
Whenever I try to scan QR code for deposit, somehow it shows "ethereum:xxxaddressxx". I don't know why ethereum is being detected before deposit address. Only MM wallet shows ethereum whenever I scan QR code

**Comment by Gudahtt** [comment]
Thanks for the report! This behavior is intended, as specified in [EIP-681](https://eips.ethereum.org/EIPS/eip-681). Maybe the app you're using doesn't support EIP-681?

I'll close this issue for now as I think this is intentional, but it would be helpful if you explained which app you were using when you encountered this.
