### ISSUE TITLE
Wallets remain unconnected for apps on the same origin URL (but different port)

### ISSUE THREAD

**Issue by deanpress** [MetaMask/metamask-extension#9190]
According to the [Metamask docs](https://docs.metamask.io/guide/ethereum-provider.html#events):

_"Callers are identified by their URL origin, which means that **all sites with the same origin share the same permissions**."_

According to [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin), an origin url is the protocol + base url, and doesn't include the port:

```js
const url = new URL("blob:https://mozilla.org:443/")
console.log(url.origin); // Logs 'https://mozilla.org'
```

So, if you have 2 ethereum apps on the same domain but 2 different ports, the connection + permissions _should_ be shared between the two (as they share the same origin).

Instead, currently you're asked to connect to both apps separately. 

Metamask includes the app's port in its identifier, which isn't part of an "origin url".

I believe that the base URL + protocol should be the origin (as per Mozilla's description), and shouldn't separate connected apps per port. Ports included in the connection identifier introduces unnecessary complexity for developers who run various front-end services for a client across different ports, while the apps are considered part of the same application/origin.

**Reproduce**

Start 2 ethereum apps on localhost on 2 separate ports. Observe that after approving one app, you still have to approve the other.

**Comment by Gudahtt** [comment]
Thanks for the report! But I believe this is working as intended.

From the MDN article that you linked:
>For `http` or `https` URLs, the scheme followed by `'://'`, followed by the domain, followed by `':'`, **followed by the port (the default port, `80` and `443` respectively, if explicitely specified)**.

(emphasis added)

The port _is_ included in the origin. The docs state that it is included only if explicitly specified, and omitted otherwise. That's why it's not shown in their example.

In practice, it seems that the default port is _always_ omitted, even if explicitly specified. But it is included for non-default ports. For example:

```
(new URL('https://example.com:444')).origin
```
will return `"https://example.com:444"`
