### ISSUE TITLE
Popup never appears on Vivaldi Browser

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#9194]
**Describe the bug**
When a logged-in MetaMask user is connecting to many sites using the Vivaldi, MetaMask fails to open a popup for the connect flow. Instead, the connect request is appearing as only a blue notification bubble on the extension icon.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to oasis.app/save on Vivaldi Browser
2. Attempt to connect the wallet on a MetaMask wallet that hasn't previously connected to this site.
3. See that the popup is never triggered.

**Expected behavior**
User should receive a popup connection request.

**Browser details (please complete the following information):**
 - OS: Manjaro Linux
 - MetaMask Version 8.0.6
 - Browser Vivaldi | 3.2.1967.41 (Stable channel) (64-bit)

**Comment by PatrykLucka** [comment]
Vivaldi is not triggering disconnect() function on port when closing the popup/notification. It is first thing being triggered after manually opening popup again. This prevents popup from being reopened (since extension thinks popup is still open). We can make an exception for Vivaldi browser not to check this condition, it can trigger multiple same notifications, but it's better than no notification.

**Comment by Gudahtt** [comment]
This seems to have been fixed in #9271, so I'll close this for now.
