### ISSUE TITLE
No conversion rates when using local node

### ISSUE THREAD

**Issue by enolan** [MetaMask/metamask-extension#9297]
**Describe the bug**
Metamask doesn't report USD values for Ether or token balances when using a local Ethereum node.

**To Reproduce (REQUIRED)**

1. Set up a local Ethereum node. I'm using OpenEthereum 3.0.1.
2. In the networks dropdown, select "localhost 8545"
3. Look at your ETH balance, and see no dollar value below it.

**Expected behavior**
Below the ETH balance there should be a dollar value, like there is when you've selected "Main Ethereum Network".

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 79.0
 - MetaMask Version 8.0.9

**Comment by c0mm0n** [comment]
Having the same issue using my node.
Seems rates come from infura endpoints but are called only when using preset node.

**Comment by Gudahtt** [comment]
We intentionally hide fiat balances when on custom RPC endpoints and testnets because the conversion rates we get only apply to Ether. We can't be sure what the native currency of a custom network is, or what it's worth.

Though you raise a good point, that we're even hiding these rates when the custom RPC endpoint is for Mainnet. This part was unintentional I believe. We can update it so they're shown for any network with a chain ID of `0x1`.

**Comment by Gudahtt** [comment]
Also, there is an Advanced setting called "Show Conversion on Testnets" that would display Mainnet conversion rates on custom networks when enabled. This is primarily intended for testing purposes, but it could be used here as a temporary workaround.

**Comment by RED29** [comment]
indeed exact the same question.. the workaround works, but it would nice if there is an input to change the API to another, like coingecko.

**Comment by ilblackdragon** [comment]
Is there a plan to extend the network configuration to support other prices for other tokens? E.g. not just price for ETH?

**Comment by Gudahtt** [comment]
This should be fixed as of #10488!
