### ISSUE TITLE
Can MetaMask be unilaterally relicensed to Consensys?

### ISSUE THREAD

**Issue by hayeah** [MetaMask/metamask-extension#9304]
**Describe the bug**

LICENSE is now "Copyright ConsenSys Software Inc. 2020. All rights reserved.", with no mention of the original MIT License.

**To Reproduce (REQUIRED)**

Visit: https://github.com/MetaMask/metamask-extension/blob/develop/LICENSE

**Expected behavior**

Incorporate the original MIT License.

The MIT License terms requires "The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

> You cannot "re-license" MIT-licensed code, and the MIT-licensed code will remain under the MIT License, but you can redistribute it as part of another project under any license you wish. You should make it clear that any changes that you make to the MIT-licensed code are released under your new license. The MIT License text & copyright notice must still be included with any unmodified MIT-licensed code. [1]

[1] https://www.tawesoft.co.uk/kb/article/mit-license-faq

**Additional context (Error Messages, etc.)**

https://github.com/MetaMask/metamask-extension/pull/9282

https://github.com/MetaMask/metamask-extension/issues/9298

**Comment by kumavis** [comment]
hi @hayeah thanks for your question

> Licensing is the legal term used to describe the terms under which people are allowed to use the copyrighted material

the re-licensing restriction you stated applies to consumers of the copyrighted material and not the owner of the copyright

let me know if I can clarify further

**Comment by kumavis** [comment]
@hayeah also want to clarify a common misconception about our new license. the past 5 years of metamask releases are still available as MIT, there's no retroactive change

**Comment by edmundedgar** [comment]
@kumavis This next line is bananas:

_You acknowledge and agree that ConsenSys Software Inc. (“ConsenSys”) (or ConsenSys’s licensors) own all legal right, title and interest in and to the work, software, application, source code, documentation and any other documents in this repository (collectively, the “Program”), including any intellectual property rights which subsist in the Program (whether those rights happen to be registered or not, and wherever in the world those rights may exist), whether in source code or any other form._

But as I think's been established in other threads, ConsenSys *doesn't* own all legal right to this code, because ConsenSys didn't write all the code, and the contributors didn't transfer the copyright to ConsenSys. ConsenSys merely has a *license* to this code, which allows it to create a derivative work under a different license. I'm not sure whether contributors who run the new version of MetaMask are effectively transferring their copyright...

**Comment by apotheon** [comment]
Are the various contributors even aware of the license change unilaterally applied to their contributions?
