### ISSUE TITLE
Make clear note of breaking API changes in changelog for releases

### ISSUE THREAD

**Issue by kael-shipman** [MetaMask/metamask-extension#9308]
**What problem are you trying to solve?**

We've been caught off guard several times by breaking API changes. Upon inspecting the changelogs, some of those changes appear to be mentioned somewhat incidentally, while some appear not to be mentioned at all.

**Describe the solution you'd like**

Have a bold **"BREAKING"** prefix for changes that break the API, along with a link to pertinent documentation. E.g.,:

Release 8.0.9

* fix some issue
* fix another issue
* **BREAKING** changed return format for `eth_requestAccounts` call ([read more](/somewhere))
* ...

**Additional context**

In this particular case, our app has worked fine for several weeks, but we just got notification from a user that it wasn't connecting and discovered that the return value of the `ethereum.send('eth_requestAccounts')` has changed from an array to an object with a `results` key containing the array.

I don't see any mention of this in the changelogs anywhere. That could be because it's not there, or because it's not obvious. Either way, it would be really helpful if breaking changes were flagged in bold.

Also, this is NOT intended to be a "you did something wrong!!" message. We really appreciate MetaMask and what it allows us to accomplish. We just want to more easily catch when we have to make updates to our app so that users aren't having to call us and tell us our app is broken.

Thanks!

**Comment by kael-shipman** [comment]
Hm.... It looks like this particular instance may be a misdiagnosis from our team. Because of the fact that each individual's browser updates at different times, we had to put a shim in for the 8.x branch upgrade to ensure that our app worked with both 7.x and 8.x extensions. It looks like for some reason that shim stopped working with the 8.0.9 release, although I don't have more details on why it stopped working.

I'll leave this issue open just because I still think it would be helpful to highlight breaking changes more emphatically, but you can close it whenever you'd like.

**Comment by rekmarks** [comment]
Hi @kael-shipman, thank you for raising this issue. It's not immediately apparent to me [which changes](https://github.com/MetaMask/metamask-extension/compare/v8.0.8...v8.0.9) could've broken your shim in 8.0.9. The only provider-related changes were some updates to our Proxy-wrapper for `window.web3`, which doesn't seem relevant here.

The difference in the behavior of `ethereum.send` may have appeared on MetaMask mobile, which is in beta. It never made it to production on the extension AFAIK, and if it did, that's our bad, and you have my apologies. I can promise that the behavior of `ethereum.send` won't change again, since it's deprecated.

A few notes before I close this:

- We _do_ have some breaking changes coming up, which you can read more about [here](https://docs.metamask.io/guide/ethereum-provider.html#upcoming-breaking-changes).
  - We'll make sure to note these on the extension and mobile changelogs when they ship on or after November 16, 2020.
- `ethereum.send` sucks. We strongly using the standardized [`ethereum.request`](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-request-args) instead.

Thanks again!

**Comment by kael-shipman** [comment]
Thanks for the comments and the additional information!
