### ISSUE TITLE
Can't do anything with a Metamask account 

### ISSUE THREAD

**Issue by Cliffyz** [MetaMask/metamask-extension#9360]
Hi. I have an issue with a Metamask account and am hoping I can get some help here.

Metamask version: 8.0.8.
Chrome extension. 

So I made 2 accounts within my wallet and I can easily switch between them.
Account 1: working fine
Account 2: doesn't transact. 

I used to use account 2, nothing wrong and there is funds on it. 
But since last week every transaction keeps pending. 
I have tried to increase the gas fee, increase slippage and I have reset it 100 times. 
All without result. 

I have tried to send funds to account 1. Keeps pending. 
I have tried to export it to mew so I would be able to transact through mew but there is no option to see the private key (I know where it should be found). 
Also I tried to get account 2 on my phone through the QR code. It says that the QR code is expired. 

All in all account 1 works fine, it has a own seed phase and private key.
Account 2 doesn't have both, doesn't transact with anything and it almost seems none existent...
How do I get it working or my funds out of this horror account?

**Comment by nwocykra** [comment]
I have the same issue. Even with the fastest level of fee also according to ethgasstation, I am getting pending each and every time. I manage to cancel them and have nothing pending between my tries. I also waited several days a few times, without luck.

Its very weird

**Comment by nwocykra** [comment]
For my issue, i found that despite metamask didn't show anything pending, i checked my account with etherscan and there was indeed still a tx pending. 
So I did the 0 transfer to myself with the nonce of the stick transaction to fix it.
Pretty sure things will work now

**Comment by Cliffyz** [comment]
I'm glad that worked for you. Alas, for me there is no TX on etherscan...

**Comment by tmashuang** [comment]
You can send your state logs to https://metamask.zendesk.com/hc/en-us/requests/new and reference the ticket number.

Most likely backed up transactions due to high network gas prices and overusing the speed up and cancel transaction feature.

**Comment by tmashuang** [comment]
>  reference the ticket number

This was meant to refer to the support ticket number in this issue thread to be able to reference your logs quickly, since I was already subscribed to this issue.

I am going to assume some information as the issue template has been filled out fully and there isn't enough information to go off of like `Account 2` being your Ledger. Seems that there could be a couple of things that could have happened. One issue could have been not plugging in your Ledger and confirming it on the ledger. The next process in the tx chain that it did not proceed to was the determining the nonce, which is an uncommon issue. 

The resolution might be to re-add your Ledger. I see from a block explorer that you've since been able to submit transactions. Let us know in a new issue if you have any more issues.

**Comment by kingarchilles** [comment]
> I have the same issue. Even with the fastest level of gas fee according to ethgasstation, I am getting pending each and every time. I managed to cancel the transactions and have nothing pending between my tries. I also waited several days a few times, without luck.
> 
> Its very weird, somethings wrong.

Hi sir May i ask how did you do it? Basically I transferred ETH to a different address which I believe it's mine. But I cant recover that wallet address anymore since my computer just reformat. Please help me.
