### ISSUE TITLE
Error during transaction speeding up

### ISSUE THREAD

**Issue by allemanfredi** [MetaMask/metamask-extension#9384]
When i try to speed up a transaction changing gas price, it does not work and i receive "failed tx", but if try to speed up it without changing gas price it works.

**Comment by tmashuang** [comment]
What is the gas price being set as?

**Comment by allemanfredi** [comment]
I wanted to use the "fast" option.

**Comment by tmashuang** [comment]
You can send your state logs to https://metamask.zendesk.com/hc/en-us/requests/new and reference the ticket number here?

**Comment by allemanfredi** [comment]
Done! the ticket number is #52906. Thanks!

**Comment by tmashuang** [comment]
Seems the all transactions in question that have been retried/sped up with a higher gas price have all went through.

**Comment by allemanfredi** [comment]
I think they was not been broadcasted because i controlled etherscan and i didn't see them.

**Comment by tmashuang** [comment]
Can you add more information to the ticket to narrow down the information? Such as the address(es), tx(s), nonce(s) in question, and even screenshots? 

It is possible that the local nonce is out of sync due to a older transaction not updating to the correct state. It is possible that the solution would be to Reset the Account in question in Settings, which is what others have suggested in previous issues. 
https://github.com/MetaMask/metamask-extension/issues/8782#issuecomment-651328412

**Comment by yarco** [comment]
this seems related https://github.com/MetaMask/metamask-extension/issues/9317

**Comment by jacobcantele** [comment]
Since we haven't received response here, I'm going to close this issue and move the conversation to #9317
