### ISSUE TITLE
"Sorry, We are unable to locate this TxnHash" On every single transaction

### ISSUE THREAD

**Issue by CrackerHax** [MetaMask/metamask-extension#9462]
**Describe the bug**
Every single transaction shows "Sorry, We are unable to locate this TxnHash"

**To Reproduce (REQUIRED)**
Any transaction I attempt to make anywhere with metamask. My wallet is not showing any pending transactions on etherscan.

**Expected behavior**
Expect transaction to complete

**Browser details (please complete the following information):**
 - OS: WIndows
 - Browser: Version 85.0.4183.121 (Official Build) (64-bit)
 - MetaMask Version [e.g. 5.0.2] 8.0.10

**Additional context (Error Messages, etc.)**
Sorry, We are unable to locate this TxnHash

**Comment by tmashuang** [comment]
Do you have any previously sped up or retried/cancelled transactions as well as transactions failed? We are seeing users with a specific pattern of these transactions that can effect the nonce calculation due to bad transaction state. Can you confirm that you have no pending transactions on a block explorer? 

If you are willing open a [MetaMask Support Ticket](https://metamask.zendesk.com/hc/en-us/requests/new) with your state logs attached, [How to Download State Logs](https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-). Then reference the ticket number here. Users have suggested with [Resetting Account ](https://metamask.zendesk.com/hc/en-us/articles/360015488891-Resetting-an-Account), which will clear your transaction history and recalculate the appropriate nonce. I am only providing the knowledge of this, without further information resetting the account might not actually fix your specific issue.

**Comment by CrackerHax** [comment]
Resetting my account worked. Thanks!

**Comment by alialparslan** [comment]
I was experiencing this and in my case it was happening because wrong nonce parameter thus making transaction invalid.
I was using same address within different networks. (AVAX P-chain and ETH) After making a transaction from one network and after switching the other network when making another transaction on that one nonce was set according to last transaction which made on other network. Resetting wallet from advanced settings solves the issue but issue repeats when above case happens.

**Comment by JamesEarle** [comment]
@CrackerHax which account? I'm having this issue with every service I attempt to use as well

**Comment by znake1st** [comment]
> @CrackerHax which account? I'm having this issue with every service I attempt to use as well

Me to same here for days im trying it.

**Comment by evilboyajay** [comment]
I am facing the same issue. From my experience, I have realized that if there will be any pending transaction, the transaction actually doesn't occur sometimes while creating or interacting with remix smart contract deployment and functions[in my case]. Also, pending transactions are not completed sometimes. Due to which we need to reset the account. I think this issue should be fixed.

**Comment by karanruparel** [comment]
I was transferring ETH from my exchange's account to my Metamask and I'm facing the same issue. Any idea how I can fix this?

**Comment by alialparslan** [comment]
> I was transferring ETH from my exchange's account to my Metamask and I'm facing the same issue. Any idea how I can fix this?

It's exchange's problem. Not related to metamask. Actually even when transaction made from metamask it may not be relavent to metamask at all but in your case metamask is not relavent.
