### ISSUE TITLE
Only first two eth addresses "initalized" on recovery seed import

### ISSUE THREAD

**Issue by kallisti5** [MetaMask/metamask-extension#9470]
**Describe the bug**
When leveraging your recovery seed, you might have accounts missing.

**To Reproduce (REQUIRED)**
1. Have over 2 eth addresses.  (small amount of funds in account 3 for example)
2. Ensure you have recovery seed.
3. Blow away wallet
4. Import recovery seed.
5. Two accounts show up, with the 3rd one missing

**Expected behavior**
All three accounts show up when importing recovery seed.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - MetaMask Version 8.0.10

**Workaround**
The additional accounts will show up if you:

1. Account
2. Create Account
3. Give it a name

Your funds will show up in the third "new" account.  This makes sense as you're creating accounts based on your seed.. however the UX interaction is a bit "weird" and I could see people opening angry bug reports that their funds are missing in this case.

Ideally, metamask could at minimum check for activity/balances on the first 25 accounts from the seed and "create" up to them if activity is found.

**Comment by tmashuang** [comment]
This is the section that effects the described issue https://github.com/MetaMask/metamask-extension/blob/1b000626498536c5312c983d44aa57834b622acf/app/scripts/metamask-controller.js#L640-L644

Does your Account 3 have an ETH balance, or just tokens? 

This wouldn't work if Account 2 has a zero balance as well since it will stop at the first zero balance. I would like to see how other feel about this issue as well. I thought there was similar ticket on this particular feature/issue with others wanting what is described here as well, but couldn't find it. 

I feel that getting account activity and token balance would require us to use a third party api (Ethplorer/Etherscan/etc) to get this information. We could check on the address nonce, and curate that list of accounts based on nonce. Any additional approaches to this are welcomed.

**Comment by Librechain** [comment]
Responding here to corroborate what the user said above. 

Had to swap OS, re-downloaded FF and figured, 'Let me get some of those ETH funds off of here real qiuck.' 

Didnt' happen. 

Seed only generated two wallet addresses but the 3rd+ addresses, despite them all being created in the same manner.  

### Here's Where I Get Really Confused 

I managed to save my last OS (all the files on it). So to pull that wallet back up, I merely rsynced the Firefox profile information to the newer OS to essentially create a "mirror". 

Once that was done, I was able to retrieve the funds (thankfully). 

What I found weird though is that, after I had rsynced the FF profile to mirror what was on my previous operating system, the mnemonic for Metamask ended up working again. 

#### Somewhat Major Issue 

Given what I experienced, it seems pretty clear to me that Metamask is **not following any standardized cryptographic standard** (which puts funds at an **insane amount of risk as we speak**) ; not to mention that as I type, all Metamask users are apparently being inundated with an unprecedented level of very directed (and targeted) phishing attacks

**Comment by rekmarks** [comment]
> Metamask is not following any standardized cryptographic standard

This is not true. @Librechain, if you re-created the n+1:th account on your new OS, you'd find that it's exactly the same as on your old OS. The problem here lies in our account balance detection code, not our account derivation code, which follows all of the applicable standards.

@Librechain, did the accounts that were not automatically recreated have positive ETH balances and/or positive token balances?
