### ISSUE TITLE
Trezor wallets not working on custom networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9661]
Per support requests:
https://consensys.zendesk.com/agent/tickets/54191
https://consensys.zendesk.com/agent/tickets/57781

I'm pretty sure this worked before our chain_id improvements, so this may have been a regression introduced in 8.1.0.

**Comment by tmashuang** [comment]
This is effected by the chain id change. The way to allow this behavior on our end would be to omit the chainId from txParams for hardware wallets on custom networks, which is not favorable. Trezor hard checks the provided chain id against their own list, [Trezor Supported Networks](https://github.com/trezor/trezor-firmware/blob/fdcb64ac2475b2fb738c75e97e6d110673e5b791/core/src/apps/ethereum/networks.py#L62-L315).

**Comment by Gudahtt** [comment]
Trezor may have addressed this in subsequent firmware updates: https://github.com/trezor/trezor-firmware/issues/1335

**Comment by bradwbradw** [comment]
Trezor has 1 job: sign a message. I'm not sure why the network id is relevant for USB hardware :(

Using the latest Trezor firmware `1.10.0`, I'm having an impossible time interacting with any dapps, because the trezor connect popup disappears right away after clicking "confirm" button in metamask.

Sorry to be commenting so much on multiple issues but I just want more visibility because I think it negatively impacts crypto adoption.
