### ISSUE TITLE
Timer on transaction or cancelable transaction

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#976]
Hi,
I guess this will be a web3 issue but I thought to mention it here to get a discussion starting.

For Etherplay, if player do not accept the start transaction quickly enough, their transaction can get canceled when it get mined.

Since we allow them to start playing the game before the mining happen, this means they get kicked out of the game midway.

One solution to this problem would be add a timer to the transaction that get automatically canceled upon the timer reaching zero.

Alternatively, there could be an api to cancel the transaction so the dapp could do the timer

What do you think ?

**Comment by flyswatter** [comment]
We could possibly support an additional parameter like `timeout`, and when it's provided, we could remove a tx if not approved within that timeout period.

It seems to me that would be backwards compatible, and meet your requirements.  How's that sound?

**Comment by wighawag** [comment]
That would be great

**Comment by flyswatter** [comment]
Ok so it's not a really high priority (obviously we have some outstanding bugs & things), but I'm filing this in our future features milestone, so we can revisit it when we have some time.

**Comment by scelts** [comment]
If a second opinion would speed up this, I'll give a +1 here. It would make life way easier for my application too, as I initiate transactions with decision timeout. 
So, I basically can't use metamask now, and have to use the custom app, as there's no way to stop payment after the timeout, and signing raw transaction which would be sent back gives a big red warning.

I think this is important, as any transaction not fixed to ETH but to $€ has expiry time due to volatility.

**Comment by danfinlay** [comment]
Having a time limit on a tx's validity makes plenty of sense, but since this would affect multiple clients, this belongs as an EIP, not a MetaMask issue. I would recommend people wanting this feature to open an EIP specifying exactly how they imagine this feature would work.

**Comment by Gudahtt** [comment]
Since this feature would require an EIP, I'll close it for now. A new issue can be opened when/if an EIP is created.
