### ISSUE TITLE
Decimal point is missing in one token balance, showing the actual balance multiplied by 10^18

### ISSUE THREAD

**Issue by ProkhorZ** [MetaMask/metamask-extension#9771]
My UNI token balance, including the dollar value, is displayed as a 20-digit number instead of a 2-digit number with 18 decimals after the period - an impossibly large amount of money. The correct amount is shown on Uniswap, in transactions on Etherscan, and in another address on Metamask where I added the token today. The same issue does not occur with other token balances.

**Browser details:**
 - Windows 10 Pro
 - No hardware wallet
 - Chrome 86.0.4240.111
 - Metamask 8.0.10

**Steps to reproduce:**
It's an edge case, it might not be reproducible. I think it's worth looking at since it might cause heart attacks or reckless spending.

1. I added Uniswap's UNI token to my Metamask account shortly after it was launched. But I didn't qualify for the airdrop, and the balance remained zero for a while.
2. I bought a few UNI tokens on Bittrex. Ironically, this took a while because I [omitted a zero](https://twitter.com/edbwt/status/1309589029759979522) in my first order. Then I withdrew them to this Ethereum account. Note: I only use Account 5, [as explained here](https://twitter.com/edbwt/status/1306006676085059586).
3. While I'd bought 21.77966... UNI, it showed up as 2177966145000... UNI, with a USD value of $50,988,687,315,279,360,000.00.

![21m UNI 1](https://user-images.githubusercontent.com/22837744/97784863-df999100-1ba1-11eb-85b7-6cd3214c97da.PNG)

4. Metamask even let me send a 21 million UNI transaction back to Bittrex:

![21m UNI 2](https://user-images.githubusercontent.com/22837744/97784888-0eb00280-1ba2-11eb-831b-e75526e1fdd5.png)

5. However, on Etherscan, this transaction showed up correctly, with 10 zeros after the decimal point before the 21:

![21m UNI 3](https://user-images.githubusercontent.com/22837744/97784935-62bae700-1ba2-11eb-9f9a-e7c15ddf9bfb.png)

6. Uniswap itself also shows the correct balance:

![21m UNI 4](https://user-images.githubusercontent.com/22837744/97784979-ad3c6380-1ba2-11eb-9eba-3c14c4f34d27.png)

7. The error is still there when I'm sending the whole balance to another address:

![21m UNI 5](https://user-images.githubusercontent.com/22837744/97785036-ff7d8480-1ba2-11eb-8d0d-e3d8168b8077.png)

8. This is an ridiculously high ETH value. Ethereum devs should have listened to me when I [proposed](https://github.com/ethereum/EIPs/issues/960) a maximum supply of 123,456,789:

![21m UNI 6](https://user-images.githubusercontent.com/22837744/97785160-9c402200-1ba3-11eb-94d4-6047d7319b8a.png)

9. For the other address (Account 1), where I added the UNI token today, **after receiving the tokens**, the correct value is displayed, truncated to only 3 decimals:

![21m UNI 8](https://user-images.githubusercontent.com/22837744/97785204-e4f7db00-1ba3-11eb-8f7d-7b7fe917991f.png)

10. After returning the tokens to Account 5, the impossibly large amount is displayed again: 

![21m UNI A returned](https://user-images.githubusercontent.com/22837744/97785293-78c9a700-1ba4-11eb-917b-e83a1e6a422d.png)

**Additional context:**

Can't find any indication that anything went wrong on Uniswap's side. One thing that makes my case unusual is that most UNI holders probably received their tokens before they added UNI to Metamask.

This might be related to fixed issue #6762.  

Coincidentally, I also have truncation issue #9318, which has been fixed, but not in version 8.0.10 yet. I don't know why my extension hasn't been updated. My browser was restarted when a worker shut off my power yesterday.

![21m UNI B truncated](https://user-images.githubusercontent.com/22837744/97785353-d0681280-1ba4-11eb-87f9-d05264c796aa.png)

**Comment by danjm** [comment]
Hi, what MetaMask version did this happen on?

**Comment by ProkhorZ** [comment]
@danjm The Chrome extension, version 8.0.10.

**Comment by danjm** [comment]
You might be able to fix this with the following steps:
- From the main screen, click on UNI in the token list, so that you are taken to the screen where UNI's balance is shown
- click the three vertical dots in the top right to open a dropdown menu. Select "Hide token"
- confirm the "Hide token" message that you see, you'll be taken back to the main screen where all your tokens are listed
- scroll to the bottom of the list of tokens and click the "Add Token" button
- On the add token screen, paste the UNI address into the search box `0x1f9840a85d5af5bf1d1762f925bdaddc4201f984`. If UNI shows up in the list select it, otherwise click the "Custom Token" tab and paste the address in the first field. Then click next
- You should see something like the following, with the correct amount of tokens:
![Screenshot from 2020-11-01 20-31-15](https://user-images.githubusercontent.com/7499938/97819128-42ae2500-1c81-11eb-9f1b-1601eaf6e7e7.png)

If the correct UNI icon doesn't show up, don't worry, that will be fixed in an near future update. Regardless the number of tokens should be correct. 

- Click "Add Tokens", and the problem should be fixed.

If not, please report here what you see and we will dig deeper into this issue.

**Comment by ProkhorZ** [comment]
Thank you, re-adding the token does result in the correct amount.

But this isn't a support call, I'm more interested in how this could have happened. Somewhere the wrong unit must have been used.

**Comment by danjm** [comment]
Whenever a token is added to MetaMask, the `symbol`, `decimals`, and `address` are stored in your local state. UNI normally has 18 decimals, but the numbers you saw indicate that values were being calculated with a decimals of 0. Somehow, when you first added the UNI token, the `decimals` property that got saved with was set to `0`.

How exactly that happened is not immediately clear...

Do you remember how you initially added the token? Did you copy and paste an address into the custom token form? If so, where did you copy the address from?

**Comment by danjm** [comment]
I wonder if you could have added the token before the node we attempted to fetch the contract data from was updated to include that contract? Or otherwise, the fetch for that data could have failed with no notice given. Either could have caused the decimals to default to zero.

**Comment by ProkhorZ** [comment]
> Do you remember how you initially added the token? Did you copy and paste an address into the custom token form? If so, where did you copy the address from?

I think I copied the contract address [from the airdrop page](https://uniswap.org/blog/uni/).

Shouldn't the default be 18 decimals, which is the most common? Maybe with a sanity check for extremely high or low numbers.

**Comment by tmashuang** [comment]
> Thank you, re-adding the token does result in the correct amount.

This seems issue is resolved. Since this issue was created, there have been improvements to how we handle failing token queries that could have been the issue, https://github.com/MetaMask/eth-token-tracker/pull/53. If this happens again, feel free to add additional information in a new issue and reference this one.
