### ISSUE TITLE
Metamask is mass reporting innocent crypto startups of being phishers

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-extension#9785]
**Describe the bug**
Many many startups are complaining of being flagged as phishing domains all the sudden. It seems that the issues are being ignored by your team.

Look at [this](https://github.com/MetaMask/eth-phishing-detect/issues)! Not cool, not ok. You are damaging the crypto ecosystem. You are hurting a ton of crypto startups including mine.

PLEASE ADDRESS THESE ISSUES! PLEASE REMOVE MY DOMAIN FROM YOUR PHISHING LIST. 

I have contributed to your repos and written tutorials on how to use solidity with Metamask. Is there any actual human involved in these phishing blacklist decisions? What is going on?

**Comment by Gudahtt** [comment]
You're referring to this issue I assume? https://github.com/MetaMask/eth-phishing-detect/issues/4358
This has been addressed already, and the updated phishing list should already be going out to clients.

Note that the phishing detection in MetaMask can be disabled in the settings, so that is one possible workaround if you encounter this in the future.

>Is there any actual human involved in these phishing blacklist decisions? What is going on?

Yes, there is. What happened in this case is that your domain was blocked for being too similar to a domain on our fuzzy list. Any domain similar enough to a fuzzy list entry is blocked by default. This is meant to handle domains that are so frequently attacked by phishers that we can't keep up with adding blocklist entries.(e.g. Uniswap). Your site was never directly blocked by us - this was unintentional. Please try to understand that there is no easy solution here - it's a tradeoff between protecting users from phishers and blocking "innocent" domains.

We are aware that there is a backlog of issues on that repo, and we are working to address that in the near future.
