### ISSUE TITLE
Metamask falsely accusing innocent crypto startups / founders of being "phishers"

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-extension#9786]
**Describe the bug**

Metamask has listed my domain as a phishing domain, along with a BUNCH of other innocent crypto startups. It appears that issues from startup founders to remove them from the list are being ignored! This is not ok. You are hurting the crypto ecosystem. You are hurting my legitimate crypto startup.

Please address this issue, please remove my domain and the others that have complained on your eth-phishing-detect repos. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to enledger.io
2. metamask warning appears

**Expected behavior**
Site should load. Ethereum tutorials should load with no warning.

I have contributed to your repos and written solidity tutorials for using Metamask! My site didn't deserve this treatment. Is there a human involved in these decisions? Maybe your decision process needs review here.

**Comment by 409H** [comment]
Added to whitelist here: https://github.com/MetaMask/eth-phishing-detect/issues/4358

See Reddit comment https://www.reddit.com/r/CryptoCurrency/comments/jnq81b/my_startup_was_falsely_accused_of_being_a/gb3vspo/

Please consider closing this ticket.

**Comment by danfinlay** [comment]
Closing this issue as the one highlighted issue has been addressed. As I wrote on your reddit post, we know we’re a bit behind on that list, and are in the process of getting a more sustainable process in place.

I’ll let each issue on that repo represent itself.

**Comment by danfinlay** [comment]
It might help to know that your site got hit because of its similarity to ledger.io, who is presently under a mass phishing attack. Many of their users are currently getting texts and emails directing them to a constantly changing stream of sites that vary off their brand name. Many of these have applied time pressure to users to get phished, which is why we added the fuzzy detection to ledger.

![5F479616-466D-4FB3-B629-0686899E2E8F](https://user-images.githubusercontent.com/542863/98129706-4a7eec80-1e6e-11eb-8636-e2b8ca922dd5.jpeg)
