### ISSUE TITLE
Metamask is falsely accusing genuine businesses and not taking corrective action

### ISSUE THREAD

**Issue by muthunagarajan1** [MetaMask/metamask-extension#9798]
Metamask is falsely accusing Genuine & Legitimate Businesses. It also fails to take corrective actions and is sitting for months on concerns raised. 

The following are the links to issues & Pull requests raised to whitelist ducatus.com . These are open since 14th of August 2020.

https://github.com/MetaMask/eth-phishing-detect/pull/4276

https://github.com/MetaMask/eth-phishing-detect/issues/4105

https://github.com/MetaMask/eth-phishing-detect/issues/4105

Take corrective action.

**Comment by Gudahtt** [comment]
We apologize for the delay in addressing these issues. We are working to address the backlog.

These sites were mistakenly blocked due to their similarity with common phishing targets. We are going to try to reduce the frequency of this happening as well, but there is no perfect solution here without exposing users to much more phishing risk.

I'm going to close this issue, as this is the wrong place to raise this concern.

**Comment by muthunagarajan1** [comment]
Apologies doesn't undo the hurt done to genuine businesses. 
The concern was raised again here because of your team's indifference to genuine concerns raised at the right place.
