### ISSUE TITLE
Translation warnings (pt_PT)

### ISSUE THREAD

**Issue by afmfe-iul** [MetaMask/metamask-extension#9820]
Not really a bug but if I have my language set to Portuguese and I visit the expanded view, the terminal has the following warnings:
![image](https://user-images.githubusercontent.com/10389190/98402192-ccce0300-205e-11eb-9576-987e8cf8feaa.png)

**Steps to reproduce** 
1. Open MetaMask on the expanded view.
2. Got to Settings > General and set your language to Portuguese
3. Check the developer console

**Expected behavior**
Everything is translated to portuguese.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Chrome Version 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: v8.1.3

I would be glad to help translate if that's an option! :)

**Comment by Gudahtt** [comment]
We show warnings for any missing translations to make it easier for volunteer translators to see which ones are missing. Most of our translations are community-supported at the moment, so they will always lag behind at least a little bit as we keep adding new text. I'm going to close this for now since this behaviour is expected.

Though,

>I would be glad to help translate if that's an option! :)

This is definitely an option! Take a look at our translation guide if you'd like to learn how to help:
https://github.com/MetaMask/metamask-extension/blob/develop/docs/translating-guide.md#adding-a-new-language

Please feel free add any missing translations, and submit them as a PR. Any improvements to translations are greatly appreciated :smiley: Feel free to reply here or in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics) with any further questions you have too, and I'd be happy to help.
