### ISSUE TITLE
QR code scans interpretting payment requests as token addresses

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#9889]

**Comment by Gudahtt** [comment]
Here is the payment request EIP: https://eips.ethereum.org/EIPS/eip-681

**Comment by danfinlay** [comment]
To ensure optimal future behavior, rather than parsing QR codes with many different strategies, it would be great if we converted them into `txParams`, and allowed handling it like a normal `sendTransaction`, which already properly handles interpreting token sends, or even contract interactions, etc.

**Comment by Gudahtt** [comment]
>it would be great if we converted them into `txParams`

What would it mean to "convert them into `txParams`"? I'm not sure I understand this suggestion.

**Comment by brad-decker** [comment]
@jacobcantele could I get some reproduction steps and perhaps a better description on this issue? @danfinlay and @Gudahtt -- bump on your conversation, I want to see where we land on potential fix paths. I might take this on, the direction is a bit unclear for me atm.

**Comment by Gudahtt** [comment]
I believe that if a user scans a QR code that resolves to a token payment request URI (as specified in EIP-681), it will populate the recipient field with the token address. I haven't confirmed that this is the case.

Naively I would expect that if we input a string that isn't an address, we should treat it as invalid. That would mean that scanning one of these token payment request QR codes would fail, but at least this bug would be fixed. We can leave proper support for this EIP to [the related tickets I referenced earlier](https://github.com/MetaMask/metamask-extension/issues/9889#issuecomment-728282102).

**Comment by brad-decker** [comment]
Is there an example QR code for a token payment request somewhere, or instructions for how I might generate one? @Gudahtt

**Comment by brad-decker** [comment]
nvm, i recreated using a website to generate QR codes and the examples in the EIP.

**Comment by danfinlay** [comment]
> What would it mean to "convert them into txParams"? I'm not sure I understand this suggestion.

What I mean is that since this URI pattern can propose _any type of transaction_, it would be good if we handled _any proposed transaction_ the same way we would if a website had proposed it:
- Tokens get the token send view
- Allowances get the allowance adjusting view
- Contract interactions get their methods displayed

By "convert to txParams" I was just suggesting that, that the QR code should go through the same method-handler that our provider methods go through.

**Comment by Gudahtt** [comment]
It sounds like you're suggesting that we support EIP-681 (#5125, #7706). We absolutely should, but I don't think we need to in order to address this bug. Validating the input is enough to at least stop doing the wrong thing here.

**Comment by brad-decker** [comment]
I went the route, for now, of just validating addresses. We should pull the work to implement the EIP into a sprint and prioritize it accordingly.
