### ISSUE TITLE
Blockies/Jazzicon should not format the seed value

### ISSUE THREAD

**Issue by DannyDelott** [MetaMask/metamask-extension#9973]
**Describe the bug**

I'd like my dApp to use the same blockies/jazzicon as MetaMask so that users have a visual confirmation that their connected to their desired wallet.

It looks like the seed value for the Blockies identicon is [`address.toLowerCase()`](https://github.com/MetaMask/metamask-extension/blob/9d4b8a4903e39ccc16c1122e31c429f89e9eba1a/ui/app/components/ui/identicon/blockieIdenticon/blockieIdenticon.component.js#L11), which produces a completely different icon than just `address`.

|Blockie A| Blockie B|
|---|---|
![image](https://user-images.githubusercontent.com/4524175/100926305-16f8a780-3498-11eb-844f-37527ca4a77c.png)|![image](https://user-images.githubusercontent.com/4524175/100926342-24ae2d00-3498-11eb-8897-f90f99ffa22c.png)

I've looked at other wallet providers and none of them format the address before generating the icon, for example [Fortmatic just feeds the address in as-is](https://github.com/fortmatic/wallette/blob/master/src/containers/login/login.tsx#L69).

I'm curious if there were reasons for the formatting-- it's not the end of the world to write a lookup function, but it feels brittle to copy over this special implementation, ie:

```ts
function getBlockiesSeed(walletType: string, address: string) { 
  if (walletType === 'MetaMask') { 
    return address.toLowerCase();
  }

  return adddress;
 }
```

**Expected behavior**

The identicon should be generated from the wallet address exactly as-is.

**Comment by danfinlay** [comment]
We would be open to adopting a standard blockie format if there was a standard format to adopt. A single wallet with a different implementation is not enough to make the case for a standard to adopt. In particular, since blockie icons have been used in the Ethereum ecosystem since before the checksum address format existed, it is clear that it is not the most established format for a blockie identicon.

If you'd like to promote a specific blockie standard to unify the wallets, I strongly encourage you to open an EIP and discussion on ethereum-magicians.org, but for the time being I don't think citing one other (more recent) wallet is enough to justify us changing this behavior.
